### ISSUE TITLE
why i failed to update pip?

### ISSUE THREAD

**Issue by chapgaga** [winpython/winpython#100]
`pip install --upgrade pip` and failed

detailed error message is as follows:
http://pastie.org/private/ntl8eifbysebaduerozetg

**Comment by stonebig** [comment]
For pip I think you have to do it that tricky way :
````
python -m pip install -U pip
````
see https://pip.pypa.io/en/latest/installing.html#upgrade-pip

**Comment by sebix** [comment]
@stonebig do we use version in 6.1.1 in current releases? We don't we update to 7.0.3, are there any blocking bugs or breaking incompatibilities with used packages?

**Comment by stonebig** [comment]
@chapgaga I hope the misleading message that caused your complaint will be fixed soon https://github.com/pypa/pip/issues/2883

@sebix : upgrade is either done manually by the user (when the right commande line is suggested to him), or will be done in next release.

**Comment by stonebig** [comment]
So, I guess the issue is answered, and the root cause issue is fixed in upstream "pip" package.
