### ISSUE TITLE
Sourceforge credibility

### ISSUE THREAD

**Issue by brownnrl** [winpython/winpython#101]
Starting with some stories from multiple venues a bit ago, there have been many questions that have arisen as to sourceforge's credibility.

http://www.reddit.com/r/linux/comments/37h4x5/sourceforge_hijacking_project_accounts_gimp/

In light of this, what venues are there to obtain downloadable end user packages that aren't mirrored from Sourceforge?  Should there be alternatives for winpython?  Thanks.

**Comment by stonebig** [comment]
Sourceforge:
- delivers currently 160 To of Winpython per day via about 15 mirrors,
- as a rather good interface for download navigation, and doesn't count the number of bytes they host for Winpython,
- welcomed Winpython when Google gave up 2 years ago, as a lot of other hosting sites did.

But you can download from there if you prefer: 
   - https://bitbucket.org/stonebig/winpython3.4.3.3/downloads
   - https://bitbucket.org/stonebig/winpython2.7.9.5/downloads

I'm not sure that bitbucket will be happy, if their bandwith is suddenly used as a sourceforge2 by Winpython.

**Comment by stonebig** [comment]
So, you have a solution to your current concern, but:
- it's not a solution to Sourceforge struggling business model,
- I'm waiting for the result of current brainstorming ongoing in the python community.

**Comment by brownnrl** [comment]
I'd recommend keeping an MD5 checksum of a "clean release" next to any sourceforge mirror for people who want to do their do diligence, and monitor for adware / malware / or control of your sourceforge account.  Also, it might be worthwhile to note the concern on your sites near to the download section.  Just in case.

I'm not trying to be unrealistic about the costs of throughput for an open source project.  You guys are doing great work, and shouldn't be bogged down with worrying about these issues.

Does github have [issues with binary releases](https://github.com/blog/1547-release-your-software)?  Is there a cost associated or limitations placed?  Maybe it's just a workflow change.  Before opening this issue I checked your releases tab.

**Comment by brownnrl** [comment]
And I'm not sure if Atlassian would begrudge the opportunity to become the next sourceforge.  I think their model is fairly well grounded in their issue trackers and IDEs.  They'd probably welcome the opportunity to take some of the limelight away from GitHub.

**Comment by stonebig** [comment]
I would rather consider a solution coming from python community, or from Windows, as a truly sustainable alternative: both would have an functional interest of serving Winpython binaries

**Comment by brownnrl** [comment]
Fair enough, I wish you luck in getting the consensus.  Thank you again for working on the project, and I apologize if the tone of my comments read in any condescending way.  I use the project, and your contributions are very much appreciated.  I would hate for something beyond your control to sour those efforts.

**Comment by sebix** [comment]
@brownnrl You may also want to have a look at scipy/scipy#4939

If you have any ideas or you can contribute any research in this area, about which services or companies may be of interest, please just add what you know.

**Comment by stonebig** [comment]
It seems sourceforge back-pedaled a bit (and I see a name at the end of the message):
http://sourceforge.net/blog/project-mirroring-policies-will-be-revisited-with-our-community-panel-existing-mirrors-removed/?utm_source=rss&utm_medium=rss&utm_campaign=project-mirroring-policies-will-be-revisited-with-our-community-panel-existing-mirrors-r

So:
- I remain confident on the well-behaving of sourceforge for Winpython and scipy,
- there is still, in my opinion:
  - the specific sustainability concern of current sourceforge model,
  - the bigger sustainability concern of  "all the shadow" pypi infrastructure(s) needed to keep alive and well Python eco-system on Windows.

I'll keep the (painfull to upload) backup on bitbucket for now.

**Comment by stonebig** [comment]
I see a complaint on a site about winpython noot having binaries on github too.
I will try to attach a 3.4.3 64bit binary as an experiment.

**Comment by stonebig** [comment]
the missing piece:
https://github.com/mmilidoni/github-downloads-count/pull/9
