### ISSUE TITLE
Launch Spyder offline

### ISSUE THREAD

**Issue by antoine06** [winpython/winpython#1011]
Hello,
I use Winpython64-3.9.5.0 on windows 10.
I cannot launch Spyder when my computer is not connected to the Internet. When my computer is connected to the internet, Spyder starts without trouble.
Is there a way to start Spyder offline ?
Thanks

**Comment by stonebig** [comment]
hum, it should work. 
did you install some Spyder plugins ?

**Comment by stonebig** [comment]
to the best of my experiments, it works with spyder-5.1.4 in latest beta. so no visible bug to iron out, so no action.
maybe:
- try with last beta
- try with another distribution
