### ISSUE TITLE
Spyder bug  "ERROR: execution aborted" (Spyder issues #13453 & #14293)

### ISSUE THREAD

**Issue by DIV-on-github** [winpython/winpython#1015]
Hi.   
There's an unresolved bug in Spyder 5.0.4, as included in WinPython 3.9.5.  
I am posting it here for two reasons.  

First, there is an easy workaround for many users, which is to alter one of the settings to  
Tools->Preferences->IPython console->Graphics->Graphics backend->Backend=inline
I suggest that in the meanwhile this should be configured as the default in the WinPython distribution.  

Second, despite several reports of the issue on the Spyder github page, these reports seem to have been either closed without remediation or are open but still awaiting action after almost one year.  
https://github.com/spyder-ide/spyder/issues/13453
https://github.com/spyder-ide/spyder/issues/14293
(I *assume* therefore that the bug has not yet been fixed, although I have not tested this in more recent versions of Spyder.)

—DIV

**Comment by stonebig** [comment]
Will check if the problem is still there, first

**Comment by stonebig** [comment]
for spyder-ide/spyder#13453 , it seems the bug is no more 
![image](https://user-images.githubusercontent.com/4312421/134774021-17cdbe85-6cb8-40b0-92f3-c0128fd6f7d4.png)

**Comment by stonebig** [comment]
so whatever the reason, there is nothing breaking there in upcoming WinPython, so nothing to fix,
