### ISSUE TITLE
Unable to start Spyder in 3.9.5.0

### ISSUE THREAD

**Issue by viscontem** [winpython/winpython#1027]
I am trying to use WinPython to launch the Spyder IDE.

I am downloaded the self-extractor of version 3.9.5.0 on GitHub, and, in the resulting folder, am starting 'spyder.exe'.

The spash screen shows, and during or at the end of the 'Initializing Status Bar' phase, disappears. Nothing happens then.

I have tried:
- To start spyder.exe as an administrator => No luck
- To start scripts/spyder.bat => No luck

I have not been able to find any spyder logs that would help me troubleshoot this issue.

Could you please help me figure it out?

**Comment by stefaneidelloth** [comment]
Have the same issue on Windows 10 when using WinPython from
Winpython64-3.10.0.1.exe
or 
Winpython64-3.10.1.0b4.exe

**Comment by stonebig** [comment]
hi Spyder can't not start indeed in WinPython-3.10.0.1. 

A solution was found at last in Winpython64-3.10.1.0b5.exe: the unexpected Pyside2-5.15.2.1.
To the best of my knowledge, it's  the only choice that allows Spyder to work on Python-3.10 right now.

Future is still PySide6 to my point of view, to get a better synergy between Python and Qt Company, for benefit and durability of both eco-systems.

**Comment by viscontem** [comment]
I can confirm the issue is solved using Winpython64-3.10.1.0b5.exe

Thanks :)
