### ISSUE TITLE
cmd.bat (WPy64-3980) fails with syntax-error

### ISSUE THREAD

**Issue by jcwinkler** [winpython/winpython#1039]
**Steps to reproduce**
In the following, it is assumed that WinPython is located at `C:\Progs\WPy64-3980`.
- Open a Windows command prompt
- Change into a directory outside of the WinPython installation location
- Call `C:\Progs\WPy64-3980\Scripts\cmd.bat`
- This results in a syntax error:
![grafik](https://user-images.githubusercontent.com/11866252/144198612-77dfbd35-a55a-4a7f-aa9e-b09e5adaaf4f.png)

**Expected behaviour**
The WinPython environment should have been set up successfully.

**Reason**
After some investigation it turns out that the problem is located in `env_for_icons.bat` and has been introduced by commit d5d7950d6c91a1fc28016e20c774a2df967da2a9

The syntax error is thrown here:
https://github.com/winpython/winpython/blob/e1b823e548871d4f7fedb89a5d7f3d85c81e63d9/make.py#L1382-L1383

There, `%WINPYWORKDIR1:~-1%` is expanded to a `"`, not `\`  or another allowed character as expected. This is since `%WINPYWORKDIR1` is set in quotationsmarks now due to the commit mentioned above
https://github.com/winpython/winpython/blob/e1b823e548871d4f7fedb89a5d7f3d85c81e63d9/make.py#L1378-L1379

**Solution**
I am not a Windows batch expert but I guess changing
https://github.com/winpython/winpython/blob/e1b823e548871d4f7fedb89a5d7f3d85c81e63d9/make.py#L1383
to
```batch
if "%WINPYWORKDIR1:~-2,-1%"=="\" set WINPYWORKDIR1=%WINPYWORKDIR1:~0,-2%"
```
should fix the problem. I tested this on my systems (Windows 8.1 and Windows 10 21H1) and it works. However, I do not overlook all possible side effects. @stonebig If you agree with this approach I can make a PR.

**Background**
I call `cmd.bat` from a menu entry in my Windows Explorer context menu "Open WinPython 3.9 command prompt here...". This worked well for years (up to at least WPy64-3950), with WPy64-3980 the mentioned problems occured.

**Comment by stonebig** [comment]
hum, I see I had screwed-up patch https://github.com/winpython/winpython/pull/1024.
re-applying first

**Comment by stonebig** [comment]
I think doublequoting in very first place was a bad idea

**Comment by stonebig** [comment]
at a certain level, DOS programing becomes non-comprehensible.

I will rather add this line before the offending line 

```` 
rem remove potential doublequote
set WINPYWORKDIR1=%WINPYWORKDIR1:"=%
rem remove some potential last \
if "%WINPYWORKDIR1:~-1%"=="\" set WINPYWORKDIR1=%WINPYWORKDIR1:~0,-1%
````

**Comment by stonebig** [comment]
tell me if it works too. 
expected advantage is that:
- it works also
- it gets rid of the doublequotes in the final  WINPYWORKDIR1
- it works if later I get 100% rid of the doublequote initial workaround

**Comment by jcwinkler** [comment]
@stonebig I tested your fix and it works fine now. Thank you!
