### ISSUE TITLE
Pandas to_hdf missing tables

### ISSUE THREAD

**Issue by ceaza** [winpython/winpython#1049]
This code snippet will not work with WinPython 3.10.0.1

```
import numpy as np
import pandas as pd 
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)),
columns=list('ABCD'))
df.to_hdf('d://data//test.hdf',key='test',append=False)
```

This is the error returned:
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.

Got it working by going through the following steps:
```
pip uninstall tables
go to precompiled tables wheels: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pytables
Download tables‑3.6.1‑cp310‑cp310‑win_amd64.whl to your pc
Install the wheel from where you saved it: pip install c:\Python\WPy64-31001\tables-3.6.1-cp310-cp310-win_amd64.whl
Also had to:
pip uninstall numexpr
and install again
pip install numexpr

```

**Comment by firai** [comment]
I assume this was WinPython Release 2021-04. Note that PyTables 3.6.1 had build issues with Python 3.10 (see https://github.com/PyTables/PyTables/issues/909), and wheels for that PyTables/Python combination do not currently exist (removed?) on Gohlke's site. PyTables 3.7+ should be installed instead.

In any case, WinPython Release 2021-05 includes PyTables 3.7.0, and the issue should be resolved.

**Comment by ceaza** [comment]
Yes, resolved in later versions, thanks I will close.
