### ISSUE TITLE
spyder icon doesn't work with spyder 2.3.5.2

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#106]
indeed:
- spyder did improve,
- and now there is a spyder.exe to call via the icon, instead of a spyder.bat.

**Comment by stonebig** [comment]
I guess change to do is:
from
````python
        self.create_launcher('Spyder.exe', 'spyder.ico',
                             args='spyder', workdir='${WINPYDIR}\Scripts',
                             settingspath=settingspath)
````

to
````python
        self.create_launcher('Spyder.exe', 'spyder.ico',
                             command='${WINPYDIR}\Scripts\spyder.exe',
                             workdir='${WINPYDIR}\Scripts',
                             settingspath=settingspath)
````

**Comment by stonebig** [comment]
it's a "good"/"modern" change from spyder, but it will break all current installations upgrading spyder.

(unless they manually preserve/copy back the previous "scripts\spyder" file.

**Comment by cgohlke** [comment]
Use the new wheel at http://www.lfd.uci.edu/~gohlke/pythonlibs/#spyder. It should include the .bat file and work with Python 3.

**Comment by stonebig** [comment]
The icon tries to launch "python python-2.7.10.amd64\Scripts\spyder".
You just added the "spyder.bat", not the "spyder".

in the historic "spyder" file there was:
````
#!D:\Winpython\basedir27\build\winpython-2.7.9\python-2.7.9\python.exe
from spyderlib import start_app
start_app.main()
````

it's not a bad thing if "spyder" can go back for previous Winpython icon compatibility, but don't you think it's wiser to change Winpython Spyder icon to use "spyder.exe" ?

**Comment by cgohlke** [comment]
> You just added the "spyder.bat", not the "spyder".

No, the wheel contains both files.

**Comment by stonebig** [comment]
![spyder_installation_effect](https://cloud.githubusercontent.com/assets/4312421/8338937/6ed1b0b8-1ab4-11e5-915b-9473c1c87ab6.GIF)

hum, it didn't landed at the previous place

**Comment by cgohlke** [comment]
Strange. The `spyder` file is in the wheel but doesn't get installed by pip.

**Comment by stonebig** [comment]
if there is no counter-argument, in next build spyder icon launcher will use the "spyder.exe" file, in rough guess it is the "modern" way expected by pypa organization.

**Comment by stonebig** [comment]
now I need to adapt winpython own sample "spyder.bat" for both type of spyder version

**Comment by cgohlke** [comment]
Try `%WINPYDIR%\python.exe -m spyderlib.start_app %*`

**Comment by stonebig** [comment]
ok, trying this way.

**Comment by stonebig** [comment]
It required a few tries and fail with the nullsoft launcher to get it right, but it looks good now.
Thank you Christoph !
