### ISSUE TITLE
Malicious behavior detected by antivirus

### ISSUE THREAD

**Issue by jeremy-coulon** [winpython/winpython#1060]
A recent update to CrowStrike Falcon Sensor, now reports any use of `scripts\python.bat` from all releases of winpython as `malicious behavior`. Which results in `Access denied`.

I don't have more information about this. Sorry.

I can't use winpython anymore.

**Comment by jeremy-coulon** [comment]
It looks like my antivirus changed its mind.

Winpython is working again.

**Comment by stonebig** [comment]
Gartner predicted a large scale cyber-attack within 2 years, with physical war associated.

Caution AND backups are recommended, that's nowadays life.
