### ISSUE TITLE
Release 2021-05 3.10 Description Errors on Home Page

### ISSUE THREAD

**Issue by firai** [winpython/winpython#1061]
I'm not sure if this belongs here or if there's another place to put this. The description for the 2021-05 3.10.2.0 release on the home page (https://winpython.github.io/) seems to have two errors:

- The Python version should say `Python 3.10.2 64bit` rather than `Python 3.9.10 64bit` (seems to be an issue with all editions of the `3.10` releases)
- `Pyside6` has actually been reverted to `Pyside2`

![image](https://user-images.githubusercontent.com/23555/152793590-05224dc6-dc58-4632-9e98-7ade4523835e.png)

P.S. I understand that work is planned for Release 2022-01 to bring back Pyside6. To be honest, I would rather get Pyside6 back for the next release even Spyder doesn't work, since I already have production code with Pyside6. But maybe I'm in the minority.

**Comment by stonebig** [comment]
PySide2 unexpected release broke the sad plan to ship again a very uncomplete python 3.10 distro.

Spyder was not yet even starting with PySide6 this time. I hope it will change within 2 month

**Comment by stonebig** [comment]
We shall get a PySide6 preview wheel for next time,  for PyPy, that may motivate Spyder Team investing time in PySide6 compatibility.

**Comment by firai** [comment]
Getting not only PyPy on Windows but PySide6 on PyPy on Windows would be exciting.

In the meanwhile, I recommend fixing the descriptions on the https://winpython.github.io/ home page, so that new users aren't confused/surprised.

**Comment by stonebig** [comment]
PySide-6 for PyPy remains a promise with no wheel in sight ... we are on Qt-6.3 target apparently around mid-march 2022

**Comment by stonebig** [comment]
will release a pypy3.8-v7.3.8rc2-win64 as b6 then an rc for pypy3.8-v7.3.8-win64, then will move on to PyPy-3.9

**Comment by firai** [comment]
Thanks for the update! I just realized that the website has its own repo, and I just created a pull request in that repo to fix the version numbers on the website for the last release as mentioned above.

**Comment by stonebig** [comment]
Thanks ! and Sorry again for the delay to merge.

**Comment by stonebig** [comment]
PySide6 is now Avalaible for PyPy, allowing other Qt stack packages to start tweaking for PyPy.

For Spyder natural compatibility, we droped back to PyQt5-5.15 for python-3.10, until PySide6 compatibility is there

**Comment by firai** [comment]
Thanks, @stonebig! Widget gallery tests seem to work OK with the PyPy beta build 3, but as your qtconsole issue shows, there are clearly other compatibility issues with certain downstream usages.

**Comment by stonebig** [comment]
It will be now cycles of improvements:
- cycles of ironing out incompatibilities and bugs, to get to next incompatibilities and bug, and more packages becoming compatible,
- cycles of small code tweaks to unlock JIT performance,
- cycles of PyPy catching up with cpython version,
- cycles of removing old JIT issues, like Hpy interface to C programs.
