### ISSUE TITLE
wp64-3.9.10.0 pip with Proxy not usable

### ISSUE THREAD

**Issue by nmarc** [winpython/winpython#1073]
ERROR: Could not install packages due to an OSError: Proxy URL had no scheme, should start with http:// or https://

install packages via PiP via Console not working. 

even if i set the Console Proxy manual -> SET HTTPS_PROXY=proxy.myproxy-net.local:8080

or try cmd proxy extends -> 
pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org --proxy "proxy.myproxy-net.local:8080"

I also edit the pip.ini with 
[global]
trusted-host = pypi.org files.pythonhosted.org pypi.python.org
proxy = http://proxy.myproxy-net.local:8080

python -m pip install --upgrade pip
ends with 
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/pip/

**Comment by stonebig** [comment]
The message says you should have a "http" in your command line, and you don't have

**Comment by nmarc** [comment]
I did some research.
It looks like something has changed as of python 3.9.

[https://stackoverflow.com/questions/68379277/how-to-set-http-proxy-in-python-3-9](https://stackoverflow.com/questions/68379277/how-to-set-http-proxy-in-python-3-9)

here the same problem from someone 9 months ago.
So far without a solution

I checked the communication to the proxy.
It looks as if,  no incoming connection is established by pip.

**Comment by stonebig** [comment]
So maybe the temporary solution is to stay on a  python-3.8 distribution

**Comment by firai** [comment]
Also see https://github.com/pypa/pip/issues/9216#issuecomment-741836058 and the issues referred to in that thread. `urllib3`, which `pip` uses for these proxy functions, is very particular about the combination of environment variable key name, URL scheme and the protocol that's actually being used when connecting. You may need to do some digging to confirm which protocol the proxy is actually negotiating when you connect to it, regardless of what URL scheme that may be given with the address. There are some suggestions in that thread and threads referenced there about various combinations that some people have found to work.
