### ISSUE TITLE
Basemap ?

### ISSUE THREAD

**Issue by deb75** [winpython/winpython#1076]
Hello,

With latest `winpython` (portable installation), I tried to import `Basemap` : 
```python
from mpl_toolkits.basemap import Basemap
```
which gave me an error : module not found and indeed, looking into `WPy64-31020/python-3.10.2.amd64/Lib/site-packages/mpl_toolkits`, there is no `basemap` module.

Is it normal that this module is not packaged with `winpython` ? Possibly because this package involves some third party libraries and/or several MB of data

Can I install it by hand ?

Regards

**Comment by firai** [comment]
You can install using ```python -m pip install basemap``` in a command prompt (or PowerShell). There are links on https://winpython.github.io/ to the lists of packages included in each release (and each edition).

**Comment by deb75** [comment]
Hi,

Thanks for your answer, I could install it as advocated.

Regards
