### ISSUE TITLE
Links and dates to be corrected on https://winpython.github.io

### ISSUE THREAD

**Issue by RivetBenoit** [winpython/winpython#1090]
The link for the Github WinPython 3.10 Download for the July 16th, 2022 release currently points to the May 3rd, 2022 release :  [https://github.com/winpython/winpython/releases/tag/4.6.20220501](https://github.com/winpython/winpython/releases/tag/4.6.20220501) instead of [https://github.com/winpython/winpython/releases/tag/4.7.20220709final](https://github.com/winpython/winpython/releases/tag/4.7.20220709final)

The link is correct for the WinPython 3.8 download.

Another bug : both release pages on [https://github.com/winpython/winpython/releases/tag/4.6.20220501](https://github.com/winpython/winpython/releases/tag/4.6.20220501) and [https://github.com/winpython/winpython/releases/tag/4.7.20220709final](https://github.com/winpython/winpython/releases/tag/4.7.20220709final) use year 2021 instead of 2022 : for example, `WinPython_ 2021-01 of May 3rd 2022` or `WinPython 2021-02 of July 16th 2022 (final)`.

I guess this will prove an easy bug to fix ;-)

**Comment by stonebig** [comment]
shamefull typos ... thank you for having reported them !
