### ISSUE TITLE
Winpython 3.10.5 - Winpython control panel does not open

### ISSUE THREAD

**Issue by jwaisner** [winpython/winpython#1109]
Upon testing this release I was able to get the console and the Idler open but upon trying to launch the control panel it does nothing. No response as if it is trying, it just acts like nothing was clicked. I am using PyQt5.

This is being used on a portable stack.

**Comment by firai** [comment]
Just to confirm, you downloaded the full version, not one of the `dot` versions, right? The control panel sometimes takes a while to load. If you're still having trouble, can you open a terminal in the `WPy64-31050` folder (or whatever folder you unzipped WinPython into), run `.\python-3.10.5.amd64\python.exe -m winpython.controlpanel` and report what messages you get? Details about your system, such as what version of Windows, etc., would also help.

**Comment by dev72** [comment]
The problem is a bugged package `packaging` used by `qtpy`.
You need to update it:
`pip install -U packaging`

Then you need to install a qt binding package.
It seem you already installed pyqt5, so it's ok.

Now it should work.

**Comment by jwaisner** [comment]
Thank you for the recommendation. I will try this and report back.

**Comment by jwaisner** [comment]
A clean rebuild of our repo and some magic fixed it. Closing this.
