### ISSUE TITLE
WinPython 3.10.5 pygame.midi.Output(0) CRASHES

### ISSUE THREAD

**Issue by milen-prg** [winpython/winpython#1110]
```
import pygame.midi

pygame.midi.init()
player = pygame.midi.Output(0) # Crash at this command!!!
```

In interpreter:

C:\WPy64-31050\scripts>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame.midi
pygame 2.1.2 (SDL 2.0.18, Python 3.10.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.midi.init()
>>> player = pygame.midi.Output(0)
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00002bd0 (most recent call first):
  File "C:\WPy64-31050\python-3.10.5.amd64\lib\site-packages\pygame\midi.py", line 424 in __init__
  File "<stdin>", line 1 in <module>

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.color, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame.pypm, pygame._freetype (total: 40)

C:\WPy64-31050\scripts>

**Comment by firai** [comment]
It seems from https://github.com/pygame/pygame/issues/3436#issuecomment-1237317620 that this issue can be closed?

**Comment by milen-prg** [comment]
Yes. Interesting is the cause that the current pygame version works in standard python installation, but not in winpython.
To hope that in new versions this problem will not occur again.
