### ISSUE TITLE
GDAL version

### ISSUE THREAD

**Issue by Patrick-Cole** [winpython/winpython#1112]
Hi,

Is there a source of new GDAL binaries? The current version shipped with WinPython (3.4.3) is not the latest and has an issue for me - its ASTER importer does not work. I think it's a version thing, since I had the same problem on Anaconda. However, the latest GDAL is 3.5.2. Is there someone who has the binaries and wheel for this version?

Regards

Patrick

**Comment by stonebig** [comment]
do you see a binary whell for windows somewhere for pip ?  
... Christoph Gohlke's no more sustained work is starting to have consequences

**Comment by stonebig** [comment]
Alternative Paths to explore:
- more native pip packages,
- more native pre-release packages (on Python-3.11 for example),
- non-native pip packages, see pyodide/WASM evolution, 
- a winpython over micro-mamba
- a winpython over https://github.com/mamba-org/vscode-micromamba
- ....

**Comment by Patrick-Cole** [comment]
I will keep checking from time to time. Hopefully a binary wheel does come up. I will also check out the alternative paths to explore. I am happy that you are aware of the issue, so I will close it for now.
