### ISSUE TITLE
SciPy-bundle-2021.05-foss-2021a.eb cannot pass the numpy test

### ISSUE THREAD

**Issue by yanchenmochen** [winpython/winpython#1116]
when I want to build the PETSc/3.15.1-foss-2021a, I ran into the issue which confused me very much time.

`
export PYTHONPATH=/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages:$PYTHONPATH &&  unset LDFLAGS && cd .. && /home/zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/bin/python -c "import sys; import numpy; sys.exit(not numpy.test(verbose=2))"

`

`
ImportError while importing test module '/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/core/tests/test_dtype.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/core/tests/test_dtype.py:4: in <module>
    import ctypes
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ctypes/__init__.py:8: in <module>
    from _ctypes import Union, Structure, Array
E   ImportError: libffi.so.7: cannot open shared object file: No such file or directory
_________________________________________________________________________ ERROR collecting core/tests/test_multiarray.py _________________________________________________________________________
ImportError while importing test module '/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/core/tests/test_multiarray.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/core/tests/test_multiarray.py:10: in <module>
    import ctypes
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ctypes/__init__.py:8: in <module>
    from _ctypes import Union, Structure, Array
E   ImportError: libffi.so.7: cannot open shared object file: No such file or directory
_______________________________________________________________________ ERROR collecting core/tests/test_umath_accuracy.py _______________________________________________________________________
ImportError while importing test module '/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/core/tests/test_umath_accuracy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/core/tests/test_umath_accuracy.py:6: in <module>
    from ctypes import c_longlong, c_double, c_float, c_int, cast, pointer, POINTER
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ctypes/__init__.py:8: in <module>
    from _ctypes import Union, Structure, Array
E   ImportError: libffi.so.7: cannot open shared object file: No such file or directory
_____________________________________________________________________________ ERROR collecting lib/tests/test_io.py ______________________________________________________________________________
ImportError while importing test module '/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/lib/tests/test_io.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/tmp/eb-ar3jsp7p/tmpglh2ot_a/lib/python3.9/site-packages/numpy/lib/tests/test_io.py:17: in <module>
    from ctypes import c_bool
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ctypes/__init__.py:8: in <module>
    from _ctypes import Union, Structure, Array
E   ImportError: libffi.so.7: cannot open shared object file: No such file or directory
======================================================================================== warnings summary ========================================================================================
zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/nose/importer.py:12
  /home/zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import find_module, load_module, acquire_lock, release_lock

zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/_pytest/cacheprovider.py:428
  /home/zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/_pytest/cacheprovider.py:428: PytestCacheWarning: cache could not write path /home/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

zjlab/.local/easybuild/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/_pytest/cacheprovider.py:382
`

[[numpy 1.19.0 + intelmkl test error](https://github.com/numpy/numpy/issues/16769)](https://github.com/numpy/numpy/issues/16769)

[[failing numpy test for some SciPy-bundle easyconfigs](https://github.com/easybuilders/easybuild-easyconfigs/issues/11789)](https://github.com/easybuilders/easybuild-easyconfigs/issues/11789)

[[SciPy-bundle/2021.05-foss-2021a Build Failure](https://github.com/easybuilders/easybuild-easyconfigs/issues/13531)](https://github.com/easybuilders/easybuild-easyconfigs/issues/13531)

**Comment by stonebig** [comment]
not a winpython aera of expertise
