### ISSUE TITLE
[question] why some environment variables are set to x86 (PROCESSOR_ARCHITECTURE=x86, ProgramFiles=C:\Program Files (x86), etc...)

### ISSUE THREAD

**Issue by ghost** [winpython/winpython#1118]
I've notices, for some time now that the environment variables overridden while WinPython runs are override by what you'll expect to have if you'll run a x86 version of Windows.

it kind of made sense with the old 32bit WinPython,  
but I'm running a latest WinPython that uses `python-3.10.7.amd64`.

I've ran `set` in normal cmd window,  
and `set` in cmd from WinPython,  
and that's what I've found:  

- `CommonProgramFiles=C:\Program Files\Common Files`  
to `CommonProgramFiles=C:\Program Files (x86)\Common Files`  
- `PROCESSOR_ARCHITECTURE=AMD64`  
to `PROCESSOR_ARCHITECTURE=x86`  
plus adding `PROCESSOR_ARCHITEW6432=AMD64`.  
- `ProgramFiles=C:\Program Files`
to `ProgramFiles=C:\Program Files (x86)`  

<hr/>

this is another change,  
but I've checked and saw that `Program Files (x86)` and `Program Files` both have 
`WindowsPowerShell` folder, so I guess that's fine..

- `PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvPkgConverter;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvSequencer;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\`  
to `PSModulePath=%ProgramFiles%\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvPkgConverter;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvSequencer;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\`

**Comment by stonebig** [comment]
winpython setup script is in `Winpython_base\scripts\env.bat`
