### ISSUE TITLE
Can I get winpython in .msi from.

### ISSUE THREAD

**Issue by Destroyinator69420** [winpython/winpython#1119]
I am writing because I wonder whether I can get winpython as an installer that will install to program files and put shortcuts in the start menu. I do not like portable apps, since they are difficult to launch and they are not at all easy to update. Thanks in advance.

**Comment by nmarc** [comment]
I do not think so.  the project specifically aims not to be.  Anaconda
might be of interest to you.

Destroyinator69420 ***@***.***> schrieb am Fr., 7. Okt. 2022,
02:19:

**Comment by stonebig** [comment]
there is an old option to "register" it, but maybe not to current standard of Python
you can try it 
![image](https://user-images.githubusercontent.com/4312421/194565503-f2138822-e655-4f55-838a-5c8c0aa629d0.png)

**Comment by stonebig** [comment]
WinPython won't do msi.
