### ISSUE TITLE
can't open IDLE (Python GUI) of Winpython64-3.10.8.0b4

### ISSUE THREAD

**Issue by pythonsoftwarefund** [winpython/winpython#1121]
when i open  open IDLE (Python GUI) of  Winpython64-3.10.8.0b4, there is no response.after copying  WPy64-31040\python-3.10.4.amd64\Lib\idlelib to  WPy64-31080b4\python-3.10.8.amd64\Lib,that's OK. IDLE (Python GUI)  is normal now.Maybe somethong wrong in idlelib.

**Comment by stonebig** [comment]
I would think it's a python-3.8.10 bug... strange

**Comment by stonebig** [comment]
yes it is https://github.com/python/cpython/issues/98324

**Comment by stonebig** [comment]
patch is to remove or comment with a # the line 7 of  .\Lib\idlelib\macosx.py
![image](https://user-images.githubusercontent.com/4312421/196772261-6c5c8ab7-46f1-43db-bd74-950d98c1240e.png)

**Comment by stonebig** [comment]
also I didn't test, or didn't notic nothing was opening... punishment

**Comment by terryjreedy** [comment]
Sorry about the mess.  I am curious what you mean by patching 'on the fly' or 'live'?  At this point, the offending import is moved to where it only executes on Mac when testing.

**Comment by stonebig** [comment]
On the fly = after pip installing the standard cpython and packages in a movable repo, a post-production treatment overwrite the python source file with the patch. 

So it's on the fly while building the winpython 

It avoids to recreate a wheel, or in this case to wait next cpython
