### ISSUE TITLE
Package include request: waitress

### ISSUE THREAD

**Issue by J3ronimo** [winpython/winpython#1123]
Hey, 

just a quick question if we can include `waitress` into WinPython: [docs](https://docs.pylonsproject.org/projects/waitress/en/stable/index.html), [pypi](https://pypi.org/project/waitress/)

It's a pure Python WSGI server which would add up nicely with Flask to build production ready websites or REST apis on Windows all from WinPython's included batteries. Where alternatives like Flask's debug server or `http.server` just don't do.

It's under the [Zope Public License (ZPL 2.1)](https://foundation.zope.dev/agreements/ZPL_2.1.pdf) which from my understanding would perfectly allow this.

It has no other dependencies and the packaged size is 50KB only, so lots of bang for very little buck.

Cheers :)

**Comment by stonebig** [comment]
ok
