### ISSUE TITLE
Include poetry in WinPython?

### ISSUE THREAD

**Issue by stefaneidelloth** [winpython/winpython#1128]
Did you already consider to include poetry in WinPython? I tried to install poetry with pip but it does not seem to be portable:

https://github.com/python-poetry/poetry/issues/6875

Maybe someone here already did it get working in a portable way?

Or maybe someone already tried and faced the same issue and that is the reason why poetry is not included in WinPython?

**Comment by stonebig** [comment]
Poetry seems based on virtualenv (or whatever venv)
![image](https://user-images.githubusercontent.com/4312421/197595124-3ee9435b-1763-4566-bf15-f165197aca1c.png)

WinPython "single line" change to make Python portable never tried to touch on this

**Comment by stonebig** [comment]
and so in WinPython spirit (another name for "capability"), virtual envs are fixed, until someone knows what to do, and wants it to happen

**Comment by stonebig** [comment]
certainly we shall have something more than "setuptools", but it's not clear what.

**Comment by stonebig** [comment]
humm .... watched PythonPackagin Authority on talkpython.fm https://www.youtube.com/watch?v=z50B6AmQwLw
and the comment from Travis

**Comment by stonebig** [comment]
WinPython tries to avoid the "virtual environment" thing, that seems to please poetry and hatch.
But it looks that PEP 704 may win over PEP 582

**Comment by stonebig** [comment]
as initial step forward, WinPython wheel is now build with flit.

**Comment by stonebig** [comment]
It looks a bit early to judge what's best:
- poetry navigates at 500K downloads
- but I see tricky conda/pip projects, bokeh and now panel, moving to "hatch".

**Comment by stefaneidelloth** [comment]
As you can see from the mention, I suggested pip to support 
`pip install`
without extra argument, to install dependencies from pyproject.toml

**Comment by stonebig** [comment]
reading  https://peps.python.org/pep-0665/

**Comment by stonebig** [comment]
in b5

**Comment by stonebig** [comment]
proved a problem in WinPython context, replaced par hatch
