### ISSUE TITLE
Pycrypto requires MSYS from MinGW

### ISSUE THREAD

**Issue by cjermain** [winpython/winpython#113]
I'm trying to install `pycrypto` on WinPython 2.7 32-bit, which raises an error about `chmod`. Even the Administrator shell with elevated permissions raises the same exception. It seems like MSYS from MinGW is required, which was discussed in the previous [Issue 67](https://code.google.com/p/winpython/issues/detail?id=67) on Google Code.

How should I go about installing `pycrypto`?

**Comment by stonebig** [comment]
maybe try this:
- download a prepared binary from http://www.voidspace.org.uk/python/modules.shtml#pycrypto
- install it via WPPM.

**Comment by stonebig** [comment]
Anaconda has it by default otherwise, If I read well http://docs.continuum.io/anaconda/pkg-docs.html

**Comment by cjermain** [comment]
Thanks @stonebig, I used the VoidSpace package and it worked great.
