### ISSUE TITLE
How do I start a *.py script by double click? from command line?

### ISSUE THREAD

**Issue by pstein** [winpython/winpython#1130]
I have extracted the newest WinPython package into folder 

D:\dev\python\v3\

In another directory I have python scripts e.g. test.py

1.) which of the python binaries are responsible for executing a python script?
I miss a Python.exe to which I can pass the Python script on command line like

Python.exe test.py

2.) Is there a way (inside the WinPython package) to associate *.py extension to the appropriate Python executable?
Afterwards a double click on a *.py file should be sufficient to execute the script.

Thank you
Peter

**Comment by stonebig** [comment]
this shall work, but may not be friendly with other Python Installation you may have
https://github.com/winpython/winpython/wiki/Installation#registration

**Comment by pstein** [comment]
Ok, thank you.

BUT: When I double click on "WinPython Control Panel.exe" something flashes for some milliseconds but Control Panel is NOT started. I am using Win10 v21H2

Whats wrong?

Furthermore:
What if I want to call a script not by double clicking but by passing the *.py via command line?

As I wrote in the first post

Python.exe test.py

does not work

**Comment by pstein** [comment]
I downloaded Winpython64-3.10.5.0dot.exe file from

https://sourceforge.net/projects/winpython/files/WinPython_3.10/3.10.5.0/

and simply extracted it.

On root level it consists of:

09.07.2022  20:09            60.440 IDLE (Python GUI).exe
09.07.2022  20:09            60.439 IDLEX.exe
09.07.2022  20:09           142.368 IPython Qt Console.exe
09.07.2022  20:09            75.292 Jupyter Lab.exe
09.07.2022  20:09            75.297 Jupyter Notebook.exe
16.03.2019  20:55             1.543 license.txt
09.07.2022  20:10    <DIR>          notebooks
09.07.2022  20:10    <DIR>          python-3.10.5.amd64
09.07.2022  20:09           145.433 Pyzo.exe
09.07.2022  20:09           152.094 Qt Assistant.exe
09.07.2022  20:09           144.412 Qt Designer.exe
09.07.2022  20:09           150.044 Qt Linguist.exe
09.07.2022  20:09    <DIR>          scripts
09.07.2022  20:09    <DIR>          settings
09.07.2022  20:09           342.048 Spyder reset.exe
09.07.2022  20:09           352.281 Spyder.exe
09.07.2022  20:10    <DIR>          t
09.07.2022  20:09           131.607 VS Code.exe
09.07.2022  20:09            73.241 WinPython Command Prompt.exe
09.07.2022  20:09           129.047 WinPython Control Panel.exe
09.07.2022  20:09            60.443 WinPython Interpreter.exe
09.07.2022  20:09           121.883 WinPython Powershell Prompt.exe
09.07.2022  20:09            92.703 WinPython Terminal.exe

**Comment by stonebig** [comment]
ok, so.... 

there is a  `D:\dev\v3\Scripts\register_python.bat ` that should allow to register, but there is not the equivalent to unregister yet. ...

**Comment by stonebig** [comment]
it's all related to https://github.com/winpython/winpython/issues/560 effort, that was not made.
not requiring Qt to do it / undo it is a first step to try

**Comment by stonebig** [comment]
hum, 

very old code, so needing "re-normalisation" to survive Win11. 

at current stage in winpython/associate.py, I need to do:
```
    # no more tolerated per windows:
    # wpdir = osp.join(target, os.pardir)
    from pathlib import Path
    wpdir = str(Path(target).parent)
```

**Comment by stonebig** [comment]
so the whole thing starts per modernizing os.path into pathlib.Path

**Comment by stonebig** [comment]
if we don't accept change requiring admin password, it still does the initial request you had...
so I will fix that minimum.

the admin seems necessary to have "start with IDLE", "start with Spyder", ...

**Comment by stonebig** [comment]
I would say it's solved in the most basic (historical) way per using wppm --register.

Next step is to explore/clean-up more this dusty '--register' thing and 'py.exe'

**Comment by stonebig** [comment]
register from Winpython Control Panel works again in Winpython 2022-04
