### ISSUE TITLE
WPy 3.11.01: Register distribution from control panel fails

### ISSUE THREAD

**Issue by jcwinkler** [winpython/winpython#1141]
**Related software**
- Winpython64-3.11.0.1dot.exe (at least)
- Windows 10 21H1 Build 19043.2130

**Steps to reproduce:**
1. Open the WinPython Control Panel
2. Choose `Advanced` - `Register distribution...`

**Observation** 
The WinPython Control Panel closes without any comments and the distribution is NOT registered

**Expected behaviour**
In previous versions a confirmation dialog opened discribing in detail what is going to happen. After confirmation the distribution has been registered. JupyterLab, Python interpreter and several other links appeared in the Windows start menu.

**Workaround**
1. Open a Windows Command Prompt
2. Changes into the `python-3.11.0-amd64` directory of your WinPython installation
3. Enter `python` to open the Winpython Python interpreter
4. Execute the following Python code:
```python
import os
from winpython import associate as wpa
wpa.register(os.getcwd())
```

**Comment by SalttownUser** [comment]
I have the same Issue on W10 21H2 Build 19044.2251

**Comment by stonebig** [comment]
Verzeihung, it was the 1st attempt to understand & clean-up that dusty code, and remove Qt requirement.

So focus was on "wppm --register" and "wppm --unregister" way to access it.

**Comment by stonebig** [comment]
just had added two  un-correct comas ...

https://github.com/winpython/winpython/blob/master/winpython/controlpanel.py#L779

https://github.com/winpython/winpython/blob/master/winpython/controlpanel.py#L799

**Comment by stonebig** [comment]
hum, same issue for the wppm command.... fixing it also
