### ISSUE TITLE
References in "Help" have issues in displaying and searching when created using Sphinx

### ISSUE THREAD

**Issue by GMGassner** [winpython/winpython#1192]
First I want to thank you @stonebig and the community for this amazing tool!

I might have encountered the first bug while using WinPython for years. If a .ipynb file is opened and python is selected as kernel, you can access the "Help" files and references for Python-specific packages.
If you open Sphinx-based references the icons are missing and in v5.3.0 (like matplotlib and SciPy) search doesn't work.
I hope to have covered all possible machine, user, and network-dependent variations. We have seen this behavior on multiple PCs and different users have experienced that issue.

e.g. matplotlib references 
![image](https://user-images.githubusercontent.com/29538920/215746806-65916770-f613-4de1-8490-9b96a680858b.png)
vs
![image](https://user-images.githubusercontent.com/29538920/215746911-ed18ad14-0247-454b-9967-5aea411aaa5f.png)

![image](https://user-images.githubusercontent.com/29538920/215747406-ce60bfb3-926b-4767-ac9c-f18dc35c67da.png)
vs
![image](https://user-images.githubusercontent.com/29538920/215747456-e664fcc8-80db-4b5b-bc49-45f1e915d896.png)

Thanks to my student Andreas for bringing it to my attention!

**Comment by stonebig** [comment]
Hi @GMGassner ,

Any idea of the fix that would work ? A similar issue in another project where we can look what they did ?

**Comment by stonebig** [comment]
Sphinx changes may happen with 6.0, not before.
A small animated showing the problem may help

**Comment by GMGassner** [comment]
> 


https://user-images.githubusercontent.com/29538920/216016871-1ad20195-4453-447d-8960-80b847f0abf6.mp4

Hi @stonebig ,
thanks for taking the time to investigate this issue. I did a short screen capture to present the problem.
- pandas kinda works but is without icons
- SciPy and NumPy search does not load
- matplotlib won't load at all, but after some time it loads although also no search

I did some digging and it might correlate with the iframe sandbox permissions or the permission of the browser to load from localhost. Also, I'm having trouble loading Developer Tools in chrome when I'm in the JupyterLab environment (never had this issue).

**Comment by stonebig** [comment]
well, well, .... I see. it was already not ok  with Jupyterlab-3.4.4 and sphinx-5.0.2
![image](https://user-images.githubusercontent.com/4312421/216136955-9880a6e9-d63a-481e-a91a-3aba35f34f23.png)

**Comment by stonebig** [comment]
found an old issue open in Jupyterlab about it , since 3 years.
https://github.com/jupyterlab/jupyterlab/issues/7506

**Comment by stonebig** [comment]
asked for direction on gitter for Jupyterlab https://gitter.im/jupyterlab/jupyterlab, let see.

**Comment by stonebig** [comment]
so, it's a security issue https://github.com/jupyterlab/jupyterlab/issues/7506#issuecomment-1413327601

**Comment by stonebig** [comment]
conclusion: not winpython's fault, nor ability to resolve
