### ISSUE TITLE
Add an "activate.bat" script calling "env.bat"

### ISSUE THREAD

**Issue by PierreRaybaut** [winpython/winpython#1208]
This would give "compatibility" with virtual environments: the %WINPYDIRBASE% directory would have a "script\activate.bat" script, as if it was a virtual environment.

I don't know if there is any side effect but if it's possible, one could simply rename "env.bat" to "activate.bat".

**Comment by stonebig** [comment]
"virtual environnements" are unknown territory... So at first, let's try  just calling env.bat ?


activate.bat=
````
@echo off
call "%~dp0env.bat"
````

**Comment by PierreRaybaut** [comment]
That's what the title of the Issue was initially suggesting, so 👍.
