### ISSUE TITLE
Will there be 32-bit builds for Python 3.11?

### ISSUE THREAD

**Issue by mojomojomojo** [winpython/winpython#1211]
The latest release only has 32-bit binaries for Python 3.10. Is WinPython ending support for 32-bit Python?

**Comment by mojomojomojo** [comment]
I have found building wxPython to be non-trivial. The documentation probably hasn't been updated in a while.

**Comment by stonebig** [comment]
a 32bit Python-3.12 build was released last cycle
- https://sourceforge.net/projects/winpython/files/WinPython_3.12/3.12.3.0/
- https://github.com/winpython/winpython/releases/tag/7.5.20240410final

**Comment by mojomojomojo** [comment]
> a 32bit Python-3.12 build was released last cycle

Sweet! Thanks.
