### ISSUE TITLE
IDLEX run IDLE instead

### ISSUE THREAD

**Issue by yasirroni** [winpython/winpython#1227]
I'm using 
Winpython64-3.10.9.0dot.exe available at https://github.com/winpython/winpython/releases/tag/5.3.20221233.

After installation, it seems that IDLEX launcher produce a plain IDLE. No feature mentioned in IDLEX [here](https://idlex.sourceforge.net/download.html) available.

**Comment by stonebig** [comment]
in small WinPythondot packages, the IDLEX packae is not included and defaults back to IDLE.
https://github.com/winpython/winpython/blob/master/changelogs/WinPythondot-64bit-3.10.9.0.md

on the big Winpython-3.10.9 it was included
https://github.com/winpython/winpython/blob/master/changelogs/WinPython-64bit-3.10.9.0.md

**Comment by stonebig** [comment]
it's only still there because still the basis of a French high schools exam. standard IDLE has the line numbering now.

**Comment by yasirroni** [comment]
I think it would be better that it is either deleted (there is still IDLE) or behaves like JupyterLab launcher (return error).

Because IDLEX launcher with IDLEX name but launch IDLE is part of, uhhhm, scam?

**Comment by stonebig** [comment]
done
