### ISSUE TITLE
“Winpython64-3.10.11.1.exe” Unable to decompress

### ISSUE THREAD

**Issue by superflq** [winpython/winpython#1235]
https://sourceforge.net/projects/winpython/files/WinPython_3.10/3.10.11.1/Winpython64-3.10.11.1.exe/download

MD5: 00abd0eb20b2a864559fa33e1e102795
MD5 is consistent, but cannot be decompressed
Repeated downloads have resulted in this error

![20230531_234206_138](https://github.com/winpython/winpython/assets/35949104/6766e987-b78c-4bf8-a30b-8e2befdd7a77)

**Comment by stonebig** [comment]
Hummm, checking...

**Comment by stonebig** [comment]
the end of creation log was already done, and there... so seems a 7zip fail or disk/ram fail....

**Comment by stonebig** [comment]
uploading to correction to github.

**Comment by stonebig** [comment]
end of repair of unexpected breakage... disk fail or 7zip fail, no way to finger point what went wrong.

**Comment by stonebig** [comment]
thanks for having well reported the issue.
