### ISSUE TITLE
DuckDB in Dot release

### ISSUE THREAD

**Issue by firai** [winpython/winpython#1246]
It appears that DuckDB was added to both the main distribution and the Dot version. Adding the package to the main distribution makes sense. However, it doesn't seem to be nearly as essential to the Dot version as the other packages. Furthermore, the package size of DuckDB seems to be somewhat large compared to the other components of the Dot version. Was adding DuckDB to the Dot version intentional?

**Comment by stonebig** [comment]
it was not intentional, a temporary test that remained by error.
