### ISSUE TITLE
Cannot import cartopy

### ISSUE THREAD

**Issue by foram-si** [winpython/winpython#1247]
I have tried the last few releases from WinPython64-3.11.4.0 to WinPython64-3.10.5.0. However, none of them allows me to import the cartopy library.  Does anyone have this problem? Any suggestion how can I fix it? 

ImportError: DLL load failed while importing trace: The specified module could not be found.

Many thanks

**Comment by ZhengXueke114** [comment]
1. form  [cgohlke/geospatial-wheels](https://github.com/cgohlke/geospatial-wheels/releases) Download `Cartopy-0.xx.x-cp310-cp310-xxxx.whl`
2. Use 7z or nanzip Open the whl file
3. copy `geos.dll` and `geos_c.dll` to `<Your winpython installation location>\WPy64-310111\python-3.x.x.amd64\Lib\site-packages\cartopy`

OR 

Install this whl directly with pip

**Comment by foram-si** [comment]
Hi ZhengXueke114

Thank you very much! It works!!

Earlier I went to Chris Gohlke’s site and got an older version Cartopy, proj, geos, Shapely but that particular version of Cartopy has another issue.

cheers

**Comment by stonebig** [comment]
At last, Cartopy project does wheels by itself, since yesterday.
That big pain in the build is gone and fresh new cartopy-0.22.0 wheel from pypi imports without error
will be in next build

**Comment by stonebig** [comment]
remains GDAL as the last problem.
