### ISSUE TITLE
Julia install documentation is out of date

### ISSUE THREAD

**Issue by Olaf987** [winpython/winpython#1261]
The installation instruction for Julia in "installing_julia_and_ijulia.ipynb" are severely outdated.

- The current version is 1.9.3. Downloading and extracting the file in t/julia and creating the settings file still works but all the hashes are out of date.
- The pip install is not needed anymore.
- Setting the environment variables is no longer required. They already exist.
- You need to add the package IJulia as well before Jupyter labs can create a Julia notebook: Pkg.add("IJulia")

I have tested this with the 2023-02 version using WinPython64-3.11.4.0.

**Comment by stonebig** [comment]
Thanks for the exploration.

As Julia as matured its own notebook, I thought nobody was interested anymore in this and nearly removed the code last month.
Did you do that per curiosity or for a real need ?

**Comment by Olaf987** [comment]
I am glad you didn't. It started out as curiosity. But this was the first time for me that the Julia-Jupyter chain worked in a portable environment without any hitches or requiring Windows surgery. I think you can congratulate yourself for having also created WinJulia. If it is not too much effort I recommend keeping Julia.

I would also grossly simplify the installation notebook. I would replace the download and installation part by simply instructing the user to download the portable Julia x64 zip file and extracting it into t/Julia. This is similar to the VScode install. Then then start with the environment stuff (I am not sure JULIAROOT is stil required. that one is not in env.bat) and  add IJulia to the packages.

If you want to I can update the notebook and send you my copy so you can commit it.

Olaf

**Comment by stonebig** [comment]
A pull request in winpython_afterdoc ?

**Comment by Olaf987** [comment]
I am not a git expert. I was raised on subversion. But I will give it a try.

**Comment by Olaf987** [comment]
Request made.  I hope this works for you

**Comment by stonebig** [comment]
looks good, thanks !

**Comment by stonebig** [comment]
I'm not a git expert either. always doing the same 3 commands
