### ISSUE TITLE
'C:\windows\system32\find.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by MagicalDrizzle** [winpython/winpython#1269]
I'm having trouble with `WinPython Command Prompt.exe`, it launches a terminal window with that message in the title, and afterward launching any binary (like `python`) will end up with that exact message repeated.

**Comment by stonebig** [comment]
Winpython version ?

**Comment by MagicalDrizzle** [comment]
Ah my apologies, 2023-03

**Comment by stonebig** [comment]
It may be similar to this https://github.com/winpython/winpython/issues/1262#issuecomment-1734319257

So try to replace in env.bat (in  "echo %winpydirbase%\scripts\env.bat"):
-  this:
````
 echo ";%PATH%;" | %FINDDIR%\find.exe /C /I ";%WINPYDIR%\;" >nul
if %ERRORLEVEL% NEQ 0 (
   set "PATH=%WINPYDIR%\Lib\site-packages\PyQt5;%WINPYDIR%\Lib\site-packages\PySide2;%WINPYDIR%\;%WINPYDIR%\DLLs;%WINPYDIR%\Scripts;%WINPYDIR%\..\t;%WINPYDIR%\..\t\Julia\bin;%WINPYDIR%\..\n;%PATH%;"
   cd .
)  
````
- per that
````
echo ";"%PATH%";" | %FINDDIR%\find.exe /C /I ";%WINPYDIR%;" >nul
if %ERRORLEVEL% NEQ 0 (
set PATH="%WINPYDIR%\Lib\site-packages\PyQt5;%WINPYDIR%\Lib\site-packages\PySide2;%WINPYDIR%;%WINPYDIR%\DLLs;%WINPYDIR%\Scripts;%WINPYDIR%..\t;%WINPYDIR%..\t\Julia\bin;%WINPYDIR%..\n;"%PATH%";"
cd .
)
````

That is replacing ;%PATH%; per ;"%PATH%";
All shall come from a BLANK SPACE bein in "%PATH%" variable

**Comment by MagicalDrizzle** [comment]
That didn't fix it unfortunately
`C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\(username)\AppData\Local\Microsoft\WindowsApps;`

**Comment by stonebig** [comment]
I'm out of clue.. re-extracting "Winpython64-3.11.5.0dot.exe" in a path with a black doesn't create errors on me
Maybe there can be:
- something odd related to Windows Vietnam, like in the japanese Windows `\` separator becoming `¥`
- something odd related to a special character in your username.

If you click directly on "scripts\cmd.bat" or "scripts\WinPython_Interpreter_PS.bat" and then it works, it may give a clue.

**Comment by stonebig** [comment]
The problem seems to be in the "PATH" variable after you clicked on the `WinPython Command Prompt.exe` , but I have on idea further

**Comment by MagicalDrizzle** [comment]
if so then may I ask what do the launchers actually do then? maybe I can execute the process manually to see what went wrong

**Comment by stonebig** [comment]
All launchers except the powershell one do use the script  /script/env.bat to get the correct path

They can call it indirectly, via script/env_for_icons.bat or another pre-layer

**Comment by MagicalDrizzle** [comment]
If it helps, 2016-01/WinPython-64bit-3.5.1.2Zero worked fine on my machine.
2016-02/WinPython-64bit-3.5.1.3Zero fails with `'cscript' is not recognized as an internal or external command,
operable program or batch file.`
All versions from 2016-03/WinPython-64bit-3.5.2.1Zero forwards fails with `'C:\windows\system32\find.exe' is not recognized as an internal or external command, operable program or batch file.`

**Comment by MagicalDrizzle** [comment]
I just want to say the new launcher works fine for me!
also antivirus seems to catch everything except virus...

**Comment by stonebig** [comment]
Getting rid of NSIS and vbs were two great moment of `liberation` from technical debt, after the ControlPanel on Qt

**Comment by MagicalDrizzle** [comment]
Do you wish for me to close the issues now then?
I do hope the false positive issues get solved soon - it would suck to finally get rid of the debt and then only able to put two packages back up
