### ISSUE TITLE
How to upgrade pip without loosing portability?

### ISSUE THREAD

**Issue by fhg-isi** [winpython/winpython#1287]
If I upgrade pip, pip stores an absolute path to python.exe and I loose portability of WinPython.
Does WinPython provide an alternative to 

`python.exe -m pip install --upgrade pip`

that keeps portability? 

(I opened the WinPython Control Panel and looked for a command "upgrade package" but did not find one.) 

Do I need to wait for the next version of WinPython to get current version of pip?

Also see

https://stackoverflow.com/questions/77001053/how-to-update-pip-and-keep-the-new-version-of-pip-portable-use-relative-path-t

**Comment by stonebig** [comment]
There is a script to restore portability , make_winpython-movable.bat, to restore portabilty

**Comment by fhg-isi** [comment]
Thank you. The path is WinPython/scripts/make_winpython_movable.bat
