### ISSUE TITLE
Spyder creating files in user's home directory

### ISSUE THREAD

**Issue by akujinnoninjin** [winpython/winpython#1307]
Not sure if this is intended behavior, but Spyder puts all of its config files in the user's local home directory - e.g. `C:\users\akujinnoninjin\`, despite the bat files creating a folder for them in the `<winpy>\settings` directory.

I've worked around this by setting the `HOME` env variable in `winpython.ini` to `..\settings`, but wanted to raise the issue.

Otherwise clean install of the 2024-01 / 3.11.8 full release, running from a USB stick.

**Comment by stonebig** [comment]
It's all depend  of what people need.
Default behavior is the simplest to maintain 
What you do is Typical way to change it.
