### ISSUE TITLE
simplify Winpython further

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#135]
Expected easy move:
- [x] remove `Add_or_removeLine.vbs', apparently no more used
- [x] remove Torthoisehg legacy code 
- [x] remove WinMerge legacy code
- [x] remove gettext legacy code
- [x] remove pre-mingwpy code, when mingwpy comes in
- [x] redo build documents following mingwpy move
- [x] remove scite.exe (note sure it is a good idea, but shipping a decrepited version is a bad idea)

Expected not easy move:
- [x] adding a package pre-selection logic per a requirements.txt
- [x] modernize/simplify wpcp launcher entry as entry point in the wheel
- [x] modernize/simplify wppm launcher/script as entry point in the wheel
- [x] reworking build system as most of the package list pre-selection logic is per a requirements.txt (definitely not easy, and ugly looking at first)
- [ ] simplify nsis icon creation code

**Comment by sebix** [comment]
> add nsis icon creator

If this is a tool to create icons as the name suggests, why? NSIS seems to be a tool to create packed executables. Icon creating tools are not in the scope what Winpython should provide IMHO.

**Comment by stonebig** [comment]
NSIS usage is in two places:
- creating the packed executable: zip the created "build" directory and wrap a basic unpacker around it 
- create the launcher icons.

A good part of the ugly remaining complexity of Winpython code is that icon creation. 
So I put it there, but you're right that it doesn't mean I should bundle it, for now.
==> changing to "simplify nsis icon creation code"

**Comment by stonebig** [comment]
failed on the last one. closing for cleanup of my checklist
