### ISSUE TITLE
Non-interactive installation results in wrong python version

### ISSUE THREAD

**Issue by liquidcarbon** [winpython/winpython#1355]
[Tried running the latest (3.12) installer with /passive flag and ended up with python 3.9.](https://github.com/liquidcarbon/puppy/actions/runs/9418394020/job/25945787089)

What's the recommended way to run non-interactive installs on Github Actions?

```
Run Invoke-WebRequest -Uri "https://github.com/winpython/winpython/releases/download/7.5.20240410final/Winpython64-3.12.3.0.exe" -OutFile "Winpython64-3.12.3.0.exe"

Run Start-Process -FilePath "Winpython64-3.12.3.0.exe" -ArgumentList "/passive"
  Start-Process -FilePath "Winpython64-3.12.3.0.exe" -ArgumentList "/passive"
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

Run $env:Path += ";C:\WinPython-64bit\python-3.12.3\Scripts"
  $env:Path += ";C:\WinPython-64bit\python-3.12.3\Scripts"
  python --version
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

Python 3.9.13
```

**Comment by stonebig** [comment]
maybe:
````
Run   $env:Path = "C:\WinPython-64bit\python-3.12.3\Scripts" + $env:Path 
  $env:Path = "C:\WinPython-64bit\python-3.12.3\Scripts" + $env:Path 
  python.bat --version
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

````

**Comment by stonebig** [comment]
or better ?:
`````
C:\WinPython-64bit\python-3.12.3\Scripts\Python.bat --version
````

**Comment by stonebig** [comment]
also maybe check the hash at arrival ?
 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | blake2b-256                                                     
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|-----------------------------------------------------------------
Bytes | 25b1156596aa8d6bb4dd7be5a8ac83cd6f5dabab09cfd0497575cc808edcd29f
b370dd44d87f8c60d6b5ffab78359d98 | b2ebae84570a8882006bf9f976e14fedfdbe5dd8 | 45d5ab340920f291a3497be30f05bb059d05ca15f5882f58fa943abf956de1ea | Winpython64-3.12.3.0.exe          |  894 147 283 Bytes | 258b2e67e81f7e79b345d5a4131345db19a7cbe04af462cbf67e1f6f13f9374a

**Comment by liquidcarbon** [comment]
looks like this is the way https://stackoverflow.com/a/32105548
`.\Winpython64-3.12.3.0.exe -y -gm2 -InstallPath="."`

**Comment by liquidcarbon** [comment]
[successful run](https://github.com/liquidcarbon/puppy/actions/runs/9423237037/job/25961209118)
so it takes a couple minutes to download and inflate, but it packs a lot of tools!

[my alternative takes slightly less time](https://github.com/liquidcarbon/puppy/actions/runs/9423237038) 
https://github.com/winpython/winpython/discussions/1342
