### ISSUE TITLE
Someone's code in Notebooks in 2024-03 release

### ISSUE THREAD

**Issue by aruss175** [winpython/winpython#1376]
If downloaded from https://github.com/winpython/winpython/releases/download/8.2.20240618final/Winpython64-3.12.4.1.exe:

Notebooks is pre-populated with what looks like to be *someone's* code:
![image](https://github.com/user-attachments/assets/e851ad57-c340-42f7-b18a-99c5f74fcc20)

ie "seaborn demo from Jake".

I am guessing this wasn't intended....

**Comment by stonebig** [comment]
It's examples from early days of jupyter and solutions to a pdf problem  for a specific audience .
 
 It's nevertheless a good remark that some examples are outdated or no-longer needed,

**Comment by stonebig** [comment]
Suggesting they should all be removed is an unexpected remark... needs thinking

**Comment by aruss175** [comment]
A clean up would be at least appreciated 👍 

In terms of all being removed - IMO running code with unclear and uncheckable origins is a security risk.  But the choice is yours.

**Comment by stonebig** [comment]
I understand, context has changed since 10 years

**Comment by stonebig** [comment]
done
