### ISSUE TITLE
Upgrade virtualenv to current 1.11.6

### ISSUE THREAD

**Issue by sebix** [winpython/winpython#15]
> Could I suggest upgrading virtualenv for the next release, it seems to be version 1.6.1 which is a couple of years old. Latest version should be: 1.11.6.

https://groups.google.com/d/msg/winpython/KcoibpKBG_k/sqw2nq5-IuMJ

**Comment by stonebig** [comment]
My understanding of this problem improved a lot thank the solving of #35.

There may be hope to have virtualenv working in winpython, but the path of least effort, for what I understand, is to first move 100% wheel format packages.

**Comment by stonebig** [comment]
virtualenv is a dependancy of Coverage. Maybe there is a functionnal justification to include it.

**Comment by stonebig** [comment]
That said, I have no clue:
- if virtualenv works well with winpython,
- what underlying support it means, for example how to behave in WPPM.

**Comment by stonebig** [comment]
Currently thinking about adding virtualenv+coverage, but not sure if it's more a pain or a service for Winpython builders and users.

**Comment by stonebig** [comment]
There is some discussion on mingwpy project, that shows that virtualenv is a complex subject: https://github.com/mingwpy/mingwpy.github.io/issues/31

**Comment by ogrisel** [comment]
Well the issue in mingwpy is a apparently just a bug in binutils that is revealed by virtualenv, not an issue with virtualenv itself. virtualenv is my primary way of setting Python dev envs and this is the first time in years that it caused an issue.

**Comment by stonebig** [comment]
ok. I see you use "virtualenv 1.14.1" the package. It was not clear to me if the internal Python "venv" version was to use.

**Comment by stonebig** [comment]
not my fight
