### ISSUE TITLE
Old website should link (or better: redirect) to github

### ISSUE THREAD

**Issue by rubenvb** [winpython/winpython#16]
I know this may seem very very silly, but when googling "winpython", you end up at one of these:
winpython.sourceforge.net
https://code.google.com/p/winpython/<some random subpage>

I was almost worried my favourite Python distro on Windows went stale (as these websites are out of date with respect to latest download versions).

Anyways, the github site isn't high on google ranking, and having outdated web pages not link here is not good for your business, I suppose. Just thought I'd give a heads up :-)

**Comment by stonebig** [comment]
two small changes during the end-of-year:
- scipy.org has redirected its link to winpython.github.io,
- I uploaded recent binaries on the old site too for 3.4/3.3/2.7.

**Comment by ankostis** [comment]
Still the most important issue, the missleading banner on the old site mentioning the ancient 2013 takeover, is still not fixed.  Most non-developers will get fooled pretty good by that :-)

**Comment by techtonik** [comment]
* [ ] https://code.google.com/p/winpython/ sidebar contains a broken link to Google Group
* [ ] http://winpython.sourceforge.net/ still doesn't have redirect to GitHub

This bug is marked as `help wanted`. How it can be helped?

**Comment by thorade** [comment]
https://code.google.com/p/spyderlib/
also contains an old/broken link

**Comment by sebix** [comment]
I neither have access to the project page at google (which can be scrubbed altogether I think) nor at sourceforge. Stonebig, what about you?
For the 2 links at the spyderlib page, I just contacted Gonzalo Pena.

Help is needed to spread the new link everywhere and contact people to update the links at their websites, just I now did. And to watch for old links ;)

**Comment by stonebig** [comment]
Only Pierre has access to https://code.google.com/p/winpython/

**Comment by sebix** [comment]
The links on https://code.google.com/p/spyderlib/ have been fixed by Carlos Cordoba, pinged by me.

**Comment by stonebig** [comment]
thanks , Sebastian !

**Comment by techtonik** [comment]
@stonebig, you are the one who can fix links on SourceForge site.

@isolver, and looks like you are the only one with access to https://code.google.com/p/winpython/ for fixing links there.

**Comment by stonebig** [comment]
Will do it within a month

**Comment by stonebig** [comment]
I'm not an html artist, but I think you should be satisfied now

**Comment by techtonik** [comment]
All link are broken. SourceForge gives 503. Groups link leads to nowhere.

* [ ] https://code.google.com/p/winpython/ sidebar contains a broken link to Google Group
* [ ] http://winpython.sourceforge.net/ still doesn't have redirect to GitHub

**Comment by stonebig** [comment]
hum, looking further

**Comment by stonebig** [comment]
and now ?

**Comment by techtonik** [comment]
:+1:  One minor nit though:

* [ ] https://code.google.com/p/winpython/ sidebar contains a broken link to Google Group

**Comment by stonebig** [comment]
ah, understood: I have no access to the old old website.

**Comment by ankostis** [comment]
My personal view is that the major obstacle for new winpython-users, the
outdated ownership notice, has been resolved. Almost nobody will stay in
the sourceforge-site  beyond the new "github" notice.

Thank you.

**Comment by jondo** [comment]
On http://winpython.sourceforge.net/, the text "Since September 2014, WinPython is hosted at http://winpython.github.io/" should link to http://winpython.github.io/, but currently links to the old https://sourceforge.net/projects/winpython/ .

**Comment by stonebig** [comment]
should be better now

**Comment by jondo** [comment]
Yes, thank you.

**Comment by stonebig** [comment]
As I was on my lost-for-html day, I tweaked also winpython.github.io.

I hope I didn't screw up anything in the process.

**Comment by techtonik** [comment]
Seems ok. Finally. =)

**Comment by thorade** [comment]
Bit late, probably everybody knows already:
http://google-opensource.blogspot.de/2015/03/farewell-to-google-code.html

**Comment by stonebig** [comment]
Yes, I should check if I removed the associated code.

**Comment by stonebig** [comment]
done, thanks for the remembering.
