### ISSUE TITLE
PyCurl

### ISSUE THREAD

**Issue by peervm** [winpython/winpython#161]
Any plans to add PyCurl?

Current PyCurl pre-built binaries don't support Python 2.7.10 because the Visual Studio has changed between 2.7.10 and 2.7.x.

Thanks.

**Comment by stonebig** [comment]
You may try:
- to download , then add via Winpython Control Panel the binary provided by Christoph Gohlke at http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl
- or just pip install pycurl

Maybe one of this solution work.

If none of them work, then I would suggest:
- using anaconda (unfortunately, pycurl seems only in there unix/mac versions)
- going the boot-to-docker way (in short, using virtualbox).

**Comment by stonebig** [comment]
well,

I was forced to try to use PyCurl because of latest JakeVanderplas blog:

https://jakevdp.github.io/blog/2015/10/17/analyzing-pronto-cycleshare-data-with-python-and-pandas/

Unfortunately, PyCurl never goes up to the end.... unstable in my opinion.
