### ISSUE TITLE
BUG: Spyder/IPython (WinPython 10.2014) can't be started under WinXP

### ISSUE THREAD

**Issue by GHPS** [winpython/winpython#17]
The problem: On my WinXP 32 machine I just tried to upgraded the WinPython 4.2014 installation to the brand new 10.2014 release. The previous version works fine, the current version doesn't hardly work  - Spyder, IPythonQT and IPython Notebook doen't start no matter how hard I try to tweak the settings. The problem seem to be serious meaning that WinPython 10.2014 and even 8.2014 are unusable under XP.

At least IPythonQT Console gives a long traceback with an "OSError: [WinError 127]" (Procedure not found) at the end. This led my to the statement of an developer of the Zero MQ  library (Christoph Gohlke) saying that the "Win 127" problem is not only known but expected in zmq and related to a missing DLL function in WinXP. 
http://github.com/zeromq/pyzmq/issues/521

Seemingly I'm the last user of WinPython on XP on this planet...

The solution: Transplant the working zmq lib. I took the current WinPython-3.3.5 installation, deleted the contents of "python-3.3.5\Lib\site-packages\zmq" and replaced it with the files of the same directory from WinPython 4.2013. Everthing works a treat now...

P.S. Since the zmq lib is compiled against Python 3.3 you can't switch to WinPython 3.4 before the original problem is fixed (or someone provides a compiled version). 
P.P.S. Seemingly Windows Server 2003 has the same problem
http://sourceforge.net/p/winpython/tickets/117/

**Comment by LifeCANvs** [comment]
> The problem: On my WinXP 32 machine I just tried to upgraded the WinPython 4.2014 installation to the brand new 10.2014 release. The previous version works fine, the current version doesn't hardly work - Spyder, IPythonQT and IPython Notebook doen't start no matter how hard I try to tweak the settings. The problem seem to be serious meaning that WinPython 10.2014 and even 8.2014 are unusable under XP.
> 
> At least IPythonQT Console gives a long traceback with an "OSError: [WinError 127]" (Procedure not found) at the end. This led my to the statement of an developer of the Zero MQ library (Christoph Gohlke) saying that the "Win 127" problem is not only known but expected in zmq and related to a missing DLL function in WinXP. [http://github.com/zeromq/pyzmq/issues/521](https://github.com/zeromq/pyzmq/issues/521)
> 
> Seemingly I'm the last user of WinPython on XP on this planet...
> 
> The solution: Transplant the working zmq lib. I took the current WinPython-3.3.5 installation, deleted the contents of "python-3.3.5\Lib\site-packages\zmq" and replaced it with the files of the same directory from WinPython 4.2013. Everthing works a treat now...
> 
> P.S. Since the zmq lib is compiled against Python 3.3 you can't switch to WinPython 3.4 before the original problem is fixed (or someone provides a compiled version). P.P.S. Seemingly Windows Server 2003 has the same problem http://sourceforge.net/p/winpython/tickets/117/

Hi. Is WinPython 10.2014 still available somewhere? I can not find it...
