### ISSUE TITLE
Missing PyQtdoc and Scidoc packages

### ISSUE THREAD

**Issue by PierreRaybaut** [winpython/winpython#173]
Everything is in the title: the documentation files (.qch files) are missing in the Qt5-based WinPython latest release. These documentation files are essential for any Qt programmer.

**Comment by stonebig** [comment]
in Qt4 I take the wheel of Christoph Gohlke, in Qt5 I take the executable of Riverbanks.

I'm surprised documentation would be in one and not in the other. did I miss-stepped somewhere ?

**Comment by PierreRaybaut** [comment]
I haven't been following WinPython for a while now, and I haven't checked if PyQtDoc is still included or not (because that's the package I was maintaining together with WinPython to include the qch doc: opening QtAssistant was directly showing the excellent Qt documentation). PyQtDoc and SciDoc were providing the minimum documentation that should be included in a distribution like WinPython.





De : stonebig
Envoyé : ‎lundi‎ ‎7‎ ‎septembre‎ ‎2015 ‎18‎:‎12
À : winpython/winpython
Cc : Pierre Raybaut





in Qt4 I take the wheel of Christoph Gohlke, in Qt5 I take the executable of Riverbanks.

I'm surprised documentation would be in one and not in the other. did I miss-stepped somewhere ?

**Comment by stonebig** [comment]
a yes, I did remove that when I was trying to keep download size in check while including a compiler.

**Comment by PierreRaybaut** [comment]
The other day I went to see a colleague using Python in another department and I was disappointed to see that he was abandoning WinPython because of the absence of embedded documentation. Actually we are forced to work on networks physically disconnected from the internet for security reasons and being forced to go to on an open network to download documentation is very annoying. This was one of the motivations for creating Python(x,y) (and then WinPython) in the first place.

So, I really think that it would be good to include valuable documentation as Qt (I don't know anyone developing with Qt that has not the documentation opened somewhere), NumPy and Scipy (and guidata, guiqwt and python-qwt...): this means re-including the packages named [PyQtdoc](https://pypi.python.org/pypi/PyQtdoc) and [SciDoc](https://pypi.python.org/pypi/Scidoc), which are very easy to maintain. Even Spyder is ready for this as the "Help" links were adapted to WinPython documentation location specifics.

**Comment by stonebig** [comment]
Well:
- there was/could be multiple flavors of Winpython,
- the problem is resources, interest, and acheiving the build-in-the-cloud strategy.

At the moment, I cannot do more than focus on the need of my own collaborators.

Basic suggestions of tonight is:
- re-download current material, add your whished package, build and upload to Winpython sites the flavor of your interest (I gave you all the rights, I hope)
- develop a better way like using https://git-lfs.github.com and appveyor
- get back control of winpython for a while.

**Comment by PierreRaybaut** [comment]
I would suggest something less drastic: just include the PyQtdoc and SciDoc packages again in WinPython. At each new release, you would ask me and I would build those packages just like old times, making them available in PyPI in the form you like.

Another argument in favor of including PyQtdoc again: without Qt docs, QtAssistant is an empty shell, you have to realize that. Having an application opening an empty documentation is quite bizarre.

**Comment by stonebig** [comment]
Everything request you have would be a no-brainer, if Winpython could be build in a cloud.

**Comment by PierreRaybaut** [comment]
I'm no following you. SciDoc and PyQtdoc are packages like others available in PyPI. I don't see the difference with guidata, guiqwt and PythonQwt for example.

**Comment by stonebig** [comment]
For sure, the PyQtdoc package on Pypi would be nice to have updated. Benefit would not be limited to Winpython : https://github.com/ContinuumIO/anaconda-issues/issues/438#issuecomment-137769852

**Comment by PierreRaybaut** [comment]
Done: [PyQt 4.8.7 is available on PyPI](https://pypi.python.org/pypi/PyQtdoc).

**Comment by PierreRaybaut** [comment]
As for SciDoc, I'll wait until guidata 1.7, guiqwt 3.0 and PythonQwt are released officially. In a few days hopefully.

**Comment by stonebig** [comment]
Would a PyQt5Doc be possible ? and if it makes sense a pyqtdesignerplugins for Qt5 ? 

Indeed:
- I strongly hope Qt5 will more help than arm in the "web technologies" transition, 
- on the opposite, I'm convinced Qt4 is a growing problem (because of web sockets and other things),
- providing an equal or better experience on Qt5 is critical to help that transition.

**Comment by PierreRaybaut** [comment]
Here is the PyQtdoc package for Qt 5.5.1: [PyQtdoc 5.5.1](https://pypi.python.org/pypi/PyQtdoc/5.5.1)

Please take a look at the "Important note".

**Comment by PierreRaybaut** [comment]
The "important note" I was referring to is the fact that, since Qt5, QtAssistant is no longer registering automatically all qch files in `Lib\site-packages\PyQt5\doc\qch`: execute `assistant.exe` with a collection file as argument.

The first solution is to register all .qch files:
1. either by executing PyQtdoc postinstallation script,
2. or by executing the batch script from WinPython command prompt (see code below).

```cmd
@echo off
call %~dp0env.bat
cd "%WINPYDIR%\Lib\site-packages\PyQt5\doc\qch"

REM Registering those help files separately to place them above the others
assistant.exe -quiet -register qtdoc.qch
assistant.exe -quiet -register qtassistant.qch
assistant.exe -quiet -register qtdesigner.qch
assistant.exe -quiet -register qtlinguist.qch
assistant.exe -quiet -register qtgui.qch
assistant.exe -quiet -register qtcore.qch

REM Registering all the help files in Lib\site-packages\PyQt5\doc\qch
for %%i in (*.qch) do assistant.exe -quiet -register %%i

REM Starting QtAssistant
start assistant.exe
```

Another solution would be to use a collection file. That is the cleanest way of using QtAssistant apparently. This can be done like this: `assistant.exe -collectionFile filename.qhc`. But a collection file project has to be written first and the collection file has then to be generated using `qcollectiongenerator`. Unfortunately, during my tests, something broke and the collection file isn't working anymore without any apparent reason...

So let's fall back to solution 2. explained above: in WinPython, one could modify the NSIS script for the QtAssistant launcher in order to integrate the registration step done by the attached script.

**Comment by stonebig** [comment]
we can launch this command before zipping the distribution, or it can be in wppm.

I do the first solution for 3 packages currently, via `run_complement.bat`:
````
@echo off 
rem %1 is WINPYDIR being prepared
rem this .bat is placed at root (buildir34, buildir34\FlavorJulia, ...)
set origin=%~dp0
set new_winpydir=%1


cd /d %new_winpydir%

call scripts\env.bat

echo =================
echo configure ipython-parallel
echo =================
jupyter-notebook.exe --generate-config

echo c.NotebookApp.server_extensions.append('ipyparallel.nbextension')>>"%winpydir%\..\settings\.jupyter\jupyter_notebook_config.py"

echo =================
echo finish install of bqplot
echo =================
if exist  "%WINPYDIR%\Lib\site-packages\bqplot" %WINPYDIR%\python.exe -m bqplot.install --user --force

echo =================
echo finish install seaborn iris example
echo =================
if exist  "%WINPYDIR%\Lib\site-packages\seaborn" %WINPYDIR%\python.exe -c "import seaborn as sns;sns.set();sns.load_dataset('iris')"

````

**Comment by stonebig** [comment]
a yes, my QtAssistant 5.5.1 is less empty now

**Comment by stonebig** [comment]
````

echo =================
echo finish install PyQtdoc
echo =================
if exist  "%WINPYDIR%\Scripts\PyQtdoc_win_post_install.bat" "%WINPYDIR%\Scripts\PyQtdoc_win_post_install.bat" "-install"

````

**Comment by stonebig** [comment]
heum, shipping now Matplotlib 1.5.0

**Comment by stonebig** [comment]
PyQt5.6 wheel containing less added features, I drop this idea. Qt will be used through intermediate libraries like PythonQwt, PyQtgraph, QtConsole, ... etc ....
