### ISSUE TITLE
make pip fly

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#182]
https://github.com/pypa/pip/issues/2328#issuecomment-145976719

I agree there should be a make_pip_fly.bat script added to simplify things. something like:
````
@echo off
call %~dp0env.bat
echo patch pip
%WINPYDIR%\python.exe -c "from winpython.utils import patch_sourcefile;patch_sourcefile(r'%WINPYDIR%\Lib\site-packages\pip\_vendor\distlib\scripts.py', 'executable = get_executable()', 'executable = os.path.join(os.path.basename(get_executable()))' )"
````

**Comment by stonebig** [comment]
we can do it both ways, so clicking on sqlite_bro.exe could work (even if not truly the same as starting winpython, as the path is not initialised

**Comment by stonebig** [comment]
bath will be:
- make_winpython_fix.bat
- make_winpython_movable.bat

but maybe it's horrible frenchglish ?

**Comment by stonebig** [comment]
https://github.com/stonebig/winpython/commit/1080831930a1dedaf6a0c3019e7150b46a138357

**Comment by ankostis** [comment]
@stonebig  just because this issues comes up in google-searches,
can you please explain what is the difference between these 2 scrips?

**Comment by stonebig** [comment]
in a normal PYTHON installation each executable in python base directory contains the absolutes executable path to `python.exe`, via a single pip package instruction:
```` executable = os.path.join(os.path.basename(get_executable())````

winpython is build by replacing the pip instruction per
````  executable = (get_executable())````

`make_winpython_fix.bat` is removing this winpython twist by per the original way-of-python-life in all executable.
```` executable = os.path.join(os.path.basename(get_executable())````

`make_winpython_movable.bat` is re-applying the Winpython build trick on pip package, and on already installed executable.


Do I explain myself good enough ?

`upgrade_pip.bat` is the last of the three trick:
- when updating `pip`, the updated pip is again in  original way-of-python-life,
- so this script updates pip and then re-apply the pip original WinPython patch on it:
   ````  executable = (get_executable())````

WinPython is basically a one-liner

**Comment by ankostis** [comment]
The code `executable = os.path.join(os.path.basename(get_executable())` can't be actually correct, I mean, it is missing the file-part, correct?
Maybe you mean:

    executable = os.path.join(os.path.basename(get_executable(), get_executable())

**Comment by stonebig** [comment]
in thos pip file:
https://github.com/pypa/pip/blob/master/src/pip/_vendor/distlib/scripts.py#L176

the line
````
 executable = get_executable()
````
is replaced per
````
 executable = os.path.join(os.path.basename(get_executable()))
````
per the magic of 
https://github.com/winpython/winpython/blob/master/winpython/wppm.py#L474..L479
