### ISSUE TITLE
Cannot switch to Tkinter via "%matplotlib tk"

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#192]
In Spyder's IPython shell of `WinPython-64bit-3.4.3.6.exe`, I can use `%matplotlib qt` and `%matplotlib inline` to switch between those interfaces. However, when I try to switch to Tkinter, I see
```
In [17]: %matplotlib tk
Warning: Cannot change to a different GUI toolkit: tk. Using qt instead.
```

Switching to Tkinter via Tools -> Preferences -> IPython console -> Graphics -> Backend works.

**Comment by jondo** [comment]
Ah! - One can only use one GUI toolkit per IPython shell, and I have used `%matplotlib qt` there before.

**Comment by jdhao** [comment]
There is another explanation that you can not change the GUI backend half in the ipython shell, http://python.6.x6.nabble.com/changing-plotting-backend-td5051966.html. But you can switch between inline mode other GUI backend.
