### ISSUE TITLE
Left parenthesis key not working in editor

### ISSUE THREAD

**Issue by ezbentley** [winpython/winpython#193]
I noticed that if 'Automatic insertion of parentheses, braces and brackets' is unchecked, then I cannot input the left parenthesis in the editor. This just started to happen with the latest release.

**Comment by stonebig** [comment]
It looks like a Spyder3 bug. Don't you want to post the issue on the spyder-ide project ? (otherwise I will)

**Comment by stonebig** [comment]
@ezbentley ,

If you have 2 minutes, you can fix it yourself by retyping these 2 lines in your `Lib\site-packages\spyderlib\widgets\sourcecode\codeeditor.py` (starting line 2607):
https://github.com/spyder-ide/spyder/pull/2810/files

**Comment by stonebig** [comment]
So it's a Spyder bug, introduced in Spyder 3.0 branch last june.

**Comment by ezbentley** [comment]
Thanks!

**Comment by stonebig** [comment]
so this one is fixed by hand in current build6.
