### ISSUE TITLE
Did WinPython drop MKL?

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#194]
In the change log for WinPython 3.4.3.6, I see that MKL has been dropped from the description of NumPy.  Does this mean that WinPython is using the vanilla build from Christoph Gohlke?
http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

I notice that Gohlke doesn't support the latest NumPy 1.10.1 with vanilla.

I also notice that Gohlke's vanilla build for NumPy 1.9.3 is dated September 22, which is before OpenBLAS 0.2.15 was released.  I tested OpenBLAS 0.2.14, and it is seriously slow!

For me, MKL is very important because OpenBLAS doesn't support the feature of dynamic number of threads, and my simulations often run for several days.
https://github.com/xianyi/OpenBLAS/issues/678

For now, I will stay with WinPython 3.4.3.5.  However, I hope the next version of WinPython will include NumPy+MKL.

**Comment by carlkl** [comment]
a quick check shows that winpython-64bit-3.4.3.6QT5 uses numpy-1.9.3-MKL. I doubt that any OpenBLAS based packages are included in winpython. Also the mingwpy package is delivered without OpenBLAS.

**Comment by stonebig** [comment]
Hi @hiccup7 

The numpy shipped by Winpython is still the one made by Christoph Gohlke, with the **MKL**.

There has been module "naming" change by Christoph Gohlke, so your sudden worries.

**Comment by hiccup7** [comment]
Thanks to @carlkl and @stonebig for the clarification.  I will continue with the upgrade to WinPython 3.4.3.6.  WinPython continues to be the fastest high performance computing (HPC) language I have found (besides assembly code) for one-dimensional data on a personal computer due to MKL's optimized multi-threaded SIMD performance.
