### ISSUE TITLE
nosetests.exe fails with "Fatal error in launcher: Unable to create process"

### ISSUE THREAD

**Issue by windancert** [winpython/winpython#195]
The supplied nosetests.exe in the scripts directory does not work in latest versions.
When I try to run it it fails with a message like this:
> E:\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\Scripts>nosetests.exe e:\source\src
> Fatal error in launcher: Unable to create process using '"python.exe"  "E:\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\Scripts\nosetests.exe" e:\source\src'

I got similar errors with the following versions:
* WinPython-64bit-2.7.10.2.exe
* WinPython-32bit-2.7.10.2.exe
* WinPython-64bit-2.7.10.3.exe

Running the Python interpreter does work:
> E:\WinPython-64bit-2.7.10.2\python-2.7.10.amd64>python
> Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
>  \>>> exit()

**Comment by stonebig** [comment]
Yes, it's normal: 
- when you directly clik on nosetest.exe it looks for python.exe present in your curent path, as it's internal directive is to use "python.exe"
- to have it working by default:
  - launch \winpython-2.7.10.3\scripts\cmd.exe
  - then type, for example: `cd %winpydir%&nosetests.exe` 

But today, you have another option:
- launch \winpython-2.7.10.3\scripts\make_winpython_fix.bat
- now doubleclick on `nosetests.exe`

**Comment by stonebig** [comment]
to sum-it up, it's normal
