### ISSUE TITLE
Error with print when running script with Idle (Python 2.X)

### ISSUE THREAD

**Issue by etiennecha** [winpython/winpython#203]
I've just installed WinPython-64bit-2.7.10.3 and run a script using "WinPython-64bit-2.7.10.3\python-2.7.10.amd64\Lib\idlelib\idle.bat -r". Any traditional 2.7 python print statement (e.g. print 'test') yields an error... which disappears when using print(). If I run use print 'test' in interactive mode, it works as expected... so I suspect that there is an issue with pre-execution parsing when running idle. Can anyone reproduce and/or provide a hint as to how to fix this issue?

**Comment by stonebig** [comment]
why not clicking on the IDLE icon directly ?

otherwise "WinPython-64bit-2.7.10.3\python-2.7.10.amd64\Lib\idlelib\idle.bat" works

**Comment by stonebig** [comment]
you may try "print (1/2)" to verify it is a python 2 that runs

**Comment by etiennecha** [comment]
I did try "print 'test'" under Idle and it definitely is python 2. The problem only occurs when I run my script using Idle from the command line (which works fine with previous versions of winpython that I still have). Given the issue, it really looks like that running Idle as I do triggers some parsing that wrongfully requires python 3 syntax.

**Comment by stonebig** [comment]
I didn't find any "idle.bat -r" example page, so I don't really know what is the normal behavior.

**Comment by etiennecha** [comment]
I use "idle.bat -r myscript.py" to run my script with Idle and keep Idle open in interactive mode. I am confused since I just re-installed winpython (on another computer) and it now seems to work fine... so maybe there is something wrong with my vim config or whatever... I'll look into that. I'm very sorry to have bothered you for nothing.

**Comment by stonebig** [comment]
no problem, it happens also to me sometimes.
