### ISSUE TITLE
Wiki How To Make WinPython: Page no longer available

### ISSUE THREAD

**Issue by jrast** [winpython/winpython#214]
The path given in the Wiki "How To Make WinPython" no longer available.
https://sourceforge.net/projects/stonebig.u/files/Do_It_Yourself/Winpython_2015-06/

I think the same resources are now under http://sourceforge.net/projects/winpython/files/WinPython_Source/Do_It_Yourself/

**Comment by stonebig** [comment]
oups ! you're right...

**Comment by jrast** [comment]
Ok, the links are now working.

But the downloads "package.win32" and "packages.win-amd64" are corrupt (can't be opened with 7zip) 

Should I open a new ticket for this problem?

**Comment by jrast** [comment]
I also checked the files in http://sourceforge.net/projects/winpython/files/WinPython_Source/Do_It_Yourself/Winpython_2015-07/basedir34/. It seems that the file "packages.srcreq.zip" is also corrupt.

**Comment by stonebig** [comment]
let me check the sha1/md5

**Comment by stonebig** [comment]
so, "packages.screq.zip", when shown to me on sourceforge has the sames md5 and sha1 as the original on my pc:
````
//
// File Checksum Integrity Verifier version 2.05.
//
		MD5				SHA-1
-------------------------------------------------------------------------
74ce15c774cd8e9a779bdb8ca60ef924 1955901b67d13d5fc95dd04ae7571d9543fb7391 winpython_2015-10-28\basedir34\packages.srcreq.zip
````
![check_packages srcreq_sourceforge](https://cloud.githubusercontent.com/assets/4312421/11633484/daa73798-9d0b-11e5-8142-7949a540eddf.GIF)
