### ISSUE TITLE
generating pdf from notebook

### ISSUE THREAD

**Issue by pvtodorov** [winpython/winpython#216]
I keep trying to save notebooks as pdf via the Jupyer dropdown menu  and getting the error:
nbconvert failed: pdflatex not found on PATH

After some searching I've found out that I should download and install a LaTeX distribution that includes pdflatex and add it to path. Has anyone done this? Also, I do not have admin rights on my machine and both WinPython and Miktex will be installed as portables, so I am not sure how I would point WinPython to the Miktex portable

I'm using WinPython-64bit-3.4.3.6 but I haven't been able to export notebooks to pdfs in previous installs either.

**Comment by stonebig** [comment]
hi @pvtodorov ,

on this, a solution recently started to appear [nbbrowserpdf]](https://github.com/Anaconda-Server/nbbrowserpdf).

But I didn't check if it was ok yet with WinPython 3.4 or 3.5 . Can you have a look and tell us ?

**Comment by pvtodorov** [comment]
On 3.4 It gets through the first line of instructions:



!pip install https://github.com/Anaconda-Server/nbbrowserpdf/archive/master.zip

Collecting https://github.com/Anaconda-Server/nbbrowserpdf/archive/master.zip
  Downloading https://github.com/Anaconda-Server/nbbrowserpdf/archive/master.zip
Collecting pypdf2 (from nbbrowserpdf==0.2.1)
Collecting ghost.py (from nbbrowserpdf==0.2.1)
Installing collected packages: pypdf2, ghost.py, nbbrowserpdf
  Running setup.py install for nbbrowserpdf
Successfully installed ghost.py-0.2.3 nbbrowserpdf-0.2.1 pypdf2-1.25.1





But then there's an error:




!python -m nbbrowserpdf.install

Traceback (most recent call last):
  File "C:\Users\abcd123\Desktop\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\abcd123\Desktop\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\abcd123\Desktop\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\nbbrowserpdf\install.py", line 93, in <module>
    from notebook.nbextensions import install_nbextension
ImportError: No module named 'notebook'

**Comment by stonebig** [comment]
at the moment, this new solution doesn't work with PyQt5.

**Comment by stonebig** [comment]
you're testing on Winpython-3.4.3.5, which is tool old (Ipython3.2 aera).

This new package, being new, suppose you have Ipython4.0 or better ==> Winpython-3.4.3.6 at least

**Comment by stonebig** [comment]
another option may rise for pdf: https://github.com/podoc/podoc

**Comment by stonebig** [comment]
in theory, that feature may be also possible via coming PyQt5.7.

**Comment by stonebig** [comment]
looks like a no-way idea:
- podoc development is stopped
- PyQt5.7 does not pdf from others
- pandoc needs pdflatex
