### ISSUE TITLE
PyQt5 issue 

### ISSUE THREAD

**Issue by dacoex** [winpython/winpython#234]
Hello,

is PyQt5 installed along with WinPython?

Using pip-installed retext I run into an issue saying the PyQt5 is not properly installed.
https://github.com/retext-project/retext/issues/183

Thanks.

**Comment by stonebig** [comment]
Hi @dacoex 

I see in your link that you are using virtualenv. I don't think WinPython works well with "virtualenv"

PyQt5:
- is in following WinPython:
 - WinPython-64bit-3.4.3.7Qt5.exe
 - WinPython-32bit-3.4.3.7Qt5.exe
 - WinPython-32bit-3.4.3.7Slim.exe
- is installed in there via the binary installer provided by [Riverbanks](https://www.riverbankcomputing.com/software/pyqt/download5), and not via pip,
- so may even less "friendly" to use in virtualenv,

==> try to work without virtualenv and with one of the suggested WinPython

**Comment by stonebig** [comment]
news from PyQt https://www.riverbankcomputing.com/pipermail/pyqt/2016-January/036836.html

````
PyQt v4
-------

PyQt v4.12 will be released soon. As Qt v4 is no longer supported, v4.12.x will be the last series of releases. It will support both SIP v4 and SIP v5. It will be supprted for the forseeable future but new releases will be relatively infrequent.

PyQt v5
-------

PyQt v5.6 will be released soon - depending on the release of Qt v5.6. New features of Qt will be added to PyQt as usual. It will support both SIP v4 and SIP v5. It is possible that new features may depend on SIP v5, but it will still be possible to use SIP v4 with those features disabled. It is planned that the Windows binary installers will no longer include Qt itself. This has become possible because installers for Python and Qt should be available that have been built with compatible compilers. It may even be possible to replace the PyQt installers with downloads from PyPi.
````

**Comment by stonebig** [comment]
there is a growing possibility that I drop every non-wheel things. So if PyQt5 cannot materialize as a wheel, I may drop it.

**Comment by stonebig** [comment]
it materializes, for now as dev wheels from Phil Thomson and with minimal QT included.

https://www.riverbankcomputing.com/software/pyqt/download5

great news.

**Comment by stonebig** [comment]
apparently no more Qtassistant/Qtdemo/QTdesigner in PyQt5.6 wheel...

**Comment by stonebig** [comment]
Qt 5.6 is now possible for WinPython 3.5, issues are on spyder/WinPython now. closing this one and opening a new one.
