### ISSUE TITLE
Add xlwings package

### ISSUE THREAD

**Issue by fzumstein** [winpython/winpython#24]
Good to see that the project is being continued! Any chance that you can add `xlwings` to the packages?

**Comment by stonebig** [comment]
I still don't feel comfortable with the dll part. For this technical aera around Excel, I'll wait for a Microsoft sponsorized move.

**Comment by akapocsi** [comment]
Anyway you can revisit this?

**Comment by stonebig** [comment]
thinking about it at each release, following xlwings progress.

**Comment by akapocsi** [comment]
Great. That's all we can ask for.

Thank you.

**Comment by stonebig** [comment]
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/Y80YhkXHOtM

**Comment by stonebig** [comment]
@akapocsi did you try a pip install on your favorite winpython ?

**Comment by stonebig** [comment]
how do I generate xlwings32.dll ?

**Comment by fzumstein** [comment]
Take them from the pypi package. Note that 32/64 refers to the Excel
version, so you'll need both dlls in both (32 and 64bit) version of
WinPython.
 If you wanted to compile the dlls on your own, you'd need to open the src
folder in VS 2015, but there's really no point in doing that.

**Comment by stonebig** [comment]
yes. rediscovering the things as I walkthrough it. 

I saw a python3 bug on github.comtypes, so I suppose using comtypes master is better if target is Python 3.4/3.5 ?

**Comment by fzumstein** [comment]
we're not using generated code by comtypes so for the purpose of xlwings it
shouldn't matter. the released version works fine.

**Comment by stonebig** [comment]
so comtypes is not a requirement ?

**Comment by fzumstein** [comment]
yes, it is a requirement, but I think the bug that you refer to only
materializes if you run GetModule to generate some Python wrapper module
and this part is not used from xlwings.

**Comment by stonebig** [comment]
ok.

**Comment by akapocsi** [comment]
Yes, the pip install worked.

**Comment by stonebig** [comment]
http://www.aaronschlegel.com/wp-content/uploads/2014/06/Python-Excel-Data-Analysis.html

**Comment by stonebig** [comment]
<3

**Comment by stonebig** [comment]
done
