### ISSUE TITLE
IPython Qt Console DOS Window

### ISSUE THREAD

**Issue by thorstenkampe** [winpython/winpython#240]
IPython Qt Console opens with a blank DOS window:
![image](https://cloud.githubusercontent.com/assets/475462/12728325/912b42ca-c921-11e5-9b73-4b19ca4a5a41.png)

**Comment by stonebig** [comment]
Yes. it works nevertheless. This is the way "jupyter-qtconsole.exe" starts.

To workaround that detail, we would need to bypass "jupyter-qtconsole.exe"

**Comment by stonebig** [comment]
here https://pythonhosted.org/setuptools/setuptools.html , it seems that suggesting 'gui_scripts' instead of 'console_scripts' may have a positive effect, but only the qtconsole packagers can decide to change their `https://github.com/jupyter/qtconsole/blob/master/setup.py`

**Comment by thorstenkampe** [comment]
I was able to wrap the executable with `hstart` (Hidden Start) so the DOS window is gone. Thanks.

**Comment by stonebig** [comment]
hstart ?

**Comment by thorstenkampe** [comment]
http://www.ntwind.com/software/hstart.html

**Comment by stonebig** [comment]
hum, it's a bit of a hammer.

**Comment by stonebig** [comment]
fixed upstream https://github.com/jupyter/qtconsole/pull/97

you will have it in next release of qtconsole
