### ISSUE TITLE
vitables does not start

### ISSUE THREAD

**Issue by dacoex** [winpython/winpython#243]
Using

````
"C:\Users\USER\WinPython-64bit-3.4.3.7\python-3.4.3.amd64\Scripts\vitables.bat"
```
nohing happens:
```
@echo off
python "%~dpn0" %*
```

**Comment by stonebig** [comment]
hi, the correct procedure is:
- click on "WinPython Command Prompt.exe"
- type "vitables" 

But maybe could it be simpler (not sure):
- edit the 'vitables.bat' file and replace "python" per "..\python"
- double click on it.

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/pull/247

**Comment by stonebig** [comment]
it does apply on .exe also .... so all the basic .exe could work by double click (in in Script, yet stay a portable Winpython).
