### ISSUE TITLE
Python with WinPython-64bit-3.5.1.2 refuses to start on Windows 7

### ISSUE THREAD

**Issue by jhillairet** [winpython/winpython#245]
Under Windows 7, once installed, python.exe shows the following system error message : 
"The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer."

After googling, it seems this problem is link to Windows update (it can't update myself my company-computer)
https://support.microsoft.com/en-us/kb/2999226

**Comment by jhillairet** [comment]
This can be solved by installing Microsoft Visual C++ Redistributable for Visual Studio 2015 Update 1
http://www.microsoft.com/en-us/download/details.aspx?id=49984

**Comment by stonebig** [comment]
The default solution is to install KB2999226 of Microsoft

https://support.microsoft.com/en-us/kb/2999226

I hoped Microsoft was going to push it on Windows 7 this december 2015, but they apparently didn't.

**Comment by stonebig** [comment]
action:
- [x specify it in the release note,
- [ ] mention it on the web site.

**Comment by hiccup7** [comment]
It looks to me like installing "Microsoft Visual C++ Redistributable for Visual Studio 2015 Update 1" would be a better default solution for the WinPython release notes and web site.  Under "Details", Microsoft says that it includes updated versions for KB 2999226.

@jhillairet - thanks for the link!

**Comment by stonebig** [comment]
ah, I will have to check that update. also maybe I'm updated after having installed  the KB 2999226.

**Comment by stonebig** [comment]
receipe to prepare a WinPythn3.5 32 bit:
- get missing dll
 - [x] download vc-redist_x64.exe and vc_redist_w86.exe from above link
 - [x] install them (version 14.0.23506 )  => will be taken in next build of WinPython3.5

- prepare WinPython3.5 32 bit zip installer:
  - download official Python3.5.1.exe installer
  - install it via following command:
    python-3.5.1.exe TargetDir=D:\WinPython\basedir35\winpython-3.5.1\python-3.5.1 /quiet  InstallAllUsers=0 Include_launcher=0 InstallLauncherAllUsers=0 Include_test=0  AssociateFiles=0 Shortcuts=0
  - wait for end of execution (hidden process)
  - zip result 'python-3.5.1' and place it  in basedir35\packages.win32\python-3.5.1.zip



- [ ] release a WinPython3.5.1.2Zero 32 bit to see.
