### ISSUE TITLE
Could you provide a 32 bit build of 3.5, please?

### ISSUE THREAD

**Issue by KOLANICH** [winpython/winpython#246]

**Comment by stonebig** [comment]
here they are, as release candidates: https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.1.2/betas:
- WinPython-32bit-3.5.1.2rc.exe
- WinPython-32bit-3.5.1.2Zerorc.exe

**Comment by stonebig** [comment]
will become official:
- when I get confirmation it fits on Windows 32 bit (no access to one currently)
- or in a few days

**Comment by KOLANICH** [comment]
Thank you. Python interpreter seems to be working.

**Comment by stonebig** [comment]
Thanks for the feedback. Have a nice day.
