### ISSUE TITLE
sframe for python3 and under Windows

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#249]
https://s3.amazonaws.com/static.dato.com/files/sframe/SFrame-1.9-cp34-none-win_amd64.whl

it's 26 Mo, it's beta1. It's not small

**Comment by stonebig** [comment]
http://www.kdnuggets.com/2016/02/scikit-flow-easy-deep-learning-tensorflow-scikit-learn.html?utm_content=buffer7f2e5&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by arita37** [comment]
It seems the link of SFRAME is broken.

**Comment by stonebig** [comment]
Yes, they apparently change name from "dato.com" to "turi.com".

I'm no more sure that sframe has a short-term future: 
- I heard of it because WesMcKinney (pandas) wanted a solution, and now he is preparing one with Hadley Wickham (R king),
- the Python distribution with investment capacities (Continuum io) is making progress without Sframe.

**Comment by stonebig** [comment]
Turi/sframe aquired by Apple ... consider it dead http://www.geekwire.com/2016/exclusive-apple-acquires-turi-major-exit-seattle-based-machine-learning-ai-startup/
