### ISSUE TITLE
Question: How is the "Zero" version smaller than standard Python?

### ISSUE THREAD

**Issue by dougthor42** [winpython/winpython#252]
In the release notes for [`WinPython 2015-08`](https://github.com/winpython/winpython/releases/tag/1.3.20151212), it says

> zero = basic portable Python (even smaller than standard Python)

I'm just curious: how is that possible? I plan on using the `zero` size as the base for some windows CI servers and am wondering if it will be any different from a standard python install. Of course, there will be a couple extra packages (winpython, idlex, etc), but I'm mainly concerned if anything is missing.

(The CI on windows thing is a long story... The short version is I don't have an Azure server so I can't use containers and WinPython lets me run in a psudo-container-like environment)

**Comment by stonebig** [comment]
hi, I'm not really sure. I think the standard installer as some of extra options, like a big debugger stack

**Comment by dougthor42** [comment]
It's probably the debugging symbols. I don't think I'll need them, so it sounds like I'm good to go.

Thanks for the info!
