### ISSUE TITLE
Conda-installed MinGW not used by cython (distutils?)

### ISSUE THREAD

**Issue by yw5aj** [winpython/winpython#26]
How to repeat the problem on WinPython 3.4 64-bit on Windows 7 64-bit:

1. Install `pycosat` and `conda` using the binaries provided by Chris Gholke;
2. Do :
    conda init
    conda install mingw
3. What I did is I wrote a simple `pyx` code and tried to compile it using `distutils` described here: http://docs.cython.org/src/quickstart/build.html#building-a-cython-module-using-distutils
4. We can see that the conda-installed MinGW is not used.

A few points that stonebig and I discovered:
1. If I do `where gcc`, it will find conda-installed `gcc.bat` first. However, it is just not used.
2. If we prepend `$WINPYDIR$\MinGW\bin` at `PATH` in line 5 of the `env.bat` found in `WinPythonDir\scripts`, this problem goes away.

**Comment by stonebig** [comment]
Carl has now an account on binstar, which may be the way to go if you want conda + mingw64 integration: https://pypi.binstar.org/carlkl

I'll update to Carl Kleffner's April17th toolchain next Winpython version.
