### ISSUE TITLE
Settings folder is re-created in WINPYTHON_DIR

### ISSUE THREAD

**Issue by guaguanco** [winpython/winpython#262]
As explained on <https://github.com/winpython/winpython/wiki/Installation#settings> I removed the `[WINPYTHON_DIR]\settings` directory to enable per user settings. However, every time I start Jupiter the folder is created again with the content:

```
.
├── nbsignatures.db
├── notebook_secret
└── runtime
    └── notebook_cookie_secret
```

I'm using WinPython 3.4.4.1Qt5

**Comment by guaguanco** [comment]
just to explain how I'm using WinPython, I keep a shared (customised) installation of WinPython for my class on a shared folder. That folder is read only, so runtime files must be created on the user profile directory. 

Is there a recommended way of doing this? With a previous version of WinPython (3.4.3.2) I had no problems

**Comment by cenano** [comment]
Same issue here (Windows 7, 64 bit, WinPython 3.4.4.1Qt5 and WinPython 3.4.4.1). Additionally, just logged in as a normal user I even can't start "Jupyter Notebook" nor "IPython Qt Console". I'm getting a ... "PermissionError: [WinError5] Access is denied: 'C:\\Program Files\\WinPython-64bit-3.4.4.1Qt5\\settings'" ...

**Comment by stonebig** [comment]
Hi @guaguanco ,

I optimized Winpython default config to run in inside the %WINPYDIR% directory because:
- it's one of my target use case,
- the other one, yours, may generate problems is you have several WinPython installations on the same PC.

Your cas is nevertheless important to my eyes, the two Variables to get right should be
````
set JUPYTER_DATA_DIR=%WINPYDIR%\..\settings
set HOME=%WINPYDIR%\..\settings
````

Please try the following:
- create the following script script `ipython_notebook_student.bat` in your `WinPython 3.4.4.1Qt5\scripts` directory
````
@echo off
call %~dp0env.bat

rem classsic WinPython
rem set JUPYTER_DATA_DIR=%WINPYDIR%\..\settings
rem set HOME=%WINPYDIR%\..\settings

rem Student WinPython
set JUPYTER_DATA_DIR=%HOMEPATH%\WinPython%WINPYVER%
set HOME=%JUPYTER_DATA_DIR%

mkdir %HOME%
mkdir %HOME%\Notebooks

cd %WINPYDIR%\Scripts
%WINPYDIR%\scripts\jupyter-notebook.exe --notebook-dir=%HOME%\Notebooks %*

````
-  then copy and paste it as a shortcut on your students desktop.

- make your "test" student click on it

**Comment by stonebig** [comment]
I updated the script, so that cython should work

**Comment by stonebig** [comment]
For spyder, it would be `spyder_for_student`
````

@echo off
call %~dp0env.bat

rem classsic WinPython
rem set JUPYTER_DATA_DIR=%WINPYDIR%\..\settings
rem set HOME=%WINPYDIR%\..\settings

rem Student WinPython
set JUPYTER_DATA_DIR=%HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
set HOME=%JUPYTER_DATA_DIR%

if not exist %HOME% mkdir %HOME%
if not exist %HOME%\Notebooks mkdir %HOME%\Notebooks

rem ******************
rem make cython use mingwpy part
rem ******************

set pydistutils_cfg=%HOME%\pydistutils.cfg

echo [config]>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

echo [build]>>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

echo [build_ext]>>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

echo cython has been set to use mingw32
echo to remove this, remove file "%pydistutils_cfg%"

rem ******************
rem launch Spyder for Student
rem ******************


cd %HOME%\Notebooks
%WINPYDIR%\python.exe -m spyderlib.start_app %*
````

**Comment by stonebig** [comment]
and `spyder_reset_for_student`:
````
@echo off
call %~dp0env.bat

rem classsic WinPython
rem set JUPYTER_DATA_DIR=%WINPYDIR%\..\settings
rem set HOME=%WINPYDIR%\..\settings

rem Student WinPython
set JUPYTER_DATA_DIR=%HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
set HOME=%JUPYTER_DATA_DIR%

if not exist %HOME% mkdir %HOME%
if not exist %HOME%\Notebooks mkdir %HOME%\Notebooks

rem ******************
rem launch Spyder reset for Student
rem ******************

%WINPYDIR%\python.exe -m spyderlib.start_app --reset %*
````

**Comment by stonebig** [comment]
hum doing that, at first launch 'spyder_for_student` seems to point to `%WINPYDIR%\scripts` and the qt console starts there... I don't see where that bad guess comes from, and how to workaround it so that first spyder qtconsole starts at %HOME%\Notebooks

You students may have to change their `C:\Users\(theuser)\Documents\WinPython3.4.4.1Qt5\.spyder-py3\workingdir` by hand

any help welcomed

**Comment by stonebig** [comment]
maybe a simpler approach:
`env_for_student.bat`
````
rem to have WinPython working in a local account
@echo off
call %~dp0env.bat

rem classic WinPython
rem set JUPYTER_DATA_DIR=%WINPYDIR%\..\settings
rem set HOME=%WINPYDIR%\..\settings

rem *****************************
rem Student WinPython
rem *****************************
set JUPYTER_DATA_DIR=%HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
set HOME=%JUPYTER_DATA_DIR%

if not exist %HOME% mkdir %HOME%
if not exist %HOME%\Notebooks mkdir %HOME%\Notebooks
if not exist %HOME%\Notebooks\docs copy %WINPYDIR%\..\Notebooks\docs %HOME%\Notebooks\docs

if not exist %HOME%\.spyder-py3  mkdir %HOME%\.spyder-py3 
if not exist %HOME%\.spyder-py3\workingdir
echo %HOME%\Notebooks>%HOME%\.spyder-py3\workingdir

rem *****************************
rem make cython use mingwpy part
rem *****************************
set pydistutils_cfg=%HOME%\pydistutils.cfg

if exist %pydistutils_cfg%  goto after_mingwpy

echo [config]>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%
echo [build]>>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%
echo [build_ext]>>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

:after_mingwpy

````

`ipython_notebook_student.bat`:
````
@echo off
call %~dp0env_for_student.bat
cd %WINPYDIR%\Scripts
%WINPYDIR%\scripts\jupyter-notebook.exe --notebook-dir=%HOME%\Notebooks %*
````

`spyder_for_student.bat`:
````
@echo off
call %~dp0env_for_student.bat
cd/D %HOME%\Notebooks
%WINPYDIR%\python.exe -m spyderlib.start_app %*
````

`spyder_reset_for_student.bat`:
````
@echo off
call %~dp0env_for_student.bat
%WINPYDIR%\python.exe -m spyderlib.start_app --reset %*
echo %HOME%\Notebooks>%HOME%\.spyder-py3\workingdir
````

**Comment by guaguanco** [comment]
@stonebig, yes changing env.bat is what I'm experimenting with right now. Concerning the default folders, I'll probably use the default locations as specified in <http://jupyter.readthedocs.org/en/latest/system.html>. I'll report back in this thread. 

BTW, the apps in `[WINPYTHON_DIR]` (e.g. `Jupyter Notebook.exe`) uses those scripts or have environment vars built in?

--sergio

**Comment by stonebig** [comment]
hi @guaguanco,

The launchers don't use the scripts, it's all wired in the "nsis" launchers:
- it's the historical way of WinPython.
- it needs a rewrite to better support your use-case, but:
  - the way to do it is not clear yet,
  - the result of your tweakings and remarks is a valuable input, before going further.

**Comment by stonebig** [comment]
I'm going to experiment a build1:
- unchanged current icons
- a series of new (student) icons, which are:
   -  launching executables via the .bat in ..\scripts, (where we can change variables)
   -  place the end-user environnement in HOME=%HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
   - end-user layout is:
            - this %HOME% is like "settings" directory of default winpython
            - default script and notebooks are in %HOME%\notebooks
- you can modify the "student" scripts in ..\scripts to fit your layout

By creating shortcut if these 'students' icons on the 'students' desktop:
 - they should be able to work without having any rights to the WinPython directory
 - these environnements should not interfer with a "system" Python or another WinPython

**Comment by stonebig** [comment]
so
[ww_patch_student.zip](https://github.com/winpython/winpython/files/149866/ww_patch_student.zip)

**Comment by stonebig** [comment]
solved by https://github.com/winpython/winpython/pull/272

Initiall settings files will stay but winPython.ini can be configured so that users do work in their local directories, where new settings will show up:

''''
[debug]
state = disabled
[environment]
HOME = %HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
JUPYTER_DATA_DIR = %HOME%
WINPYWORKDIR = %HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%\Notebooks
''''

will creates the folowing hierarchy (for WinPython 3.4.4.1Qt5):
```
%HOMEDRIVE%%HOMEPATH%\Documents\WinPython 3.4.4.1Qt5
├── settings
    └── .matplotlib
    └── .ipython
    └── .pydistutils.cfg
└── Notebooks
    └── docs
```

two scripts allows the common Winpython directory to behaves the classic way or the new way:
- make_working_directory_be_not_winpython.bat
- make_working_directory_be_winpython.bat
