### ISSUE TITLE
Theano with GPU config failed

### ISSUE THREAD

**Issue by ghost** [winpython/winpython#263]
Hello,

Theano under CPU is fine with WinPython 3.4.

But, when configuring with GPU; it failed:

Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.4.3-64\cuda_ndarray\cuda_ndarray.pyd mod.cu -LD:\_devs\Python01\WinPython-64\python-3.4.3.amd64\libs -LD:\_devs\Python01\WinPython-64\python-3.4.3.amd64 -lpython34 -lcublas -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavilable)
WARNING:theano.sandbox.cuda:CUDA is installed, but device gpu is not available  (error: cuda unavilable)
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH

My config file is
[global]
floatX = float32
device = gpu

[nvcc]
fastmath = True
--flags=-LD:_devs\Python01\WinPython-64\python-3.4.3.amd64\libs
--compiler_bindir=D:_app\visualstudio13\VC\bin\amd64\

[cuda]
 Set to where the cuda drivers are installed.
 You might have to change this depending where your cuda driver/what version is installed.
root=D:_app\nvidiacuda\gpu\gdk_win7_amd64_release\nvml

Is there anything is missing ?

Kind regards

**Comment by stonebig** [comment]
hi @arita291 

I'm afraid here is not the best place to get help. you may try:
- stackoverflow,
- or Theano user group.

Something related to your message seems in  https://groups.google.com/forum/#!topic/theano-users/-N-W6GKL4eU

**Comment by stonebig** [comment]
I expect that cntk and Tensorflow should be or become better options for Python-3.5+, on Windows

**Comment by stonebig** [comment]
There is an interesting post here: https://github.com/Theano/Theano/issues/5348

**Comment by stonebig** [comment]
the main problem with Theano, is that it relies on mingwpy (or other gcc) that is not available for Python-3.5+. 

Until that is resolved, one way or the other, all complaints about Theano can only be resolved  by using a legacy WinPython-2.7/3.4 , or switching to another package (Tensorflow, CNTK, ...), or switching of Distro., or switching of Operating System or switching to Windows10 "Linux (WSL)" mode

Microsoft Pythonistas are the best positionned to move things forward on this, if they can.
