### ISSUE TITLE
WinPython 'spyder' launcher will fail with spyder 3.0.0beta3

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#276]
see https://github.com/spyder-ide/spyder/issues/3038

**Comment by stonebig** [comment]
fixed by https://github.com/winpython/winpython/pull/277 .

for previous version users upgrading to spyder-3.0.0.beta3 or higher will have to apply an 'icons patch' extracted from coming build2:
- new icon launchers:  spyder.exe , spyder_reset.exe
- new scripts: env_for_icons.bat, Noshell.vbs, WinPythonIni.vbs

**Comment by stonebig** [comment]
not pretty but simpler solution for older WinPython: 
- don't use the spyder icon
- launch "WinPython Command Prompt.exe"
- type "spyder.exe"

**Comment by JaehunSim** [comment]
> not pretty but simpler solution for older WinPython will be:
> 
> * don't use the spyder icon
> * launch "WinPython Command Prompt.exe"
> * type "spyder.exe"

This only helped and it's very easy. Thanks.
