### ISSUE TITLE
Add mpmath package to support upgrade to SymPy v1.0

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#290]
SymPy v1.0 release notes say that the mpmath changes to an external package:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.0
The latest mpmath package is available as a wheel here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by stonebig** [comment]
I noticed. but you can already:
- pip install mpmath
- then install the sympy wheel of cgohlke.

Can't you ?
