### ISSUE TITLE
Remove the "Spyder (reset).exe" launcher

### ISSUE THREAD

**Issue by PierreRaybaut** [winpython/winpython#292]
I strongly recommend removing the "Spyder (reset).exe" launcher as it can be executed easily by mistake (for example... instead of Spyder itself) and the effect for the average user would be quite the opposite to the expected result. :-) Some people spend a lot of time reorganizing Spyder main window or tweaking its options, so resetting those settings accidently would be catastophic.

==> The "scripts/spyder(reset).bat" batch script seems sufficient for resetting Spyder, as it's not something you do everyday.

**Comment by stonebig** [comment]
ok.
