### ISSUE TITLE
pyuic4.bat don't run when folder name contains space..

### ISSUE THREAD

**Issue by thierryBottaro** [winpython/winpython#299]
Current code (in Winpython 2016-01 Python 3,5,1,2 _64bit) for pyuic4.bat is :
```
@echo off
if "%WINPYDIR%"=="" call %~dp0..\..\scripts\env.bat
python "%WINPYDIR%\Lib\site-packages\PyQt4\uic\pyuic.py" %1 %2 %3 %4 %5 %6 %7 %8 %9
```
it gives me : 

> 
> 'C:\Program' is not recognized as an internal or external command, operable program or batch file.
> 'python' is not recognized as an internal or external command, operable program or batch file.

I get it to run with these modifications : (notice the quotes...)
```
@echo off
if "%WINPYDIR%"=="" call "%~dp0..\..\scripts\env.bat"
"%WINPYDIR%\python.exe" "%WINPYDIR%\Lib\site-packages\PyQt4\uic\pyuic.py" %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Comment by stonebig** [comment]
Thanks for the solution to this test I never want to do.
May I include directly the associated code change or do you want to do a PR ?

**Comment by stonebig** [comment]
and why "%WINPYDIR%\python.exe" instead of "python" ?

**Comment by thierryBottaro** [comment]
je crois qu'on peut parler français :)
merci pour la procédure, j'avais jamais proposé une modification dans
GitHub :)
j'ai donc fait la modif, j'ai même réussi à faire la "pull request",
j'imagine que tu dois la "merger"...

Pour ta 2ième question, je viens de re-tester chez moi juste "python", et
il me dit :
> The syntax for the file name, directory name, or volume label syntax is
incorrect.
> The "python" command is either misspelled or could not be found.

Ce qui n'est pas surprenant : WinPython est par défaut installer comme une
appli "portable". Donc la commande "python" n'est pas une commande reconnue.
La logique même d'une application portable implique l'utilisation de
"%WINPYDIR%\...
" , non ?
je remarque que dans le "env.bat", il n'y a même pas de définition pour
"python".

J'ai peut-être oublié de préciser que j'exécute ce pyuic4.bat dans la
console DOS "normale", pas dans la "WinPython Command Prompt"
maintenant que j'en parle, je viens d'essayer : dans le "WinPython Command
Prompt", la commande
'pyuic4 monFichierUI.ui > sortieUI.py'
fonctionne.

Merci pour ta réponse si rapide,
Thierry



2016-03-22 19:47 GMT+01:00 stonebig <notifications@github.com>:

**Comment by stonebig** [comment]
oui, c'est exactement ça. A+

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/pull/301
