### ISSUE TITLE
from scipy.sparse.linalg import LinearOperator raise an ImportErr DLL in Python 3.5.1.[1|2]

### ISSUE THREAD

**Issue by thierryBottaro** [winpython/winpython#300]
I actually just wanted to import curve_fit from scipy.optimize and get a long traceback.
> ....
> from scipy.optimize import curve_fit
>   File "C:\Program Files\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\optimize\__init__.py", line 222, in <module>
>     from ._minimize import *
>   File "C:\Program Files\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
>     from .lbfgsb import _minimize_lbfgsb
>   File "C:\Program Files\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 44, in <module>
>     from scipy.sparse.linalg import LinearOperator
>   File "C:\Program Files\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\sparse\__init__.py", line 213, in <module>
>     from .csr import *
>   File "C:\Program Files\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\sparse\csr.py", line 13, in <module>
>     from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
> ImportError: DLL load failed: The specified module could not be found.

This import work with WinPython-64bit-**2.7**.10.2 but neither with WinPython-64bit-**3.5.1.1** nor with WinPython-64bit-**3.5.1.2**

I have checked the 
python-3.5.1.amd64\lib\site-packages\scipy\sparse\_SPARSETOOLS.CP35-WIN_AMD64.PYD
with "Dependency Walker", which said it did not found 3 DLLs : PYTHON35.DLL; MSVCP140.DLL; VCRUNTIME140.DLL but all 3 are in the python directory.

**Comment by stonebig** [comment]
this does work on my pc/windows 7 64:
````
from scipy.sparse.linalg import LinearOperator
from scipy.optimize import curve_fit
````

so, my best bet, is 
<p>(*) For WinPython 3.5, Windows 7/8 users may have to install <a href="https://www.microsoft.com/en-us/download/details.aspx?id=49984">Microsoft Visual C++ Redistributable for Visual Studio 2015</a>

**Comment by thierryBottaro** [comment]
Bingo !!!
Thank you very much.

I tried it at home with a new install of Winpython 3,5,1,2 and worked at once. I then double checked in installed programs, and I did not have Redistributable Visual 2015 ... 

It is still strange that I did not found anyone on the internet with this error (now, I guess, it is changed thanks to this ticket)
