### ISSUE TITLE
separate python packages into groups based on functionality

### ISSUE THREAD

**Issue by denfromufa** [winpython/winpython#302]
suggested groups:
- plotting
- numerical
- UI
- packaging
- Windows and Office specific
- language interop
- data manipulation

**Comment by stonebig** [comment]
there is currently a place for functionnality in https://github.com/winpython/winpython/blob/master/winpython/data/packages.ini

for example:
````
[cython]
description=Cython is a language that makes writing C extensions for the Python language as easy as Python
url=http://www.cython.org
category=util
````

thoughts:
- it's an effort to determine and maintain this information by hand currently,
- I always dream of getting the default classification (and the package description) from Pypi, at least when nothing is written in package.ini, if the internet is available and the user wants the refresh and for installed packages.

==> Loading the General Description would save me some time.

**Comment by denfromufa** [comment]
PYPI does provide classification here, not sure how reliable it is though:

https://pypi.python.org/pypi?%3Aaction=browse

But maintaining by hand is also possible, since once a package is added to
WinPython - its classification is static.

**Comment by stonebig** [comment]
pypi.org shall be replaced soon per pypi.org (warehouse), where I don't see this classification..

Most of work, when not restructuring, is to update the package labels list, so I hope an answer will show up within a year

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/issues/620 may be the evolution of current situation.
