### ISSUE TITLE
pymssql for sql server

### ISSUE THREAD

**Issue by denfromufa** [winpython/winpython#307]
pymssql is quite hard to install on windows, due to 3rd party dependencies - FreeTDS and OpenSSL, yet it provides SQL server driver for SQLAlchemy. this should be included by default.

**Comment by stonebig** [comment]
can't we get access via dao or odbc ?

**Comment by denfromufa** [comment]
there are 2 alternatives to pymssql that work with sqlachemy - mxODBC
(commericla) and (py)pyodbc (open-source but not much maintained anymore).
I'm not sure about anything else CPython specific. pythonnet is completely
different beast which requires minimal .NET knowledge.

**Comment by stonebig** [comment]
"import System.Data.OleDb as ADONET" should work, but I don't have a sqlserver to try it

**Comment by stonebig** [comment]
pyodbc or ADO.NET to replace pymssql ? https://groups.google.com/forum/#!topic/pyodbc/lU1dpxAFH9w

**Comment by denfromufa** [comment]
Yes, I saw that! pyodbc also supports MS Access.

**Comment by denfromufa** [comment]
Iopro has enhanced interface based pyodbc with numpy support

**Comment by stonebig** [comment]
I don't find iopro on pypi , nor cgohlke.  I don't see where are the source, I don't know if it can be a wheel.
...

Any link / advice / suggestion  ?

**Comment by stonebig** [comment]
ah, "30-day free trial " .... sorry for asking

**Comment by denfromufa** [comment]
Yes, iopro is commercial.
