### ISSUE TITLE
Repeated calls to env.bat fill up PATH var

### ISSUE THREAD

**Issue by dougthor42** [winpython/winpython#310]
# Summary
Repeated calls to env.bat will append duplicate items to PATH and eventually overflow.

## Steps to Reproduce:
1.  Open up WinPython Command Prompt
2.  `cd <WinPython_Dir>/scripts/`
3.  execute `env.bat` multiple times (13 seems to do the trick for WinPython34, 17 for WinPython27)
4.  Error occurs.

## Tested on
+ WinPython 3.4.3.2, 64-bit
+ WinPython ~~2.7.3~~ 2.7.6.2, 32-bit

## More information
+ Seems like it could be solved by adding a check for the PATH var, in a similar vein to [this StackOverflow anwer](http://stackoverflow.com/a/19929778/1354930)
+ For anyone interested in attempting to fix this: the `env.bat` file is created in `winpython/make.py`, line 549.

### Steps to Reproduce
![image](https://cloud.githubusercontent.com/assets/5386897/14336368/e2bb7334-fc17-11e5-8cdd-dc87ce80f176.png)

### PATH environment variable gets filled up
![image](https://cloud.githubusercontent.com/assets/5386897/14336378/fa4f3bf2-fc17-11e5-8cbd-7dbf769533c6.png)

**Comment by stonebig** [comment]
try this and let me know:
````
echo ;%PATH%; | find /C /I ";%WINPYDIR%\;" >nul
if %ERRORLEVEL% NEQ 0 set PATH=%WINPYDIR%\Lib\site-packages\PyQt5;%WINPYDIR%\Lib\site-packages\PyQt4;%WINPYDIR%\;%WINPYDIR%\DLLs;%WINPYDIR%\Scripts;%WINPYDIR%\..\tools;%WINPYDIR%\..\tools\mingw32\bin;%WINPYDIR%\..\tools\R\bin\i386;%WINPYDIR%\..\tools\Julia\bin;%PATH%;
````

**Comment by dougthor42** [comment]
That looks like it worked, thanks.

Checked on both versions that I have.

Do you want me to submit a PR for the change or will you guys fix it on your own?

**Comment by stonebig** [comment]
a PR is welcomed. It will be merged for next release, no this one, so will be pending 10 days
