### ISSUE TITLE
PDF via LaTeX

### ISSUE THREAD

**Issue by jackjameshoward** [winpython/winpython#312]
Is there a solution available to export notebooks  as pdf from jupyter. 
Whenever I use the built in option 

> PDF via LaTeX (.pdf)

 I get this error:

> nbconvert failed: pdflatex not found on PATH

I am using WinPython-64bit-3.4.4.1

**Comment by jackjameshoward** [comment]
I recently tried a new install of WinPython-64bit-3.4.4.1 and did 
`pip install -- upgrade notebook --no-deps`
and 
`pip install -- upgrade nbconvert --no-deps`
Now I get a new error 

> Could not import nbconvert: No module named entrypoints

**Comment by stonebig** [comment]
hi,

there is a promise of new nbconvert to remove need of a Latex distribution, but it currently use packages that are not windows compatible (last time I checked, at least)
https://github.com/winpython/winpython/issues/216

So you curent option is to install **TexLive** or **MikeTex**

**Comment by jackjameshoward** [comment]
@stonebig Does jupyter have the ability to configure the path for MikeTex? My MikeTex is the portable version

**Comment by stonebig** [comment]
If you install miktex system wide, for example, it's in your path so Jupyter must see it
