### ISSUE TITLE
whick version-32 or 64 bit should I use ?

### ISSUE THREAD

**Issue by qq2898** [winpython/winpython#319]
my computer is Win7 64bit,  and  python 2.7 32bit installed , so which version should I use in WinPython? 32 or 64? thank you

**Comment by stonebig** [comment]
The 64bit versions are recommanded:
- they are much more performant on numeric computations,
- the 32bit versions do work, but you may choose them only if you have a good reason.

It's all free, you can download both and do your own comparisons on you use case and PC.
