### ISSUE TITLE
PYTHONPATH manager functionality

### ISSUE THREAD

**Issue by Winand** [winpython/winpython#321]
Posted this ti Spyder

<del>
I'm not sure that it's an issue of WinPython or an issue at all.
The following code allows to import custom version of `pandas`  in IDLEX, but not in Spyder, which loads the package from `site-packages` folder until i rename the pandas folder there to smth else.</del>
```
import sys
sys.path.insert(1, r'D:\andray\Software\Python\pandas\build\lib.win32-3.4')
import pandas as pd
print(pd.__version__)
```

-
One should use `PYTHONPATH manager` instead of messing around with `sys.path` in Spyder, right?
Then could you enhance its functionality so I can switch on-off paths like this:
![image](https://cloud.githubusercontent.com/assets/53390/14910063/d416981c-0df2-11e6-8392-8ca4ad96b73f.png)
If I want to test the same code with different versions of the same library it's not very handy to completely remove an item from the list and then add it again

**Comment by RoyiAvital** [comment]
Does `env` command set the `PYTHONPATH`?

Because I don't see it on WinPython command line.

**Comment by RoyiAvital** [comment]
OK, If I don't register and just use the `cli`, shouldn't it be set as well?

**Comment by stonebig** [comment]
I don't see where it hurts, have you an example to illustrate the problem ?

**Comment by RoyiAvital** [comment]
I installed something a package which complained it didn't exist.
