### ISSUE TITLE
work again with spaces in path, part 2

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#322]
I had already made the changes to cmd.bat and register_python.bat suggested by #316.  However, I found "WinPython Control Panel.exe" icon crashed with WinPython 3.4.4.2 installed in
"C:\Program Files\".  Here is how I fixed it:

In env_for_icons.bat, change:
    call %~dp0env.bat
to:
    call "%~dp0env.bat"

In wpcp.bat, change:
    %WINPYDIR%\python.exe
to:
    "%WINPYDIR%\python.exe"

I suspect there are other calls or direct use of executables in the batch files in the WinPython scripts folder that need the same fix.

**Comment by stonebig** [comment]
you're right I missed some fix.
