### ISSUE TITLE
PyQt5.6 for Python3.5

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#325]
several things to fix:
- [x] remove QtDemo Icon
- [x] launch QtDemo (if present) in `Qt_libraries_demo.ipynb`
- [x] remove Qtassistant (useless if we don't ship documentation, If I understand well)
- [x] remove Qtdesigner and QtLinguist icons when not available and when release includes Qt5.6,
- [x] late discovery; this is true for the wheel installer, but not for the .exe installer

status of july 18th:
- [x] use PyQt5.6.0 wheel and patch to get  Spyder "WebEngine" help working
- [x] drop PyQt5.6 ".exe" experiments (so abandon Qtdesigner, QtLinguist)

==> waiting a week, in hope Spyder and PyQt do some progress towards each other.

The simple solution going forward seems to:
- reduce historic Qt "development center" traces from Website,
- the value of Qt is now:
  - by it's usage by Qtconsole/Spyder/Matplotlib/PyQtgraph/PyQt,
  - by it's underlying latest technologies bricks (WebEngine, Websockets, 3D).

**Comment by stonebig** [comment]
seems to need blas also:
````
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?
````

**Comment by hiccup7** [comment]
MKL _is_ a blas library.

**Comment by stonebig** [comment]
yes, maybe I have to remember how to parametrize .theanorc. I didn't have time to look further
