### ISSUE TITLE
Fail to use openpyxl from cmd

### ISSUE THREAD

**Issue by johmue** [winpython/winpython#326]
Hi,

I struggle to use openpyxl from cmd. Most likely I'm doing it wrong but I googled a lot and dit not find a working solution so far. I unpacked WinPython, started ```.\scripts\cmd.bat``` installed openpyxl via
```
C:\test> pip install openpyxl
```
and tried to run a simple test file
```python
# test.py
import openpyxl
print(openpyxl.__version__)
```
within the cmd window
```
C:\test> python test.py
```
Unfortunately I get all the time the following error message:
```
Traceback (most recent call last):
  File "openpyxl.py", line 2, in <module>
    import openpyxl
  File "C:\test\openpyxl.py", line 3, in <module>
    print(openpyxl.__version__)
AttributeError: module 'openpyxl' has no attribute '__version__'
```
Can you please point me in the right direction. Thanks.

BTW this package is really awesome!

**Comment by stonebig** [comment]
as a basic workaround doing this wil gie you the version of all your packages, openxyl included:
```
C:\test> pip list
```

**Comment by johmue** [comment]
The problem is not really, that I need the version. The problem is that python can not resolve methods and properties of classes and packages. When I use the above approach.

**Comment by stonebig** [comment]
it works. try on a given package:
- start "Winpython Interpreter"
- type:
````python3
import matplotlib
print( matplotlib.__version__)
````
