### ISSUE TITLE
install additional package from zero version - WinPython-64bit-3.5.1.3Zero.exe

### ISSUE THREAD

**Issue by spectereye** [winpython/winpython#337]
thanks for great portable python in windows!
for easier distribution, i  prefer min. package - WinPython-64bit-3.5.1.3Zero.exe.
so i can copy all my script with this in a folder, not too big, it's ~70M after unpacking

normally i need automation programes like office, inventor...which use com automation, so need pywin32 package, but when i install from WinPython Command Prompt.exe, found error

```
Collecting pywin32
  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32
```
could you please help this? thanks!

also comments that there is many .exe file in zero version, but only some of them can run actually, then why not clean up...thanks!

**Comment by stonebig** [comment]
well:
- Zero version whose goal was to be same size or smaller than Python default installer, and pywin32 is really (too) big,
- I added Pythonnet in the Zero, as I hoped it could be the an alternative for some cases.

**Comment by stonebig** [comment]
You can experiment with "mini" version WinPython-64bit-3.5.1.4Minib3.exe at: 
https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.1.4/betas/

**Comment by stonebig** [comment]
popularity experiment with https://github.com/winpython/winpython/pull/339

**Comment by spectereye** [comment]
Thanks a lot! better that min version is also flexiable, i mean i can choose package by pip by myself, and my question about install pywin32 into zero version, any suggestions?

**Comment by stonebig** [comment]
min = zero version + pywin32

Your request is equivalent to ask to re-badge "mini" as "zero", isn't it ?

**Comment by spectereye** [comment]
min = zero version + pywin32?! just know it! thanks a lot! then sovled!
