### ISSUE TITLE
PyQt5 transition

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#34]
The Qt5 transition will occure during 2015, as Official PyQt4 support dies end 2015.
==> That simplifies decisions a bit.

Qt5.5 , released arounf june 2015, deprecates Qt Webkit, in favor of QtWebEngine (Chromium 40).
==> That looks the version to target 

from a MinRK comment:
````
You need to use Qt5 for websocket support
Qt4 only supports the pre-release drafts of websockets, which IPython (tornado, really) doesn't support
````

So having Spyder embedding a IPython Notebook means having Qt5.
Having Qt5 for Python2.7 won't happen unless Christoph Gohlke provides a binary for Python2.7
http://python.6.x6.nabble.com/Windows-installers-for-PyQt5-and-Python2-td5036304.html

This tries to summary what needs to be done:
- [x] WPPM is Qt5/Qt4 compatible on  (as Python2.7/3.3 may not make it to Qt5)
- [x] do an internal alpha to see what happens
- [x] IPython3 qtconsole supports roughly Qt5 (https://github.com/ipython/ipython/issues/7707)
- [x] formlayout is maintained in spyder (`from spyderlib.widgets.formlayout import fedit`), but this part seems tricky to use from outside)
- [x] pyqtgraph as the suggested alternative to guiqwt + PyQwt 
- [x] find a PyQt5 wheel (or just figure out how Pierre Raybaut was doing before)
- [x] fix QtDemo icon for PyQt5
- [x] workaround for `set QT_API=pyqt5' (for wppm)
- [x] make.py strategy to detect install need of PyQt5
- [x] Spyder master of july 16th + Qt5 patch works !
- [x] Qt 5.5 + patch Winpython, for current Spyder to work
- [x] Spyder 2.4 or 3.0 to support Qt5 (not 2.3)
- [ ] guidata, PyQtdesignerplugins  replacement for PyQt5  (or none)
- [ ] https://github.com/rwarren/qt_backport may be also a lower level solution
- [ ] there seems to be  a `Six`-for-qt like solution https://github.com/avalentino/qtsix

**Comment by yw5aj** [comment]
Being curious (and sorry for asking so many questions :)

Are there any packages dependent on guiqwt and guidata that we are using? Thinking about what would happen if we just drop these two (not necessarily saying we should).

Shawn

**Comment by stonebig** [comment]
I removed Winpython (WPPM) dependancy on guidata  here: https://github.com/winpython/winpython/commit/32ec794d13a11b47d7364f5d8f343764fd4e885d

Nevertheless, droping guiqwt and guidata may be an issue:
- for the current "Qt" icons of Winpython, though: Qt Designer, 
- for users depending on it.

**Comment by stonebig** [comment]
I read this from http://www.riverbankcomputing.co.uk/software/pyqt/intro
````
support for Qt v4 will cease at the end of 2015
````

**Comment by stonebig** [comment]
So:
- becoming Qt5/Qt4 compatible is the strategy for 2015
- a Qt5 version may start to live in beta, when a compatible pyqtgraph 0.9.11 will be out

**Comment by stonebig** [comment]
Well, I'm going to replicate Spyderlib team recent Qt5/4 effort, as it's the same qt codebase from Pierre Raybaut.

**Comment by stonebig** [comment]
Qt5 (and Ipython in spyder) is Spyder 2.4 stuff, so current Spyder 2.3.4  is not Qt5 ready.

**Comment by stonebig** [comment]
PyQt5 is not smooth sailing yet: errors without details
![qt5-first_cry](https://cloud.githubusercontent.com/assets/4312421/6998207/ccef1ec6-dbd8-11e4-9c21-7ceb6489feef.GIF)

**Comment by stonebig** [comment]
I fear I will have to wait for an official wheel package PyQt5

**Comment by stonebig** [comment]
There was an explanation talk about websocket at pycon2015

https://www.youtube.com/watch?v=u5QT3luWx7w

**Comment by stonebig** [comment]
Getting Close

![wppm_qt5-first_cry](https://cloud.githubusercontent.com/assets/4312421/7219003/e142ffc4-e68b-11e4-91cb-99c7e6fa9e0a.GIF)

**Comment by stonebig** [comment]
milestone today: 
- I can build with PyQt5-5.4.1-gpl-Py3.4-Qt5.4.1-x64.exe
- all problems were (are still) to re-discover and patch existing tricks in WinPython code for Qt4.

**Comment by stonebig** [comment]
import imp
try:
        #importing top level PyQt4/PySide module is ok...
        mod = __import__('PyQt4')
        print('PyQt4')
except:
    pass
try:
        #importing top level PyQt4/PySide module is ok...
        mod = __import__('PyQt5')
        print('PyQt5')
except:
    pass

**Comment by stonebig** [comment]
Getting pretty close
![spyder_qt5_first_cry](https://cloud.githubusercontent.com/assets/4312421/8729201/f654a32e-2be9-11e5-9cea-5979167ce887.GIF)

**Comment by stonebig** [comment]
preview release ! https://github.com/winpython/winpython/releases/tag/1.2.20150723qt5

**Comment by stonebig** [comment]
feedback from lidstrom 83:
- The pyqtgraph release included isn't PyQt5 compatible.  To make it work, I removed the included pyqtgraph package and installed the development branch I downloaded from github.
- To use pyuic5, I had to change the relative imports in the pyuic and driver modules in PyQt5.uic to absolute imports.
- When using the WInPython Control Panel to remove or add packages, the progress dialog has no border and it never completes.

Another issue I've noticed (unrelated to PyQt5) is that if I put my WinPython distribution in the root directory of my C: drive, the included scripts (e.g. pyuic5.bat) don't run properly without replacing %WINPYDIR% with the explicit path.  Is this a permissions thing?

**Comment by stonebig** [comment]
so:
- [ ] use master branch of PyQt5 for WinpythonQt5 (until next official release)

**Comment by lidstrom83** [comment]
FWIW here is somebody else having the same pyuic5 problem:
http://code.activestate.com/lists/python-list/666469/

Somebody recommended there to load pyuic.py as a module.  I changed the relative imports to absolute imports instead since PyQt4 does exactly that.

**Comment by stonebig** [comment]
hi @lidstrom83 

I see words but I don't connect the dots on what I need to do (my level 0 of PyQt5)

I see that WinPython does overwrite pyuic5.bat with its version, around line 455 of wppm.py.

so:
- is it a PyQt5 bug to report to riverbank ?
- is it a pyiuc5.bat code generated by WinPython to fix ?

should I just write in pyiuc5.bat:
````python3
@echo off
python -m PyQt5.uic.pyuic
````

instead of 
````python3
@echo off
python "%WINPYDIR%\Lib\site-packages\PyQt5\uic\pyuic.py" %1 %2 %3 %4 %5 %6 %7 %8 %9
````

**Comment by stonebig** [comment]
th relative way seems to work in ggplot ... I feel stupid

https://github.com/yhat/ggplot/blob/master/ggplot/scales/scale_colour_gradient.py#L3

**Comment by stonebig** [comment]
apparently this remove the bad message:
````python3
@echo off
python -m PyQt5.uic.pyuic %1 %2 %3 %4 %5 %6 %7 %8 %9
````

As WinPython generates it, I can fix it.

==> Is it the thing to Do ?

**Comment by stonebig** [comment]
I don't know how to fix `Control Panel never ending issue bug` .

**Comment by stonebig** [comment]
downgrading to PyQt5.4.1 from PyQt5.5.0 solves the Spyder problem.

**Comment by lidstrom83** [comment]
I noticed ViTables requires PyQt4, and also found that you're already aware of this:
https://github.com/uvemas/ViTables/issues/40

Should it be removed from the PyQt5 distribution pending PyQt5 support?

HDF Compass is a potential alternative:
https://www.hdfgroup.org/projects/compass/index.html

It's written in Python, but can't be run from source for this distribution since it requires Python 2.7; however, they do provide a frozen Windows app.  It's a ~60MB "one-click exe and does not need any installation", and "does not provide any editing functionality (which enables the UI to be less cluttered)."

**Comment by stonebig** [comment]
Oups ! I had forgot vitables was not Qt5 compatible.

The workaround you suggest is a problem:
- it's not Python3.4+,
- 60MB to replace a 0.3 MB would mean WinPython will get 59MB bigger to download.

**Comment by stonebig** [comment]
second build with PyQt5, with PyQt5.4.1 only but hopefully with much smaller bugs.

I'm waiting for PyQt5.5.1 for another try at Qt5.5.

https://github.com/winpython/winpython/releases/tag/1.2.20150731Qt5

**Comment by stonebig** [comment]
Apparently latest Spyder fix makes it ok for PyQt5.5.0, so WPPM issues in WinPython on PyQt5.5.0 are probably Winpython bugs (or tweaks needed)

**Comment by stonebig** [comment]
So I'm at the step where PyQt5.5.0 nearly works:
- Spyder should be ok, except it's a copy of raw github + patch, (I don't succeed to do a wheel)
- WPPM uninstall nicely several selected packages (launching a DOS window for pip uninstall, refreshing, redo for next package), but for if only 1 package is to uninstall, a maybe 'was normal' uninstall popup window shows up after the DOS uninstall, and never disappears.
==> I hope some will be able to help fix this

**Comment by stonebig** [comment]
Closing this meta issue, replacing per the small remaining issue on Winpython Control Panel.
