### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by techtonik** [winpython/winpython#341]
![untitled](https://cloud.githubusercontent.com/assets/515889/15702765/82eb33c8-27ea-11e6-9aee-3b629428bc9b.png)

Seems like some .dlls are missing from distribution. Namely:

```
api-ms-win-crt-runtime-l1-1-0.dll
```

This is the problem reported on another user behalf, so he has no chance to like troubleshoot it, because it is his first Python experience. 

I'd prefer builds with https://mingwpy.github.io/

**Comment by stonebig** [comment]
Isn't it that the user didn't install vs2015 runtime on his PC ? 

If that one is mising because of Winpython, shouldn't there  be 17 others also ?

![crt_zoo](https://cloud.githubusercontent.com/assets/4312421/15726061/2453d0da-284f-11e6-81e2-c3f5ee850b00.PNG)

**Comment by techtonik** [comment]
Most likely yes. But plain Python 3.5 doesn't require those to be installed on Windows, so why WinPython fails if those are not available?

**Comment by stonebig** [comment]
Winpython may not work for everybody's PC or everybody's taste. Maybe your new user may have a better luck with anaconda.

**Comment by techtonik** [comment]
Plain standard Python doesn't contain convenient editor, i.e. Spyder. Also, user experience in Windows command line is awful.

**Comment by stonebig** [comment]
Coming back to this:
- what your newcomer tried is not clear to me (launching Jupyter, then qtconsole, the IDLEX ?),
- I always noticed the reliable way to trash complex systems is to click on all buttons at once,
- on my old PC, Spyder always fail first time I try a new instalaltion of Winpython (probably because of a time out while windows populates its cache), so the same sort of thing can happen here.

**Comment by techtonik** [comment]
Newcomer tried to bring Python to learn programming on Windows. He downloaded WinPython, because he thought that it is Python tailored specifically for Windows users. He tried to run everything, but nothing works.

**Comment by stonebig** [comment]
so my guess is that he is on windows 7, and a WinPython3.4 without need of vs2015  will be a better fit.

for example WinPython-64bit-3.4.4.1Qt5.exe

otherwise install vs2015 redistribuable first (https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c)

**Comment by techtonik** [comment]
Does official Python 3.5.x require this too?

**Comment by stonebig** [comment]
You need vs2015 redistribuable if you are not on Windows 10 and :
- you are WinPython 3.5.0+,
- ior you are WinPython 3.4.4.2+ and you want to use numba,

**Comment by techtonik** [comment]
This does answer the question `Does official Python 3.5.x require this too?`, which boils down to..

Is WinPython 3.5.x binary compatible with Python 3.5.x extensions?

Because if Python 3.5.x uses different run-time, then it is not.

**Comment by stonebig** [comment]
Python 3.5.x "official" is made with vs2015, and so needs vs2015 runtime on Windows 7/8/8.1

**Comment by techtonik** [comment]
But I don't remember any crashes after installation, so does official Python installer ship those bundled?

**Comment by stonebig** [comment]
No.

**Comment by techtonik** [comment]
![python3 5 1-install-error-0x80240017](https://cloud.githubusercontent.com/assets/515889/16201611/e8db5aac-371a-11e6-8d34-dcc05f9d21e4.png)

Official 32-bit installer fails to install. I am still waiting for an answer about which version of Windows is it, but I guess it is Windows 8.

**Comment by takluyver** [comment]
I believe that the Python.org installers do ensure by some means that the necessary C runtime is installed. I'm not sure if it's bundled or downloaded through Windows update as necessary or something else.

**Comment by techtonik** [comment]
It is Windows 8.1 64-bit. The above screenshot with error 0x80240017 is from official python.org installer, so it looks like it doesn't bundle or download anything or even show descriptive error message.

**Comment by stonebig** [comment]
you may ask to @zooba on twitter, or just install manually the vc0215 runtime and see if the error message disappears all of a sudden.

I hoped that Microsoft would have installed it automatically via a windows update for the rest of us not on  `#Windows10`. I was apparently wrong.

**Comment by takluyver** [comment]
I googled the error code plus Python and found this issue: http://bugs.python.org/issue25157

It sounds like it's something to do with Windows update and the installation of the C runtime packages, but it's probably a system problem rather than a bug in the installer.

**Comment by takluyver** [comment]
Oh, and I also got this Windows support page, which suggests manually installing an update to resolve that error: https://support.microsoft.com/en-us/kb/2906956

**Comment by zooba** [comment]
The official installer bundles (or downloads) the UCRT, which is not the full vcredist runtime, but it is enough for core CPython and C extension modules (but not C++).

WinPython probably wants to bundle or install the full vcredist, or at least make it trivially easy for users to get it. Alternatively, be very careful not to include extensions that use C++/OMP/etc..

**Comment by stonebig** [comment]
To me, the compiler runtime is an OS thing, since vs2015 (back to normal, imho).

**Comment by zooba** [comment]
Sure, and all supported and updated OSs should have the correct CRT (but not C++ runtime) already. You'll just have to be prepared to explain the workaround to people who aren't willing to install updates :)

**Comment by techtonik** [comment]
@takluyver so your bundled updates won't help? Do you have some "empty installer" for https://github.com/takluyver/pynsist/ with that run-time check so that I can forward the link to user to see if the fix for https://github.com/takluyver/pynsist/issues/68 works for that specific error.

**Comment by techtonik** [comment]
@zooba or people with malware that blocks or reverts those updates. =)

**Comment by stonebig** [comment]
for the sanity of the winpython hotline, failing to install on not-updated PCs is rather good news.

**Comment by zooba** [comment]
@stonebig In that case, if `LoadLibrary("ucrtbase.dll")` fails, you know the machine isn't up to date. That's the easiest way to see whether the correct CRT is installed.

**Comment by stonebig** [comment]
hum, to warn a user that he doesn't have the UCRT, Winpython may first succeed to start.

unless that thing is doable in vbscript ?

**Comment by takluyver** [comment]
@techtonik If the official Python installers are failing to install the CRT, I highly doubt that Pynsist's hackish solution will work. I don't have empty installers, though I can provide one of the built examples if necessary, but:

- It probably won't work.
- Even if it did, I don't think it would provide much information about the problem or potential proper solutions.
- It's probably best not to teach new users a habit of running exes from some random person's Dropbox public folder.

**Comment by zooba** [comment]
@stonebig I compiled the official installer with the CRT statically linked to avoid that issue.

**Comment by techtonik** [comment]
@zooba so, the correct logic for better user experience is not only to redirect (ideally download) users to required update, but also to check for update prerequisites, right?

https://support.microsoft.com/en-us/kb/2999226#bookmark-prerequisites

**Comment by zooba** [comment]
It depends on the failure state. For the official installer, we would fail with an obscure error message if you don't have the prerequisites. That was because we were doing the install ourselves.

If you're simply linking to the full vcredist, then it should fail with a detailed message if the prereqs are missing. An annoying extra download before finding that out, but not necessarily the end of the world, depending on the expected user base.
