### ISSUE TITLE
Request winpython 2.7 zero version

### ISSUE THREAD

**Issue by Rochey** [winpython/winpython#344]
Hi all,
I'm requesting a winpython 2.7 zero version please.
I'm new to python and am leaning it in conjunction with juniper networking. I only require a working python environment and the junos-eznc library. I'd like to install this to a usb drive.

As a side note, I have downloaded the latest 2.7 version and uninstalled everything that pip had installed. This started to give me a windows error but eventually uninstalled everything. I installed junos-eznc and everything else it needed and it seems to work ok. Will I be alright with this installation? or later down the line should I expect issues.

Any help is much appreciated.
Rochey

**Comment by stonebig** [comment]
Hi @Rochey 

There is no more work being done on any WinPython2.7. Plumetting an existing Python2.7 as you did may your best option, for what you need.

Keeping legacy bricks like Python.7 floating while trying to run as fast as computer science is impossible for a small project like WinPython, maybe even for the Python community.

**Comment by Rochey** [comment]
Thanks for the feedback. 
I would go to version 3.5 but I think the issue is that ncclient hasn't been upgraded to work with 3.5 yet.
Is there an easy way to remove everything? e.g. "pip uninstall *" or something similar?

**Comment by stonebig** [comment]
maybe I will do it once, just to see if it barely works

**Comment by stonebig** [comment]
https://sourceforge.net/projects/winpython/files/WinPython_2.7/2.7.11.1/betas

**Comment by Rochey** [comment]
Thanks @stonebig 
Downloading and testing it now.
