### ISSUE TITLE
Failure to start because of white space in folder directory (version 3.5.1.3Zero 32bit).

### ISSUE THREAD

**Issue by user-e** [winpython/winpython#345]
![image](https://cloud.githubusercontent.com/assets/13541254/16319041/81eae346-3989-11e6-93ae-ad1fd94e6c48.png)
Whitespace in any folder as part of the file path that the WinPython (version 3.5.1.3Zero 32bit) test files are stored in causes the WinPython Interpreter to fail (and perhaps some other files), as shown in the above test case image. Solving this problem may be a simple case of putting quotation marks around whatever file is attempted to be run.

**Comment by stonebig** [comment]
I may think it should be solved by https://github.com/winpython/winpython/pull/316

So you may use current beta https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.1.4/betas/WinPython-32bit-3.5.1.4Zerob3.exe/download

**Comment by user-e** [comment]
As I said, "Solving this problem may be a simple case of putting quotation marks around whatever file is attempted to be run.". This small problem is evident in the changes (added quotation marks) to 1 file to solve it (https://github.com/winpython/winpython/pull/316/files).
![Screenshot of the edits done (Github diff), described above.](https://cloud.githubusercontent.com/assets/13541254/16362595/c637f124-3baa-11e6-94c5-ab4c18451295.png)  
Now it should be solved - WinPython coders, remember to quote filenames!
