### ISSUE TITLE
QT Designer - code generation failed

### ISSUE THREAD

**Issue by Mike-D2** [winpython/winpython#347]
Being new to win python, I'm trying to create a GUI. QT designer appears to work fine untill you try to generate the code to put into a python program - I havent found any documentation on this procedure, so I may be missing someting. Howerver, when I try Form>View code ; I get a code generation failed message.
![qtdesigner1](https://cloud.githubusercontent.com/assets/20135110/16353409/ca15e8f6-3acd-11e6-83b5-790406e2eed8.JPG)
What is wrong? I also tried to install a previous version, and got the same error.

**Comment by stonebig** [comment]
If you desin is in d:\toto\myscreen.ui, you may launch "Winpython Command Prompt", and from there:
````
pyuic4 d:\toto\myscreen.ui
````

**Comment by Mike-D2** [comment]
Thanks a lot.
PLEASE: Can pyuic4 be modified such that the output file name can be specified in the invoke statement i.e. -o "monty.py" {complete with path name, or using same directory as input ui file? Having the result turn up as "FILE" in scripts is leaving the job unfinished?

**Comment by stonebig** [comment]
````
pyuic4 d:\toto\myscreen.ui > monty.py
```

**Comment by Mike-D2** [comment]
Thank you. 
pyuic4 d:\toto\myscreen.ui > monty.py
! Undocumented, typing pyuic4 -h, does not include this.

**Comment by stonebig** [comment]
solved

**Comment by Khalidhussain1134** [comment]
Hi, I am trying to generate the python code from Form view code in Qt Designer, I face the following error, I also tried it for qt4, but the error is same
![capture](https://user-images.githubusercontent.com/26816358/35906112-4b768118-0be1-11e8-88f1-b66338544048.JPG)

Kindly help me to solve this error. I have no WinPython as in case of Mike-D2.

**Comment by anolduse** [comment]
This is 2020 and Im still getting same error + the system cannot find the file specified.
I just installed everything properly.

Are you developers dumb? you can't make a correct program. Idiot.

**Comment by anolduse** [comment]
If you can't make a program correctly then stop developing, you and your program is headache.

**Comment by anolduse** [comment]
![image](https://user-images.githubusercontent.com/40627485/85147386-65a8e100-b26c-11ea-8833-069d6c012f9c.png)

Motherfuckers what is this error now?
