### ISSUE TITLE
PyLint Issue

### ISSUE THREAD

**Issue by Patrick-Cole** [winpython/winpython#35]
Hi,

I have problems using pylint on version 3.4.2.3

If I run it from within spyder, nothing happens. 

If I run it from WinPython Command Prompt.exe I get the following error:

Fatal error in launcher: Unable to create process using '"D:\Winpython\basedir34\build\winpython-3.4.2.amd64\python-3.4.2.amd64\python.exe" "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\Scripts\pylint.exe"'

My WinPython is installed in the following directory: C:\WinPython-64bit-3.4.2.3

**Comment by stonebig** [comment]
Hi Patrick, 

What happen if you try pylint.bat ?

**Comment by stonebig** [comment]
Well... you're right. I have the issue also.
There is a problem when the .whl format is used for pylint.

I don't see it when checking the build on the same PC, because I didn't yet destroy the "build" directory.

**Comment by stonebig** [comment]
cython work on your release from the commande line, but has also the same issue on latest beta, now that Christoph Gohlke just switched to the .whl format.
==> I can back pedal to .tar format for pylint, but that won't make it for Christoph's binaries

**Comment by stonebig** [comment]
asking for help / advice on the wheel package (not sure if it there I must complain).
https://bitbucket.org/pypa/wheel/issue/130/pip-install-whl-create-launchers-that-are

**Comment by Patrick-Cole** [comment]
Hi, sorry for my delay in answering, I was not at the office. I live in South Africa so I guess I am in a different timezone to you? 

I did find a temporary solution of a sort. If I rename pylint.exe to pylint (no extension) then the pylint.bat will work. After this, spyder started to work with pylint fine. I guess it is not the ideal solution but it works for me for now. 

I suppose that re-writing the .bat file might be more elegant? I am not sure. This worked for me however.

Thanks for looking into this. I am very impressed with all the great work that you are doing!!

**Comment by stonebig** [comment]
In France it's currently one hour later than you.

The problem is lying around since the beginning of Winpython, biting us from time to time.

Yesterday Christoph Gohlke came to the rescue, and found the root cause of this and some possible fixes.

==> Your issue and the underlying cause may be fixed properly in next release.

**Comment by Patrick-Cole** [comment]
Thanks - I am downloading it now.

**Comment by Patrick-Cole** [comment]
Just tested it - it works perfectly thanks :+1:

**Comment by stonebig** [comment]
Super

Thank you for your time to report the issue and check the correction.

**Comment by guotie** [comment]
python 3.5.3 on windows 10 x64 encounter the same problem.
