### ISSUE TITLE
Issues with calling "python" from WinPython Command Prompt.exe

### ISSUE THREAD

**Issue by dougthor42** [winpython/winpython#352]
## Summary
There seem to be a couple issues when calling `python` from the WinPython Command Prompt.

### Issue 1:
+ **Bug:** Calling `python` while in the `install_dir/scripts` directory opens up `ptPython`.
+ **Expected:** Calling `python` from any directory should run the standard python REPL. Calling `ptpython` from any directory should run ptpython.

### Issue 2:
+ **Bug:** Exiting `ptPython` while in the `install_dir/scripts` directory exits to the `install_dir/notebooks` directory, but only if entered by using Bug1 above.
+ **Expected:** Exiting `ptpython` while in the `install_dir/scripts` directory should return the user to the `install_dir/scripts` directory.

## Example:
![winpython_ptpython_issue](https://cloud.githubusercontent.com/assets/5386897/16502752/bd284f08-3ec4-11e6-83a1-3050d685908d.gif)

## Version:
Fresh install of WinPython 3.5.1.3 (bd23ff5dd433f91a59eadb97d454bd8da2eab157)

**Comment by dougthor42** [comment]
Note that calling `ptpython` from `install_dir/scripts` does **not** cause the 2nd issue to occur. I've updated the OP to reflect this.

**Comment by stonebig** [comment]
this should be fix with https://github.com/winpython/winpython/pull/317  of April 2nd. Please try recent builds or wait next release

**Comment by dougthor42** [comment]
I've finally gotten around to testing this, sorry for the delay! Issue 1 seems to be resolved. However, issue 2 still occurs. I've opened up bug #384 for it.

Thanks,
