### ISSUE TITLE
numpy 1.11.1 upgrade problems

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#353]
I tried to upgrade numpy to 1.11.1 in WinPython 64-bit 3.5.1.3 installed under C:\Program Files\, with the scripts modified in accord with #316 and #323.  This is now the only numpy version provided by Gohlke.  Using WinPython Control Panel, I removed scipy, numexpr, numba, MKL-service and then numpy packages.  Next, I installed numpy 1.11.1 and then the latest versions of the above packages from Gohlke's site (scipy 0.17.1 being the latest released version).  The problem I noticed is that WinPython Control Panel now only shows one installed package.

Any reason why numpy 1.11.1 would be incompatible?

Do I understand correctly that the above packages are compiled by Gohlke with the particular numpy+MKL version?  In other words, when I update numpy+MKL, I also need to update every package that depends on numpy+MKL?

WinPython release 2016-03 beta builds so far only have Qt5.  Do I understand correctly that problems with Qt5 and mingwpy are what prevent the final release of WinPython 2016-03?  If so, how about if 2016-03 is based on Qt4, and delay the Qt5 stuff until WinPython 2016-04?  The updates of all the scientific packages above are important for me, not Qt5.  An update based on Python 3.4 and Qt4 would also be helpful where mingwpy is needed.

**Comment by stonebig** [comment]
there should be no compatibility problem. If you think of a former space_in_path bug, do the change in a temporarly non-spaced directory path.

**Comment by hiccup7** [comment]
Could the problem have been fixed by the recent commit entitled 'fix wppm bug with "+mkl"'?

**Comment by stonebig** [comment]
ah, I forgot about this one. Indeed.

You can also place the cgohlke wheel in "d:\toto" and from WinPython Command Prompt do a "pip install d:\toto\numpy-1.11.1+mkl-cp35-cp35m-win_amd64.whl"

**Comment by hiccup7** [comment]
With a fresh installation, I used WinPython Control Panel to remove packages as before.  All the remaining packages are still visible in WCP at this point.  Then I followed your instructions _exactly_ with pip install of numpy.  WCP then shows only one installed package (just like when I used WCP install numpy).

Is it correct that numpy can't be upgraded in WinPython 64-bit 3.5.1.3?  If so, a quick release of WinPython 2016-03 with Qt4 would be helpful.

**Comment by stonebig** [comment]
hi @hiccup7 . I'll do a RC tonight or tomorrow. In the mean time, maybe this would do the trick for your current winpython:
- start winpython command prompt
- launch `pip install --upgrade --force-reinstall https://github.com/winpython/winpython/zipball/master`

**Comment by hiccup7** [comment]
My PC for Python has no internet connection.  I have time to wait for the RC.  Thanks for your help.

**Comment by stonebig** [comment]
done!
