### ISSUE TITLE
mayavi qt_embedding.py example crashes in WinPython 3.5.1.3

### ISSUE THREAD

**Issue by alec-kalinin** [winpython/winpython#360]
I use "mayavi-4.4.4" package from [ http://www.lfd.uci.edu/~gohlke/pythonlibs/ ] repository to display 3D graphics in Qt application. The example of the "Qt" and "mayavi" integration is available here: [ http://docs.enthought.com/mayavi/mayavi/auto/example_qt_embedding.html ].

This example works fine in "WinPython 3.4.4.2", but this example in "WinPython 3.5.1.3" do not work and causes the crush of python.

**Comment by stonebig** [comment]
Maybe try to launch it in a "dedicated" python console (or Qtconsole) ?

If it doesn't work and you don't see bug reports on that in Mayavi development site, I may suggest:
-  you retry with "WinPython 3.4.4.3"
-  you retry with "WinPython 3.5.2.1"

If all fails, maybe consider open an "issue/ask for guidance"  on Mayavi developpement site.

**Comment by stonebig** [comment]
It's maybe just that Mayavi is not truly stable yet with Python 3.5. see:
- https://github.com/enthought/mayavi/issues/384
- https://github.com/enthought/mayavi/issues/395
