### ISSUE TITLE
can't launch ?

### ISSUE THREAD

**Issue by mzakaria130** [winpython/winpython#362]
![winpython](https://cloud.githubusercontent.com/assets/20611710/17077673/8e36849e-5102-11e6-86cc-5e91ee668968.png)

**Comment by stonebig** [comment]
"can't launch" what ? with what version of WinPython ?

**Comment by mzakaria130** [comment]
Thank you for answering my questions , sorry for the basic question , I still lay

**Comment by stonebig** [comment]
No problem. I kept the "non-fonctional" shortcuts as they should become functional if you install PyQt and Spyder over it.
