### ISSUE TITLE
WinPython3.5.2 + automatic graphics backend

### ISSUE THREAD

**Issue by udoliess** [winpython/winpython#365]
With WinPython 3.5.1 I used automatic graphics backend (Preferences/IPython console/Graphics/Backend=Automatic) to show matplotlib chart as flying window. (After changing backend setting you have to restart Spyder.) My test code is:
import matplotlib.pyplot as plt
plt.plot([1,2,4])
With WinPython 3.5.2 the flying window appears but it hangs (window is blank and does not respond to any user action).

**Comment by stonebig** [comment]
Yes, unless you launch in a new console (a new process), you may only use the "%matplotlib inline" mode.

As far as I understand, coming fixes from upstream is to silently do that "%inline".
