### ISSUE TITLE
Python launcher missing from 3.5.2.1Qt5

### ISSUE THREAD

**Issue by garu57** [winpython/winpython#366]
py.exe and pyw.exe missing from this release.
Don't know if they were missing in any previous 3.5 release, this is my first 3.5 install after 3.4.

I had to install and uninstall the official Python release to get those exe's.

Please include them again in next release.

Thanks,
Gabriele

**Comment by stonebig** [comment]
good remark. I have no clue

**Comment by garu57** [comment]
Well, it looks like that for 3.5 there is no longer the way to extract the launcher into the python install directory.
The launcher is installed in a different step and if you use `Include_launcher=1 InstallLauncherAllUsers=1` it will end into `C:\Windows`, if you use `Include_launcher=1 InstallLauncherAllUsers=0` it will end into `%LocalAppData%\Programs\Python\Launcher`.
From there you could retrieve it and put it int the python directory, but given the changes about launcher installation, i wonder if it makes sense.

I posed some questions about to Steve Dower, the python installer architect, if you can keep this open for a while, i'll post if i get any answer.
Gabriele

**Comment by stonebig** [comment]
ok.

**Comment by garu57** [comment]
I've got a very rapid answer indeed. Steve is a very nice guy. I'm posting here the mails because they may be of interest to you.

> 
Hi Steve,
excuse me if i bother you, but i've seen you are the main architect for 3.5 windows installer, and i'd like to pose you some questions about. (i'm working with 3.5.2)
>
1- i need to extract the complete installation but without polluting the registry. I tried all the possible combinations of arguments for scripting interface but it seems there is no way other than performing an install, copy the files elsewhere and uninstall to clean the registry. I'm i correct?
>
2- i'd like to extract the python installer, again without registry involvement, into the same target dir where installation is extracted, but while i can change the target dir for python itself, i've not been able to override the destination of the launcher files. Did i miss something?
>
3- it looks like there is no way to /uninstall the pythonlauncher via the scripting interface and the only way i've found is through the Programs and Features panel, i'm i correct?
>
4- could you consider to simplify the life of those who need to build other distributions (like WinPython) by offering the option to extract installation and launcher via the scripting interface without polluting the registry? (you may have noted the bad feeling i have against the registry for the tendency it has to become a cesspool of rotten cadavers of past installations... At least i saw that python installer diligently cleans all the remnants of its past existence)
>
5- May i expose you a dream? A fully portable launcher that (optionally) happily ignores all about registry and find all the python installation locations via the configuration file... I know that at least for file association i need the registry, but for the rest...
>
Just in case you wonder, i'm not involved in WinPython development, i'm only a user, and all these questions come out after discussing with the developers about the lack of the launcher in WinPython 3.5.2 distribution.

And here is the answer:

>
Hi Gabriele
>
I’m aware of these concerns but unfortunately there are some other aspects that make the suggestion a bad idea.
>
Currently, the implementation of Python will read the registry to find where it is installed. If this is absent, some other heuristics are used, but these can fail. We’ve seen a number of issues here when Anaconda and/or Canopy are installed simultaneously, as they both overwrite these entries and hence may fail to load.
>
The easiest way to extract the layout is to do an install and copy the files. However, if you have an installer that is laying out the official build of CPython, I’d much prefer you downloaded the MSIs (using the exe installer with the /layout option) and installed them directly. Otherwise, the second installer may cause conflicts with the first one. Another approach is to build your own copy of Python with the registry path modified (in PC/getpathp.c and tools/msi/lib/lib_files.wxs) to avoid conflicts.
>
 I have some plans to remove this registry lookup for 3.6, so depending on whether those make it then the next version may make it safer to have a registry-free distribution. However, right now, it is not generally recommended. I am experimenting with Nuget packages so that build systems can use a Python install without touching the registry, though those will only work with 3.5 and some of the early support for suppressing external lookups – it’s very much not designed for use in a user-facing distro like WinPython. It is intended for automated scenarios that know exactly where it has been installed – there are no shortcuts, file associations or documentation.
>
For question 3, no you cannot uninstall the Python launcher through the executable installer. That may be something I add for 3.6, but likely not. You can uninstall it by getting the MSI directly and running it with “msiexec /U launcher.msi”.
>
For question 5, the launcher is already fully portable if you copy it around. The problem is that you actually want your Python install to be registry-free, which we don’t support (the “configuration file” you mention is the registry).
>
Feel free to let the WinPython developers know to get in touch with me and I’m happy to explain why we have these limitations and how they can produce their own version without them. But given the majority of Python installs come from the python.org installers, we need to ensure that they will work correctly and behave as users expect.

**Comment by garu57** [comment]
In conclusion i think that you can forget my request. Being things the way they are, i think it's better if i install the launcher through the official Installer.
Thanks,
Gabriele

**Comment by stonebig** [comment]
there may be a necessity, or a communauty respect, to become py.exe compatible. 

help welcome to digg into how-tos/PEP on that subject, and prepare a patch

**Comment by heetbeet** [comment]
"If you use `Include_launcher=1` `InstallLauncherAllUsers=0` it will end into `%LocalAppData%\Programs\Python\Launcher`." Would it be possible to temporarily `set LocalAppData=<path to WinPython>`, retrieve the files from there, and then set it back to the original?

**Comment by stonebig** [comment]
Sorry, I'm not knowledgable on this subject, so I try to clarify.

Can you explain me the target result to achieve on the end-user pc, and what it will brings :
- we can imagine to have a "py.exe" next to "python.exe" of winpython,
- then ?

**Comment by stonebig** [comment]
closing in favor of https://github.com/winpython/winpython/issues/560
