### ISSUE TITLE
Please clarify reasons for inclusion of pyvenv.cfg in 3.5.2 releases

### ISSUE THREAD

**Issue by garu57** [winpython/winpython#367]
Given that WinPython has happily worked for eons without the need to mangle `sys.path` creation and given that `pyvenv.cfg` with `applocal = True`, along with python executable is mostly oriented towards python embedded in applications it is not clear why you included it.

The major effect of that cfg is to ignore any windows registry entry for python while building `sys.path` and since you offer the option to register WinPython installation, you should at least document the fact that as 3.5 installations are distributed now, registration has no effect at all for `sys.path` building, unless `pyvenv.cfg` is removed.

The second effect that directly affected me is that with `applocal = True,` the user directory is no longer included in `sys.path`.

By the way, to restore the original behavior, `pyvenv.cfg` must be removed. Putting `applocal = False` in it has the strange effect, that i didn't find documented anywhere in official python doc, to include the parent directory in `sys.path`.

Thank you so much for your wonderful work and best regards,
Gabriele

**Comment by stonebig** [comment]
the pyvenv.cfg thing must come from a remark from a more competent guy than me, I have to find back where it is.

**Comment by garu57** [comment]
Well, i see.
But you should be aware that (from same `Python Setup and Usage`):
~~~~
For those who want to bundle Python into their application or distribution, the following 
advice will prevent conflicts with other installations: 
    - Include a pyvenv.cfg file alongside your executable containing applocal = true. 
This will ensure that your own directory will be used to resolve paths even if you have 
included the standard library in a ZIP  file. It will also ignore user site-packages and 
other paths listed in the registry.
~~~~
This means that if one, like me, has registered the WinPython installation, is using it as its main installation and has a user site-packages, the inclusion of `pyvenv.cfg` with `applocal = True`, break the installation as the `sys.path` is not built as expected and this is a backward incompatible change that should at least be well documented.

Gabriele

**Comment by stonebig** [comment]
wait and see what 3.6 change will be.

**Comment by ankostis** [comment]
Just for reference, ``applocal=True` property is gone in 3.6, replaced with the `._pth` file: https://docs.python.org/3.6/using/windows.html#finding-modules

**Comment by stonebig** [comment]
Thanks .... The python 3.6 documentation is a little bit foggy to me,

==> Can you suggest the typical text I should put in "sys.path" to match roughly previous situation  ?

**Comment by ankostis** [comment]
You cannot use `sys.path` anymore; you have to add a new file `python36._pth` in it's place (alongside the executable) with (at least) this content:

```python
## This file isolates WinPython according to these instructions:
#  https://docs.python.org/3.6/using/windows.html#finding-modules
import site
```

But I haven't tried it so you should experiment if more content is needed, i.e. to add another line like this:

    .\Lib

**Comment by stonebig** [comment]
thanks, will re-try in a week with beta2

**Comment by stonebig** [comment]
I don't find the "right" setting to put in python36._pth

**Comment by stonebig** [comment]
trying to make it work is an epic fail with beta2... maybe it's me, maybe it's WinPython design that conflicts

**Comment by stonebig** [comment]
ah, maybe progree: distlib-2.4 was not yet in Python-3.6b2... I may get something that work

**Comment by stonebig** [comment]
so WinPython-3.6.0 will most probably not include a pyvenv.cfg, only a python._pth

**Comment by ankostis** [comment]
Maybe I wasn't that clear, but yes, `sys.cfg` has been dropped completely in PY36.
Thank soy for your great efforts.

**Comment by stonebig** [comment]
new recommandation for Python-3.6 is to not use "python._pth" anymore (http://bugs.python.org/issue29578)  .... so just rename it "python_nomore._pth" and check all is ok
