### ISSUE TITLE
Feature request: PyGMO

### ISSUE THREAD

**Issue by arita37** [winpython/winpython#374]
Hi,

There is the excellent package from ESA PYGMO (optimization).
It would be nice to be included natively in WinPython.
https://github.com/esa/pagmo/wiki/Guide-to-Compilation-on-Windows-x64

Thanks

**Comment by stonebig** [comment]
hi,

Current choice of optimisation and operation research packages in WinPython is probably not optimal, and I'm wide open to suggestions.

Any suggestion should :
- be python 3.4/3.5 compatible, in wheel package format
- provide some nice links on  examples and tutorials the proposed package
- maybe solves the 99 pences problem in winpython_checker.ipynb (so we can replace Pulp): http://nbviewer.jupyter.org/github/winpython/winpython_afterdoc/blob/master/docs/Winpython_checker.ipynb


On Python3:
- Pygmo is only provided in 64 bit and in a msi package,
- it looks not compatible with Python3.5 (as of now, looking at your link)
==> It doesn't fit, as it is.

**Comment by RoyiAvital** [comment]
What about [CVXOPT](http://cvxopt.org/)?

Along with [CVXPY](http://www.cvxpy.org/en/latest/) it would be awesome.

**Comment by stonebig** [comment]
and would CVXOPT+CVXPY allow to redo current PULP example ? 
````
# Pulp example : minimizing the weight to carry 99 pennies
#                (from Philip I Thomas)
# see https://www.youtube.com/watch?v=UmMn-N5w-lI#t=995
# Import PuLP modeler functions
from pulp import *
# The prob variable is created to contain the problem data        
prob = LpProblem("99 pennies Problem",LpMinimize)

# Variables represent how many of each coin we want to carry
pennies = LpVariable("Number of pennies",0,None,LpInteger)
nickels = LpVariable("Number of nickels",0,None,LpInteger)
dimes = LpVariable("Number of dimes",0,None,LpInteger)
quarters = LpVariable("Number of quarters",0,None,LpInteger)

# The objective function is added to 'prob' first

# we want to minimize (LpMinimize) this 
prob += 2.5 * pennies + 5 * nickels + 2.268 * dimes + 5.670 * quarters, "Total coins Weight"

# We want exactly 99 cents
prob += 1 * pennies + 5 * nickels + 10 * dimes + 25 * quarters == 99, ""

# The problem data is written to an .lp file
prob.writeLP("99cents.lp")
prob.solve()

# print ("status",LpStatus[prob.status] )
print ("Minimal Weight to carry exactly 99 pennies is %s grams" % value(prob.objective))
# Each of the variables is printed with it's resolved optimum value
for v in prob.variables():
    print (v.name, "=", v.varValue)
````
(giving)
````
Minimal Weight to carry exactly 99 pennies is 31.546 grams
Number_of_dimes = 2.0
Number_of_nickels = 0.0
Number_of_pennies = 4.0
Number_of_quarters = 3.0
````

**Comment by RoyiAvital** [comment]
@stonebig, It doesn't have to replace.
It can be in addition to.

But yes, they can do that.

The point is CVXPY is the Python equivalent of [CVX](http://cvxr.com/cvx/) which is the most popular MATLAB toolbox for Convex Optimization.  
It means it will attract many MATLAB users and will make them feel home.
Since CVXPY requires CVXOPT you must provide them both.

They are great, really.

**Comment by stonebig** [comment]
oups, problem: cvxpy requires pyreadline:
````
No matching distribution found for pyreadline>=1.7.1 (from dill>=0.2.5->multiprocess->cvxpy)
````

**Comment by RoyiAvital** [comment]
I'm not a big specialist, but can we add `pyreadline` as well?
Or there is a big problem with adding it?

**Comment by stonebig** [comment]
It's the only package that would still be installed via a ".exe" package.

I was so happy to remove it, back-pedaling is not an easy decision.

==> I would prefer cvxpy to move away from "multiprocess" package
