### ISSUE TITLE
Parentheses in path name breaks env.bat, stops Spyder.exe and other commands from running

### ISSUE THREAD

**Issue by jokfish** [winpython/winpython#375]
Symptoms are that double clicking Spyder.exe just does nothing. 

In WinPython-64bit-3.5.2.1Qt5 (and I believe other 3.4 and 3.5s) the test for R and Julia directories is done with the section
`````
if exist "%WINPYDIR%\..\tools\R\bin" (
    set R_HOME=%WINPYDIR%\..\tools\R
    if "%WINPYARCH%"=="WIN32" (
        set R_HOMEbin=%R_HOME%\bin\i386
    ) else (
        set R_HOMEbin=%R_HOME%\bin\x64
    )
)
`````

Which fails with the following error if there are any parentheses (specifically round brackets) in the path name;
`\WinPython-64bit-3.5.2.1Qt5\scripts\..\python-3.5.2.amd64\..\tools\R was unexpected at this time.`

In WinPython-64bit-2.7.9.5 this test was done with an 'if NOT exist' statement, which seemed to catch this error
`````
if not exist "%WINPYDIR%\..\tools\R\bin" goto r_bad
set R_HOME=%WINPYDIR%\..\tools\R
if %WINPYARCH%=="WIN32"     set R_HOMEbin=%R_HOME%\bin\i386
if not %WINPYARCH%=="WIN32" set R_HOMEbin=%R_HOME%\bin\x64
:r_bad
`````

I have tried copying the method into the 3.5.2.1 env.bat and have confirmed that it fixes the problem.
`````
if not exist "%WINPYDIR%\..\tools\R\bin" goto r_bad
set R_HOME=%WINPYDIR%\..\tools\R
if "%WINPYARCH%"=="WIN32" (
	set R_HOMEbin=%R_HOME%\bin\i386
) else (
	set R_HOMEbin=%R_HOME%\bin\x64
)
:r_bad
`````

Although it's only a work around, because I'm guessing it doesn't solve the problem where the directory has parentheses in the name AND R or Julia exist.

Thanks to everyone who has put so much work into this great package.

**Comment by stonebig** [comment]
can youi gibe me an example of a path name `(specifically round brackets)`, so I'm sure to understand ?

**Comment by stonebig** [comment]
so, something safety-belted like that:
`````
rem ******************
rem handle R if included
rem ******************
if not exist "%WINPYDIR%\..\tools\R\bin" goto r_bad
set R_HOME=%WINPYDIR%\..\tools\R
if     "%WINPYARCH%"=="WIN32" set R_HOMEbin=%R_HOME%\bin\i386
if not "%WINPYARCH%"=="WIN32" set R_HOMEbin=%R_HOME%\bin\x64
)
:r_bad

`````

**Comment by jokfish** [comment]
When I was testing I used the folder c:/tmp/(tmp)/ to verify it wasn't path length. 

That second section of code you posted looks better, were you able to replicate the problem?

The DOS was so ugly I couldn't get my head around it, offended my spoilt eyes that are so used to looking at Python ;)

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/pull/376
