### ISSUE TITLE
why zero?

### ISSUE THREAD

**Issue by kklmn** [winpython/winpython#378]
What is the point of the "Zero" distribution? I was searching the pages for a smallest description -- nothing. Such a basic need as scipy is not possible with pip because of BLAS and LAPACK. Why then WinPython is needed if I have to screw many things together myself? I could then start directly from python.org/download. This is not just a complaint, I really want to know it as a loyal long-years user of WinPython, before I download anaconda. Thanks!

**Comment by kklmn** [comment]
PS For a number of reasons I need Python 2.7. Its last non-zero WinPython version is one year old soon.

**Comment by stonebig** [comment]
"Zero" is for the minimal version, with the less number of packages.

Indeed there is no more refresh of "Full" WinPython2.7: no time to spend on it.

The "Zero" version may allow you to reconstitute a full version, by:
- downloading all wished packages from cgohlke (in let say "c:\toto" directory)
- placing their names in a c:\toto\mylist.txt" file
- then launching from winpython command prompt a:

`pip install -r "c:\toto\mylist.txt" --no-index --find-links=c:\toto --trusted-host=None`
