### ISSUE TITLE
Cannot install netCDF4 wheel package using Control Panel

### ISSUE THREAD

**Issue by cpaulik** [winpython/winpython#38]
Hi,

I just tried to install the netCDF4 package using the .whl installer from http://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4

But I get the error:

>The following package filenaming are **not recognized** by WinPython Control Panel: netCDF4-1.1.3->cp27-none-win_amd64.whl"

Using the command 
```
wheel install netCDF4-1.1.3-cp27-none-win_amd64.whl
```
installs the package without problems.

Thanks.

WinPython version 2.7.9.1 64Bit
Windows 7

**Comment by stonebig** [comment]
You're right,

Christoph Gohlke sudden love for wheels of all type, after years of "exe" stability, was not anticipated.

The next build6 should have this fixed

**Comment by stonebig** [comment]
If you have time, you can try the fix here.

build6 should be pretty stable and close to final.

https://sourceforge.net/projects/stonebig.u/files/Winpython_betas/WinPython-64bit-2.7.9.2_build6.exe

**Comment by cpaulik** [comment]
Thanks. The new version works without problems.

**Comment by stonebig** [comment]
super ! 
Thank your for your time to report the issue and check the correction.
