### ISSUE TITLE
update/switch of  optimization packages ?

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#380]
we currently use Pulp: GLPK, COIN CLP/CBC, CPLEX, and GUROBI

maybe cvxopt and cvxpy are better fit:  GSL, FFTW,  GLPK 

pygmo is far far away in the galaxy (tricky to install), something different ?

**Comment by RoyiAvital** [comment]
Does the package include GUROBI?
I thought GUROBI is commercial.

Why not have all of them?

**Comment by stonebig** [comment]
Including "everything" makes "standard" WinPython bigger to download, longer to install.

Until there is an excellent reason, WinPython tries to stay below 300Mo.

**Comment by RoyiAvital** [comment]
I see, good point.

What about GUROBI?

By the way, an option would be to have and edition with more packages?

**Comment by stonebig** [comment]
Gurobi is not free nor open source.

**Comment by RoyiAvital** [comment]
This is what I thought hence I didn't understand what you meant writing:

> we currently use Pulp: GLPK, COIN CLP/CBC, CPLEX, and GUROBI

**Comment by stonebig** [comment]
I copied this from https://en.wikipedia.org/wiki/COIN-OR#PuLP

**Comment by RoyiAvital** [comment]
I see.
Well looking at [PuLP on GitHub](https://github.com/coin-or/pulp) it seems to be pre equipped only with COIN CLP/CBC.

Thank You.

**Comment by stonebig** [comment]
otherwise, it seems "multiprocess" could be evicerated from cvxpy requirements, as only used in an example.

**Comment by stonebig** [comment]
I may hunt back for another optimizer as PULP is too slow and only includes CLP/CBC

soplex (or SCIP/soplex ?)  seems the necessary future , when possible, unless we can integrate a Julia thing (when  it becomes stable and ok on windows)

http://stackoverflow.com/questions/39924316/speed-of-cplex-vs-cplex-using-scip

**Comment by stonebig** [comment]
I can include cvxpy now, yet not sure if it's an interesting package.

**Comment by RoyiAvital** [comment]
[CVXPY](https://github.com/cvxgrp/cvxpy) is amazing addition.

Many users coming form MATLAB which use CVX will feel at home.
Please add it.

Thank You.

**Comment by stonebig** [comment]
ok, retrying.

**Comment by stonebig** [comment]
cvxpy is there. let say it's ok for now.

**Comment by RoyiAvital** [comment]
@stonebig , You're the best.

Have you looked at collaboration with PortableApps?

Thank You.

**Comment by stonebig** [comment]
It looks an outdated (or automated) bundle. see the dates on  https://portableapps.com/development/outdated

**Comment by RoyiAvital** [comment]
They have something updated:

https://portableapps.com/node/56106

But in order to make it official (Which will bring more exposure) they ask for the official owner of the program to show interest.

If you contact the site owner ([John T. Haller](https://github.com/JohnTHaller), Their GitHub - https://github.com/PortableApps) or express on that thread that you're the owner of WinPython and would like to see it official it will become official.

This will bring more users and great exposure.
WinPython deserves it.
