### ISSUE TITLE
Exiting python after being called from "...\scripts" directory changes the CWD.

### ISSUE THREAD

**Issue by dougthor42** [winpython/winpython#384]
## Summary
Exiting python after being called from "...\scripts" directory changes the CWD.

## Steps to Reproduce:
1. Open up `<install_dir>\WinPython Command Prompt.exe`
2. type `python` to start the interpreter
3. type `exit()`

### Expected Behavior:
The CWD stays at `<install_dir>\scripts`.

### Actual Behavior:
The current directory changes to `<install_dir>\notebooks`.

## Example:
![winpython_python_issue](https://cloud.githubusercontent.com/assets/5386897/18104621/ddc2402c-6eb0-11e6-9d18-9fe5b61557bb.gif)

## Versions:
+ Fresh install of WinPython 3.5.2.2, 64-bit, Qt5
  + 48533fbe6b94eee5a8a3c82f0a49a2019e7a4cfd
  + tag 1.6.20160828
+ Windows 10 Pro, Anniversary Update (v1607, build 14393.82)

## Related Issues:
+ #352

**Comment by stonebig** [comment]
in scripts, change current python.bat from 
````
@echo off
call "%~dp0env_for_icons.bat"
cd/D "%WINPYWORKDIR%"
rem backward compatibility for  python command-line users
"%WINPYDIR%\python.exe"  %*
````
to
````
@echo off
call "%~dp0env_for_icons.bat"
rem backward compatibility for  python command-line users
"%WINPYDIR%\python.exe"  %*
````

will be in next beta
