### ISSUE TITLE
New install of WinPython-64bit-2.7.12.3Zero - Control Panel & Spyder do not run

### ISSUE THREAD

**Issue by Humancell** [winpython/winpython#400]
I'm pretty good at installing and using software, but something is very wrong here.  I did the install of this package to my D:/python directory.  It created the entire sub-directory structure within there ... and nothing works.

Attempting to run the WinPython Control Panel, or Spyder does nothing.  Even from the command line ... no errors, nothing.  Just a new command prompt.

I then tried installing the C++ redistributables ... nothing.  Same thing.  No errors ... no pop-ups ... not sure if there is a log I can look at ...

I'm on Windows 7, everything is current.  I've been Googling and reading everything I can, but can't find anything to help.

Shouldn't this just work?

**Comment by stonebig** [comment]
Yes, the "Zero" versions do contain only a minimal list of packages: https://github.com/winpython/winpython/blob/master/changelogs/WinPythonZero-2.7.12.3.md

You may compare it, to python default installer or miniconda.

Here is about the same question and more detail answer here:
https://github.com/winpython/winpython/issues/397

**Comment by Humancell** [comment]
That explains the very small size of the installer!  Thank you!  That worked.  I uninstalled and went to version WinPython-64bit-2.7.10.3

This might be a silly question, but why is the "Zero" version including .exe files that are know not to work?  Does this mean it's upgradable - somehow - to have all of the included parts work?

It really seems to be a support nightmare, with people like me thoroughly confused attempting to install it.

**Comment by stonebig** [comment]
because of simplicity, indeed:
- you can do "pip install jupyter" in your zero with great chance of success when clicking on "jupyter.exe" after,
- the ".exe" icons rely for the moment on nsis tool, so it would be unknown complexity to create them on the fly.

that could change, if I can get rid of nsis for icons.

**Comment by helge42** [comment]
hi, 
to get jupyter in the zero-version it works with winpython-3.5.4.
But with "pip3 install spyder" I can't get the spyder-icon working. It just happen nothing.
Any advice?
sincerely , Helge

**Comment by stonebig** [comment]
hi @edge42, you must install PyQt5 to get Spyder to work.
"pip install PyQt5"
see the other thread on it: https://github.com/winpython/winpython/issues/508#issuecomment-342632784

Spyder doesn't enforce PyQt5 over PyQt4 over PySide, so doesn't tell you you need a "Qt" enabler package..
