### ISSUE TITLE
Failing to launch control panel, spyder, qt linguist and qt designer - WinPython-64bit-2.7.12.3Zero

### ISSUE THREAD

**Issue by tgrandje** [winpython/winpython#401]
Hi

I tried to install WinPython-64bit-2.7.12.3Zero on my personnal laptop (having it previously installed on a professional laptop on windows 7), using the .exe from sourceforge (no problem whatsoever during the installation).

Afterwards, all applications seems to work fine except for :
- WinPython Control Panel.exe
- Qt Designer.exe
- Qt Linguist.exe

No windows ever launches (I don't have any error message neither), it's juste the application doesn't seem to function. I tried several "compatibilities" options (windows 7, 8 : it doesn't seems to change anything).

I just installed the WinPython-64bit-3.4.4.4Qt5, and this time everything seems to work fine.
Thanks in advance for any suggestion !
tgrandje

_PS : first issue submitted on github : I hope I didn't violated any rule, nor mistaked the place for requests..._

**Comment by stonebig** [comment]
Hi @tgrandje 

Everybody did a first submission on Github.

the "Zero" versions do contain only a minimal list of packages: https://github.com/winpython/winpython/blob/master/changelogs/WinPythonZero-2.7.12.3.md

You may consider it's somewhere between python default installer and miniconda.

Here is about the same question and more detail answer here:
#397

**Comment by tgrandje** [comment]
Hi and thanks !

That solved it. I feel kind of silly about it though... There seems to be a lot of posts about it, but I didn't find those (searched essentially with google...). It's always the same : when you suspect it's about one thing (in that case win10), you have trouble finding the right posts...

Sorry for the inconvenience !
tgrandje

**Comment by stonebig** [comment]
no problem: the experts of tomorrow are the newcomers of today, and must be welcomed.
