### ISSUE TITLE
How to use pip from normal cmd prompt

### ISSUE THREAD

**Issue by mafrosis** [winpython/winpython#403]
Hello, please excuse any obvious mistakes here - I'm a Windows noob (not a python noob, though).

I'm trying to write a batch script which will download/unpack WinPython and then install a package into it with `pip`. However, I'm unable to use `pip` unless I start the WinPython prompt via `WinPython Command Prompt.exe`.

Is this possible? What environment bootstrapping does `WinPython Command Prompt.exe` do, which is missing from a generic `cmd.exe`? Is there a alternate/better way of achieving this?

Thanks!

**Comment by stonebig** [comment]
the icons are, in recent versions, just launching ".bat' treatments in \winpython-64bit-3.x.y.z\scripts.

if you want to pip install something, type:
````
call .....\winpython-64bit-3.5.x.3\scripts\env.bat
pip install asyncio
````

one exception for pip:
`````
call .....\winpython-64bit-3.5.x.3\scripts\upgrade_pip.bat
````

**Comment by mafrosis** [comment]
This is great. Thank you!

**Comment by NedJWestern** [comment]
This is awesome. Thanks! I notice the equivalent option for PowerShell is calling the `WinPython_PS_Prompt.ps1` file.
