### ISSUE TITLE
Spyder, Control Panel, and other apps do not start

### ISSUE THREAD

**Issue by slhck** [winpython/winpython#405]
Running a fresh install of WinPython 64-Bit 2.7.12.3 on Windows 7 Professional, 64-bit.

When I try to start Spyder or the Control Panel, or other apps like nothing happens.

When I open a command window and run `spyder.bat`, I get this:

```
C:\WinPython\WinPython-64bit-2.7.12.3Zero\scripts>spyder.bat
Der Befehl ""C:\WinPython\WinPython-64bit-2.7.12.3Zero\scripts\..\python-2.7.12.amd64\scripts\spyder.exe"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

(Sorry, German.) So apparently it's looking for `spyder.exe` in `scripts`, but of course there is no such executable there. Also, it ends up in the `notebooks` directory after running that script.

Any pointers on what's going wrong here?

**Comment by stonebig** [comment]
Yes, the "Zero" versions do contain only a minimal list of packages: https://github.com/winpython/winpython/blob/master/changelogs/WinPythonZero-2.7.12.3.md

You may consider it's somewhere between python default installer and miniconda.

Here is about the same question and more detail answer here:
#397

**Comment by slhck** [comment]
Ah, now I understand. Thank you very much for the pointers. Although I have to admit: it's quite confusing for new users of WinPython to understand this. There's no error message, no documentation, nothing that'd hint at this issue. It seems like it's broken. A colleague recently told me the same.

Do you think the WinPython documentation or the software itself could be amended to save users from having to troubleshoot this (non-)issue?

PS: I understand that one would move away from 2.7, but just like for the other poster, the migration was never worth the effort for me and the dozens of colleagues who depend on it.

**Comment by stonebig** [comment]
This is the problem:
- I had zero internal requirement nor need for a full WinPython2.7,
- I nevertheless maintained a Full WinPython-2.7 to help people cross the bridge to Python 3,
- so new user came on Python3, legacy users didn't (why change if there is a fresh and easy WinPython 2.7).

 ==> Maintaining a Full WinPython-2.7 was counter-productive.

**Comment by slhck** [comment]
I understand where you're coming from! (Well, maybe this is the event that finally makes me switch?)
