### ISSUE TITLE
Cannot open App in WinPython folder

### ISSUE THREAD

**Issue by PhanDuc** [winpython/winpython#407]
Hi,
I installed winpython on windows 10 64bit. After that i run "WinPython Control Panel.exe" or "Spyder.exe" or "IDLEX (Python GUI).exe" but not any of that open.
I copy app from that folder to desktop, when i run its show an error : 
"Can not find script file "C:\Users\palev\Desktop\script\Noshell.vbs"

**Comment by stonebig** [comment]
maybe you wanted to "create shortcuts" on your desktop ?
