### ISSUE TITLE
Spyder.exe doesn't launch (winpython zero)

### ISSUE THREAD

**Issue by DominiqueMakowski** [winpython/winpython#408]
Hello, 
I've downloaded winpython 3.5.2.2 zero 64bits, but when I try to open spyder.exe, spyder reset.exe or the control panel, nothing happens. I've tried it on 3 different computers (all windows 10 64x) and the same happens.

Note that winpython (not zero) works like a charm.

Thanks for your precious work 😉 
Cheers

**Comment by stonebig** [comment]
there is no Spyder in WinPythonZero, only Python and a few packages: https://github.com/winpython/winpython/blob/master/changelogs/WinPythonZero-3.5.2.2.md

**Comment by DominiqueMakowski** [comment]
Well then it makes sense 😄 

Maybe remove the spyder icons in the next release to prevent other people from posting the same issue?

**Comment by stonebig** [comment]
you can add it after. problem is I can't make the spyder icon appear by magic if you install it
