### ISSUE TITLE
Winpython *.bat launchers change the current working directory after exiting

### ISSUE THREAD

**Issue by heetbeet** [winpython/winpython#409]
# Summary
In the `make.py` script, most `*.bat` launchers are set to contain the line `cd/D "%WINPYWORKDIR%"` or a similar `cd/D ...` line. This causes an unexpected change in the current working directory when accessing these launchers from the command prompt. Issue #384 details this unexpected behaviour for `python.bat`, I raise this issue to be applicable for all `*.bat` launchers.

# Example
![bd284f08-3ec4-11e6-83a1-3050d685908d](https://cloud.githubusercontent.com/assets/4103775/19382379/42bae106-9200-11e6-8da2-7e9ba09cbb43.gif)

**Comment by stonebig** [comment]
point valid.

**Comment by stonebig** [comment]
hum,

I think this problem was solved in latest WinPython-3.5.2.3, via  commit of September 1rst, 2016:
https://github.com/winpython/winpython/commit/a3265790332cdf78fb7fac1aed71ceb0c64b64dd

**Comment by heetbeet** [comment]
@stonebig, yes part of the problem was solved in a326579, but only for `python.bat`, I recommend it to be solved for all `.bat` launchers. Unless I am mistaken, would it be possible to reopen this issue?

**Comment by stonebig** [comment]
would mean doing separate batches, as "python.bat" vs "winpython.bat"

**Comment by stonebig** [comment]
winidlex.bat = called by the icon, change directory
idlex.bat = called directly

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/pull/414
