### ISSUE TITLE
"Unable to create process using ..." errors for the *.exe launchers in WinPython...\python...\Scripts

### ISSUE THREAD

**Issue by heetbeet** [winpython/winpython#410]
# Summary

When I run any of the `*.exe` files contained in the scripts directory of `...\WinPython...\python...\Scripts` an error occurs with the message:<br>`Fatal error in launcher: Unable to create process using '"'`

This error is not present when running any of the `.bat` files in `...\WinPython...\scripts`. This mostly effects launchers that doesn't have wrapper launchers in `...\WinPython...\scripts` such as pip and ipython, since this is their only point of entry.
# Examples

![untitled2](https://cloud.githubusercontent.com/assets/4103775/19383147/4c1e671a-9203-11e6-8e8b-9094d9ed7520.png)
# Versions

My version of Winpython is WinPython-64bit-3.5.2.2Qt5.

**Comment by heetbeet** [comment]
I found a workaround to get all the launchers working by wrapping them all in `.bat` files. For those also seeking this temporary solution, here is some code to replace the file extentions `*.exe` to `*.ignore` (and thus hiding their executability) and creating `*.bat` wrappers as an entries to these `*.ignore` file. To do this, `cd` to the scripts directory, and run the following python code:

```
import os

dir, _, files = next(os.walk('.'))
exe_files = [os.path.join(dir, file) for file in files if file.lower().endswith('.exe')]
ign_files = [os.path.join(dir, os.path.split(file)[1][:-len('.exe')]+'.ignore') for file in exe_files]
bat_files = [os.path.join(dir, os.path.split(file)[1][:-len('.exe')]+'.bat') for file in exe_files]

bat_content = r'''
@echo off
call "%~dp0..\..\scripts\env.bat"
"%~dp0{name}" %*
'''

for exe_file, hid_file, bat_file in zip(exe_files, ign_files, bat_files):
    os.rename(exe_file, hid_file)
    with open(bat_file, 'w') as f:
        f.write(bat_content.replace('{name}', os.path.split(hid_file)[-1]))
```

**Comment by heetbeet** [comment]
My previous approach might be a bit too disruptive, a better way is to make an additional directory `WinPython-xxbit-x.x.x.x\scripts_python` that contains all the `WinPython-xxbit-x.x.x.x\python-x.x.x.x\Scripts` goodies, so you can add that dir to your windows path without any side-effects. To do so, make sure you are in the `WinPython-xxbit-x.x.x.x` directory and run the following python code:

```
import os

_, dirs, _ = next(os.walk('.'))
pydir = [dir for dir in dirs if dir.startswith('python-')][0]
from_dir, _, files = next(os.walk(os.path.join(pydir, 'Scripts')))
to_dir = 'scripts_python'

try:
    os.mkdir('scripts_python')
except OSError:
    pass

exe_files = [os.path.join(from_dir, file) for file in files if file.lower().endswith('.exe') or file.lower().endswith('.bat')]
bat_files = [os.path.join(to_dir, os.path.split(file)[1][:-len('.exe')]+'.bat') for file in exe_files]

bat_content = r'''
@echo off
call "%~dp0..\scripts\env.bat"
"%~dp0..\{insert}" %*
'''

for exe_file, bat_file in zip(exe_files, bat_files):
    with open(bat_file, 'w') as f:
        f.write(
            bat_content.replace('{insert}', exe_file)
            )
```

# Result
![batdirs2](https://cloud.githubusercontent.com/assets/4103775/19389825/c482c6f2-9225-11e6-9f8a-1acae9a5478e.png)

**Comment by stonebig** [comment]
another solution is to make winpython "fix", by executing `...\WinPython...\scripts\make_winpython_fix.bat`

**Comment by heetbeet** [comment]
I was wondering, one of the goals of Winpython is to be portable. With the current winpython setup, if you run one of the WinPython launchers from a script, the environment of that script changes for the rest of the script's lifetime (lots of `set THIS=that` commands are run through the `env.bat` script). This can lead to some unexpected behaviour. Say you have a Python 2.7 registered on your machine, and you want to run only one command under your WinPython 3.x, and then some more under your registered Python, your script will fail at that.  Here is an example of a script with some unexpected behaviour:
```
python -c "print 'hello from 2' "
C:\WinPython-64bit-3.5.2.2Qt5\scripts\python -c "print('hello from 3') "
python -c "print 'hello from 2' "
```

My suggestion is to create a `env_exit.bat` file to undo any changes made to the Windows variables. In `env.bat` all the `set VARIABLE=something` will need to be replaced with something like
```
(set WINPYTHON_BACKUP=%WINPYTHON_BACKUP%VARIABLE{EQUALS}%VARIABLE%{SEPERATOR}
set VARIABLE=something)
```
so that `env_exit.bat` can loop through the `WINPYTHON_BACKUP` Windows variable separated by `{SEPERATOR}` and reset all the variables to their original.

Anycase, it might then be useful to have all the executables in `WinPython-xxx\python-xxx\Scripts` and `WinPython-xxx\python-xxx` to be wrapped as such:
```
%~dp0..\scripts\env.bat
<path to executable>
%~dp0..\scripts\env_exit.bat
```
And be placed in a directory named something like `WinPython-xxx\scripts_portable`. Then any of the original python executables can be run in a portable fashion without any unexpected behaviour. I would also suggest that some executables such as `pythonw` and `spyder` gets tagged as non-prompt or something and gets a different launcher (like a `.vbs` or a `.bat` with a `start` command) not to have that ugly command prompt window lurking around.

I would like to contribute to this, how to I make a pull request?

**Comment by stonebig** [comment]
Hum,

**get back to how you were before**
The big python braind would suggest to use "py.exe" strategy instead. 

**executables such as pythonw and spyder gets tagged as non-prompt**
This is what the icons do: they launch "winpython-xxbit-x.x.x.x\scripts\Noshell.vbs spyder.bat" for example.

**Comment by stonebig** [comment]
there is something maybe related there: https://bugs.python.org/issue32457
