### ISSUE TITLE
winpython/data/packages.ini is not synced

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#411]
I see the following inconsistency:
openpyxl is listed [in the packages.ini](https://github.com/winpython/winpython
/blob/b1b822ff0553d87394f6f72c4ea5034ff4e0877c/winpython/data/packages.ini#L593), but not in the [website's packages list](https://github.com/winpython/winpython/blob/master/changelogs/WinPython-3.5.2.2.md).

In fact, it is not contained e.g. in `WinPython-64bit-3.5.2.2.exe`: `from openpyxl import load_workbook` gives `ImportError: No module named 'openpyxl'`.

(Why was it removed?)

**Comment by stonebig** [comment]
There are more packages in "package list" then in (shipped) "Winpython".

The Website's packages list only list what's included in a given "WinPython" version/bundle by default.

**Comment by jondo** [comment]
I see. So this is a list of packages that potentially could be included in bundles.

**Comment by stonebig** [comment]
you can install any package, just "WinPython Control Panel" will only display the description of this package that it will find in the "package list".

unlisted packages will just have no description, but will work as usual
