### ISSUE TITLE
Control Panel entries missing after installing whl

### ISSUE THREAD

**Issue by solarjoe** [winpython/winpython#413]
Hello,

I have a problem and hope you can help me (WinPython-64bit-3.4.4.1).

After downloading and installing the according pyCUDA from http://www.lfd.uci.edu/~gohlke/pythonlibs/ 
(pycuda-2016.1.2+cuda7518-cp34-cp34m-win_amd64.whl) the "Uninstall packages" list is empty, except for one entry (pyreadline?).

Issue is reproduceable.
Has someone ever had a similar problem? What can I try to debug this?

**Comment by stonebig** [comment]
It was (or it is) a failure to distinguish complex package names by the WPPM window.

Winpython works nevertheless and you can use "pip list" to get your list of packages.

**Comment by hiccup7** [comment]
Was this issue solved by pull request #443 ?

**Comment by stonebig** [comment]
it should, as it''s now a simple-stupid split of strings separated per "-".
