### ISSUE TITLE
Regression: Closing Spyder takes several seconds

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#42]
With WinPython-64bit-3.4.2.2.exe, closing Spyder (via menu or window button) happens immediately, while with WinPython-64bit-3.4.2.3.exe and WinPython-64bit-3.4.2.4.exe it always takes at least 6 seconds to close a freshly opened Spyder instance without any open documents, and even longer than 30 seconds after a small script (using os, glob, PIL, matplotlib, scipy, mahotas, numpy) has been run within.

(This is on Windows 7 Professional.)

**Comment by stonebig** [comment]
You're right.

See this thread:
https://groups.google.com/forum/#!searchin/spyderlib/closing/spyderlib/qm77HhwBa9c/tSYIYeWyibcJ

I didn't look if there was a patch identified for Spyder, if it Spyder, since that problem was raised.
==> Can you check ?

**Comment by jondo** [comment]
I also found no patch.
I am closing this issue, since this seems to be an upstream problem.

**Comment by stonebig** [comment]
ok.
