### ISSUE TITLE
Failures installing sounddevice wheel

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#423]
Since I could not get PyAudio to work with the WDMKS api that I desire, I attempted to install the wheel "sounddevice-0.3.5-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36-none-win_amd64.whl" from https://pypi.python.org/pypi/sounddevice/ into 64-bit WinPython 3.5.2.2.
I tried elevated WinPython Control Panel and "wppm -i" from the elevated WinPython Command Prompt, and both threw an error saying the file is not recognized.  I thought it might be the file name length, so a made copy to a short file name.  With both methods, the file was then recognized, but I still got an error saying the wheel is not compatible with 64-bit Python 3.5.

This PR is 2 problems:
1) long wheel names are not recognized
2) Please look at the wheel file and see if really is incompatible.

**Comment by stonebig** [comment]
oups ! This was unexpected a wheel name.

I clearly didn't understood how to split wheels name in proper pieces. patch welcomed.

In the mean time, You can use "pip install sounddevice" to install it via the command line.

**Comment by hiccup7** [comment]
The computer where I am doing the installation is disconnected from the internet, but I have transferred the wheel file to it using the USB flash drive.  Should I use an elevated "WinPython Interpreter.exe" to do the installation?  I am confused about the pip command because the documentation I saw only downloads from the internet.  WinPython already has all the dependencies of the sounddevice package.  How do I install a wheel file that I already copied to my PC (with no internet connection)?

**Comment by stonebig** [comment]
if your wheel is on "e:\BigWheelTheory\sounddevice-0.3.5-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36-none-win_amd64.whl"

do **pip install "e:\BigWheelTheory\sounddevice-0.3.5-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36-none-win_amd64.whl"**

**Comment by hiccup7** [comment]
I tried using "WinPython Interpreter.exe" from the WinPython root with elevated privileges.  This didn't work because the pip command is not found.  Is it a bug that "WinPython Interpreter.exe" doesn't set up the path?

I succeeded by using "WinPython Command Prompt.exe" from the WinPython root with elevated privileges, and typing the following command:
```
python -m pip install "e:\BigWheelTheory\sounddevice-0.3.5-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36-none-win_amd64.whl"
```
pip checked the dependencies during the installation.  I don't know if the -m option was important, but it is suggested at https://pypi.python.org/pypi/sounddevice/

I can now import sounddevice from the console in Spyder.  Also, sounddevice 0.3.5 now appears in the WinPython Control Panel.  I hope this means I can uninstall sounddevice from the WinPython Control Panel if I need to.

**Comment by stonebig** [comment]
"python -m pip" is needed to upgrade pip, as "pip.exe" directly would lock the "pip.exe" object and made the upgrade impossible. for all other package "pip install" is just nice

**Comment by hiccup7** [comment]
I have started testing sounddevice, so I can now declare that sounddevice is compatible with 64-bit Python 3.5.  Therefore, this PR is with WinPython Control Panel and/or wppm.

@stonebig - Please identify the WinPython project source file that splits a wheel name into proper pieces.  This will improve the chances that a kind soul will offer a patch.

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/blob/master/winpython/wppm.py#L143..L158

https://github.com/winpython/winpython/blob/master/winpython/utils.py#L484

**Comment by hiccup7** [comment]
How about adding a "Help Wanted" label?

**Comment by hiccup7** [comment]
@stonebig - Your instructions for using pip to install a local wheel (or pure Python source) file were very helpful to me, including the explanation about the -m option.  I suggest updating the following page to help others who also encounter problems with wppm or WinPython Control Panel:
https://github.com/winpython/winpython/wiki/Installing-Additional-Packages

**Comment by stonebig** [comment]
please do

**Comment by stonebig** [comment]
any news on this decoding ? I don't find a simple using internal pip wires. I may have to do it myself

**Comment by stonebig** [comment]
I may use .split(), much simpler to understand

**Comment by stonebig** [comment]
ok, next version will allow to install soundevice via wppm
