### ISSUE TITLE
PIP cache path ?

### ISSUE THREAD

**Issue by crazy-max** [winpython/winpython#424]
Hi!

Is it possible to override the default pip cache path located at `%USERPROFILE%\AppData\Local\` ?
Would be nice to use the `winpython.ini` to override the path :)

**Comment by stonebig** [comment]
There is a dynamic read of WinPython.ini now by the icons. 
see "make_working_directory_be_not_winpython.bat" as an example.

Would that answer your need?

**Comment by crazy-max** [comment]
Yes but do you know the name of the environment variable to change the pip cache path ?
Currently all PIP cache goes to `%USERPROFILE%\AppData\Local\pip\cache` and i want to put these files in the `settings` folder for example.
Is that possible ?

**Comment by stonebig** [comment]
no idea.

**Comment by crazy-max** [comment]
Ok i found the var name in the official pip documentation.
Just add a new line in `winpython.ini` :

```
[debug]
state = disabled
[environment]
#HOME = %HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
#JUPYTER_DATA_DIR = %HOME%
#WINPYWORKDIR = %HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%\Notebooks
PIP_CACHE_DIR = C:\WinPython%WINPYVER%\tmp
```
