### ISSUE TITLE
ipython console: subprocess.call causes new command window to open

### ISSUE THREAD

**Issue by phoriwan** [winpython/winpython#430]
While in the previous releases external executables called by subprocess.call() were processed within the ipython console, in the latest release (3.5.2.3Qt5) new command windows therefore are opened. This has two essential disadvantages: slower processing and the new command windows are set active so that parallel work in other applications may be interrupted.

Does a workaround for this issue exist?

**Comment by stonebig** [comment]
I'm afraid it's rather a question for Ipython team, you may ask them, with a typical example script.
