### ISSUE TITLE
Qt Designer for Qt5

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#431]
From https://pypi.python.org/pypi/pyqt5-tools
> The PyQt5 wheels do not provide tools such as Qt Designer that were included in the old binary installers. This package aims to provide those in a separate package which is useful for developers while the official PyQt5 wheels stay focused on fulfulling the dependencies of PyQt5 applications.

Note that the referenced Github project has a newer release available.  I haven't tried pyqt5-tools.  Has anyone tried pyqt5-tools with WinPython?

For Qt5 releases, I propose WinPython either includes pyqt5-tools or informs the user about the availability of pyqt5-tools.

**Comment by stonebig** [comment]
PyQt5-tools is marked "2 - Pre-Alpha", and a bit heavy as there is some duplicated binaries from PyQt5 package.

**Comment by hiccup7** [comment]
I offered the option of informing the user about the availability of pyqt5-tools.

**Comment by hiccup7** [comment]
pyqt5-tools download is 150 MB, so I think informing the user about it is the best option.  See the following for where to get the latest version: https://github.com/altendky/pyqt5-tools/issues/1

**Comment by stonebig** [comment]
interested users can do "pip install pyqt5-tools", but WinPython being too close to its death limit of 2Gb, "pyqt5-tools" won't be included.
