### ISSUE TITLE
Contents of WinPython_PS_Prompt file

### ISSUE THREAD

**Issue by georgejean** [winpython/winpython#432]
Hi,

My WinPython version is 3.5.2.2Qt5.
The powershell launch icon is a good thing but I see one strange line in this file (discovered when I wanted to configure my profile):
```powershell
if (-not $env:WINPYDIR -eq "$dp0\..\python-3.4.4.amd64")...
```
shouldn't this line be replaced by this one (adding brackets):
```powershell
if (-not ($env:WINPYDIR -eq "$dp0\..\python-3.4.4.amd64"))
```
?
`-not $env:WINPYDIR -eq "$dp0\..\python-3.4.4.amd64"` is the same as `(-not $env:WINPYDIR) -eq "$dp0\..\python-3.4.4.amd64"` and a non-empty string is True when cast into a boolean.

**Comment by georgejean** [comment]
By the way, `$dp0\..\python-3.4.4.amd64` shouldn't be also replaced by `$dp0\..\python-3.5.2.amd64` taking account of my WinPython Version?

**Comment by stonebig** [comment]
the goal of these lines is to not pile-up twice directories in the path.

You're right they should match your WinPython version, there may be a bug somewhere

**Comment by stonebig** [comment]
it was solved 18 days ago. it's in latest release

https://github.com/winpython/winpython/pull/419

**Comment by georgejean** [comment]
Thanks for your answer but I see again in this file a line like
```powershell
if (-not $env:WINPYDIR -eq [System.IO.Path]::GetFullPath( $env:WINPYDIRBASE+"\python-3.5.2.amd64") )
```
If you want to test if two non empty strings `$a` and `$b` are not the same, you should use:
```powershell
if (-not($a -eq $b))
```
instead of
```powershell
if (-not $a -eq $b)
```
because the boolean expression `(-not $a -eq $b)` is the same as
```powershell
(-not $a) -eq $b
```
where the strings `$a` and `$b` are automatically converted in boolean, so this expression has always a value equal to `$false` because it is the same as
```powershell
$false -eq $true
```
for two non empty strings `$a` and `$b`.
Thus, for example,
```powershell
(-not "Q:\WinPython-64bit-3.5.2.3Qt5\python-3.4.4.amd64" -eq "Q:\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64")
```
has always a value equal to false (contrary to what it is expected) and every instructions following the line
```powershell
if (-not $env:WINPYDIR -eq [System.IO.Path]::GetFullPath( $env:WINPYDIRBASE+"\python-3.5.2.amd64") ) 
```
are never executed.

**Comment by stonebig** [comment]
shame on me.... fix on the way

**Comment by stonebig** [comment]
the bug comes from my lisp-phobia

**Comment by stonebig** [comment]
````
# avoid double_init (will only resize screen)
if (-not ($env:WINPYDIR -eq [System.IO.Path]::GetFullPath( $env:WINPYDIRBASE+"\python-3.6.0b3.amd64")) ) {
````
