### ISSUE TITLE
cmd_ps and WinPython_Interpreter_PS files

### ISSUE THREAD

**Issue by georgejean** [winpython/winpython#436]
A suggestion:
If we replace the content of the cmd_ps.bat and WinPython_Interpreter_PS.bat files (in the script folder) respectively by

```batch
@echo off
rem safe bet 
call "%~dp0env_for_icons.bat"
Powershell.exe -Command "& {Start-Process PowerShell.exe -ArgumentList '-ExecutionPolicy RemoteSigned -noexit -File ""%~dp0WinPython_PS_Prompt.ps1""'}"
exit
```

and

```batch
@echo off
rem no safe bet (for comparisons)
Powershell.exe -Command "& {Start-Process PowerShell.exe -ArgumentList '-ExecutionPolicy RemoteSigned -noexit -File ""%~dp0WinPython_PS_Prompt.ps1""'}"
exit
```

we start a beautiful powershell console with all its features.
It seems thus that the "Set-WindowSize" part of the WinPython_PS_Prompt file can be removed.

**Comment by stonebig** [comment]
ok for the beautiful powershell console.

you want to propose a patch today or I re-implement it myself ?

**Comment by georgejean** [comment]
Sorry, I'm a noob in Git and Github and I don't know how to do that (I don't want to make a mistake) so I let you re-implement.

**Comment by stonebig** [comment]
done
