### ISSUE TITLE
How to customize pip source ?

### ISSUE THREAD

**Issue by eromoe** [winpython/winpython#438]
I need set
```
[global]
trusted-host = mirrors.aliyun.com
index-url = http://mirrors.aliyun.com/pypi/simple
```
But I don't know where to put this

**Comment by stonebig** [comment]
see https://pip.pypa.io/en/stable/user_guide/#config-file

###
On Windows the configuration file is %APPDATA%\pip\pip.ini
###

**Comment by eromoe** [comment]
@stonebig No, not that. I have python 2.7 install on my windows 10, and I have set pip.ini on user home. But winpython can't use that pip.ini, that's why I ask here.

**Comment by stonebig** [comment]
hum try in "\settings" of winpython directory tree
