### ISSUE TITLE
Include new mayavi v.4.5.0 (with Python 3.x support) with dependencies? 

### ISSUE THREAD

**Issue by srk** [winpython/winpython#442]
Suggestion: Include new mayavi v.4.5.0 (with Python 3.x support) with dependencies in the standard full distributions. I realize that the extra dependencies are quite heavy (w/VTK, Traits etc.) but it's a well-used library with many scientific visualization applications.
Tried to do this but fell down a rabbithole of VS/Windows Kit dependencies, header files missing etc. Anyone else had success?

**Comment by stonebig** [comment]
mayavi is best supported in enthought distribution, if you truly need it now.

If you try experiment it in WinPython, maybe use the "PyQt4" version of mayavi provided by Christoph Gohlke, and a "PyQt4" WinPython version.

**Comment by srk** [comment]
OK, used WinPython 3.5.2.3 64-bit (QT4) distribution, downloaded wheels from Christophe Gohlke's site (first installing VTK, traits, traitsui and a few other ETS packages, just to be sure, then finally mayavi 4.5.0 itself). I dragged and dropped the wheels into the WinPython Control Panel. Downloaded and ran a test program from the mayavi website to make interactive dialogs. Screenshot of result is attached.

Not sure if the screenshot upload worked. In summary, the process you suggested was successful. There was a small error message to the console: "libpng warning: iCCP: known incorrect sRGB profile", but the interactive program seemed to work OK.

**Comment by stonebig** [comment]
mayavi+vtk is 30Mo. 

Why do you want it in WinPython rather than just using enthought ?

**Comment by srk** [comment]
I like the flexibility of WinPython, being able to install multiple independent versions and the portability. I proposed the change because I wasn't aware that I could successfully install the necessary wheels from Gohlke's site. As WinPython seems to be used by a lot of scientists/engineers, and because I had been waiting for a long time for Python 3 support to be added to Mayavi, I suggested the addition. I understand the issue about the size though. Perhaps a short note could be added to the wiki on how to download and install it on WinPython.

**Comment by stonebig** [comment]
you can add it, the wiki is opened.

**Comment by srk** [comment]
OK, I added a brief and crude draft to the wiki. Feel free to edit.

**Comment by stonebig** [comment]
Thanks for your contribution, @srk ! This wiki needs some activity, and I have not time for it

**Comment by stonebig** [comment]
ah a pyconfr video shows mayavi ... https://youtu.be/-fjV3a33FWI?t=352

**Comment by stonebig** [comment]
even in this video, they use python2.7 limited tool snakerunsnake...  found snakeviz as a workaround

**Comment by stonebig** [comment]
spyder just included a fix that impacted mayavi https://github.com/spyder-ide/spyder/issues/3759

I see it's only Qt4 compatible though: http://docs.enthought.com/mayavi/mayavi/building_applications.html#integrating-in-a-qt-application

**Comment by stonebig** [comment]
Mayavi being stuck on Qt4 for now, it won't be included in default WinPython
