### ISSUE TITLE
Icons in Spyder von WinPython 3.5.2.3QT5

### ISSUE THREAD

**Issue by thierryBottaro** [winpython/winpython#446]
In Spyder from WinPython 3.5.2.3QT5 are gone !
![image](https://cloud.githubusercontent.com/assets/15816165/20972749/31d1f076-bc96-11e6-90bf-f45f977407d0.png)

here is the same folder under the Spyder from Winpython 3.4.4.3
![image](https://cloud.githubusercontent.com/assets/15816165/20972804/60e4a4e4-bc96-11e6-9923-d66c3b191e11.png)

I have checked in "Preferences", and I have the same "QT windows style" (WindowsVista) and same "Icon Theme" (spyder 3). Changing those configuration does not changes my icon issue

I have a fresh install, under Windows 7 Entreprise

**Comment by stonebig** [comment]
I have difficulties to catch up. can you do a full size screen shot ?

**Comment by thierryBottaro** [comment]
Here you are : 
![image](https://cloud.githubusercontent.com/assets/15816165/21005585/a70090b0-bd35-11e6-9662-b25915499cf7.png)

**Comment by thierryBottaro** [comment]
on the same fresh install, I don't have autocompletion (with Tab) anymore in the Spyder Editor.
Autocompletion works as expected in Spyder iPython console.

Not sure if these 2 annoyances are linked or not.

**Comment by stonebig** [comment]
I reproduce your problem; but I don't see any open issue on this in Spyder project.... curious

**Comment by stonebig** [comment]
for the autocompletion not working in the editor... it worked once, after waiting like 2 minutes.

**Comment by thierryBottaro** [comment]
after 2 reboot, the autocompletion worked.
Icons are still not there. that's not as terrible, but if I understand your
answer, I should report it in the Spyder project.
I will.


2016-12-10 19:39 GMT+01:00 stonebig <notifications@github.com>:

**Comment by thierryBottaro** [comment]
So I opened a Spyder Issue, and the answer was really disappointing to me : "it's not a bug, it's a feature: Theme unification" ! 
https://github.com/spyder-ide/spyder/issues/3825#issuecomment-266251287
So not sure that the upgrade to Spyder 3.0.2+ will change anything to that issue.
