### ISSUE TITLE
Missing WinPython-32bit-3.5.2.3.exe built?

### ISSUE THREAD

**Issue by ventilator** [winpython/winpython#447]
Hi, 

I am missing a 32bit version of the current WinPython 3.5.2.3 without Qt. Why isn't there one?
Is it save to use WinPython-32bit-3.5.2.3Qt5.exe instead? Does the version with Qt have any drawbacks, e.g. limited tkinter support?

![image](https://cloud.githubusercontent.com/assets/4276067/21002741/9daf140e-bd27-11e6-88cc-42dd95399837.png)

**Comment by stonebig** [comment]
WinPython-64bit-3.5.2.3.exe has also Qt, but the legacy Qt4. 

there is no published WinPython-32bit-3.5.2.3.exe indeed, as your current maintainer doesn't want to build more than 6 "big" binaries per release, and would like to go down to 4.

**Comment by ventilator** [comment]
Thanks for clearing up that dropping the 32bit built was no mistake. Unfortunatly I am using a lot of legacy 32bit-Windows machines in production, so using the 64bit built is not an option. But I can understand dropping 32bit support, looking at the download statistics for 32bit.
