### ISSUE TITLE
WPPM does not fully uninstall PyQt5

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#449]
Some WinPython users need to replace PyQt5 with PyQt4.  In my case, because of this bug: https://github.com/matplotlib/matplotlib/issues/7688

Here is the procedure that worked for me with 64-bit WinPython 3.5.2.4Qt5b3:
1) Download from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4
2) Copy file to D:\toto\PyQt4‑4.11.4‑cp35‑none‑win_amd64.whl
3) Run "WinPython Command Prompt.exe" as administrator
4) In the cmd.exe window, type >wppm -u PyQt5
5) In the cmd.exe window, type >wppm -i D:\toto\PyQt4‑4.11.4‑cp35‑none‑win_amd64.whl
6) Delete the folder "%WINPYDIR%\Lib\site-packages\PyQt5"

Step 6) is necessary because wppm does not delete the folder with the uninstall of PyQt5, and many WinPython scripts (such as env.bat) look for the existence of the folder "%WINPYDIR%\Lib\site-packages\PyQt5" to determine if Qt5 is used.

Should wppm be changed so that step 6) is not necessary?

**Comment by stonebig** [comment]
Hum, the problem is that we had missing things in PyQt5 directory, because of PyQt5 wheel deficiencies.

Maybe shall we test an object below that directory... `__init__.py` seems the only common file
