### ISSUE TITLE
Installing the correct VS compiler MSC 1900 - wheel building fails

### ISSUE THREAD

**Issue by srk** [winpython/winpython#457]
Currently using Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32 under Windows 8.1 64-bit.

Any attempt to build software that involves building wheels fails, with 'cygwinccompile.py' not having found MSC 1900. How can I fix this? I've installed VS 2012 and VS2015, and still get the error. I think comprehensive advice should be listed in the FAQ, or at least in the wiki. I know Python 3.6 is close, but it would still be very useful to know how to solve this problem.

**Comment by stonebig** [comment]
It's my fault, I guess. a wonrg setting is in the default install.

to chang settings, launch the script "winpython-64bit-3.5.2.3\scripts\make_cython_use_vc.bat"

**Comment by srk** [comment]
did that, then:
c:\python\win64python3523\python-3.5.2.amd64\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by stonebig** [comment]
hum, this thread may give hints : http://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory

**Comment by srk** [comment]
Good tip, thanks.
Currently reinstalling the full Win 8.1 SDK, and will also manually set the INCLUDE environment variable. Doesn't seem to be a WinPython - related problem, so I will close this issue. Thanks again.
