### ISSUE TITLE
WinPython 2.7(.12 / .10) control panel failing to display installed plugins after installing package "quantities"

### ISSUE THREAD

**Issue by tgrandje** [winpython/winpython#461]
Hello

I had the same trouble with 2 different relases of winpython 2.7. After installing [package "quantities"](https://pypi.python.org/pypi/quantities), the control pannel do not display installed plugins anymore.

So far, I had found that it is caused by a 'quantities-0+unknown.dist-info' folder, created here :
\\WinPython-32bit-2.7.10.3\python-2.7.10\Lib\site-packages\quantities-0+unknown.dist-info

Deleting the folder seems to resolve the problem, though it don't know what it may alterate... 

_To be precise, I do not know what this plugin is meant for : I'm currently trying to install package PyLaTex (and failing so far) and it seem to be required... That's why I didn't check if 'quantities' was working right (though 'import quantities' seems to work fine)..._

Regards
tgrandje

Edit : it also seems to be ok to just rename the folder (adding a '_rename' at the end of the folder's name do the job... So it may not be linked to the astonishing "+" character in the name.)

**Comment by lmxtom** [comment]
we still need a full "winpython-2.7" base on 2.7.13,thks!

**Comment by stonebig** [comment]
What value would bring you a full winpython-2.7 over for example an Anaconda-2.7 ?
 
I can write about the negatives:
- my time,
- technical 2.7 debt to carry on 
- slowing Python3 migration

The only positive is that it can use Theano on windows , but so do WinPython-3.4.

**Comment by tgrandje** [comment]
For my part, I totally understand your reasons.
I currently started working on an application using python 2.7. When it's finished, I'll consider upgrading it to 3.X, but I'll stick to this version until then...
Thanks for your great job anyway !

**Comment by lmxtom** [comment]
thk,stonebig! for your message. I will use the Anaconda-2.7!
