### ISSUE TITLE
How to install packages in WinPython "Zero" versions

### ISSUE THREAD

**Issue by GlassGruber** [winpython/winpython#463]
Hey there,
as per #437, #405 and #397 the WP Control Panel is not properly working with Zero versions. 
So how can I install packages with WinPython Zero without the Control Panel? 
Thank you!

**Comment by selepo** [comment]
Have you tried running pip install "package" ?

**Comment by GlassGruber** [comment]
Gah I'm very sorry, this is a bad RTFM issue, I totally missed the dedicated [doc page in wiki](https://github.com/winpython/winpython/wiki/Installing-Additional-Packages). Yes using `pip` in the scripts folder is working properly!

I'm quite naive with Pyton, I got confused by this doc page on [WPPM](https://github.com/winpython/winpython/wiki/WPPM) where it's written:
> WinPython is a portable distribution of Python. In other words, even if it provides a working Python environment, WinPython does not install Python on your machine. As a consequence, it's not possible to install packages using standard Python installers (these installers will look for Python in Windows registry and won't find it).

so I thought that pip wouldn't be able to work out properly and didn't even tried.

May I ask some clarification on the purpose of the WPPM then? If pip is working am I confusing what a "standard Python installer" is ?

Thank you!

**Comment by stonebig** [comment]
hum, maybe I should revisit documentation. WinPython did become 100%  compatible with pip in recent years, but parts of the documentation have not been fully updated.

**Comment by stonebig** [comment]
Is it better now ? https://github.com/winpython/winpython/wiki/WPPM

(I'm not very good in **clear or english** documentation)

**Comment by selepo** [comment]
Hmm, pip absolutely works. Whether install with exe file works, depends (in my experience) on the exe installer. I have for example yet to be able to install nltk (at least without registrering winpython). 

I noticed at the bottom of the page it says that pip itself needs to be upgraded using a special script. Is this still true, I wasn't aware and haven't noticed any negative side effects after upgrading pip using "python -m pip install --upgrade pip"

**Comment by stonebig** [comment]
I should reword that:
- PIP can be upgrade the santadr way, but you loose WinPython directory "movability"
- the special procedure is to keep (or restore) that "movability"

**Comment by stonebig** [comment]
... now the page is a little bit to big, may afraid some. :-( 

Again, feel free to improve the style and wording.

**Comment by GlassGruber** [comment]
@stonebig the doc looks good to me! And it's not that long IMO, and now it looks pretty much clear what are the options to install new packages. Thank you!
