### ISSUE TITLE
WinPython 3.4.4.5Qt5 is not compatible with Win XP

### ISSUE THREAD

**Issue by KOLANICH** [winpython/winpython#464]
```InterlockedCompareExchange64``` is not found in ```kernel32.dll```. That function was introduced in Vista. Appears presumably somewhere in packages' binaries : it appears only when I run a script loading some modules in Python. To be more precise, [this one](https://github.com/KOLANICH/ahkab/blob/tunnel_junction/doc/examples/testsimtunnjun.py). It depends on ahkab. Ahkab depends on bunch of libraries including numpy.

**Comment by stonebig** [comment]
I confirm, recent Winpython since a few year are not compatible with WinXP. 
Microsoft stopped support of Windows XP  April 8, 2014.

==> Y7ou may try a Winpython version earlier than that:
- WinPython3.3.5.0,
- WinPython-2.7.6.4,
- or earlier versions.

**Comment by KOLANICH** [comment]
>I confirm, recent Winpython since a few year are not compatible with Windows XP.

In fact April's 3.4.4.<some number>QT5 was compatible and worked fine. It seems more like a compiler-related issue.

>Microsoft stopped support of Windows XP April 8, 2014.

Enterprises don't care. Especially in the cases when pc hardware is old itself, has old devices, old drivers for them and there is no reason to upgrade it.

**Comment by stonebig** [comment]
After a while, "Technical debt" becomes "Time bomb" .
