### ISSUE TITLE
No Qt apps in WinPython-64bit-3.5.2.3Qt5.exe

### ISSUE THREAD

**Issue by starcrescent** [winpython/winpython#475]
Well this is not a bug. However I could not find a forum to ask.
There are no Qt apps in WinPython-64bit-3.5.2.3Qt5.exe installation.
No  Qt Designer
No Qt Linguist
No Qt Assistant

**Comment by stonebig** [comment]
indeed, it's not in PyQt5.7 official wheels.

The icons are kept for user wanting to instal the PyQt4 wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4

and the remove PyQt5.

**Comment by starcrescent** [comment]
Actually there are neither icons nor exe files either.

**Comment by stonebig** [comment]
oups, yes !  I did put back the icons for coming release: WinPython-64bit-3.5.3.0Qt5rc3.exe

**Comment by drewbagel423** [comment]
Please forgive me because I'm new to this, but I see "QT Designer.exe" in my WinPython-64bit-3.5.3.0Qt5 installation folder. When I attempt to launch it, however, nothing happens. Is it just an empty .exe file? If so, is there a way for me to add QT Designer to my installation (while still being portable)?

**Comment by stonebig** [comment]
riverbanks, the PyQt5 provider, doesn't include anymore "Qt Designer", so the lack o "Qt Designer".

The "Qt Designer" icon works when PyQt4 is re-installed in place of PyQt5, what a few users do, so I kept the icon.

**Comment by drewbagel423** [comment]
Stonebug, thanks for responding. Isn't QT designer available as part of the "qttools5-dev-tools" package though?

**Comment by stonebig** [comment]
yes, you can do a "pip install Pyqt5-tools", see https://github.com/winpython/winpython/issues/502#issuecomment-381762877
