### ISSUE TITLE
WinPython Control Panel crashes after replacing PyQt5 with PyQt4

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#483]
Using 64-bit WinPython 3.5.3.0Qt5 on Win8.1, I did the following:
1. Download from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4
2. Copy file to D:\toto\PyQt4‑4.11.4‑cp35‑none‑win_amd64.whl
3. Run "WinPython Command Prompt.exe" as administrator
4. In the cmd.exe window, type >wppm -u PyQt5
5. In the cmd.exe window, type >wppm -i D:\toto\PyQt4‑4.11.4‑cp35‑none‑win_amd64.whl
6. Run WinPython Control Panel with elevated privileges

The result is that WinPython Control Panel process terminates.  I worked around the problem by deleting the folder "%WINPYDIR%\Lib\site-packages\PyQt5".

Perhaps the problem occurs because PyQt5 is in the path before PyQt4, and uninstalling PyQt5 leaves a DLL.  How about changing env.bat to use different paths for the PyQt5 and PyQt4 cases?

By the way, I am using PyQt4 because I continue to have this problem: https://github.com/matplotlib/matplotlib/issues/7688
I would have re-opened this issue: https://github.com/winpython/winpython/issues/449
But the WinPython project does not allow users to do this.

**Comment by stonebig** [comment]
It should work, and indeed it doesn't ... inquiring what I did wrong (again).

**Comment by stonebig** [comment]
a longer term solution would be to rely on QtPy, or have WPPM not relying on Qt packages.

**Comment by hiccup7** [comment]
The most important thing to me is that WinPython continues to support replacing PyQt5 with PyQt4.  The WinPython 3.5.3.0Qt5 issue I found isn't causing me a real problem because I have a work-around.  No hard feelings...

I did some more testing today with Spyder+matplotlib+PyQt5, and I posted the results at matplotlib/matplotlib#7688

**Comment by stonebig** [comment]
try "set QT_API=pyqt" or "set QT_API=pyqt4" in your env.bat.

**Comment by stonebig** [comment]
WinPython shall support PyQt4, or diversity, as PySide2 should become an option, sometime next year.

**Comment by hiccup7** [comment]
I customize the batch file for starting Spyder in each WinPython installation folder.  Where WinPython has PyQt4 installed, I have "set QT_API=pyqt".  Where WinPython has PyQt5 installed, I have "set QT_API=pyqt5".

**Comment by stonebig** [comment]
The default test I do is the "generic" one everybody does... So I'll tweak it as written before, but the true solution is to stop patching PyQt5.
