### ISSUE TITLE
WinPythonZero: Can't register distribution.

### ISSUE THREAD

**Issue by warownia1** [winpython/winpython#484]
Trying to register distribution from WinPython Control Panel causes it to close unexpectedly.
Error occurs on Windows 10.
Steps taken:
 - install WinPythonZero3.5.3.0_amd64
 - launch WinPython Command Prompt
 - enter `pip install pyqt5 pypiwin32`
 - open WinPython Control Panel >Advanced > Register Distribution
 - After clicking `Yes` in a popup window Control Panel exits.

`.py` files get associated with python and 'Edit with IDLE' entry is added, but shortcuts are not created in a Start Menu.
Using `register_python.bat` from `D:\WinPython-64bit-3.5.3.0Zero\scripts\` works properly.
Unregistering distribution works from the Control Panel.

Registering distribution using `WinPython-64bit-3.4.4.5Qt5` version works with no problem.

**Comment by stonebig** [comment]
I read the code and I don't know why it doesn't work. help Welcome.

**Comment by hiccup7** [comment]
WinPython Control Panel creates/modifies Windows registry keys to "register a distribution".  In https://github.com/winpython/winpython/issues/351, I give example scripts for regedit that do the equivalent.  Use regedit to view the registry keys and see what WinPython Control Panel did wrong, and report the results back here.  You can correct the registry keys manually in regedit or modify my example script and import the script with regedit.

**Comment by stonebig** [comment]
I shall create a script so it can be done without Qt

**Comment by stonebig** [comment]
you can now with "wppm --register" and "wppm- -unregister", but it needs pywin32 packages, wihch is not in dot version..
... so  only partial ok

**Comment by stonebig** [comment]
done
