### ISSUE TITLE
Possible Spyder/Winpython bug.

### ISSUE THREAD

**Issue by Patrick-Cole** [winpython/winpython#486]
Hi,

I am not sure if this is relevant here, or on the Spyder forum, so I decided to start here. 

I have a bug which I have noted in the latest release. I am using WinPython-64bit-3.5.3.0Qt5. The Spyder version is therefore 3.1.2

When I run a Qt program, and it has a bug in a function accessed by the qt signal/slot architecture, no errors are passed to the python console

I am using a standard python console (not ipython). It runs with the setting 'Execute in a new dedicated Python console'  The source code is below. Notice the test function has an obvious typo which should generate an error. 

````
import sys
from PyQt5.QtWidgets import QMainWindow, QPushButton, QApplication


class ApplicationWindow(QMainWindow):
    """ Application Window """
    def __init__(self):
        super().__init__()

        button = QPushButton('Press Me', self)
        button.clicked.connect(self.test)

    def test(self):
        aaa


def main():
    """ main qt gui """

    app = QApplication(sys.argv)
    wid = ApplicationWindow()
    wid.show()

    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
````

**Comment by stonebig** [comment]
Hi @Patrick-Cole 

It doesn't look Spyder specific, as there is the same non-crash under "qtconsole.bat".

I don't think it's WinPython problem, but I may be wrong.

It could just be Qt5 or PyQt5 bugs.

==> Maybe try with Anaconda ?

**Comment by stonebig** [comment]
when the origin is unknow, mayb asking on stackoverflow is a simpler option ?

**Comment by Patrick-Cole** [comment]
Okay, thanks for the advice. I will see what I can find out. Thanks for all your hard work on Winpython! It really appreciated.

**Comment by Patrick-Cole** [comment]
Okay, just an update. I tested with the latest Anaconda (3.6 Python comes with it, as well at Qt5 and Spyder 3.1.2) and it seems to work fine. I will continue to experiment.

**Comment by stonebig** [comment]
It blows up, as it should,  on current spyder-3.1 trunk. maybe a late patch.

**Comment by Patrick-Cole** [comment]
Hi,

I found other references to this:

http://stackoverflow.com/questions/33736819/pyqt-no-error-msg-traceback-on-exit
https://github.com/jupyter/qtconsole/issues/156

It seems many IDE's are affected by this. A workaround is proposed by Winand at:
https://gist.github.com/Winand/e98e3f2f073826b7c08b58fb6d338b51

where the following code is added:

from PyQt5 import QtCore
import traceback

if QtCore.QT_VERSION >= 0x50501:
    def excepthook(type_, value, traceback_):
        traceback.print_exception(type_, value, traceback_)
        QtCore.qFatal('')
    sys.excepthook = excepthook

When added to my code, everything is fine. So there seems to be some issue between the way Qt reports bugs and the sys.excepthook routine.  I am guessing that this is something that the spyder guys can code a workaround easily for now. I will be patient and use this workaround until it is fixed. 

Thanks for looking into this for me as well.
