### ISSUE TITLE
Add gmpy2 package?

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#499]
WinPython already includes sympy and its required dependency mpmath.  mpmath uses gmpy/gmpy2 for greater speed if it is installed: http://www.lfd.uci.edu/~gohlke/pythonlibs/#gmpy
My testing with mp.prec=114 (equivalent to float128) shows gmpy2 speeds up heavy functions by a factor of 2!  Therefore, I always install gmpy2 in WinPython.  The wheel is about 0.5MB.  It would save me some time if future WinPython builds included gmpy2.

**Comment by stonebig** [comment]
Its popularity on github is tiny at the moment. Wait and See what happen when SageMath will rely on Jupyter Notebook.

**Comment by denfromufa** [comment]
I agree on gmpy2 and I use it with sympy for high-precision root solving on polynomial equations.

Here is one example where gmpy2 beats CPython even on regular calculations with predictable performance:

http://stackoverflow.com/a/36638366/2230844

**Comment by stonebig** [comment]
@denfromufa the thread is old. Is the performance remark still valid with Victor Stinner working day and night on Python-3.6  / 3.8 performance ?

**Comment by denfromufa** [comment]
Fastcall optimizations are not order of magnitude speedups and not intended
for numerical code from my understanding. Gmpy2 can speed up significantly
due to optimized C code.

But I see that gmpy2 does not yet officially support Python 3.6.

**Comment by hiccup7** [comment]
mpmath is only using gmpy2 integers.  See http://www.mpmath.org/doc/current/setup.html#using-gmpy-optional
cgohlke's gmpy2 wheels include Python 3.6.  Do gmpy2 integers fail for Python 3.6?

There have been a lot of commits since the last release, including Python 3 fixes.  Since mpmath is pure Python, a user can download a zip file of the current GitHub master branch and update his/her WinPython installation using the WinPython Control Panel.

**Comment by denfromufa** [comment]
According to this blog post mpmath is using gmpy not just for integers but also decimals.

You can run gmpy2 and mpmath tests under Python 3.5 and 3.6 to see any differences.

I did not notice @cgohlke wheels for Py36. Conda does not yet provide 3.6 binaries for gmpy2.

Note that the license is GPL.

**Comment by denfromufa** [comment]
http://fredrik-j.blogspot.com/2008/06/gmpy-makes-mpmath-more-speedy.html?m=1

**Comment by stonebig** [comment]
I will include it in next beta.

**Comment by hiccup7** [comment]
Since the Anaconda repository does not include gmpy2 for Python 3.6, WinPython serves an important role in getting gmpy2 out to the scientific Python community and getting more testing.  If there are any problems with gmpy2 for Python 3.6, they may not be in the subset of functionality used by mpmath.

**Comment by hiccup7** [comment]
Tested in WinPython-64bit-3.5.3.1Qt5b2 and working well.  Thanks!

**Comment by stonebig** [comment]
super! thanks for the feedback.
