### ISSUE TITLE
Normalize path not working on 3.6.0.0

### ISSUE THREAD

**Issue by crazy-max** [winpython/winpython#500]
Hi,

I've got a problem with your `python.bat` script.
When the script is launched the `WINPYDIRBASE` is wrong.
It seems to come from the `:NORMALIZEPATH` call.
I've solved the problem here crazy-max/neard#221 by using `pushd` `popd` but is there a better alternative ?

Thanks!

**Comment by stonebig** [comment]
I see you mea:
````
@echo off
set WINPYDIRBASE=%~dp0..
rem get a normalize path
CALL :NORMALIZEPATH "%WINPYDIRBASE%"
set WINPYDIRBASE=%RETVAL%
set RETVAL=
````
By

````
@echo off
set WINPYDIRBASETMP=%~dp0..
pushd %WINPYDIRBASETMP%
set WINPYDIRBASE=%CD%
popd
`````

I 'm surprised you have a problem...  what can be  special with your PC ? (compared to mine)

**Comment by stonebig** [comment]
I think I remember  I prefered the not-push_pop method, in case the directory of winpython would not be a letter (so not work with CD), but nothing may work in that case.

**Comment by stonebig** [comment]
will do that, as my current code is looking pre-fortran aera

**Comment by crazy-max** [comment]
Hi @stonebig !

All devs using [Neard](http://neard.io) have this problem. I have reproduced this issue on Windows 7 Pro SP1 and Windows 10 Pro. I have not checked Windows XP SP3 yet.

I think the problem comes from the parent folder `python3.6.0.0` in the path.
`E:\Portable\Neard\tools\python\python3.6.0.0` is generated as `E:\Portable\Neard\tools\python\python3.6.0.0python3.6.0` with your normalize method.
Maybe the last `.0` is the issue.

**Comment by stonebig** [comment]
hum, so maybe a DOS function has been renamed by Neard, and doesn't work the same

**Comment by crazy-max** [comment]
It's linked to [TCC/LE](https://jpsoft.com/tccle-cmd-replacement.html) which is embedded in the Neard console.
Thanks a lot for your merge 👍
