### ISSUE TITLE
Qt Designer.exe in WinPython-64bit-3.6.0.1Qt5

### ISSUE THREAD

**Issue by leoli1119** [winpython/winpython#502]
Can not open Qt Designer.exe in WinPython-64bit-3.6.0.1Qt5
What should I do if I want to open Qt Designer.exe?

**Comment by stonebig** [comment]
The first option is to downgrade to PyQt4.

The second option is to experiment with https://github.com/altendky/pyqt5-tools

Waiting for a Third option

**Comment by selepo** [comment]
Can confirm the issue is the same on 32bit-version. To make things harder i run 32-bit winpython on a 64-bit system, so it won't allow me to install the right version of pyqt5-tools...

**Comment by yi1wang** [comment]
Has the same problem with this version. Be honest, I have tried WinPython-64bit-3.6.x.xQt5, WinPython-64bit-3.5.x.xQt5, their Qt Designer.exe doesn't work at all (on windows 7 and windows 10 64bit version). When you double click it, nothing popup. Luckily, Qt Designer.exe in WinPython-64bit-3.4.x.xQt5 works. I stick to this version now.

**Comment by stonebig** [comment]
There is no QtDesigner delivered with PyQt5.8 per the original author. The QtDesigner icon is kept for the few people who downgrade to PyQt4

**Comment by selepo** [comment]
Ok, not sure if this helps anyone else, but this seems to work for me. 

If one download the wheel (32bit or 64bit) and open https://pypi.python.org/pypi/pyqt5-tools in 7zip, there is a folder pyqt-tools/designer which can be extracted, and seems to have all files necessary to run   qt designer.

**Comment by maltehi** [comment]
Following that approach, I installed pyqt5-tools through pip and changed the path for the pyqt5 call in scripts/qtdesigner.bat to `"%WINPYDIR%\Lib\site-packages\pyqt5-tools\designer.exe" %*`, so it is pointing to the pyqt5-tools directory instead of the PyQt5 one.

Seems to work fine!

**Comment by stonebig** [comment]
I will include the workaround of @maltehi , so the icon will work for people downloading pyqt5-tools

**Comment by RunCite** [comment]
In the version WinPython-64bit-3.3.5.9 downloadable on page:
http://www.softpedia.com/get/Programming/Coding-languages-Compilers/WinPython.shtml#download,
I used the QT4 Designer and it works (Python 3.3.5) ....

**Comment by stonebig** [comment]
indeed, PyQt4 was a complete package. Since this time, for whatever reason, the PyQt maintainer stopped shipping it .

I don't expect this to change until PySide2, a revival of PySide for Qt5, sponsored by QT team, takes-off.

**Comment by zancos** [comment]
Install from "WinPython Control Panel" the following package (pip). On this way you will have a fully Qt5 designer working.

https://pypi.python.org/pypi/pyqt5-tools

**Comment by Junyinghouse** [comment]
can anyone share the link for download the Qt Designer

**Comment by j7j11** [comment]
> "pip install Pyqt5-tools".

@fernijon Thank you for your help, it worked perfectly.

**Comment by stonebig** [comment]
as a complementary note: new Spyder version are going to drop PyQt4 compatibility.

**Comment by geissbuehler** [comment]
In pyqt5-tools newer than 5.9.0.* the install path has changed from `site-packages\pyqt5-tools` to `site-packages\pyqt5_tools`. The workaround should now look like this: `pip install pyqt5-tools==5.9.0.* pyqt5`
I already prepared a pull request (https://github.com/winpython/winpython/pull/679) to handle the new path in WinPython.
