### ISSUE TITLE
spyder.exe does not works after I run the "pip install --upgrade spyder"

### ISSUE THREAD

**Issue by asmwarrior** [winpython/winpython#508]
Hi, I'm using WinPython-64bit-3.5.3.0Qt5 which comes with Spyder 3.1.2. Now in the console, I just run the command `pip install --upgrade spyder`, and I see that it is successfully upgrade to 3.1.3 version of Spyder.

Now, when I double click the spyder.exe in the root install folder, nothing happens.

I have to switch the current directory to  `\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\Scripts` and type the `spyder3.exe`, so that the upgraded spyder started.

Any ideas? 
Thanks.

**Comment by stonebig** [comment]
Indeed, the spyder executable change from "spyder.exe" to "spyder3.exe"

So, in `\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\Scripts\spyder.bat`:
-  replace `spyder.exe` 
- per `spyder3.exe`

**Comment by boocko** [comment]
OP clicked exe directly, so this cannot be linked to bat file. I have similar problems. Still googling. Might be something with Qt.

**Comment by stonebig** [comment]
if you wat the click on the spyder3.exe to work, you have first to run `scripts\make_winpython_fix.bat`

**Comment by asmwarrior** [comment]
> if you want a direct click on the spyder3.exe to work, you have first to run scripts\make_winpython_fix.bat
I just did this, but this does not work, double click on the spyder.exe in the root folder does not launch the spyder.

There is a typo in your comment, the spyder.bat and spyder_reset.bat are in the folder:
`\WinPython-64bit-3.5.3.0Qt5\scripts\` not the one in `\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\Scripts`.
But change those two bat files does not solve the issue, I mean I have change the two bat files, and then run the `scripts\make_winpython_fix.bat`, and still no luck to launch the spyder by the spyder.exe in the root folder.

**Comment by nashv** [comment]
Agreed. After Spyder upgraded to 3.1.3, the Spyder.exe in the root folder does not launch Spyder Even after  changing the bat files mentioned here to "spyder3.exe"

**Comment by Haolle** [comment]
just installed and upgraded spyder by:
  pip install spyder
  pip install --upgrade spyder

I tried to launch spyder from: 
  C:\Program Files\Python35\Scripts\spyder3.exe

but, nothing happened.
any ideas?

**Comment by stonebig** [comment]
probably you use an old version of winpython. and recently "spyder.exe"  launcher changed to "spyder3.exe" (https://github.com/hiccup7)

so:
- edit winpython-...\scripts\spyder.bat
- change in it "\spyder.exe" per "\spyder**3**.exe"
- save and retry the Spyder icon.

**Comment by Haolle** [comment]
I newly installed python3.5.2, and spyder3.1.4 by pip. I can find spyder3.exe, but cannot find spyder.bat.

**Comment by stonebig** [comment]
spyder.exe is in "winpython-64bit-..\python-3.5.3.amd64\Scripts"

spyder.bat is in "spyder.exe is in "winpython-64bit-..\Scripts"

**Comment by mannharleen** [comment]
Same issue. no resolution?

**Comment by stonebig** [comment]
@mannharleen, at this point I don't know what same issue you have. 

Generic solution are:
- you download a full new version if simple "pip install --upgrade spyder" didn't work. 
- you switch to Anaconda distro (for example) that is probably more "upgrade-in-place" minded.

**Comment by dalito** [comment]
I believe the issue occurs if no or a wrong PyQT is installed. First I also hat this issue but all went fine when I also updated PyQt:
```
pip3 install -U PyQt5
pip3 install -U spyder
```
Spyder does not specify PyQt as dependency in setup.py so it is not automatically installed/updated.

**Comment by pietvanham** [comment]
>dalito: I believe the issue occurs if no or a wrong PyQT is installed. First I also had this issue but all went fine when I also updated PyQt:pip3 install -U PyQt5 pip3 install -U spyder Spyder does not specify PyQt as dependency in setup.py so it is not automatically installed/updated.

This worked as a charm for me

**Comment by safrulsetiawan** [comment]
@dalito Thank you so much for posting here. It really works.
