### ISSUE TITLE
Spyder doesnt start

### ISSUE THREAD

**Issue by aalcaldegrau** [winpython/winpython#509]
I tried to install WinPython-64bit-2.7.13.0Zero but Install was aborted because I tried to create a new folder, so I tried to install again, but didnt pay attention and installed the WinPython-64bit-3.5.3.0Qt5
After noticing the Version wasnt the one I wanted, I tried to install again the  WinPython-64bit-2.7.13.0Zero, and then tried to run Spyder.exe and didnt work, the same with SpyderReset. So I deleted both versions, tried to install older versions, 32bit version, and Spyder still didnt work in that versions. Reinstall WinPython-64bit-3.5.3.0Qt5 and Spyder works, but only in that version. 
AlsoWinPython Control Panel doesnt work, or Qtdesigner. Only IDLEX (Python GUI).
Then I googled and saw some options to fix the problem, but none worked. I see no spyder.ini file, or even .spyder2 folder. I dont find any path enviroment variable that seems problematic neither
I even cant see anything in console by command spyder --show-console
I tried some commands like easy_install pydicom
Any help? Any ideas?
I have Windows 7 Professional

**Comment by stonebig** [comment]
WinPython-64bit-2.7.13.0Zero doesn't include PyQt4, and PyQt4 is not on pypi. 

See here for instructions to add PyQt4: https://github.com/winpython/winpython/issues/397#issuecomment-247381629

then launch WinPython command line and type "pip install Spyder", and it should work

**Comment by DominiqueMakowski** [comment]
To avoid further confusion (I had the same problem), maybe it would be possible to remove the spyder.exe icon in the next zero distributions?

**Comment by stonebig** [comment]
The Zero distribution is a small thing that may grow as big as the full version : icons are there for this possibility, until I can replace the "nullsoft installer"  to create these icons.

An alternative would be to propose to install "spyder" when you click on it and it's not there, but it can be done "easily"  only for Python-3.5/3.6.

... I mays stop entirely Python-2.7/3.4 Zero versions to be able to move one.

**Comment by markkco** [comment]
Hello. I have had trouble setting WinPython 2.7.13 (64bit) with Spyder (on Win 7Prox64 SP1). Spyder would not start. Problem for me was having PyQt4 path in environment (%WINPYDIR%\Lib\site-packages\PyQt4). After I removed mentioned path, Spyder starts normally. 

What I did was removing from set PATH=: 
"%WINPYDIR%\Lib\site-packages\PyQt5;%WINPYDIR%\Lib\site-packages\PyQt4;" 
in WinPython\scripts\env.bat

Notice that if you remove path for PyQt you will not be able to start Qt Designer or Qt Linguist from WinPython folder. You can start those from Spyder Tools -> External Tools.
Or you could maybe modify qtdesigner.bat and qtlinguist.bat (in same folder as env.bat) to include removed PyQt path from env.bat (did not try that).

PS:
Running Spyder from its source code ("python bootstrap.py" in downloaded root Spyder source dir) does not have this problem. 
WinPython 3.6 (64bit) does not have this problem.

**Comment by stonebig** [comment]
if you want latest and greatest Spyder, you may consider shifting to python-3.6 . latest jupyter and spyder are loosing features or compatibility with python-2.7 and Qt4.
