### ISSUE TITLE
How can I verify if numpy+mkl works well

### ISSUE THREAD

**Issue by xwang71785** [winpython/winpython#512]
In the latest release of WinPython 3.4/3.5/3.6, the Numpy package is marked that mkl is added.
But when I test the Numpy with below code
>>> import numpy
>>> id(numpy.dot) == id(numpy.core.multiarray.dot)
it returns True
What should I do to make mkl work?

**Comment by stonebig** [comment]
did you try this ? http://stackoverflow.com/questions/22645423/make-sure-numpy-is-using-mkl-library-on-mac-pro

**Comment by xwang71785** [comment]
Thank you
