### ISSUE TITLE
Windows timestamp not updated on .py files saved in editor

### ISSUE THREAD

**Issue by nerdfever** [winpython/winpython#519]
This is kind of strange. Files edited & saved with the Spyder editor don't get updated timestamps in the Windows file system.

I'm on WinPython 3.0.0dev and Windows 10 Pro x64.

**Comment by stonebig** [comment]
Can you re-check per "right-click ==> Properties" on your source file  ? 

Indeed:
- my Windows 10 tends not to reflect immediately in the "file explorer" when a change has been made,
- sometimes, the default date displayed by the "file explorer" is the creation date, not the updated date of the file.

**Comment by nerdfever** [comment]
You're right. The modification date is correct, it's that Windows explorer is showing the creation date, not the modification date.

Clearly a Windows bug (must be a recent one), not a Spyder/WinPython bug. Sorry for the noise.

![ss](https://cloud.githubusercontent.com/assets/9833299/24975522/fd28de8c-1f93-11e7-9856-425881c31493.png)
