### ISSUE TITLE
Troubles with 3.6.1: numpy is not MKL and pyzmq is broken

### ISSUE THREAD

**Issue by KOLANICH** [winpython/winpython#521]
1 Shipped version of scipy requires NUMPY_MKL, but it is not present. It is impossible to replace the shipped version of scipy with the one from pypa for 32-bit OS's because there is no 32 bit wheel in pypa. Of course you are free to say "we are not going to fix it, we drop 32bit architectures (as everyone else did) instead" ...
2 The shipped version of pyzmq is broken. Ship the one from pypa, that one works. The problem is long lasting, the solution was found on stackoverflow, if I remember right (now I cannot find it again).

The same problems are experienced on 2 PCs:
1 Win 7, no Visual Studio, Python 3.6.1
2 Win XP, no Visual Studio, Python 3.4

**Comment by stonebig** [comment]
hi @KOLANICH 

Your two issues are unexpected. Can you provide one tiny program example for each of them, so I can  check  ?

**Comment by KOLANICH** [comment]
1
```python
import scipy
```

2 try to launch jupyter notebook

**Comment by stonebig** [comment]
hum,  

It works in "full" winpython:
````
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import scipy
>>> 
````
Would  it be possible you are using WinPython-32bit-3.6.1.0Zero ? it does not contain scipy, nor jupyter.
it contains only https://github.com/winpython/winpython/blob/master/changelogs/WinPythonZero-3.6.1.0.md

**Comment by stonebig** [comment]
Concerning Windows 32bit, support from new "numeric" packages seems  to go down since end of 2016. It may die by 2020 (a much slower death than expected, as first amd64 was in 2003, 13 years ago)

**Comment by KOLANICH** [comment]
>It works in "full" winpython:
On the PC I work on it doesn't. I don't know why. This was experienced on the fresh installation of the version from the latest release on GitHub by that date.

>Would it be possible you are using WinPython-32bit-3.6.1.0Zero ? it does not contain scipy, nor jupyter.

I use the full one with Jupyter and Qt.

**Comment by stonebig** [comment]
suggestion, try by order of workarounds :
- in "winpython-32bit-3.6.1.1\python-3.6.1.amd64", rename "python_onHold._pth" as "python._pth"
- try with a winpython 3.5,
- try with a winpython 3.4  version, (first, if you are not on windows 10)

**Comment by KOLANICH** [comment]
>try with anaconda

In fact it is the quickest and the most effortless solution. I have done exactly this. Spent an hour installing that, but that worth: everything worked out of the box. Unfortunately on another PC (the one with XP, python 3.4, no Visual Studio) I cannot use Anaconda, the troubles are the same. IMHO there is something wrong with the releases.

**Comment by stonebig** [comment]
On windows xp, try the last WinPython that was just release before XP support ended from Microsoft. AFter that moment, a lot of binary packages started to stop working

**Comment by Jai-GAY** [comment]
i think i could have face the same problem too after i install tensorflow which update the numpy due to requirement. if i remember correctly, it was fine before tensorflow installation. still trying to figure it out how to support both of my learning.

Traceback (most recent call last):
  File "[Part2.py](https://github.com/machine-learning-projects/machine-learning-recipes)", line 21, in <module>
    from sklearn.datasets import load_iris
  File "E:\WinPython\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "E:\WinPython\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\sklearn\base.py", line 10, in <module>
    from scipy import sparse
  File "E:\WinPython\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy._distributor_init import NUMPY_MKL  # requires numpy+mkl
ImportError: cannot import name 'NUMPY_MKL'

**Comment by Jai-GAY** [comment]
hopefully the [next release](https://github.com/winpython/winpython/issues/516) will solve this issue.
