### ISSUE TITLE
vitables

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#534]
hi all, 

any help to finalize vitables come-back is welcomed. see https://github.com/uvemas/ViTables/issues/63

**Comment by stonebig** [comment]
maybe it's a too late attempt, yet I didn't see any alternative and current try to make it work seems not far away from working

**Comment by stonebig** [comment]
ok, vitables works again thanks to @ankostis effort, in Python3/PyQt5 for now.

**Comment by ankostis** [comment]
@uvemas maybe you should bake a pypi release it of it?

**Comment by uvemas** [comment]
ViTables 3 is out. Source packages, wheels and conda packages are available (visit the Downloads section of vitables.org). It is not available on PyPI due to the problem mentioned in uvemas/ViTables/#67 . Sorry for the inconvenience.
