### ISSUE TITLE
SuperSmoother

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#535]
SuperSmoother is a small, pure-Python package that provides very sophisticated data smoothing with a simple API.  I have been using it with WinPython 3.5.x, and it works well.
https://pypi.python.org/pypi/supersmoother

https://github.com/jakevdp/supersmoother has examples in an online Jupyter notebook viewer, and the PDF reference has the academic paper explaining the algorithm.

Please consider adding it to WinPython.

**Comment by hiccup7** [comment]
Tested in WinPython-64bit-3.5.3.2Qt5b2.  SuperSmoother works fine.  Thanks!

**Comment by stonebig** [comment]
Jakevdp is a brilliant mind.
