### ISSUE TITLE
Import previous issues/tickets from Sourceforge

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#55]
I suggest importing at least the open tickets from [sf.net](https://sourceforge.net/p/winpython/tickets/).

**Comment by sebix** [comment]
I understand your point and also had that idea, but most of the tickets there are no longer valid, not replicable or the creator is not reachable. It would make more sense if all those are closed, except for the newer ones and feature requests which can be ported to this repo, with the advice to reopen here if the problem still exists and the reporter is still active.

I don't have the rights there to do that.

**Comment by stonebig** [comment]
Hi @jondo ,

Can you have a look, and tell us which tickets from the old sf.net are important and not yet re-opened on github ?

**Comment by jondo** [comment]
Well, I thought of [#116 (Enable compression "tiff_lzw" in Pillow)](http://sourceforge.net/p/winpython/tickets/116/), but I now remember that the remaining problem there was an [upstream issue](https://github.com/python-pillow/Pillow/issues/660#issuecomment-44179846).
