### ISSUE TITLE
WinPython-64bit-3.6.2.0Qt5rc Assertion Failed Error

### ISSUE THREAD

**Issue by ceaza** [winpython/winpython#559]
![error](https://user-images.githubusercontent.com/9589657/29417720-7c6b0604-836a-11e7-82e4-b6d9b37b8a4c.png)

**Comment by stonebig** [comment]
it's because of a slow start. it's solved in next version of winpty.https://github.com/spyder-ide/spyder-terminal/issues/101

But it was containing a bigger problem, so I didn't upgrade https://github.com/spyder-ide/pywinpty/issues/52

.
==> it should be ok if you start a second time. let me know

otherwise, wait a little for version winpyt-0.2.0 https://github.com/spyder-ide/pywinpty/issues/52

**Comment by ceaza** [comment]
Thanks! Tried starting a few times. WinPython is the best!

**Comment by stonebig** [comment]
If it's a permanent issue I may do an rc2

**Comment by ceaza** [comment]
It's quite new: i7-6700 3.4gh , 20 gig ram and with solid state drive.

**Comment by ceaza** [comment]
Same error on latest WinPython-64bit-3.6.2.0Qt5 after multiple starts.

**Comment by stonebig** [comment]
Well, I didn't find any improvement on my super-slow PC with further patch from Spyder, but your PC is super-fast, so I can't really check  your situation. So my best suggestions are that:
- backward solution:
  - you uninstall spyder-terminal : 
  - click on  "WinPython Command Prompt.exe"
    - type "pip uninstall  spyder-terminal".
    - download and install "pypiwin32" "pip install --upgrade pywinpty spyder-terminal" when pywinpty will be at version 0.3 
- or forward solution:
  - download and install cgohlke wheel "pypiwin32‑221+dummy‑py2.py3‑none‑any.whl" from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32  (use " WinPython Control Panel.exe" to pick and install the downloaded wheel)
  - then   "pip install --upgrade pywinpty spyder-terminal spyder"

**Comment by andfoy** [comment]
@stonebig pywinpty 0.2 and spyder-terminal 0.2.1 are coming tomorrow. I hope both releases fix the afromentioned problem.

**Comment by ceaza** [comment]
Did the forward solution. Seems sorted.

pywin32==221
pywinpty==0.1.4
spyder-terminal==0.2.0
spyder==3.2.1

**Comment by stonebig** [comment]
otherwise, since yesterday, pywinpty-0.2.0 is out, so the dependency to pypiwin32 has gone away.

  https://github.com/spyder-ide/pywinpty/releases/tag/v0.2.0

**Comment by andfoy** [comment]
Both package releases are now available on PyPi

**Comment by stonebig** [comment]
and python-prompt author has discoverd winpty, through TitanSnow own wrapper https://github.com/PSoWin/yawinpty/issues/1

**Comment by ceaza** [comment]
Thanks, that also works.

**Comment by hwolf46** [comment]
Setting back to version 3.2.3 resolved the problem with adressing the kernel, both 3.5 and 3.6 had this problem on my laptop (W10 edu edition 64bit)

**Comment by grickm** [comment]
I encountered this problem. Uninstalling spyder-terminal fixed it. I then reinstalled spyder-terminal, and the assert error stopped appearing on startup.
