### ISSUE TITLE
WinPython-64bit-3.6.2.0Qt5: auto completion in editor broken: users must "pip uninstall enum34" to restore the functionality

### ISSUE THREAD

**Issue by captaindet** [winpython/winpython#563]
the title says it all, it is not working for me. does work in spyder ipython console

**Comment by captaindet** [comment]
to be more specific, in spyder editor
- completion of identifiers
- all of intellisense / member access / signature display
is broken. back to WinPython-64bit-3.6.1.0Qt5 for now.

**Comment by stonebig** [comment]
Could you post  a screenshot of both examples working in  "WinPython-64bit-3.6.1.0Qt5" ?

**Comment by captaindet** [comment]
guess my explanation sucked ;)

see attached screenshots. the first two open up after with 'tab' or 'ctr-space', the third one opens automatically. again, these things used to work, now they don't.


![intellisense1](https://user-images.githubusercontent.com/18389153/29735009-cd288054-8a49-11e7-95e8-53c566532e7c.png)
![intellisense2](https://user-images.githubusercontent.com/18389153/29735016-e04c0318-8a49-11e7-9736-fcb95852343c.png)
![intellisense3](https://user-images.githubusercontent.com/18389153/29735022-e5375db4-8a49-11e7-9f35-2ba509fab1ca.png)

**Comment by stonebig** [comment]
thanks ! Now checking. Can you specify your PC configuration: Operating system, cpu, ram, type of disk  (spinning or ssd) ?

**Comment by stonebig** [comment]
Hum, I can't get solved this mystery by a simple upgrade of these packages. 

Yet, I detect that on a slow PC, the spyder-notebook extension is what slows down a lot  the start-up.

A possibility is that the analysis of all packages per jedi takes too much time.

**Comment by captaindet** [comment]
> thanks ! Now checking. Can you specify your PC configuration: Operating system, 
> cpu, ram, type of disk (spinning or ssd) ?

i can assure you performance is not an issue. i have this problem on all of my 3 machines, one is very fast/modern. memory is huge (32GB on one, 16GB on the other two), and i have the python tree either on SSD or on a ramdisk. my OS is W7. i only use winpython in portable 'mode' though, no system integration.

> on WinPython-64bit-3.5.4.0Qt5 at 2nd launch,

as i mentioned:  it also works perfectly well with the previous release
WinPython-64bit-3.6.1.0Qt5

also, autocompletion works fine in the ipython console, it "only" fails in the spyder editor.

> not on WinPython-64bit-3.6.2.0Qt5.

ah, so you do observe the issue as well?  

> There should be an issue open somewhere (on Jedi., Spyder, rope ...), can you find something ?

i have found only very old spyder autocompletion issues that apparently were caused by not having the (correct) rope package installed:

[https://stackoverflow.com/questions/18316459/spyder-autocomplete-doesnt-work-with-64-bit-winpython-2-7-5](url)
[https://stackoverflow.com/questions/18044312/spyder-does-not-autocomplete-local-variables](url)

hope you can resolve the issue. i appreciate your efforts with winpython a lot. many thanks!

**Comment by stonebig** [comment]
the slim version that works:
- launches 4 Python processes and 4 QtWebengine processes,
- has no spyder-notebook nor spyder-terminal plugin.

**Comment by stonebig** [comment]
so it stops working when I add this list of packages:
````
bcolz
clrmagic
edward
emcee
enum34
fasteners
fastparquet
feather_format
formlayout
fuzzywuzzy
geopy
gitdb2
gitpython
gmpy2
greenlet
guidata
guiqwt
h5py
husl
ipython_sql
joblib
julia
jupyter_sphinx
keras
keras_vis
lasagne
locket
metakernel
mkl_service
monotonic
mpld3
mpmath
````

**Comment by stonebig** [comment]
list of package addition creatin problem downs to:
````bcolz
clrmagic
enum34
formlayout
h5py
husl
ipython_sql
joblib
jupyter_sphinx
monotonic
````

**Comment by stonebig** [comment]
list down to:
````
bcolz
clrmagic
enum34
h5py
````

**Comment by stonebig** [comment]
so:
- "pip install enum34" breaks the auto-completion in spyder editor, under WinPython-3.6.2
- "pip uinstall enum34" restores the auto-completion in spyder editor, under WinPython-3.6.2

**Comment by stonebig** [comment]
so simple and immediate and without side-effect solution:
- start WinPython-3.6.2.0 "WinPython Command Prompt"
- type "pip uninstall enum34" (and answer "y" to remove it)

**Comment by captaindet** [comment]
nice detective work! this fixes it for me too.  thanks!

**Comment by stonebig** [comment]
solved in today uploading build WinPython-64bit-3.6.2.1Qt5b1
