### ISSUE TITLE
Spyder/Python crash

### ISSUE THREAD

**Issue by lmagazzini** [winpython/winpython#565]
On a Windows7 PC, WinPython-32bit-3.6.2.0Qt5 installed (on E:\ disk)
The same occurred on previous version WinPython 3.5.4.0Qt5-32bit
I clicked on spider.exe in the main folder,  then the Spyder splashscreen appears, when loading editor the Python crash 
Is there anybody can help me?

**Comment by stonebig** [comment]
try to click spyder_reset icon, before trying again.

Otherwise, If your on Windows 7, it may work better with a non-Qt5 version. or a version before Qt5.8: WinPython 3.4.4.6Qt5 , or maybe WinPython 3.5.3.0Qt5

**Comment by hiccup7** [comment]
Spyder v3.2.6 fixed a lot of crash bugs which have been around for a long time.
@lmagazzini  - Did upgrading to Spyder v3.2.6 or WinPython-64bit-3.6.4.0Qt5b4 (or later) solve your issue?

**Comment by hiccup7** [comment]
@stonebig Since the user has not responded in over a week, I recommend closing this issue.  These old open Spyder issues give people the wrong impression about compatibility between WinPython and Spyder.

For the same reason, I recommend closing #577 and #541
