### ISSUE TITLE
Bokeh command line issue in WinPython-64bit-3.5.4.0Qt5

### ISSUE THREAD

**Issue by lolo31370** [winpython/winpython#567]
When I execute bokeh.exe from \python-3.5.4.amd64\Scripts, I have the error :
Fatal error in launcher: Unable to create process using '"'

**Comment by stonebig** [comment]
executables in winpython  are not made to be typed directly, so you may:
  - click on "Winpython Command Prompt",
  - then type "bokeh sampledata", for example,  in the command line

**Comment by lolo31370** [comment]
Thank you very much !
