### ISSUE TITLE
Very long boot time on windows7, spyder 3.2.1.dev0, WinPythonQt5-64bit-3.6.2.0

### ISSUE THREAD

**Issue by xgnata** [winpython/winpython#569]
See https://github.com/spyder-ide/spyder/issues/5429
There is something wrong with spyder.exe and/or the Qt5 environment in WinPythonQt5-64bit-3.6.2.0

**Comment by stonebig** [comment]
I don't have anymore Windows 7. What is the hardware configuration of your PC ? What process consumes cpu cycle when you launch WinPython ?

On Windows 7 I can only suggest WinPython Versions before Windows 10 initial summer launch, or try an alternate distro

I think with Spyder-included Plugins, startup did degrade. so you can try:
- "pip uninstall Spyder-notebook"
- "pip uninstall Spyder-Terminal"
- "pip uninstall spyder-reports"

**Comment by Patrick-Cole** [comment]
I have windows 7 and use the WinPython-64bit-3.5.4.0Qt5 version. It works fine on my PC. I am not sure that spyder is fully compatible yet with python 3.6 anyway. pypi says it works with 3.5 and when I did try the 3.6 release, I think I saw a few bugs related to this. I may be wrong though

**Comment by xgnata** [comment]
OK it looks like I'm facing this issue with encryption
https://stackoverflow.com/questions/29997274/python-is-very-slow-to-start-on-windows-7
I'm going to check with IT but it seems hopeless. It is not better with
anaconda.


Le 11 oct. 2017 7:39 AM, "Patrick" <notifications@github.com> a écrit :

I have windows 7 and use the WinPython-64bit-3.5.4.0Qt5 version. It works
fine on my PC. I am not sure that spyder is fully compatible yet with
python 3.6 anyway. pypi says it works with 3.5 and when I did try the 3.6
release, I think I saw a few bugs related to this. I may be wrong though

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/winpython/winpython/issues/569#issuecomment-335688814>,
or mute the thread

**Comment by stonebig** [comment]
maybe try this experiment: go to winpython-...\tools, and rename pandoc.exe as no_pandoc.exe.

**Comment by xgnata** [comment]
no_pandoc.exe does not help.

It looks like the root cause is something like :

https://stackoverflow.com/questions/29997274/python-is-very-slow-to-start-on-windows-7

Unfortunately I cannot uninstall SafeGuard to be sure that it is the 
problem.

**Comment by stonebig** [comment]
if you remove spyder plugins, there should be less process(es) started, and so less SafeGuard analysis done.

**Comment by stonebig** [comment]
ok, if I uninstall spyder plugins, I go back to "old time" start-up time, 30" hot-start, that is 3 times quicker then with the plugins.

==> I think I will not ship plugins in next release, expect maybe spyder-reports:
- spyder-terminal cannot open 2 terminals,
- spyder-notebook doesn't support a full experience.

so you may try:
- pip uninstall spyder-notebook
- pip uninstall spyder-terminal
- pip uninstall spyder-reports

**Comment by stonebig** [comment]
ok, by removing spyder-notebook and spyder-terminal, cold boot on a very old pc comes down from 6' to 2':
- I'll do that in next rc,
- users suffering from the slow start-up may uninstall spyder-notebook and spyder-terminal.

**Comment by xgnata** [comment]
It does help indeed. Thanks.
