### ISSUE TITLE
Will there be winpython2.7.14-zero 

### ISSUE THREAD

**Issue by joylin1984** [winpython/winpython#580]
Will there be winpython2.7.14-zero ？

**Comment by stonebig** [comment]
Hi @joylin. WinPython goal is to help extend Python ecosystem reach.

Doing that is counter-productive:
- it would reduce intensive to python2 users to move to python3,
- it would increase incentive from new python users to consider python2 as an option, 
- it would increase burden on python maintainers at all level of the eco-system, having to compromise efficiency and focus, for retro-compatibility.
