### ISSUE TITLE
"Unable to create process using "" Error - Orange.bat

### ISSUE THREAD

**Issue by joesoap99** [winpython/winpython#588]
Windows 7 64 bit.
WinPython-64bit-3.6.3.0

I am trying to open Orange (orange-canvas.exe) from a simple bat file. (see below)
This worked in WinPython-64bit-3.6.3.0 but now gives an error
"Unable to create process using ""  "

orange.bat:
@ECHO OFF
START G:\WinPython\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Scripts orange-canvas %1

There was a similar error reported at:
https://github.com/winpython/winpython/issues/410
which was too technical for my present understanding.

Orange was installed from:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

Orange works fine manually from the command prompt.
Tedious typing in the long path statements each time.

Any help welcome to get the bat file working.

**Comment by stonebig** [comment]
and this ?
````
orange.bat:
@echo OFF
call G:\WinPython\WinPython-64bit-3.6.3.0Qt5\scripts\env_for_icons.bat
START G:\WinPython\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Scripts orange-canvas %1
````

**Comment by joesoap99** [comment]
Thank you for replying so quickly.
I added the first method call and it now works fine.

Anaconda on my setup gets corrupted every upgrade, wasting hours of trial and error fixes, so I have moved over to WinPython now. It works every time. Another big thank you.
