### ISSUE TITLE
Bluetooth API error when starting WinPython Control Panel?

### ISSUE THREAD

**Issue by srk** [winpython/winpython#592]
OS: Windows 8.1 Professional (64-bit)
WinPython: 3.6.2.0 64-bit QT5
On starting WinPython Control Panel, I get the error dialog:

'This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (100.10586 or above)'

I assume this is some problem with the underlying Windows/.NET dlls, but can anyone tell me how to fix this error? Winpython Command Line seems to work as normal.

**Comment by stonebig** [comment]
Interesting: do you mean PyQt5-5.10 needs Windows 10 ?

**Comment by stonebig** [comment]
move back to PyQt5-5.9.2 as Spyder and Bluetooth don't like PyQt-5.10.0

**Comment by hiccup7** [comment]
Mouse cursor issue with PyQt 5.10 https://github.com/spyder-ide/spyder/issues/6393
Planned to be fixed in Spyder v3.2.7.  However, see the developer's comment: "There has been several reports that things are failing strangely with 5.10."

**Comment by hiccup7** [comment]
Spyder v3.2.7 now requires PyQt older than v5.10.

**Comment by altendky** [comment]
`import PyQt5.Qt` imports everything including bluetooth.  While that import looks nice for the sake of only having one it does cost in scenarios such as this.  So, just use the regular imports like `import PyQt5.QtWidgets` instead.

**Comment by stonebig** [comment]
Aaaaaaargh. So WinPython embedded version will be updated from QtPy-1.3.0 to QtPy-1.42.
Thank you @altendky 

User in needs can copy ther copy of QtPy in  
\Lib\site-packages\qtpy 
   to 
\Lib\site-packages\winpython\_vendor\qtpy

**Comment by rmd13** [comment]
Win8.1 cannot start cellpose because of the PyQt5 compatibility problem,

The solution is :

change
from PyQt5.Qt import *
to

import PyQt5
from PyQt5 import *
in any place of cellpose code that import PyQt5.

Another solution is renamed file C:\Python\Python38-32\Lib\site-packages\PyQt5\Qt\bin\Qt5Bluetooth.dll to _Qt5Bluetooth.dll.

More details see:

https://stackoverflow.com/questions/55205708/why-pyqt5-import-show-a-error-about-windows-and-bluetooth

**Comment by stonebig** [comment]
and what are the said places ?  
Microsoft support for Windows 8.1 will end on January 10, 2023. so:
- you can proposing  a patch in all bad packages with the problem, that impacts you,
- or it's a bit of helping yourself  with a nice 'replace' in all problematic source files 'live'
