### ISSUE TITLE
Only Winpy version 3.7 all releases not working with Pyzo

### ISSUE THREAD

**Issue by ramlaxman** [winpython/winpython#594]
I am not able to use winpython with Pyzo release. Whenever I am setting environment variable in Pyzo, it is giving me the error:
" Traceback (most recent call last):
  File "H:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\start.py", line 46, in <module>
    import yoton
  File "H:\Program Files (x86)\pyzo\source\pyzo\yoton\__init__.py", line 39, in <module>
    from yoton.clientserver import RequestServer, do_request
  File "H:\Program Files (x86)\pyzo\source\pyzo\yoton\clientserver.py", line 81
    def __init__(self, address, async=False, verbose=0):
                                    ^
SyntaxError: invalid syntax
The process failed to start (invalid command?). (1)"

**While all other WinPython versions are working fine. So I don't think there is any problem with Pyzo versions.**

**Comment by stonebig** [comment]
Python-3.7 is still beta status, you may have found a Python-3.7 bug ?

**Comment by ramlaxman** [comment]
Can't say for sure. As I am avid user of Winpython new releases, they were tend to work with Pyzo without any problems (Yes I am talking about Beta status of all other versions) but I am getting above error msg only when using Winpy 3.7x not with 3.6b1,3.5a1 (alpha & beta releases).

**Comment by stonebig** [comment]
in pure truth , it's a bit early to raise the remark : Anaconda modules don't test itself against python-3.7, so pyzo maintainer will have an hard time checking the issue

**Comment by stonebig** [comment]
you can retry you luck with Python-3.7.0 beta2
https://github.com/winpython/winpython/releases/edit/1.9.20180301

**Comment by ramlaxman** [comment]
no luck. Better I will wait for first stable release of Winpython 3.7.

**Comment by stonebig** [comment]
https://github.com/pyzo/pyzo/issues/529

**Comment by stonebig** [comment]
so... this bug is not a WinPython bug.

**Comment by stonebig** [comment]
I can't get pyzo to work on any winpython..... how do you succeed ?

**Comment by stonebig** [comment]
it should not work per clicking on pyzo.exe, but it does.... how strange:
![pyzo-3 7](https://user-images.githubusercontent.com/4312421/36932729-e4073590-1ecd-11e8-94cb-b01493c9428f.png)

solved
