### ISSUE TITLE
Installing openpyxl 2.5.0

### ISSUE THREAD

**Issue by bestickley** [winpython/winpython#597]
I want to install openpyxl 2.5.0 and these are the methods I've tried so far:

1) "pip install openpyxl" in WinPython Command Prompt
2) "pip install C:\WinPython\python-3.6.3.amd64\Libs\site-packages\openpyxl\openpyxl-2.5.0-py2.py3-none-any.whl" in WinPython Command Prompt
3) Opened WinPython Control Panel and installed the file mentioned above. 

Each method has not worked. 

I appreciate any help. Thank you.

**Comment by stonebig** [comment]
you may try:
- to download it from https://www.lfd.uci.edu/~gohlke/pythonlibs/ into d:\toto
- pip install d:\toto\openpyxl‑2.5.0‑py2.py3‑none‑any.whl

**Comment by bestickley** [comment]
Unfortunately, that method did not work. Here is the cmd text:

C:\WinPy\scripts>pip install C:\WinPy\python-3.6.3.amd64\Lib\site-packages\openp
yxl\openpyxl-2.5.0-py2.py3-none-any.whl
Processing c:\winpy\python-3.6.3.amd64\lib\site-packages\openpyxl\openpyxl-2.5.0
-py2.py3-none-any.whl
Collecting et-xmlfile (from openpyxl==2.5.0)
  Could not fetch URL https://pypi.python.org/simple/et-xmlfile/: There was a pr oblem confirming the ssl certificate: [SSL: UNKNOWN_PROTOCOL] unknown protocol (
_ssl.c:777) - skipping
  Could not find a version that satisfies the requirement et-xmlfile (from openp
yxl==2.5.0) (from versions: )
No matching distribution found for et-xmlfile (from openpyxl==2.5.0)

**Comment by stonebig** [comment]
if you did download the wheel at `c:\winpy\python-3.6.3.amd64\lib\site-packages\openpyxl\openpyxl-2.5.0-py2.py3-none-any.whl`, then I have no idea.
