### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by orbitalz** [winpython/winpython#599]
I've just renamed the installed folder such as [winpython] to @winpython and everything get messed up. For example, the jupyterlab shows the warning message about 'jupyterlab-matplotlib and the likes' does not properly build. I then installed the new version but the problem persisted. So, I've used the command 'pip install --upgrade --force-reinstall jupyterlab' and it gives the error `Exception:
Traceback (most recent call last):
  File "D:\@Apps\WinPython-64bit-3.6.Qt5\python-3.6.3.amd64\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive:`

I guess I suppose not to rename the folder, don't I?

**Comment by stonebig** [comment]
Hum:
- I fear part of the problem is javascript packaging system, and Jupyterlab being a very moving target,
- you may not have this problem with latest beta.

As Jupyterlab stabilize, I hope the problem won't show up .... after Jupyterlab-1.0, this end of spring.
