### ISSUE TITLE
Tornado5

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#601]
tracking what  Tornado-5 still miss, I see:
- [x] jupyter_client closing patch https://github.com/jupyter/jupyter_client/commit/4bfb5c4e00c4f5342b62523fffc79512f454ac92 (missing a patch release)
- [x] bokeh compatibility https://github.com/bokeh/bokeh/commit/cc63e559b5f0fa2f3ab8105683347ed588b612c8 (in bokeh-0.12.15.dev2)

**Comment by stonebig** [comment]
hum, clearly tornado-5 consequences may take a while to be sorted out.

**Comment by hiccup7** [comment]
See https://github.com/spyder-ide/spyder/pull/6626

**Comment by stonebig** [comment]
yes, this and others issues.

**Comment by stonebig** [comment]
requires bokeh-0.12.16dev2 or better

**Comment by stonebig** [comment]
we are at Tornado-5.0.2 + bokeh-0.12.16dev3 now, merging.
