### ISSUE TITLE
integrating XXXX instead of Tensorflow

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#631]
reasons to try the change:
- WinPython is edging to the upper limit of the NSIS installer (2 Go uncompressed):
  . going to a smaller Deep Learning Package is option 1
  . droping a Deep Learning package is option 2
  . droping Theano is a whished option, but then we loose pymc3, so no yet.
- Tensorflow recent versions are no more available for old cpus ==> bad at schools, can't check if ok.

Alternatives:
- popularity of DL frameworks: Tensorflow, PyTorch, chainer, cntk
- only PyTorch and cntk are currently old-cpu compatible, (chainer is no more ?)
- anaconda looks to create a numpy2=numpy+cupy_piece_of_chainer, but not yet there
- microsoft will integrate DL in the O.S (a python interface), but not yet there,
- WinPython can only integrate  a package that can work also in non-nvidia mode / old cpu.

Popularity:
- PyTorch is 3Mo smaller then Tensorflow, and the next popular choice, and made:
   - the courageous effort to move from Lua to Python3 in 2017,
   - the April-2018 awesome effort to be nice on Windows.
- Microsoft is currently moving (fast?), but below the radars.

So:
- will try Torch + TorchVision in beta,
- see if it sticks.

**Comment by stonebig** [comment]
ok, this works https://pytorch.org/tutorials/advanced/neural_style_tutorial.html#sphx-glr-advanced-neural-style-tutorial-py

**Comment by stonebig** [comment]
Pytorch-1.0 document https://pytorch.org/2018/05/02/road-to-1.0.html

I see big changes coming:
- Aten merging with Caffee2,
- torch.jit.

Maybe PyTorch-1.0 will inflate too much and won't fit anymore in WinPython

**Comment by stonebig** [comment]
I discover cntk has shrinked to 8 Mo....

May be the next experiment.

Old experiment found back: https://github.com/lengstrom/fast-style-transfer

**Comment by stonebig** [comment]
mission statements ? :
- Chainer = A flexible framework of neural networks
- CNTK = The Microsoft Cognitive Toolkit
- TensorFlow  = TensorFlow helps the tensors flow
- Pyro = distributed object middleware for Python (IPC/RPC)
- PyTorch = a deep learning framework for fast, flexible experimentation **or** Tensors and Dynamic neural networks in Python with strong GPU acceleration

**Comment by RoyiAvital** [comment]
When you write:

>> anaconda looks to create a numpy2=numpy+cupy_piece_of_chainer, but not yet there

Where do you get the information from?

Regarding PyTorch, the installers size won't change due to the merge with Caffe2.
It's only for maintainability inside Facebook of those 2 frameworks.

**Comment by stonebig** [comment]
there: https://discourse.pymc.io/t/pytorch-backend-for-pymc4/61/39

**Comment by RoyiAvital** [comment]
@stonebig , He doesn't state he is from Anaconda.
Also I can't see any statement there is Numpy2 which has built in CuPY integration.

**Comment by stonebig** [comment]
fresher news from @teoliphant aroun his numpy2/numba/chainer plan:
- https://twitter.com/teoliphant/status/994612940992073729

https://xnd.io/ -- an exciting young project for providing unified array-computing primitives for multiple language run-times:  https://us.pycon.org/2018/community/sprints/ …

**Comment by wmac** [comment]
We use Tensorflow and Keras as our low and high-level machine learning packages in our school ... Though PyTorch might be considered...

I think Theano could go...and tensorflow can be used for Keras,,,

**Comment by stonebig** [comment]
so, after shifting to a new installer:
- every deep learning package can fit,
- I'll keepTensorflow/Keras for now, as it was the historic choice after Theano,
