### ISSUE TITLE
Release 1.7.20170401 generated a bad manifest for WinPython-64bit-2.7.13.1Zero.exe

### ISSUE THREAD

**Issue by brianddk** [winpython/winpython#634]
https://github.com/winpython/winpython/blob/818587d4a1a67f5e4db7d59e5d880fb3b63f5f25/winpython/disthelpers.py#L169

Microsoft.VC90.CRT.manifest inside the WinPython-64bit-2.7.13.1Zero.exe package shiped with `type=""`
in the `assemblyIdentity` tag.  This causes winsxs to fall over and die.

**Comment by stonebig** [comment]
this is code from @PierreRaybaut I never even tried to understand. So I may have screw up at some point ?

**Comment by stonebig** [comment]
maybe this  chines-written part was important ?

https://github.com/winpython/winpython/blob/master/winpython/disthelpers.py#L148..L151

**Comment by brianddk** [comment]
I think the keys are constants.  They are just GUIDs generated whenever MSFT releases a new CRT.  The guids were ok... just the missing type was the problem.

**Comment by pigeek** [comment]
@brianddk , what should be the type?

**Comment by pigeek** [comment]
Apparently as per https://docs.microsoft.com/en-us/visualstudio/deployment/assemblyidentity-element-clickonce-deployment?view=vs-2017 type should be set to "win32".

**Comment by stonebig** [comment]
Python-2.7 is R.I.P.
