### ISSUE TITLE
WinPython base read-only on a multi-user system, changes written to user directory?

### ISSUE THREAD

**Issue by kannes** [winpython/winpython#637]
I would like to use WinPython to provide many people with an good base and easy setup for Python development. Our computer systems are shared machines with user-specific things being saved on a network drive.

We want the WinPython base installation to be installed once per system but allow users to configure it and install packages. Those alterations should be stored in their user directory.

Is there a way to install WinPython system-wide as administrator and have it save all changes, installs and configuration on a specific, external path (e.g. the X: drive is the user's home directory, so "X:\WinPython\" or something)? We might have some system variable mapped to that, I would have to check.

**Comment by stonebig** [comment]
you can try to see what happen by removing`#` in subdirectory settings\winpython.ini.

````
[debug]
state = disabled
[environment]
#HOME = %HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
#JUPYTER_DATA_DIR = %HOME%
#WINPYWORKDIR = %HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%\Notebooks
````

Some  users may have more real case experience on this, so you may ask on stackoverflow

**Comment by stonebig** [comment]
Maybe WinPython is not your easiest starting point for this.

**Comment by kannes** [comment]
We set it up successfully and have it used by ~30 students for several weeks now. :)

I documented what I did at https://gitlab.com/Hannes42/shared-winpython-base , hopefully this will be useful to others. For any questions don't hesitate to ask me or file issues over at that repo.

**Comment by stonebig** [comment]
well, I'm looking at your todo:
- Package installation via WinPython Control Panel is not working: 
  . what it does is there https://github.com/winpython/winpython/blob/master/winpython/wppm.py#L428..L452
  . that you can translate as:
```
%WINPYDIR%\..\scripts\env.bat && cd/D %WINPYDIR% && %WINPYDIR%\python.exe -m pip wheel1.whl wheel2.whl ...
````


- pyzo: it seems it wants to have its initial directory pointing at python.exe.
- get rid of windows confirmation dialogs at launching the bat scripts: I think you won't avoid that unless the ".bat" are on your user C drive, their "DESKTOP" for example.

**Comment by stonebig** [comment]
hi @kannes ,

how is evolving your user setup today ? 
what version of Python (and Python distro) are you using for your students ? 
does  it work on windows 7 ?

**Comment by kannes** [comment]
Hey @stonebig, thank you for asking! I have left the university where we used this setup long ago and have no idea what they are using nowadays.

**Comment by stonebig** [comment]
ok, I have to setup a school with WinPython-3.6 or better.
I would have been curious on what they do now at your university.
