### ISSUE TITLE
stop python3.3 support

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#64]
warning users in advance

**Comment by yw5aj** [comment]
+1. From https://groups.google.com/d/msg/sympy/2853E532sR4/c8cXXIrrm0MJ  it says:

2.5    89   1.3% 
2.6   609   9.0% 
2.7  5501  81.4% 
3.2   191   2.8% 
3.3   797  11.8% 
3.4  2916  43.1% 
3.5   238   2.0%

**Comment by stonebig** [comment]
I only have a python 3.3.5 binary, as python 3.3.6 doesn' exist in a binary form.
==> Maintaining a Python 3.3 branch could give users a perpetual false sense of `security`.

**Comment by stonebig** [comment]
done
