### ISSUE TITLE
Executables Spyder.exe, WCCP.exe not working (ActiveX Component can't create object)

### ISSUE THREAD

**Issue by solarjoe** [winpython/winpython#640]
(WinPython64-3.6.5.0Q5, Windows 7)

When I want to run Spyder.exe or WCCP.exe I get the error message

```
Windows Script Host
scripts/Noshell.vbs
ActiveX Component can't create object
Runtime error in MS VBscript
```
Executing the files with "run as administrator" solves the problem, but is not
a good workaround in our company.

Following the URL in noshell.vbs I was messing around with 
`start /b cmd /c command`, `call`, etc, but I could not find a solution.

Do you have an idea how this could be solved?

**Comment by solarjoe** [comment]
Could it be that *.bat files are only allowed for admins and *.cmd can be run as normal users?

**Comment by solarjoe** [comment]
Problem was that bat files were not associated correctly, I had to delete

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.bat\UserChoice`

It works now.

**Comment by stonebig** [comment]
thanks for having auto-resolved this. it was a wired error
