### ISSUE TITLE
Qt designer worked once, then never again

### ISSUE THREAD

**Issue by gordonhch** [winpython/winpython#647]
Problem:

Using QT designer on WinPython64-3.7.0.1rc for once. could not open again after closing it.

Task manager shows process and very quickly it ended.

reinstalling does not solve it, nor installing WinPython64-3.6.5.0Qt5 could help.

Solution:

(partly found on https://blog.csdn.net/u013704336/article/details/48134355 )

Go to C:\Users\[username]\.designer

Delete gradients.xml

then open WinPython command line or powershell

install pyqt5-tools with pip

the shortcut exe will automatically use the new instance of QT Designer to work.

Might not be helpful for debugging but it works for me.

Info:
running on Windows 10 1803

**Comment by stonebig** [comment]
谢谢 !
