### ISSUE TITLE
Update Spyder links and description after 3.3.1 is released to PyPI 

### ISSUE THREAD

**Issue by CAM-Gerlach** [winpython/winpython#656]
Since the current links and description on PyPI was well out of date and will be comprehensively updated with 3.3.1, it would be nice to update that sometime after Spyder 3.3.1 hits PyPI (currently planned for today or tomorrow), ideally by the next WinPython release, so we can close out spyder-ide/spyder-docs#39 . Thanks!

**Comment by CAM-Gerlach** [comment]
@stonebig I think so, since the last milestoned issues/PRs were just closed/merged last night. Once the milestone is closed, you'll know the release process has started. Thanks!

**Comment by CAM-Gerlach** [comment]
@stonebig As of today (or probably yesterday in your timezone) Spyder 3.3.1 is [up on PyPI](https://pypi.org/project/spyder/), FYI.

**Comment by stonebig** [comment]
ok, closing.
