### ISSUE TITLE
Are old wheels available to re-create an old released WinPython archive?

### ISSUE THREAD

**Issue by ankostis** [winpython/winpython#659]
Once more thank you for your efforts.

I have been re-package and distributing WinPython for 3-4 years now,
and there is a need to go "back in time" from a later distribution;
that is, to downgrade e.g. `numpy` to the previous WinPython release.

Is there by chance the original wheels from Gohlke store somewhere where i can access them?

**Comment by stonebig** [comment]
you can look there, https://sourceforge.net/projects/winpython/files/WinPython_Source/Do_It_Yourself/

I was doing it till 2016, then stopped. what are you looking especially ?

**Comment by stonebig** [comment]
you can also:
- remove numpy where you want to replace it,
- copy the files from another winpython as they are listed in `....\Lib\site-packages\numpy-1.xx.y+mkl.dist-info\RECORD`, with the `numpy-1.xx.y+mkl.dist-info` directory

**Comment by ankostis** [comment]
Wow, i missed that your replied in the middle of the summer that fast.  Today went back to lost a reminder and saw your answers. Big-thank you.

Can i close it?

**Comment by stonebig** [comment]
yes
