### ISSUE TITLE
multiprocessing in Spyder doesn't seem to work??

### ISSUE THREAD

**Issue by nerdfever** [winpython/winpython#660]
I suppose it must be something I'm doing wrong, but I find it mysterious:

```
from multiprocessing import Process

def f(name):
    print('hello', name)

if __name__ == '__main__':
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()
```

That's straight out of the [multiprocessing module documentation](https://docs.python.org/3.6/library/multiprocessing.html).

In WinPython, I get no output at all from the Console.

From the command line it works fine:
```
C:\Users\Dave\data\Code\Python>python3 test.py
hello bob
```

Setup:

Win10 x64
WinPython 3.6.6.1
Spyder 3.3.0
Python 3.6.6.amd64

**Comment by stonebig** [comment]
same thing if you run it with IDLE. so it's not a Spyder specific problem.

**Comment by stonebig** [comment]
you may be more lucky with Pyzo (option "run as script")
![image](https://user-images.githubusercontent.com/4312421/44580758-6faa4780-a79b-11e8-8140-346294b2a252.png)
