### ISSUE TITLE
Is it possible to run shell commands from WinPython Interactive 

### ISSUE THREAD

**Issue by MiniMe4GH** [winpython/winpython#662]
Hi guys

the IPython docs say that if you run "!ls" that will be executed in the shell and will show you the files and the folders in the current folder
When I try that from WinPython which apparently include IPython I am getting a "Syntax error" 

Is the above possible  (run shell commands by precending them with !) in WinPython ?

**Comment by stonebig** [comment]
`ls` is for  linux/mac, `dir` is the equivzalent on Windows/dos.
try 
````
!dir
````

**Comment by 1001QAdotNET** [comment]
Thanks for replying but this does not seem to work from WinPython interpreter.exe which can be configured to show a IPython like prompt.
I had to install IPython and to start it and from there !dir worked
My question is regarding the WinPyton interpreter.exe...I like the emas/vi options and all that look but I would have liked to have the above functionality as well

the documentation is deceiving because it says IPython is available from day one.
Am I wrong in the above?

**Comment by stonebig** [comment]
@1001QAdotNET:
- Winpython interpreter is just a python prompt, decorated per python-prompt, but notihng more.
- if you installed a "zero" version, then there is no Ipython inside, only IDLE or IDLEX.

Goal of the winpython "zero" version was to be about the same size of the standard python installer.

**Comment by stonebig** [comment]
otherwise, from https://stackoverflow.com/questions/89228/calling-an-external-command-in-python

````
from subprocess import call
call(["cmd","/K", "dir", "&&", "exit"])
`````
gives
````
 Le volume dans le lecteur C n’a pas de nom.
 Le numéro de série du volume est 98F9-A53D

 Répertoire de C:\WinP\bd37\bu\winp64-3.7.x.2\notebooks

27/08/2018  13:47    <DIR>          .
27/08/2018  13:47    <DIR>          ..
27/08/2018  08:10    <DIR>          docs
27/08/2018  15:45    <DIR>          WASM_almar_klein_demo
               0 fichier(s)                0 octets
               4 Rép(s)  22 858 899 456 octets libres
````

**Comment by 1001QAdotNET** [comment]
Not sure I am following you
What am I looking at when I run WinPython interpretor.exe? 
Is that the decoreated Python promot ? I am seeing some menus there ...like if I press F2 I can customize some options and so on
Is that thing(interpreter or whatever), supposed to contain IPython ?

**Comment by 1001QAdotNET** [comment]
Ok I did not know about that module. An interesting one.Now it is clear, thank you!

**Comment by 1001QAdotNET** [comment]
One more question- It take it that ipython can't be launched from within WinPython ... I could see after installing and launching IPython that in fact IPython launches a python.exe in background

**Comment by stonebig** [comment]
Did you mean/want that ?
- click on "winpython commande prompt"
- type "ipython" 

![image](https://user-images.githubusercontent.com/4312421/44690196-42d78800-aa5a-11e8-9f1f-321acfe0a79d.png)

**Comment by 1001QAdotNET** [comment]
that was easy and I knew it
I was hoping to bring IPython within the neat interface offered by prompt-toolkit

**Comment by stonebig** [comment]
and, to get it under prompt-toolkit:
Did you mean/want that ?
- click on "winpython commande prompt"
- type "ptipython" 

![image](https://user-images.githubusercontent.com/4312421/44705815-02026200-aaa0-11e8-88ec-f6b734087cc1.png)
![image](https://user-images.githubusercontent.com/4312421/44705896-383fe180-aaa0-11e8-8c5e-f3e7ecce33ea.png)

**Comment by 1001QAdotNET** [comment]
thank you!
