### ISSUE TITLE
SimPy

### ISSUE THREAD

**Issue by wmac** [winpython/winpython#670]
Can we have the most popular python "discrete event simulation" library called SimPy in the package?

Thanks.

**Comment by stonebig** [comment]
Where did you see it's popular ? Have you an example of use ? to register on github just for this question, you may have a good use-case

**Comment by wmac** [comment]
Hello,

On Matlab people use Matlab's own "SimEvent" to simulate processes (e.g.
systems that have queues like networks, physical service points e.g. shop,
bank, street, petrol station). In python the only stable choice I know is
this one.

It has a wikipedia page and google trends shows relative interest on it
(the name is searched more than my beloved winpython) and there are 3
million references to it on the internet (according google).

https://en.wikipedia.org/wiki/SimPy

https://trends.google.com/trends/explore?geo=US&q=simpy,winpython

Regards,
Mac

**Comment by wmac** [comment]
Oh, btw. I did my PhD on simulation and modeling (half of the times you will do discrete event) and I prefer my students to use python and not Matlab for quick prototyping (and possibly full simulations).

**Comment by stonebig** [comment]
ok

**Comment by stonebig** [comment]
in current build 2
