### ISSUE TITLE
installing_R notebook - reference to hash SHA1 should be removed

### ISSUE THREAD

**Issue by keluc** [winpython/winpython#672]
I don't seem to find the notebook (i.e. the notebook 'installing_R.ipynb' that's in the docs subfolder) in the project so I post only the issue.

[Cran ](https://cran.r-project.org/bin/windows/base/)doesn't provide SHA1 anymore. Notebook should be corrected.

Every reference to and test of sha1 should be removed.

**Comment by stonebig** [comment]
I did compute the sha-1, and put it in the notebook, but you can ignore that test if you want.
I consider only md5 + sha 1 to be the minimal "equality" proof as of now.

Maybe I should replace sha-1 per sha-256, with all these big clouds accumulating power.

**Comment by keluc** [comment]
Ok, it's just that the notebook points to the most recent R version, 3.5.1 for the moment ("https://cran.r-project.org/bin/windows/base/"). Older versions seem to be under "https://cran.r-project.org/bin/windows/base/old/".

**Comment by stonebig** [comment]
a yes, R un-friendly practice to move binaries.

**Comment by stonebig** [comment]
I will updat to use the archive, not moving part

**Comment by stonebig** [comment]
https://github.com/winpython/winpython_afterdoc/pull/49
