### ISSUE TITLE
cvxpy issue communicating with mkl

### ISSUE THREAD

**Issue by chickadee7** [winpython/winpython#674]
I just installed cvxpy 1.0.6 using anaconda.  My operating system is Ubuntu 18.04.1.  When I run
`nosetests cvxpy`
I get the error
`....................................................Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.`

After doing some research on forums, I think MKL is a library called by numpy and scipy?  However, numpy and scipy work just fine for me.  I'm able to execute commands from those packages with no trouble.  I've tried the commands

`conda install nomkl numpy scipy scikit-learn numexpr`
`conda remove mkl mkl-service`

`conda install  -f  numpy`
 
and none of those fixed the error.  Also, others reported that the command
`python -c 'import sklearn.linear_model.tests.test_randomized_l1'`
generated an error, but when I run this, I get no error.  It seems as if the problem has to do with cvxpy.

**Comment by stonebig** [comment]
it's a question for anaconda mailing list. re-post it there https://groups.google.com/a/continuum.io/forum/#!forum/anaconda

**Comment by stonebig** [comment]
solved per https://github.com/winpython/winpython_afterdoc/pull/49
