### ISSUE TITLE
WinPython doesn't start [Strange Error Prompt]

### ISSUE THREAD

**Issue by BloodEvolution** [winpython/winpython#676]
Hi !
When i double click on idle python nothing start.
But when i open the command prompt of winpython i have that on my screen ...
I tried to uninstall python and winpython but the error is still here...
Did someone know what is the problem ? 
Thx
![dqfqdf](https://user-images.githubusercontent.com/22706510/47286634-cbece480-d5ef-11e8-87a3-4a84bf883b32.png)

**Comment by stonebig** [comment]
same as https://github.com/winpython/winpython/issues/677
