### ISSUE TITLE
Idle Winpython dosen't start [Starnge error Prompt]

### ISSUE THREAD

**Issue by BloodEvolution** [winpython/winpython#677]
Hi !
When i try to launch Idle Python, nothing appends...
But when i launch the prompt, i have the following stange screen :
![dqfqdf](https://user-images.githubusercontent.com/22706510/47286950-ea071480-d5f0-11e8-82bf-ca714334b13b.png)
I tried to uninstall python and winpython but the error is still here.
Did someone has an idea of what is the problem ?
Thx !

**Comment by stonebig** [comment]
there is an executable in "mysql" that conflicts with a python executable. I don't remember the name. maybe idle.exe or idlex.exe

**Comment by BloodEvolution** [comment]
Thx  !!!!

**Comment by stonebig** [comment]
so I will remain ignorant of the conflicting name.
