### ISSUE TITLE
Geopandas and fiona

### ISSUE THREAD

**Issue by Patrick-Cole** [winpython/winpython#682]
Hi,

I am using WinPython 3.7.0.2-64bit and have noticed that fiona and geopandas do not have all their dependencies. To be able to get everything to work, I had to also install (from https://www.lfd.uci.edu/~gohlke/pythonlibs/) the following:

gdal 2.3.2
fiona (reinstall after gdal)
Rtree-0.8.3
psycopg2-2.7.5

gdal is the fundamental library upon which fiona (and therefore geopandas) is built. Without it, you cannot import a shape file. For some reason I had to reinstall fiona after that (but that may need some more testing) just to get fiona to work. 

Rtree and Psycopg2 I had to install to get the overlay function in geopandas to work. They are two optional libraries on geopandas website. 

To test this last point, you can run this (it is directly from the geopandas site)

    import matplotlib.pyplto as plt
    from shapely.geometry import Polygon

    polys1 = geopandas.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),
                                  Polygon([(2,2), (4,2), (4,4), (2,4)])])
    polys2 = geopandas.GeoSeries([Polygon([(1,1), (3,1), (3,3), (1,3)]),
                                  Polygon([(3,3), (5,3), (5,5), (3,5)])])

    df1 = geopandas.GeoDataFrame({'geometry': polys1, 'df1':[1,2]})
    df2 = geopandas.GeoDataFrame({'geometry': polys2, 'df2':[1,2]})

    ax = df1.plot(color='red');
    df2.plot(ax=ax, color='green', alpha=0.5);
    plt.show()

    res_union = geopandas.overlay(df1, df2, how='union')

If it works, res_union will return with information in it. The relevant geopandas webpage is: http://geopandas.org/set_operations.html

I thought you might want to know for the next release. I love that geopandas, and fiona are now in winpython. I would like to see rasterio there as well if possible, to complete the easy import of raster data using the gdal libraries if possible. This is totally up to you of course.

Regards

Patrick

**Comment by stonebig** [comment]
I need to replace NSIS installer for that, switching To 7zip or inno setup

**Comment by stonebig** [comment]
geopandas and fiona went there because plotnine **previous** version made it mandatory 

Plotnine removed the constraint, and next WinPython doesn't have anymore fiona and geopandas.

https://github.com/has2k1/plotnine/commit/24c4d3d6c1f016d886568978945196a305eff479#diff-2eeaed663bd0d25b7e608891384b7298

As current NSIS installer is limiting WinPython "uncompressed" to 2.3Go, I'm not ready to re-include them for now.

The good news is that changing of Installer seems possible, most likely to "crude" 7zip

**Comment by Patrick-Cole** [comment]
Okay, good to know. I don't mind manually installing gdal, fiona and geopandas for my needs. Thanks for all your hard work on Winpython!

**Comment by stonebig** [comment]
so the tricky question are:
- why you had to re-install fiona ?
- why on earth map did you need a psycopg2 (postgreSQL connector) package ?
