### ISSUE TITLE
Even more stripped out version of winpython than Zero?

### ISSUE THREAD

**Issue by Sup3rGeo** [winpython/winpython#683]
Hi,

I was looking for some zip-deployable, fully functional (with pip) version of python that we can distribute.

The embeddable version in the official website does not play well with pip (https://github.com/pypa/pip/issues/4207#issuecomment-433378988) and the Zero version of `winpython`, even though it is light, still has a lot of packages and executables. We are looking for something that would be almost like a clean virtual environment.

So the question is, (1) is there any intention to make a really clean version as described and (2) is there a way I can get to that point by getting the zero version, stripping it off and zipping it?

And lastly: Is winpython really 100% functional compared to a full python installation?

Thanks!

**Comment by stonebig** [comment]
well, nothing forbides you to:
- install a WinPythonZero "matrix" in Z:\matrix\winp32-3.7.0.2
- click on "winpython command prompt"
- launch "pip uninstall six sqlite_bro pythonnet python-snappy pyodbc pygments ptpython prompt-toolkit partd parso locket joblib jedi docopt dask cloudpickle brotli  idlex QtPy toolz wcwidth wheel -y"
- then recompress and make an auto-executable of the result (example via 7zip)
  - "7z"  a "z:\matrix\test.exe" "Z:\matrix\winp32-3.7.0.2" -sfx
  - "z:\matrix\test.exe" -y -oZ:\my_shrink\winp32-3.7.0.2> NUL

**Comment by stonebig** [comment]
Maybe:
- WinPython is not the right optimum for your use case,
- you may search also for something like a "nugget" package or "microsoft store" python (coming from Steve Dower).

**Comment by Sup3rGeo** [comment]
Thanks @stonebig for the pointers!

Concerning stripping down winpython, should it be working fine if I get rid of everything except the python folder (`python-3.6.6.amd64`) ?

Also in my company here, we are currently copying the tree from a python installation together with some DLLs. Is it more or less the approach you take to make winpython? I worry we might not be taking the *proper* approach and would like to compare with that you do.

Nice tip about the nugget package, but how (do you/can we) know that it also should work if I just use the python tree inside it? (it seems to work fine with my tests). I just wanted to make sure I won't have any surprises if we just distribute this one, for instance.

**Comment by stonebig** [comment]
WinPython may still work, **if** you have the python.exe in the path, for whatever program/user you want to use it for. 

If your company has a solution, why looking for another one ?

**Comment by Sup3rGeo** [comment]
> If your company has a solution, why looking for another one ?
I am trying to understand the right way of doing it, to know if we are possibly doing something wrong.

I think it there is this need gap (like the official embeddedable but with functional `pip`), as we really would like to avoid maintaining stuff to create a stripped down python (that's really not our core business). Hope eventually you think about providing that as well (although this would be the true *zero ), so our build process become just download and unpack :)

**Comment by stonebig** [comment]
well, you didn't wrote about your success/failure of your  current experiment

**Comment by Sup3rGeo** [comment]
Success. So it would be like inspecting a building that is still standing.

**Comment by stonebig** [comment]
So I can now generate a .zip or 7zip-extractible.
 

Name | Version | Description
-----|---------|------------
[Python](http://www.python.org/) | 3.7.2 | Python programming language with standard library
[pip](https://pypi.org/project/pip) | 18.1 | A tool for installing and managing Python packages
[setuptools](https://pypi.org/project/setuptools) | 40.6.3 | Download, build, install, upgrade, and uninstall Python packages - easily
[sqlite_bro](https://pypi.org/project/sqlite_bro) | 0.8.11 | a graphic SQLite Client in 1 Python file
[winpython](http://winpython.github.io/) | 1.11.20181222 | WinPython distribution tools, including WPPM (package manager)

**Comment by stonebig** [comment]
so there is an experimental ".dot" version on build2, made with nsis or as a .zip

**Comment by stonebig** [comment]
Apparently, there was not much demand for this.

Still it was an opportunity to understand and remove some legacy.
