### ISSUE TITLE
os.system() and subprocess.run() don't seem to work in WinPython/Spyder

### ISSUE THREAD

**Issue by nerdfever** [winpython/winpython#688]
This works from Python on the command line, but not in WinPython/Spyder (nothing happens).

Why, and is there a workaround?

test.py:

    import subprocess, os

    def test():
        #os.system("test.bat") # this line doesn't work either
        subprocess.run("test.bat", shell=True)

    if __name__ == "__main__":
        test()

test.bat:

    echo "this is test.bat"
    pause

**Comment by stonebig** [comment]
try this:
- launch Winp.. \scripts\make_winpython_fix.bat, then try again,
- or ensure you are launching your subprocess with default directory being where is python.exe.

**Comment by stonebig** [comment]
Did you try with spyder on another platform ? Maybe it will work better.

**Comment by stonebig** [comment]
you may experiment pyzo, as an alternative. it works slightly better but not like you imagine

**Comment by nerdfever** [comment]
@stonebig I'll try pyzo. I love Spyder for most things, but there are a few things it just doesn't work for.

Something about the way it interfaces with the Windows system is broken (I suspect the root cause is iPython somehow.) For example, here's more code that works OK with regular Python from the command line, but not in Spyder:

    class Logger(object):
        def __init__(self):
            self.terminal = sys.stdout
            self.log = open("log.dat", "a")

        def write(self, message):
            self.terminal.write(message)
            self.log.write(message)
 
    sys.stdout = Logger()

**Comment by stonebig** [comment]
pyzo doesn't support the pause

![image](https://user-images.githubusercontent.com/4312421/48016882-1a8c9980-e12d-11e8-96b5-44703c60d771.png)

**Comment by nerdfever** [comment]
No, pyzo doesn't support the pause, but it gets further than Sypder does.

**Comment by stonebig** [comment]
I think your dream  can only work in a DOS window, for now. until something really new like maybe this arrives https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by nerdfever** [comment]
@stonebig You may be right, but I've been using Pyzo successfully. As long as the batch file doesn't "pause" for input, Pyzo works well in this situation. (So thanks for the suggestion.)

I prefer Spyder for most Python work, but for these kinds of scripts Spyder just doesn't work.

(Plus, Pyzo loads much faster!)
