### ISSUE TITLE
Interrupting raw_input freezes IPython console

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#69]
Given this Python 2 snippet:
```python
while True:
    raw_input('press <return> to continue')
```
I am running this in an IPython console (e.g. of WinPython-64bit-2.7.9.3.exe).
When I try to stop the script by pressing CTRL+C, the console does not react any more.
In a normal console, the script stops with `KeyboardInterrupt` at least when pressing 'return' after CTRL+C.

The same happens with `input` instead of `raw_input` in Python 3 (e.g. WinPython-64bit-3.4.3.1.exe).

**Comment by jondo** [comment]
My current woraround is to include `time.sleep(3)` in the loop. When CTRL+C is pressed during this sleep, the script correctly stops with `KeyboardInterrupt` after waking up.

**Comment by stonebig** [comment]
It's the same situation in the `IPython Qt Console`, leaving spyder aside of this problem.

The `IPython Qt Console` is loosing support from the Ipython team itself, which focus on the `IPython Notebook`.

As a workaround, the Spyder-ide team is preparing an optional `IPython Notebook` console, but:
- it's not fully ready yet,
- it requires `Qt5` PyQt5, which:
   - is not available on my usual store http://www.lfd.uci.edu/~gohlke/pythonlibs,
   - requires from winpython and other packages using `Qt4` a rewrite effort.

**Comment by stonebig** [comment]
There is no solution to this, except the indirect effect of switching to PyQt5.
