### ISSUE TITLE
simplegeneric missing in 2018 4

### ISSUE THREAD

**Issue by MartinHorstmann** [winpython/winpython#691]
hi all
tried to install R and it doesn't work - solved by installing simplegeneric via "pip install simplegeneric"
applies to:  3.7.1.0-64bit and 3.6.6.2Qt5-64bit (2018 4)
please add simplegeneric

kind regards
Martin

**Comment by stonebig** [comment]
ah... it comes from this 
https://github.com/ipython/ipython/commit/dc0ceb16f92e0e943435106e863a5cfccd724a2d

![image](https://user-images.githubusercontent.com/4312421/48977879-6e8efc00-f0a3-11e8-9e2b-17dd5ad2084b.png)

I can include it, but is it just a matter of having Rpy2 examples and test rewritten in a modern way ?

**Comment by stonebig** [comment]
done in build1
