### ISSUE TITLE
Installed NSIS, but WinPython says I haven't

### ISSUE THREAD

**Issue by DragonOsman** [winpython/winpython#696]
I installed NSIS from the official site and added the installation directory to my PATH, but then when I tried to run the command `python make.py` (I'd already run `python setup.py install` before this successfully), I had this error:
```
C:\Python27\winpython>python make.py
Traceback (most recent call last):
  File "make.py", line 76, in <module>
    ISCC_EXE = get_iscc_exe()  # Inno Setup Compiler (iscc.exe)
  File "make.py", line 74, in get_iscc_exe
    raise RuntimeError("NSIS is not installed on this computer.")
RuntimeError: NSIS is not installed on this computer.
```
Is there something else I have to do?  Note: I need WinPython for the Emsdk, which requires Python 2.7.  I have Python 2.7.15, so I cloned the WinPython repository inside my Python 2.7 directory (C:/Python27).

**Comment by Satertek** [comment]
The installer was transitioned to Inno last month, looks like the error message didn't get updated.

Try installing Inno: http://www.jrsoftware.org/isdl.php#stable

**Comment by stonebig** [comment]
I didn't delete the old code so you can basically still use NSIS by changing thse two lines:
https://github.com/winpython/winpython/blob/master/make.py#L1575..L1576

to
````
dist.create_installer()
#dist.create_installer_inno()
````

**Comment by stonebig** [comment]
I may even add the 7zip installer, the 7zip zipper....

**Comment by stonebig** [comment]
I agree the error message is uncorrect
