### ISSUE TITLE
Typo in README.rst

### ISSUE THREAD

**Issue by M-Watson** [winpython/winpython#713]
Simple typo, in dependencies it says:

Python2 >= 2.7 or Python3 >= 3.4 (Python>= 3.6 is recommanded)
PyQt5 >= 5.6 or PySide2>=5.11 (PyQt5.9 or Pyside2-5.12 is recommanded)

recommanded should be changed to recommended

**Comment by stonebig** [comment]
Oups!

**Comment by stonebig** [comment]
Fixed per https://github.com/winpython/winpython/pull/715

Sorry for my poor english orthograph

**Comment by M-Watson** [comment]
Ha, mistakes happen! I know this was such a minor fix but I figured I would point it out!
