### ISSUE TITLE
Optimized binaries for numpy, scipy, scikit-learn with INTEL CPUs

### ISSUE THREAD

**Issue by jxrossel** [winpython/winpython#717]
Hi,

I was wondering if WinPython already (or could) benefits from the INTEL-optimized binaries for numerical computation:
* Introduction: https://software.intel.com/distribution-for-python/benchmarks?utm_source=iw&utm_medium=blog&utm_campaign=TEC_Python_benchmarks_Oct2019-Reindersblog_cmd_Oct2018&utm_content=text+link
* Packaging: https://software.intel.com/en-us/articles/installing-the-intel-distribution-for-python-and-intel-performance-libraries-with-pip-and

**Comment by stonebig** [comment]
Yes you can, no I won't. For these things, the safe source is cgohlke. I don't expect a big difference between intel direct and cgohlke "MKL" ones, but you can benchmark.

**Comment by jxrossel** [comment]
Ok, thanks for the feedback!
