### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Code4SAFrankie** [winpython/winpython#723]
nxviz version: 0.6.0
    Python version: 3.6.6
    Operating System: Windows 10

Description

from nxviz import MatrixPlot

Running example code from 2-networkx-basics-instructor.ipynb

What I Did

from nxviz import MatrixPlot

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

from nxviz import MatrixPlot

ImportError Traceback (most recent call last)
in ()
----> 1 from nxviz import MatrixPlot
2
3 m = MatrixPlot(G)
4 m.draw()
5 plt.show()

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\nxviz_init_.py in ()
----> 1 from nxviz.plots import ArcPlot, CircosPlot, MatrixPlot, GeoPlot # NOQA
2
3 version = "0.6.0"

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\nxviz\plots.py in ()
15 text_alignment)
16 from .polcart import to_degrees
---> 17 from .utils import (cmaps, infer_data_type, is_data_diverging, items_in_groups,
18 n_group_colorpallet, num_discrete_groups, to_pandas_edges,
19 to_pandas_nodes)

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\nxviz\utils.py in ()
2
3 import pandas as pd
----> 4 import seaborn as sns
5 from matplotlib.colors import ListedColormap
6 from palettable.colorbrewer import diverging, qualitative, sequential

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn_init_.py in ()
4
5 # Import seaborn objects
----> 6 from .rcmod import *
7 from .utils import *
8 from .palettes import *

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\rcmod.py in ()
3 import functools
4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
6
7

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\palettes.py in ()
10 from .external.six.moves import range
11
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
13 from .colors import xkcd_rgb, crayons
14

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\utils.py in ()
5
6 import numpy as np
----> 7 from scipy import stats
8 import pandas as pd
9 import matplotlib as mpl

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\scipy\stats_init_.py in ()
343 from future import division, print_function, absolute_import
344
--> 345 from .stats import *
346 from .distributions import *
347 from .morestats import *

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\scipy\stats\stats.py in ()
167 from scipy._lib.six import callable, string_types
168 from scipy._lib._version import NumpyVersion
--> 169 import scipy.special as special
170 import scipy.linalg as linalg
171 from . import distributions

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\scipy\special_init_.py in ()
638 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
639
--> 640 from ._ufuncs import *
641
642 from .basic import *

ImportError: DLL load failed: The specified module could not be found.

**Comment by stonebig** [comment]
It seems similar to this https://github.com/conda/conda/issues/7720
You may try the following:
- download from https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy
   -  either numpy‑1.15.4+mkl‑cp36‑cp36m‑win_amd64.whl
   -  or  numpy‑1.16.2+mkl‑cp36‑cp36m‑win_amd64.whl
- let suppose you placed it in d:\toto\mkl‑cp36‑cp36m‑win_amd64.whl
- launch "WinPython Command Prompt"
- type "pip uninstall numpy -y"
- type "pip install d:\toto\mkl‑cp36‑cp36m‑win_amd64.whl", and retry.

**Comment by stonebig** [comment]
I can't reproduce.... did you do any sort  of update of your WinPython64-3.6.6.2Qt5.exe ?

**Comment by stonebig** [comment]
ok, here is your likely problem:
- nxviz claims numpy-1.16.1 https://github.com/ericmjl/nxviz/blob/master/requirements.txt#L9
- WinPython64-3.6.6.2Qt5.exe wass shippeed with numpy-1.14.5 
- so "pip" just updated you to numpy-1.16.1 using the https://pypi.org/project/numpy/ version the doesn't include the Math Kernel Library of Intel, and so you lost your MKL (that is included in cgohlke numpy-1.15.4, so removed with it)

... so solution is what I suggested.

**Comment by stonebig** [comment]
new version will come with 1.16.2+mkl, so the full list of  "==" requirements of nxviz is a problem when you install it, see https://github.com/ericmjl/nxviz/blob/master/requirements.txt#L9

**Comment by stonebig** [comment]
I tried to explain the problem to nxviz maintainers. Until they adapt their practice (or not), you'll have to re-install numpy from  https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy each time the problem comes back

**Comment by stonebig** [comment]
workaround is I include a "==" free nxviz in Winpython. yet it's not a increasingly popular package... would it be able to display "dask" graphs ? current solution uesd per dask maintainer, graphviz,  is too big
