### ISSUE TITLE
bayesian_neural_network.ipynb deprecated in WinPython 3.6.8 (and probably others)

### ISSUE THREAD

**Issue by cweickhmann** [winpython/winpython#727]
**Problem**
In `notebooks/docs` the example workbook `bayesian_neural_network.ipynb` is deprecated and does not work with current packages anymore.

**Solution**
There's an updated example from August 2018 which is referenced in the following forum post:
https://discourse.pymc.io/t/advi-minibatch-is-deprecated/1833

The file should be available at: http://docs.pymc.io/notebooks/bayesian_neural_network_advi.html

**Comment by stonebig** [comment]
Hum, did  you check it runs better ?

**Comment by cweickhmann** [comment]
Mea culpa! I see what I did: Copied it from an older release (maybe 3.6.1 but maybe earlier).
Then that's never been a problem.

Thanks for the hint with Theano!
