### ISSUE TITLE
Shortcut to QtDesigner through pyqt5-tools not working

### ISSUE THREAD

**Issue by gclotault** [winpython/winpython#730]
In the script to launch QtDesigner through pyqt5 with pyqt5-tools, there is a typo in the script with a "-" instead of a "_" in the folder name.

Script :
`@echo off
call "%~dp0env_for_icons.bat"
cd/D "%WINPYWORKDIR%"
if "%QT_API%"=="pyqt5" (
    if exist "%WINPYDIR%\Lib\site-packages\pyqt5-tools\designer.exe" (
        "%WINPYDIR%\Lib\site-packages\pyqt5-tools\designer.exe" %*
    ) else (
        "%WINPYDIR%\Lib\site-packages\PyQt5\designer.exe" %*
    )
) else if exist "%WINPYDIR%\Lib\site-packages\pyqt4\designer.exe" (
    "%WINPYDIR%\Lib\site-packages\PyQt4\designer.exe" %*
) else (
    "%WINPYDIR%\Lib\site-packages\PySide2\designer.exe" %*
)`

Name of the folder in \Lib\site-packages\ 

![image](https://user-images.githubusercontent.com/22662515/54563308-20db2e00-49c9-11e9-9360-29849ff7bf25.png)

**Comment by stonebig** [comment]
Argh. Will patch for next release

**Comment by stonebig** [comment]
https://github.com/winpython/winpython/pull/731

**Comment by stonebig** [comment]
pyqt5-tools is included in coming Winpython64-3.8.6.0codb3.exe.
