### ISSUE TITLE
Qt Designer.exe and Qt Linguist.exe in WinPython installation directory do nothing

### ISSUE THREAD

**Issue by norweeg** [winpython/winpython#735]
Clicking on the Qt Designer and Linguist executables does nothing.  Even after manually installing pyqt5-tools per https://github.com/winpython/winpython/issues/502#issuecomment-378903424 (which I shouldn't have to do if Qt Designer and Qt Linquist are ostensibly installed out-of-box), the executables *still* do nothing.

installed winpython version: Winpython64-3.7.2.0

**Comment by stonebig** [comment]
Yes, it's no longer in pyqt5 wheel.  You have it within winpython "ps2" pyside2 version. Unfortunately spyder is not compatible with pyside2 at the moment

**Comment by norweeg** [comment]
@stonebig it just got moved to pyqt5-tools.  I used to be able to manually install pyqt5-tools with pip and then the exe files worked, but that is no longer the case.   I can install pyqt5-tools and launch them with the command prompt, though.  I'm wondering why pyqt5-tools isn't just added to the winpython package list and the shortcuts updated

**Comment by stonebig** [comment]
on the whole Qt stack thing:
- WinPython leans toward the PySide2, as supported per Qt Company,
- PyQt5 branch will be stopped when Spyder will become compatible, in 2020.

**Comment by PierreRaybaut** [comment]
Regarding your last comment on Qt stack:

- Is this roadmap still valid?
- Would it be interesting to support PyQt5 for a little longer?
- If so, it would be worth considering to ship pyqt5_tools (this would require also #881).

**Comment by stonebig** [comment]
both are back in Big Builds.
