### ISSUE TITLE
Suggestion on package list

### ISSUE THREAD

**Issue by RaymanNg** [winpython/winpython#741]
- Replace cx_Freeze with pyinstaller
It seems that [pyinstaller](https://github.com/pyinstaller/pyinstaller) has more active development than [cx_Freeze](https://github.com/anthony-tuininga/cx_Freeze). I have tried both to freeze a simple PyQt5 application, cx_Freeze gave me a folder larger than 200MB while pyinstaller gave 50MB around.

- Add a code formatter package in package list
Installing a code formatter like autopep8 has become a Must Do after I install WinPython, since a consistent code format is important for a Python project.

**Comment by stonebig** [comment]
And does it work also with pyside2 ?

**Comment by RaymanNg** [comment]
I did not test with PySide2 because I only installed the PyQt version WinPython.

But after a quick issues search I think both of them have problem with PySide2. You can check these two issues:
https://github.com/pyinstaller/pyinstaller/issues/4177#issue-433972801
https://github.com/anthony-tuininga/cx_Freeze/issues/256#issuecomment-392704194

Personally, I think pyinstaller is more preferable than cx_Freeze since it has better support for PyQt.

BTW, what is your opinion about adding a code formatter package like autopep8 in package list?

**Comment by stonebig** [comment]
Cx_freeze is the initial year 2009 choice of Winpython creator. 
Pyside2 support is the unit of measure for this kind of package

Autopep8 I will have a look

**Comment by stonebig** [comment]
done
