### ISSUE TITLE
Spyder 4 in beta 3 crashes when creating new project

### ISSUE THREAD

**Issue by tstreibl** [winpython/winpython#761]
Just for info with little expectation for help. This problem has already been reported to spyder team but won't be fixed until Anaconda distribution runs into it.

See https://github.com/spyder-ide/spyder/issues/9841 (closed)

**Comment by stonebig** [comment]
Hum, ok, but does Spyder-3.3.5 works for you ? 
WinPython ships with Spyder-3 because Spyder team didn't want to support Spyder-4 until it's out of beta, with an apparent good reason.

**Comment by tstreibl** [comment]
Yes, certainly Sypder 3 is sufficient. Thank for the explanation.
I totally understand that the Spyder team can't do trouble shooting only because of version differences.
It's only sad because Spyder-4 beta 3 already seams to run quite well except this (for me very important and very basic) "new project" feature which for a non expert just look like a bunch of settings. The progress in the new features is obvious so since my live does not depend on spyder this beta is already a big tempation.

**Comment by stonebig** [comment]
You can downgrade PyQt5 and pyqtwebengine,  and everything shall work to your liking
