### ISSUE TITLE
Beta build for FlavorJulia to help resolve OpenBLAS issues

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#77]
Please create a beta build for FlavorJulia to help resolve OpenBLAS issues.  Build Julia like WinPython-64bit-3.4.3.2FlavorJulia, except:
a) add MAX_STACK_ALLOC=2048 to the make options for OpenBLAS, and
b) use the develop branch of OpenBLAS

This build will have these benefits:
1) Potentially fixes this bug in WinPython: https://github.com/xianyi/OpenBLAS/issues/532
2) Supports me testing this fix: https://github.com/xianyi/OpenBLAS/issues/530
3) Provides an improved OpenBLAS to be used in WinPython 2015-04

By the way, please keep MKL BLAS for NumPy and SciPy in the near future, as OpenBLAS currently has a number of performance problems compared to MKL BLAS.

**Comment by stonebig** [comment]
If you are speaking of the OpenBlas as implemented by Julia, it's a Julia's team question.
I can / you can only try:
- to open julia console,
- to refresh packages (and hopefully OpenBlas of julia) by 
 `Pkg.update()`

I don't know how you can introduce a beta OpenBlas in Julia for windows

**Comment by stonebig** [comment]
Besides that:
- Julia 0.3.x had some performance weak points, that may be resolved in Julia 0.4,
- maybe Julia team won't put a OpenBlas beta in anything else than Julia0.4dev,
- your performance issue seems in a "pure" Julia environnement.

==> Wouldn't it be simpler:
- to ask julia team if they can put the OpenBlas beta on their Julia0.4 repos,
- install a julia0.4dev directly downloaded from julialang.org to get this beta and do the performance test you need ?

**Comment by stonebig** [comment]
(and the download count of FlavorJulia is disappointing, so I think I won't do another one before Julia 0.4beta3)

**Comment by hiccup7** [comment]
In the Julia console, execute `Pkg.status()`.  Notice that there is no separate package for OpenBLAS or BLAS.  Doesn't this mean that Julia must be rebuilt from source in order to update OpenBLAS?

Do you build Julia using the Windows Self-Extracting Archive (.exe) from here?
http://julialang.org/downloads/

My performance issues are indeed in a "pure" Julia environment, but my code calls Python modules too.  So WinPython is a great environment to provide a happy marriage of Julia and Python.

**Comment by stonebig** [comment]
Well, you're right. Eating my own dog food, I don't see Julia fetching refreshed DLLs.

**Comment by stonebig** [comment]
and maybe:
````
using WinRPM
WinRPM.update()
````

**Comment by stonebig** [comment]
I see Julia team picked up your request: https://github.com/JuliaLang/julia/issues/10780

**Comment by hiccup7** [comment]
@stonebig , So far, I see my choices are to wait for Julia v0.4 release or to build Julia from source.

When you build WinPython FlavorJulia, do you build Julia using the Windows Self-Extracting Archive (.exe) from here?
http://julialang.org/downloads/

**Comment by stonebig** [comment]
Yes, I do roughly the below procedure in an existing winpython (without julia, or with settings\.julia and tools\julia removed):
http://nbviewer.ipython.org/github/winpython/winpython_afterdoc/blob/master/examples/installing_julia_and_ijulia.ipynb

then, replace .settings\ipython\kernels\julia\kernl.json by this:
````
{
"argv": [
"[WINPYDIR]\\..\\tools\\julia\\bin\\julia",
"-i",
"-F",
"[WINPYDIR]\\..\\settings\\.julia\\v0.3\\IJulia\\src\\kernel.jl",
"{connection_file}"
],
"display_name": "Julia",
"language": "julia"
} 
````

**Comment by hiccup7** [comment]
Thanks for the details!
