### ISSUE TITLE
What is PS2?  (Documentation)

### ISSUE THREAD

**Issue by cowlinator** [winpython/winpython#771]
The download page at https://winpython.github.io/ , the `README.rst` here in this repo, and the info at https://github.com/winpython/winpython/releases all do not mention what `PS2` stands for.

Have you succeeded in making a version of Python that runs on Windows that runs on a Playstation 2?

**Comment by stonebig** [comment]
Oups sorry ! Ps2 stands for Winpython with Pyside2 instead of PyQt5.

A playstation ps2 may have some hope in a micropython port like https://github.com/astrelsky/ps2-upython

**Comment by cowlinator** [comment]
@stonebig , thanks for answering my question.

But the purpose of this issue was not just to get my question answered, it was to ask you to include this information in the documentation.

**Comment by benkinooby** [comment]
+1 for https://github.com/winpython/winpython/issues/771#issuecomment-531410165

I just spent some time on trying to figure out what "Ps2" may stand for.
Dito for "WinPython 3.7.4.1cod-64bit" <- what does cod stand for?

A simple one-liner at https://winpython.github.io/#releases will be very helpful.

Thank you so much for running this project!

**Comment by Metallicow** [comment]
LOL I didn't even know micropython had stuff for Playstation2...
I guess the OP is modding on a playstation haha.

**Comment by stonebig** [comment]
It's rumored that Playstation 5 will be compatible all the way down to PS1, so your chances of running MicroPython on a Playstation just increased a bit.

**Comment by cowlinator** [comment]
Nope, I'm not modding anything.  And that sounds like an impossible rumor to me.
