### ISSUE TITLE
Guidata & PyQt5 : ModuleNotFoundError  'No module named 'sip'

### ISSUE THREAD

**Issue by keluc** [winpython/winpython#774]
When running example scripts from guidata one will get this ModuleNotFoundError since  in  "guidata\qt\__init__.py" the default behaviour is to fall back on 'PyQt4'  after which the module 'sip' is imported 

```
os.environ.setdefault('QT_API', 'pyqt')
assert os.environ['QT_API'] in ('pyqt5', 'pyqt', 'pyside')

API = os.environ['QT_API']
API_NAME = {'pyqt5': 'PyQt5', 'pyqt': 'PyQt4', 'pyside': 'PySide'}[API]

if API == 'pyqt':
    # Spyder 2.3 is compatible with both #1 and #2 PyQt API,
    # but to avoid issues with IPython and other Qt plugins
    # we choose to support only API #2 for 2.4+
    import sip
    try:
```

and after some try/except's PyQt5 is imported.  

```
    except ImportError:
        # Trying PyQt5 before switching to PySide (at this point, PyQt4 may 
        # not be installed but PyQt5 or Pyside could still be if the QT_API 
        # environment variable hasn't been set-up)
        try:
            import PyQt5  # analysis:ignore
            API = os.environ['QT_API'] = 'pyqt5'
            API_NAME = 'PyQt5'
        except ImportError:
            API = os.environ['QT_API'] = 'pyside'
            API_NAME = 'PySide'
```

The sip module was removed in release 2019-01 but I see that "PyQt5_sip" was added. 
Therefore the 'import sip' statement doesn't work anymore (while "import PyQt5.sip" works)

Remark: workaround is to set the environment variable when using guidata
```
import os
os.environ['QT_API'] = 'pyqt5'
````

**Comment by stonebig** [comment]
well, I did a workaround guidata to work on Pyside2, but didn't dare placing it in the PyQt5 ones. maybe I should.

**Comment by PierreRaybaut** [comment]
This will be solved with #877

**Comment by stonebig** [comment]
ok, it is in next beta or rc.

**Comment by PierreRaybaut** [comment]
Ok, thanks 👍

**Comment by stonebig** [comment]
so glad to see you back, Pierre.

**Comment by PierreRaybaut** [comment]
Glad to see that you're still here!
