### ISSUE TITLE
Tab completion in numpy (base) not working

### ISSUE THREAD

**Issue by thomas-haslwanter** [winpython/winpython#778]
In the current WinPython release (3.7.4.0) the tab-completion in the base numpy package does not work, neither in the jupyter QtConsole, nor in the Jupyter Notebook.
For example, after

```
import numpy as np
from numpy import random
from scipy import signal

```
I get tab-completion after typing
```
signals.s+TAB
random.+TAB

```
But there is no tab-completion after e.g.
`np.ar+TAB`

PS: I just found out that an upgrade of numpy fixes the problem!

**Comment by stonebig** [comment]
new WinPython 2019-03 release is out
