### ISSUE TITLE
please add package scikit-plot

### ISSUE THREAD

**Issue by dearfad** [winpython/winpython#783]
scikit plot, An intuitive library to add plotting functionality to scikit-learn objects.
https://github.com/reiinakano/scikit-plot

**Comment by stonebig** [comment]
https://github.com/reiinakano/scikit-plot/issues/100

**Comment by dearfad** [comment]
...  sorry to hear that.

**Comment by stonebig** [comment]
rule of thumb : maintainance is 2x the effort of creation, so most packages die after 3 years.

**Comment by idomic** [comment]
@stonebig not always!
We've been working hard on [scikit-evaluation](https://github.com/ploomber/sklearn-evaluation) for more than 3 years.
Feel free to connect about it if it can bring you value for plotting.
