### ISSUE TITLE
fiona cannot be used because depends GDAL 2.X

### ISSUE THREAD

**Issue by qq2898** [winpython/winpython#786]
in recent new version winpython, GDAL has upgrade to 3.X , and with  Rasterio > 1.0.25 which also depends GDAL 3.X ,but fiona now has not support GDAL 3.X ,so if fiona intalled, it must install GDAL 2.X and rasterio < 1.0.25.

**Comment by stonebig** [comment]
fiona looks stick since April, if I follow the discussions on https://github.com/Toblerity/Fiona/issues/803

there is to consider if fiona is more critical than modern gdal-3, that is out since may 2019

**Comment by stonebig** [comment]
Hope is back https://github.com/Toblerity/Fiona/pull/804

**Comment by stonebig** [comment]
fiona-1.8.9 is now compatible with gdal 3.X
