### ISSUE TITLE
Will winpython  install packages with built in C++ for Linux

### ISSUE THREAD

**Issue by Sandy4321** [winpython/winpython#797]
1
anaconda has problems with installing packages with C++ code built in
2
According to
https://www.infoworld.com/article/3267976/12-pythons-for-every-programming-need.html
Also included is a C/C++ compiler, since many Windows machines don’t have one included, and many Python extensions require or can make use of it.

So winpython does not need additional installation for   Windows Compilers
https://wiki.python.org/moin/WindowsCompilers

Is it true ???

3
Will winpython  install packages with built in C++ for Linux
for example 
https://github.com/fingoldin/pycorels
just by 
pip install corels

Thanks

**Comment by stonebig** [comment]
till Python-3.4 (or Python-2.7) , WinPython was shipping with mingpwy https://github.com/winpython/winpython/blob/master/changelogs/WinPython-3.4.4.5.md

Since then, Microsoft eased the situation and released for free vstudio 2019 community , and the associated runtime. 

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Hope it helps

**Comment by stonebig** [comment]
as you may notice, the Windows Client Python geekWorld is small, let say 10 people, so mingwpy died, and relying/pushing on Microsoft Python squad  (4 people ?) is the only sustainable option.

**Comment by Sandy4321** [comment]
I see
So how to use 
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
With Win Python
I tried to use vc compiler with Anaconda but it does not work
Can you help get detailed instructions how to install vs compiler to make it work with WinPython

**Comment by stonebig** [comment]
stackoverflow will be your friend in your quest.  https://stackoverflow.com/questions/15803738/how-to-compile-code-with-visual-studio-using-makefile/26072546

also this ?  https://timcera.bitbucket.io/posts/appveyor_finally.html

maybe there is no simple solution to your problem.

**Comment by Sandy4321** [comment]
Great thanks
By way in any case what compiler is provided together with WinPython
At least windows C++ based python packages and cython can be compiled?

**Comment by stonebig** [comment]
till WinPython-3.4.4.5 you could compile on your own, as mingwpy was integrated.

**Comment by stonebig** [comment]
with WinPython-4.2 , I guess you will be able again to compile on your own, as the target may be something like WASM.
