### ISSUE TITLE
install by unziping zip vs installation by . exe?

### ISSUE THREAD

**Issue by Sandy4321** [winpython/winpython#799]
May you help understand what is difference to install by unziping zip vs installation by . exe?

**Comment by stonebig** [comment]
The ".exe" is an auto-extract 7-zip. So you van unzup it via the 7-zip programme you may have already installed on your pc

**Comment by stonebig** [comment]
a ".zip" file is about 20% bigger, so I won't do .zip file.
my recent try to go another direction then LZMA2 ended there  in Q1 2019 https://github.com/winpython/winpython/issues/709

let me know when something has changed

**Comment by stonebig** [comment]
when 7zip will support zstd, we may reconsider options of zstd over lzma2.

For now Zstd has pretty much removed every other technnology in "smalll to intermediate compression with speed" 
https://twitter.com/Cyan4973/status/1229205402094456832

**Comment by stonebig** [comment]
still no move from 7zip nor windows 11....

**Comment by firai** [comment]
Forks of 7-zip (https://github.com/M2Team/NanaZip and https://github.com/mcmilk/7-Zip-zstd) support Zstandard, but I'm not sure if they support producing exes with Zstandard. Given the [lack of response over at 7-zip's forum about Zstandard](https://sourceforge.net/p/sevenzip/discussion/45797/thread/a6e36b9dd9/) other than pointing out forks and alternatives, it's entirely possible (likely even) that Zstandard would never make it into 7-zip core.

**Comment by stonebig** [comment]
For ubiquitous "zstd archive" decompression, maybe an initiative could come from zstd project or Microsoft.

**Comment by stonebig** [comment]
giving up for now

**Comment by stonebig** [comment]
there is a change, since Windows 11 22H2 update of november, Windows 11 can open ".7z" archives...
so we can publish also "non-.exe" build, as latest windows 11 users can de-compress natively

**Comment by stonebig** [comment]
well, a bit niche for now 
![image](https://github.com/winpython/winpython/assets/4312421/3cd4b518-ade0-40ec-b274-3bdd2e20c822)

**Comment by stonebig** [comment]
Windows 11 22H2 users can just post-fix winpython.exe in winpython.exe.7z, and then the archive is visible
