### ISSUE TITLE
Is Py 2.7 and Py 3.x possible in a development package

### ISSUE THREAD

**Issue by Metallicow** [winpython/winpython#802]
I use python 2.7 and python 3.x for development with wxPython Phoenix.
Phoenix runs on python 2.7 or 3.x.
Do you have a build that does this and if not could one be setup to work that way since 2.7.18 will be the last release of Py 2.7?

On a normal windows 7 install you just double click on the python script or console/terminal and it will launch with the default python(2.7 in my case). If I want to run python 3, then usually I use the `py -3 myprogram.py` switch in terminal.

I understand that doing this requires both python builds to have their own packages installed in site-packages. And since this is possible under normal windows installs, I'm curious as if you have a WinPython build like this? If not it would be nice if one was available.

note: wx can also have multiple versions installed in site and switched if you mod the wx.pth file

**Comment by stonebig** [comment]
you install (sort of unzip) a legacy winpython-2.7 and a winpython-3  in two different "user" location of your PC and you should hav two separateed environment that way.

For example:
- install WinPython-64bit-2.7.13.1Zero.exe in d:\myDevPack\Python27
- install Winpython64-3.7.6.0dot.exe in d:\myDevPack\Python37

Click on the IDLE icon of each environment to launch the associated Python-2.7 or 3.7.

**Comment by Metallicow** [comment]
Umm ok. The python.exe in the `python-2.7.13` directory seems to work.
...So basically it appears I should be able to copy just the python-x.x.x directories out of the unzipped folders and should work for my purposes.

How is it you make a portable python anyhow? Do you compile python yourself or do you tweek some sort of settings files?

**Comment by stonebig** [comment]
there is no magic nor compilation:
- the scripts/env.bat is setting up the path before any WinPython icon you click on,
- the "make_winpython_movable.bat" is patching pip (preventively), and executables (curatively) "chebang line":
  - https://github.com/winpython/winpython/blob/master/winpython/wppm.py#L493..L541
  - https://github.com/winpython/winpython/blob/master/winpython/wppm.py#L383..L411

basically, a one liner.

**Comment by Metallicow** [comment]
I just need a bare bones portable python directories. I wasn't clicking on the winpython exe stuff. For example if I wanted to make a 2.7.17 until 2.7.18 comes out, what exactly is the difference in making it besides extracting it from the official python installer. Are the only files I should need are those 2 bat files.
All those are doing is patching shebang lines...? Im confused.

**Comment by stonebig** [comment]
to get **any** Python installation movable: 
- you patch the shebang lines for python.exe executable to be searched on the PATH variable.
- then you set your PATH variable correctly before callling a Python program.
