### ISSUE TITLE
Class built-in attribute dir fails

### ISSUE THREAD

**Issue by jeielefeld** [winpython/winpython#803]
I'm using winPython 3.7.4 with spider IDE
The following code will will result in an error:

s = 'abc'
len(dir(s))

TypeError: 'str' object is not callable

also

i = 123
len(dir(i))

TypeError: 'str' object is not callable

--

Is the built-in attribute __dir__() somehow converted to string?

I am doing the code exercise in the book 'Python in Easy Steps' 2nd edition pp120 and 121
item #6 (pp121) in the code fails with the same error or TypeError: 'str' object is not callable

as such i did two simple tests with very simple code listed at the begging of this letter.
They also failed.

Here is the code provided by the author: 
--
file: Bird.py
class Bird :

	'''A base class to define bird properties.'''

	count = 0

	def __init__( self , chat ) :

		self.sound = chat
		Bird.count += 1

	def talk( self ) :

		return self.sound
--
file: address.py
from Bird import *

chick = Bird( 'Cheep, cheep!' )
chick.age = '1 week'

print( '\nChick Says:' ,  chick.talk() )
print( 'Chick Age:' , chick.age )

chick.age = '2 weeks'
print( 'Chick Now:' , chick.age )

setattr( chick , 'age' , '3 weeks' )

print( '\nChick Attributes...' )
for attrib in dir( chick ) :                            # this where it fails
	if attrib[0] != '_' :
		print( attrib , ':' , getattr( chick , attrib ) )

delattr( chick , 'age' )
print( '\nChick age Attribute?' , hasattr( chick , 'age' ) )

--
JohnB

**Comment by jeielefeld** [comment]
Another way to use dir() attribute which also fails when using Spider IDE:
--

# -*- coding: utf-8 -*-
"""
Created on Thu Jan 16 17:24:21 2020

@author: 15082
"""

# file: dog.py

def bark(pet = 'A Dog'):
    print(pet,'Says WOOF!')
    
def lick(pet = 'A Dog'):
    print(pet,'Drinks water')
    
def nap(pet = 'A dog'):
    print(pet,'Sleeps in Sun')

---

# -*- coding: utf-8 -*-
"""
Created on Thu Jan 16 17:35:24 2020

@author: 15082
"""

# dog test

import dog

for i in dir(dog):
    print(i)

--
The results running the above code in Spider IDE is:

runfile('C:/WinPython/WPy64-3741/my-scripts/attribute100.py', wdir='C:/WinPython/WPy64-3741/my-scripts')
Reloaded modules: dog
Traceback (most recent call last):

  File "<ipython-input-244-da76f565aa43>", line 1, in <module>
    runfile('C:/WinPython/WPy64-3741/my-scripts/attribute100.py', wdir='C:/WinPython/WPy64-3741/my-scripts')

  File "C:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/WinPython/WPy64-3741/my-scripts/attribute100.py", line 12, in <module>
    for i in dir(dog):

TypeError: 'str' object is not callable

--
JohnB

**Comment by stonebig** [comment]
hum, it's not a WinPython problem, you have that problem everywhere, don't you ?
