### ISSUE TITLE
Q: Is Pystan included in distribution?

### ISSUE THREAD

**Issue by lefig** [winpython/winpython#804]
Hi there,

I have a previous version of excellent winpython and had problems installing Pystan for a separate project (FB prophet). 

With upgrading in mind - I see there is a mention of Pystan in some sources but would appreciate confirming whether it is included or possibly may be in the future.

Thanks!

**Comment by stonebig** [comment]
I tried because of fb  prophet, but it was not windows/vsc++ friendly enough, and I failed.

**Comment by lefig** [comment]
Likewise, I have followed all the detailed steps outlined on Pystan. Thanks for mentioning.

**Comment by stonebig** [comment]
refer to this https://github.com/winpython/winpython/issues/780
