### ISSUE TITLE
 how to run jupiter notebook pls

### ISSUE THREAD

**Issue by Sandy4321** [winpython/winpython#810]
how to run jupiter notebook pls
it is not working as in 
http://bluegalaxy.info/codewalk/2018/07/28/python-install-winpython-jupyter-notebook/

error is after double click 
![image](https://user-images.githubusercontent.com/11426119/75061907-aefc4600-54af-11ea-9282-51c8d861aa27.png)

'"E:\WINPYTHON_N1\WPy64-3741\python-3.7.4.amd64\scripts\jupyter-notebook.exe"' is not recognized as an internal or external command,
operable program or batch file.

E:\WINPYTHON_N1\WPy64-3741\notebooks>

**Comment by stonebig** [comment]
The versions that are >= 300 Mo download size have Jupyter. For example:
- Winpython64-3.7.6.0.exe
- Winpython64-3.7.6.0dot.exe
