### ISSUE TITLE
Winpython64-3.7.6.0.exe: spyder takes about 8% CPU usage on Windows 7

### ISSUE THREAD

**Issue by asmwarrior** [winpython/winpython#816]
Hi, I see that spyder in Winpython64-3.7.6.0.exe takes about 8% of cpu when in Idle.

I see some one reported a similar issue in spyder's issus here, and I add a comment there. (see [my comment in spyder's issue](https://github.com/spyder-ide/spyder/issues/10585#issuecomment-598552832)

Since I'm not sure whether it is a spyder issue or Winpython issue, I think I have to report it here.

I just tried an old version of Winpython, which is WinPython-64bit-3.5.3.1Qt5, and I don't see the spyder there eat much cpu time, I see it is 0% in Idle.

Any ideas?

**Comment by stonebig** [comment]
No. maybe the switch from Qt4 to Qt5.

**Comment by stonebig** [comment]
try Pyzo, IDLE or vscod if it's a problem.

**Comment by asmwarrior** [comment]
Hi, thanks for the reply.
Do you know what is the latest version of WinPython which still use the QT4 for the spyder?
With spyder, I have good debug experience, I have just used the Pyzo, I think see much debug feature support.

**Comment by stonebig** [comment]
Look in the changelog directory, there is the list of provided packages per version

**Comment by asmwarrior** [comment]
> I just tried an old version of Winpython, which is WinPython-64bit-3.5.3.1Qt5, and I don't see the spyder there eat much cpu time, I see it is 0% in Idle.

I just check this old version, and it does use the pyqt5(5.9.2), spyder 3.2.6, which works OK. So, it is not the pyqt5 and pyqt4's difference.

**Comment by stonebig** [comment]
On my old PC, Spyder starts and run 30% during maybe 30 seconds, then calm down to zero.
The initial noisy start shall be attributed to "jedi", I think, that build/re-build it's dictionnary

**Comment by asmwarrior** [comment]
> 
> 
> On my old PC, Spyder starts and run 30% during maybe 30 seconds, then calm down to zero.
> The initial noisy start shall be attributed to "jedi", I think, that build/re-build its dictionnary

Thanks for the test.

But my symptom is not the same as yours. I even install the Winpython64-3.8.1.0dot.exe, and manually install spyder(which is 4.0.1) in the command line, and the result is the same bad issue, and a process always eat 8% cpu.

**Comment by stonebig** [comment]
Spyder-4.0.x is another problem, on windows.

**Comment by stonebig** [comment]
Spyder-4.1.0 on latest builds takes ... 0% . you may have a problem

**Comment by asmwarrior** [comment]
> 
> 
> Spyder-4.1.0 on latest build takes ... 0%, on Windows 10.
 I will check it.
Do you mean I have to install the latest winpython, such as the ones in top of the page https://winpython.github.io/, and then manually upgrade the spyder to 4.1.0?

I'm in Windows 7 64bit.

**Comment by asmwarrior** [comment]
Some good news, I just installed the Winpython64-3.7.6.0.exe in another 64bit Windows 7. When starting the spyder, it first use 25% of the cpu for about several seconds(maybe 20 or 30 seconds), and then it fall down to 0%. 

But I'm not sure why my original Windows 7 system has such issue.

Is it possible that winpython wrote some configuration to the system folder like c:/document and settings/ or similar folders? maybe, I can totally remove those folders and try again.

**Comment by asmwarrior** [comment]
Here is the more information when I see a 8% cpu spyder, I see from the dependency menu, it shows that:

```
IPython >=4.0     :  7.13.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.4.4 (OK)
qtconsole >=4.2.0 :  4.7.1 (OK)
rope >=0.9.4      :  0.16.0 (OK)
sphinx >=0.6.6    :  2.4.4 (OK)
sympy >=0.7.3     :  None (NOK)

```

So, I'm not sure why those modules are not OK?

I compared with a 0% cpu spyder in another Win7, I see all modules are OK.

**Comment by asmwarrior** [comment]
I try to import numpy in the IDLE (Python GUI).exe, and here is the result:

```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> 

It is the same error when I run the command in the WinPython Command Prompt.exe

So, is there any I can check whether those modules are missing?
```

**Comment by asmwarrior** [comment]
![another-pc](https://user-images.githubusercontent.com/561818/77041016-109eca00-69f4-11ea-89ed-4691c4c2ced2.png)
![one-pc](https://user-images.githubusercontent.com/561818/77041025-14cae780-69f4-11ea-8c09-d74f5123dc5f.png)

The above are the two screen shot of the two PCs, which is all win7 64bit, which install the same winpython.

Now, you can see in the winpython control panel. in one pc, the numpy and other spyder's dependency modules are missing, but in another pc, all modules are there.

What's the reason cause this difference?

**Comment by asmwarrior** [comment]
Sorry, some of my previous comments are not correct, I mistakenly compare the different winpython version. I will remove them.

**Comment by asmwarrior** [comment]
Hi, I think I found the problem.
Let me explain what causes this problem.

I see some spyder related issue here:  [Spyder won't start on Windows 7 · Issue #3710 · spyder-ide/spyder](https://github.com/spyder-ide/spyder/issues/3710) and [Crash on start because of problems with the PyQt 5.7 wheels · Issue #3520 · spyder-ide/spyder](https://github.com/spyder-ide/spyder/issues/3520), it refer to some video driver issue.

While in my first Win7 notebook, I have two video drivers: one is the Intel integrated video driver, and the other is the NVIDIA video driver. By default, the spyder use the Intel's driver. This cause the problem.

Now, I can change the configure to let all the applications to use the NVIDIA video driver. And then start the spyder again, I don't see the 8% cpu problem now.

As a conclusion, the Intel's driver is not compatible with QT5(pyqt 5.x), which cause the 8% cpu issue.

**Comment by stonebig** [comment]
Thank you for the auto-inquiry and solution reporting.

**Comment by asmwarrior** [comment]
Hi, never mind, I think Winpython is great! Thanks for your work!

Here are some extra good news.

Today, I just upgrade my Intel HD graphics video driver on my Win7 from version 21.20.16.4508 to 21.20.16.5103, and I just tested again. Now spyder works 0% cpu when Idle.  Which means the  Intel's driver 21.20.16.5103 is now compatible with QT5(pyqt 5.x).
