### ISSUE TITLE
getting theano working out of the box with mingwpy (on python3.4, then friends)

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#82]
Steps:
- [x] include a theano wheel,
- [x] auto-create `theano-cache.bat` , `theano-nose.bat`, `theano-test.bat`
- [x] passing the basic test
- [x] integrate it back in default build
- [x] include a theano test in winpython-checker
- [x] lasagne wheel (may be square, we'll see)
- [x] add .theanorc for [blas] ldflags = -lopenblaspy

**Comment by hiccup7** [comment]
OpenBLAS v0.2.14 is several times slower than MKL BLAS on use cases important to Theano users.  The OpenBLAS team has committed some changes, but has not yet been able to resolve bugs.  Since WinPython already uses MKL BLAS in NumPy+MKL, could WinPython use MKL BLAS with Theano?

**Comment by stonebig** [comment]
MKL is not free, Theano can only use MKL via the numpy dll compiled by Christoph Gohlke.

**Comment by hiccup7** [comment]
I agree.  Would the Theano team need to change their code to support this?  Or can you just change WinPython build options to make Theano use MKL in the NumPy DLL?

**Comment by stonebig** [comment]
That is rather questions for Theano team.

**Comment by carlkl** [comment]
I guess you need VisualC and the Intel Fortran compiler to use MKL from Theano.
Which use cases are several times slower compared to MKL? Is this true for the latest development version?

**Comment by hiccup7** [comment]
See https://github.com/xianyi/OpenBLAS/issues
I tested #530 & #532 on the latest develop branch, and they are still several times slower compared to MKL.

**Comment by stonebig** [comment]
Until I can get Theano working with 'basic' mingwpy, these are just theorical issues.

For the moment theano documentation is written for Winpython+TDM_GCC, and I don't know really know how to make it work with mingwpy.

**Comment by stonebig** [comment]
Could this be the problem ?
http://stackoverflow.com/questions/4070015/undefined-reference-when-linking-c-code-in-linux

````
The functions open, read, write, close, etc. have underscores in front of their names on Windows, but they do not on Linux
````

**Comment by stonebig** [comment]
seeeing this:
https://github.com/Theano/Theano/issues/2733

**Comment by stonebig** [comment]
@hiccup7 
I now understand your GEMM concern:
http://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/

**Comment by carlkl** [comment]
theano is working with plain python + mingwpy + openblas when using the openblas compiled numpy. In this case theano is using the blas information from numpy.distutils. checked with "python check_blas.py" in heano/misc. 
Obviously this fails unsing numpy-MKL as in WinPython. I have  to learn how to setup ${HOME}/.theanorc to make this work in WinPython.

**Comment by stonebig** [comment]
with plain python 3.4 ?

**Comment by carlkl** [comment]
Yes, plain python 3.4 (64bit) + numpy-openblas with exactly the same winpython/toools/mingw32/bin as winpython in the PATH works, but not winpython itself. I'll dig into this later on.

**Comment by stonebig** [comment]
An interesting README (with a benchmark section), on this frontpage.
https://github.com/aigamedev/scikit-neuralnetwork

**Comment by carlkl** [comment]
Theano works with mingwpy (aka tools\mingw32 for WinPython) IF AND ONLY IF libmsvcr100.a (libmsvcr90.a for python2.6-3.2) is copied from mingwpy into the <python>\libs folder. Feedback please

**Comment by stonebig** [comment]
checking

**Comment by carlkl** [comment]
I could find it in ...\x86_64-w64-mingw32\lib\ but I need to copy it into libs as well

**Comment by stonebig** [comment]
so my `make_cython_use_mingw.bat` used a  wrong path to look for `libmsvcr100.a`, and I didn't notice until theano.

**Comment by stonebig** [comment]
.bat corrected, now looking result

**Comment by stonebig** [comment]
corrected make_cython_use_mingw.bat:
````
@echo off
call %~dp0env.bat
@echo on
rem ******************
rem mingw part (supposing you install it in \tools\mingw32)
rem ******************
set tmp_mingwdirectory=mingw32
if not exist "%WINPYDIR%\..\tools\%tmp_mingwdirectory%\bin" goto mingw_end



set WINPYXX=%WINPYVER:~0,1%%WINPYVER:~2,1%

set WINPYARCH="WIN32"
if  "%WiNPYDIR:~-5%"=="amd64" set WINPYARCH="WIN-AMD64"

if %WINPYARCH%=="WIN32"     set BASEMINGW=i686-w64-mingw32
if %WINPYARCH%=="WIN-AMD64" set BASEMINGW=x86_64-w64-mingw32

set WINMINGW=lib\gcc\%BASEMINGW%

if not  %WINPYARCH%=="WIN-AMD64" goto no_distutil_patch
%~dp0Find_And_replace.vbs "%WINPYDIR%\Lib\distutils\cygwinccompiler.py" "-O -W" "-O -DMS_WIN64 -W"
:no_distutil_patch


rem Python 3.3+ case
set WINPYMSVCR=libmsvcr100.a
set WINPYSPEC=specs100

rem Python2.7 case
IF "%WINPYXX%"=="27" set WINPYMSVCR=libmsvcr90.a
IF "%WINPYXX%"=="27" set WINPYSPEC=specs90

cd %WINPYDIR%
copy  /Y ..\tools\mingw32\%BASEMINGW%\lib\%WINPYMSVCR%  libs\%WINPYMSVCR%

REM copy the right version of gcc
set dir482=..\tools\mingw32\%WINMINGW%\4.8.2\%WINPYSPEC%
if exist %dir482% copy  /Y %dir482% ..\tools\mingw32\%WINMINGW%\4.8.2\specs

set dir492=..\tools\mingw32\%WINMINGW%\4.9.2\%WINPYSPEC%
if exist %dir492% copy  /Y %dir492% ..\tools\mingw32\%WINMINGW%\4.9.2\specs

REM generate python.34 import file

..\tools\mingw32\bin\gendef.exe python%WINPYXX%.dll
..\tools\mingw32\bin\dlltool -D python%WINPYXX%.dll -d python%WINPYXX%.def -l libpython%WINPYXX%.dll.a
move /Y libpython%WINPYXX%.dll.a libs
del python%WINPYXX%.def

set pydistutils_cfg=%WINPYDIR%\..\settings\pydistutils.cfg

set tmp_blank=
echo [config]>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

echo [build]>>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

echo [build_ext]>>%pydistutils_cfg%
echo compiler=mingw32>>%pydistutils_cfg%

echo cython has been set to use mingw32
echo to remove this, remove file "%pydistutils_cfg%"

goto mingw_success

:mingw_end
echo "%WINPYDIR%\..\tools\%tmp_mingwdirectory%\bin" not found

:mingw_success
pause

````

**Comment by hiccup7** [comment]
Looking at https://github.com/xianyi/OpenBLAS/issues/478, it seems that @jeromerobert 's latest fix has not yet been committed to the @xianyi 's OpenBLAS develop branch yet.  Maybe still buggy.

I am waiting for the OpenBLAS v0.2.15 release before I compare GEMM() speed against MKL BLAS.  I use Julia to test OpenBLAS and WinPython to test MKL.  Since I found OpenBLAS several times slower than MKL on DDOT() and DGEMV(), I would not assume OpenBLAS is faster than MKL for GEMM().  I do support the OpenBLAS project, and I will continue to submit PRs of test results until I feel comfortable replacing MKL with OpenBLAS.

**Comment by stonebig** [comment]
for the Deep Learning package part, don't we need Theano (ok now) + pylearn2 + something ?

**Comment by carlkl** [comment]
@hiccup7, can you test this approach (WinPython and theano with mingwpy, OpenBLAS support) with a non trivial testcase on windows?

**Comment by hiccup7** [comment]
I depend heavily on the BLAS library, whether it is in Python+SciPy or Julia.  Julia does not provide binary distributions with MKL BLAS, so I am motivated to get OpenBLAS to be at least as fast as MKL BLAS.  I suspect that OpenBLAS will also be the future with Python+SciPy.  SciPy provides wrappers for BLAS functions.

I have no experience with Theano, and I think that it will not be useful for the problems I want to solve.

In the last 7 hours, there have been 3 new commits to the OpenBLAS develop branch.  I am very interested in testing these.  If there is a WinPython beta build using OpenBLAS for SciPy, I would be happy to test it.  If testing shows that it is slower than MKL, I hope WinPython will use MKL for the release version.

**Comment by stonebig** [comment]
I see OpenBlas has a benchmark directory but unfortunately I don't see basic test in their Travis CI builds (https://travis-ci.org/xianyi/OpenBLAS/jobs/59530841).

Maybe there is an external site that do these benchmarks, as it should  be a Key Indicator for them.

**Comment by hiccup7** [comment]
It is a big task to create a comprehensive test suite for OpenBLAS, especially when it comes to speed tests.  I think we can only expect Travis CI to do basic tests for functionality, not for speed.  Since OpenBLAS is developed by volunteers, it is up to us (the community) to do speed testing.

**Comment by carlkl** [comment]
Ensure correctness of the calculations is the first and most important step. This should be done with CI if possible. Working on OpenBLAS performance gaps could be performed step by step. GEMM performance is not far beyond MKL during my limited tests.

**Comment by carlkl** [comment]
Winpython is using numpy-MKL. numpy and scipy based on OpenBLAS is not released yet.

**Comment by hiccup7** [comment]
Do we have any documentation that the Theano only uses the GEMM() function in OpenBLAS?  Perhaps Theano also uses ?GEMV() and ?DOT() functions for multiplications with vectors, for higher speed than GEMM().  If so, Theano will exhibit the same problems with OpenBLAS as I have seen in my tests (until they are fixed on the develop branch).

**Comment by carlkl** [comment]
unfortunately the openblas latest develop https://github.com/xianyi/OpenBLAS/commit/406d9d64e97eb6bd83f7d9d55336272391e4126a together with a cherrypicked https://github.com/jeromerobert/OpenBLAS/commit/ee71dd3bf1480599e71c06064d8fd9d3f74f5a38 patch doesn't solved the gemv performance issue https://github.com/xianyi/OpenBLAS/issues/532 yet. The library was build with MAX_STACK_ALLOC=2048.

**Comment by stonebig** [comment]
````
Starting training...
Epoch 1 of 500 took 18.937s
  training loss:		1.319942
  validation loss:		0.448809
  validation accuracy:		88.25 %%
Epoch 2 of 500 took 22.362s
  training loss:		0.579317
  validation loss:		0.324674
  validation accuracy:		90.72 %%
Epoch 3 of 500 took 18.309s
  training loss:		0.460603
  validation loss:		0.276274
  validation accuracy:		91.94 %%
````

**Comment by stonebig** [comment]
build2 seems to work

**Comment by hiccup7** [comment]
@carlkl , thank you for performance testing OpenBLAS' develop branch and reporting your results to the team.
