### ISSUE TITLE
Issue to launch QT Console/Spyder/WinPython Control .... WPy64-3760

### ISSUE THREAD

**Issue by Christo59Dev** [winpython/winpython#822]
Hello, 

I have downloaded the WinPython v3.7.6.0 and the "normal" package where Ishould be able to use the software right out of the box.

![Capture](https://user-images.githubusercontent.com/62807178/77829553-09c63480-7123-11ea-9580-3ff698c88fbb.PNG)

However, it seems that everything requiring GUI, does not start, and QT Console come-up with an error I set in the attachment.
![Capture1](https://user-images.githubusercontent.com/62807178/77829573-25c9d600-7123-11ea-82b1-e7b57a48263b.PNG)

I have read similar issues but it was because they downloaded version 0 that requires installing PyQt5.  Am I in the same case? Is WinPython 100% percent isolated?

The only application that runs fine though I did not test deeply is Jupyter.
My OS is Windows10-Pro 64bits.
The package has been unzipped on the desktop.

Thank you for your support.

Christopher.

**Comment by stonebig** [comment]
Hi Christopher, 

That's odd: nobody complained on such a thing last 3 month , but I may have missed an update.

May I suggest:
- you start "Winpython command prompt" and launch "pip install Qtconsole --upgrade",
- if it doesn't resolve the issue, retry on the latest version Winpython64-3.7.7.0.exe ? (I changed the download button)

**Comment by stonebig** [comment]
if the first suggestion works, it may be that Qtconsole-4.6 was not friendly with Qt-5.14.

**Comment by Christo59Dev** [comment]
Hello, 

**So for the first solution**: It did not work.
![Capture](https://user-images.githubusercontent.com/62807178/77831163-be655380-712d-11ea-94ce-1a2f1077e42d.PNG)

![Capture1](https://user-images.githubusercontent.com/62807178/77831167-cc1ad900-712d-11ea-82f5-d778dac2f031.PNG)

I am downloading the v3.7.7.0.

Christopher.

Christopher

**Comment by Christo59Dev** [comment]
Hello, 

I have the same issue with version Winpython64-3.7.7.0.exe.
I do not understand what's wrong really ...

![Capture2](https://user-images.githubusercontent.com/62807178/77833483-f6749280-713d-11ea-9b3d-e64b1443b646.PNG)

Not sure it can help, is the fact to have installed Python 3.5/3.6/3.7/3.8 from the Python website can impact the operation of some application?
Is the management of 1 path could be the cause?

I read some articles but this is not really clear, some people solve their issues in updating what you told me, some others it absolutely changes nothing like me.

Christopher.

**Comment by Christo59Dev** [comment]
Hello, 

I continue my investigation and I found a weird behavior.
Be patient to read as it is a bit long, I am not a professional of Python (I am training hard to learn)

1. As I have got an issue in launching the application with PySide (that is not supported anymore), I have started to investigate the __init__ file from the module pyqt.

![Capture2](https://user-images.githubusercontent.com/62807178/77835589-7b67a800-714e-11ea-86f4-e16bd599e769.PNG)

In the python file "WPy64-3760\python-3.7.6.amd64\Lib\site-packages\qtpy" of the unzipped folder, it is written that we can choose between 4 bindings:
- pyqt5 (automatically choosed by default == > line of code `os.environ.setdefault(QT_API, 'pyqt5')`
- pyside2
- pyside
- pyqt4 | pyqt

### Question 1:
The module PyQt5 is well in the "site-packages" folder, why does the script do not select it at first? 
The folder exist in your packages, there are absolutely no reason it looks something else.

### Question 2:
Then I set-up my environment variable QT_API = pyqt5 (see picture below):

![Capture3](https://user-images.githubusercontent.com/62807178/77835620-dd281200-714e-11ea-998d-cb69fbf9cdf2.PNG)

Then I made home make script to make sure it does really read my variable QT_API (and it really does, thr proof in pictures):

![picture5](https://user-images.githubusercontent.com/62807178/77835643-0cd71a00-714f-11ea-97e0-85040a7ba633.PNG)

If we look at the script, the program should not raise this error as it could not reach that code! 
Look in the file:

[__init__.txt](https://github.com/winpython/winpython/files/4398022/__init__.txt)

What makes the program to think we want to use PySide?

I hope my explanation are clear enough.
If not, I am available to re-explain.

Thank you for your support.

Christopher

**Comment by stonebig** [comment]
Pyside2 doesn't use cip, so you may have a chance. to use it you may have to remove PyQt5.
```
pip uninstall PyQt5 --y
pip install Pyside2
```
or try https://sourceforge.net/projects/winpython/files/WinPython_3.7/3.7.6.0/Winpython64-3.7.6.0ps2.exe/download

**Comment by Christo59Dev** [comment]
Hello, 

I have tested in the WinPython command prompt the following code:
```
pip uninstall PyQt5 --y
pip install Pyside2
```
and it finally works. (believe it or not, I am happy like a little kid!)

Spyder, QtConsole, Pyzo & WinPython control panel all seem to work properly.

For QtDesigner and Qt Linguist, you need to go in the package PySide2 to open them. 
Those by default in the parent folder seem to not be valid anymore.

Hope this can help other users.

 Christopher.

**Comment by stonebig** [comment]
hum, Pyside2 includes everything , but you may have the "other" QtDesigner and QtLinguist, that you have installed aside for PyQt5. 
so, try to uninstall it, if you indeed installed a side package for  them (PyQt5Designer, or what)
`pip uninstall   PyQt5Designer --y`
