### ISSUE TITLE
Python .NET process exits with 120 status code 

### ISSUE THREAD

**Issue by mahakjain314** [winpython/winpython#854]
I am trying to run a Python executable in a .NET process. The process exits with 120 status code.

Python Source - https://github.com/winpython/winpython/releases/download/2.2.20191022/Winpython64-3.8.0.0cod.exe

.NET Framework - 4.5

Script: Simple Hello World Program 
print ("Hello World!")

Program Code:

    class Program
    {
        static Process process;
        static bool OutputDataProcessingComplete = false;
        static bool ErrorDataProcessingComplete = false;

        static void Main(string[] args)
        {
            string executablePath = @"C:\WPy64-3800\python-3.8.0.amd64\python.exe";
            string fileName = @"C:\scripts\hellopy3.py";
            StartProcess(executablePath, fileName, args);
        }

        public static void StartProcess(string executablePath, string filePath, IList<string> arguments)
        {
            ProcessStartInfo startInfo = new ProcessStartInfo
            {
                WindowStyle = ProcessWindowStyle.Hidden,
                UseShellExecute = false,
                FileName = executablePath,
                Arguments = GetProcessArguments(filePath, arguments),
                RedirectStandardOutput = true,
                RedirectStandardError = true
            };

            process = new Process();
            process.StartInfo = startInfo;
            process.EnableRaisingEvents = true;

            process.OutputDataReceived += JobProcessOutputDataReceivedEventHandler;
            process.ErrorDataReceived += JobProcessErrorDataReceivedEventHandler;
            process.Exited += JobProcessExitedEventHandler;

            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
            process.WaitForExit();

            Console.WriteLine("Process Completed!");
        }

        private static void JobProcessExitedEventHandler(object sender, EventArgs e)
        {
            var totalWaitMilliseconds = 0;
            const int CoolDownPeriodMilliseconds = 200;
            const int TimeoutMilliseconds = 1000 * 60 * 3;
            while (OutputDataProcessingComplete != true || ErrorDataProcessingComplete != true)
            {
                Thread.Sleep(CoolDownPeriodMilliseconds);
                totalWaitMilliseconds += CoolDownPeriodMilliseconds;
                if (totalWaitMilliseconds > TimeoutMilliseconds)
                {
                    throw new TimeoutException(string.Format("Stream processing timeout reached."));
                }
            }

            Console.WriteLine("ExitCode: " + process.ExitCode);
        }

        private static void JobProcessErrorDataReceivedEventHandler(object sender, DataReceivedEventArgs e)
        {
            if (e == null)
            {
                return;
            }

            if (e.Data != null)
            {
                Console.WriteLine("Error: " + e.Data);
            }
            else
            {
                ErrorDataProcessingComplete = true;
                Console.WriteLine("ProcessBased JobError Output Processing Complete");
            }
        }

        private static void JobProcessOutputDataReceivedEventHandler(object sender, DataReceivedEventArgs e)
        {
            if (e == null)
            {
                return;
            }

            if (e.Data != null)
            {
                Console.WriteLine("Output: " + e.Data);
            }
            else
            {
                OutputDataProcessingComplete = true;
                Console.WriteLine("Standard Output Processing completed");
            }
        }

        public static string GetProcessArguments(string filePath, IList<string> arguments)
        {
            ///
        }
    }

Behaviour Observed: The Python executable is returning 120 status code. e.Data is always coming as null.

Few helpful links -
120 status code for Python - https://bugs.python.org/issue29130
.NET Process - https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netframework-4.5

Any help is appreciated!

**Comment by stonebig** [comment]
there is a new OFFICIAL version of pythonnet at last, you may re-try with pythonnet-2.5.1.

**Comment by mahakjain314** [comment]
I was able to resolve the issue after setting the environment variable PYTHONLEGACYWINDOWSSTDIO=1
