### ISSUE TITLE
lost with understanding different versions in 2020-02 release

### ISSUE THREAD

**Issue by tstreibl** [winpython/winpython#856]
Hi,

I'm compleatly lost with the different version in this release - sorry, might be too stupid. 

- Readme talks about a "cod" branche. Didn't find any files with "cod" in the assets. 
- Is python 3.8.3 not yet ready for spyder? At least I couldn't find a Winpython64-3.8.3.0.exe in the assets. There's only a Winpython64-3.8.3.0dot.exe  which to my understanding is a minimalistic, stripped down version? At least in the last "2020-01" release there was a  Winpython64-3.8.2.0.exe.

A little legend explaining "cod", "dot", "ps2", "qt5" ... version might be helpful for beginners like me.

Your doing a great job with winpython! Thanks a lot for all this hard work!

**Comment by stonebig** [comment]
Spyder is in Winpython64-3.8.3.0.exe and Winpython64-3.8.3.0cod.exe

Version with "dot" do not contain anything but the basic WinPython infrastructure, and Python.

**Comment by tstreibl** [comment]
thanks - now the files became visible in "releases".
