### ISSUE TITLE
Add msvc_runtime package

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#863]
Please add the package from https://www.lfd.uci.edu/~gohlke/pythonlibs/#msvc_runtime

I tried it with WinPython64-3.7.7.1, and it added 4 DLLs that are not included in WinPython64-3.7.7.1.  Working well.
WinPython64-3.7.7.1 includes v14.25 DLLs, while the latest msvc_runtime package includes v14.26 DLLs.

Advantages I see:
- Users need not separately install vc_redist_x64.exe (out-of-the-box success!)
- Supports different DLL versions in different WinPython versions in case the newest DLL breaks an old WinPython version.
- The WinPython build process automatically checks for latest msvc_runtime package, while vc_redist_x64.exe version check is manual (which explains why the latest vc_redist_x64.exe from 21 March was overlooked).
- All MS DLLs from vc_redist_x64.exe are included -- even when new ones are added by MS.

**Comment by stonebig** [comment]
I think i will switch to this.

**Comment by stonebig** [comment]
done in https://github.com/winpython/winpython/pull/865 

maybe 25% of rusted legacy code removed.
