### ISSUE TITLE
why the exe with 'cod' larger than no?

### ISSUE THREAD

**Issue by qq2898** [winpython/winpython#864]
Winpython64-3.8.3.0cod.exe | 2020-05-23 | 658.4 MB

Winpython64-3.8.3.0.exe | 2020-05-23 | 728.6 MB

Why the  Winpython64-3.8.3.0cod.exe has a vscode more than the another one but it is smaller .....

**Comment by stonebig** [comment]
the cod version includes VScode+Python-VScode 
the non-code version includes Tensorflow and Torch.

... and apparently VScode+Python-VScode takes more space than Tensorflow+Torch.

**Comment by stonebig** [comment]
Qt stack, Numpy, Torch, Tensorflow, Nodejs, VScode are heavy-weights, and are shipping sometimes their own vendored big Chromium motor or MKL binary.

**Comment by stonebig** [comment]
Tensorflow is removed in next release, so you will "feel" things are back to normal with "cod" version being bigger.
