### ISSUE TITLE
Add the latest guiqwt release (v3.0.4)

### ISSUE THREAD

**Issue by PierreRaybaut** [winpython/winpython#878]
Following #877, guidata is fully functionnal with WinPython.
Given that guiqwt is available (and also fully functionnal) for Python 3.8, you might consider adding the [latest guiqwt](https://pypi.org/project/guiqwt/#files) release to WinPython.

**Comment by stonebig** [comment]
checking it works for Python-3.9, needs a cup of coffe

**Comment by stonebig** [comment]
ok, will be in next beta or rc.

**Comment by PierreRaybaut** [comment]
Sorry about that: just found a few bugs related to Python 3.8/NumPy 1.18.
Those are fixed in guiqwt v3.0.4, hence the new title and the issue reopening.

Thanks.

**Comment by stonebig** [comment]
Planning to ship with numpy-1.19, will it be ok ?

**Comment by PierreRaybaut** [comment]
Yes, thank you.

**Comment by stonebig** [comment]
done
