### ISSUE TITLE
Add the latest PythonQwt release (v0.6.2)

### ISSUE THREAD

**Issue by PierreRaybaut** [winpython/winpython#879]
Following #877 and #878, I suggest upgrading PythonQwt to the latest release: v0.6.2.

Successfully tested on:

    WinPython-32bit-2.7.6.4
    WinPython-64bit-2.7.6.4
    WinPython-64bit-3.4.4.3
    WinPython-64bit-3.4.4.3Qt5
    WPy64-3680
    WPy64-3771
    WPy64-3830

**Comment by stonebig** [comment]
done
