### ISSUE TITLE
'webroot secureanywhere' suspects winpython 2.7.5.3 of being PUA

### ISSUE THREAD

**Issue by sebix** [winpython/winpython#88]
Mark Davidson reported, that his anti virus program 'webroot secureanywhere, v8.0.8.7.6' on Win 7 gives an alert for `winpython-64bit-2.7.5.3`:

    Mon 2015-04-27 18:57:49.0900	Infection detected: c:\winpython-64bit-2.7.5.3\winpython control panel.exe [MD5: 3CB8CC6DDB9B73FC90F8ED4F3FF00E2A] [3/00080410] [Pua.Safe.Software]
    Mon 2015-04-27 18:57:50.0129	Begin passive write scan (1 file(s))
    Mon 2015-04-27 18:57:50.0652	End passive write scan (1 file(s))
    Mon 2015-04-27 18:59:06.0277	Infection detected: c:\winpython-64bit-2.7.5.3\winpython command prompt.exe [MD5: 125B4CC938464B87A4967AA7DEE9AD81] [3/00080C10] [Pua.Safe.Software]

PUA does mean *'Potentially unwanted Application'*, [Wikipedia](https://en.wikipedia.org/wiki/Malware#Grayware):
> Another term, PUP, which stands for Potentially Unwanted Program (or PUA Potentially Unwanted Application),[61] refers to applications that would be considered unwanted despite often having been downloaded by the user, possibly after failing to read a download agreement. PUPs include spyware, adware, fraudulent dialers. Many security products classify unauthorised key generators as grayware, although they frequently carry true malware in addition to their ostensible purpose.

How do we deal with this?

**Comment by stonebig** [comment]
Same procedure as here https://github.com/winpython/winpython.github.io/issues/18
