### ISSUE TITLE
WinPython 32 bit Spyder

### ISSUE THREAD

**Issue by cnsltnt51** [winpython/winpython#894]
Windows 10 Pro
WinPython32-3.8.5.0dot = Python 3.8 32bit only
Spyder.exe does not run.

**Comment by stonebig** [comment]
Windows 10 Pro and you try a 32bit Python ?

**Comment by cnsltnt51** [comment]
I use 32-bit to be able to move data into and out of MSAccess. Lot's of programs still use MSAccess 32bit.

**Comment by stonebig** [comment]
Click on winpython command prompt, then try:

Pip install spyder

**Comment by cnsltnt51** [comment]
Collecting spyder
  Downloading spyder-4.1.5-py3-none-any.whl (10.7 MB)
     |████████████████████████████████| 10.7 MB 3.2 MB/s
Collecting pyqt5<5.13; python_version >= "3"
  Downloading PyQt5-5.12.3-5.12.9-cp35.cp36.cp37.cp38-none-win32.whl (43.3 MB)
     |████████████████████████████████| 43.3 MB 6.8 MB/s
Collecting jedi==0.17.1
  Downloading jedi-0.17.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB ...
Collecting parso==0.7.0
  Downloading parso-0.7.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB ...
Collecting qtconsole>=4.6.0
  Downloading qtconsole-4.7.7-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB ...
Collecting paramiko>=2.4.0; platform_system == "Windows"
  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 6.4 MB/s
Collecting pyqtwebengine<5.13; python_version >= "3"
  Downloading PyQtWebEngine-5.12.1-5.12.9-cp35.cp36.cp37.cp38-none-win32.whl (41.5 MB)
     |████████████████████████████████| 41.5 MB 151 kB/s
Collecting cloudpickle>=0.5.0
  Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting pexpect>=4.4.0
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 2.9 MB/s
Collecting nbconvert>=4.0
  Downloading nbconvert-6.0.7-py3-none-any.whl (552 kB)
     |████████████████████████████████| 552 kB 6.8 MB/s
Collecting diff-match-patch>=20181111
  Downloading diff_match_patch-20200713-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 88 kB/s
Collecting qdarkstyle>=2.8
  Using cached QDarkStyle-2.8.1-py2.py3-none-any.whl (217 kB)
Collecting qtawesome>=0.5.7
  Downloading QtAwesome-1.0.1-py3-none-any.whl (863 kB)
     |████████████████████████████████| 863 kB ...
Collecting ipython>=4.0
  Downloading ipython-7.18.1-py3-none-any.whl (786 kB)
     |████████████████████████████████| 786 kB 6.4 MB/s
Collecting pickleshare>=0.4
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting numpydoc>=0.6.0
  Downloading numpydoc-1.1.0-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 2.1 MB/s
Collecting watchdog
  Downloading watchdog-0.10.3.tar.gz (94 kB)
     |████████████████████████████████| 94 kB ...
Collecting psutil>=5.3
  Downloading psutil-5.7.3-cp37-cp37m-win32.whl (238 kB)
     |████████████████████████████████| 238 kB ...
Collecting pylint>=1.0
  Downloading pylint-2.6.0-py3-none-any.whl (325 kB)
     |████████████████████████████████| 325 kB 6.4 MB/s
Collecting qtpy>=1.5.0
  Downloading QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB ...
Collecting atomicwrites>=1.2.0
  Downloading atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting spyder-kernels<1.10.0,>=1.9.4
  Downloading spyder_kernels-1.9.4-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 3.6 MB/s
Collecting python-language-server[all]<1.0.0,>=0.34.0
  Downloading python_language_server-0.35.1-py2.py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 3.2 MB/s
Collecting pygments>=2.0
  Downloading Pygments-2.7.2-py3-none-any.whl (948 kB)
     |████████████████████████████████| 948 kB ...
Collecting pyzmq>=17
  Downloading pyzmq-19.0.2-cp37-cp37m-win32.whl (895 kB)
     |████████████████████████████████| 895 kB ...
Collecting intervaltree
  Downloading intervaltree-3.1.0.tar.gz (32 kB)
Collecting keyring; sys_platform != "linux2"
  Downloading keyring-21.4.0-py3-none-any.whl (31 kB)
Collecting sphinx>=0.6.6
  Downloading Sphinx-3.2.1-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 6.4 MB/s
Requirement already satisfied: chardet>=2.0.0 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from spyder) (3.0.4)
Collecting PyQt5_sip<13,>=4.19.14
  Downloading PyQt5_sip-12.8.1-cp37-cp37m-win32.whl (50 kB)
     |████████████████████████████████| 50 kB ...
Collecting traitlets
  Downloading traitlets-5.0.5-py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB ...
Collecting jupyter-core
  Downloading jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 778 kB/s
Collecting jupyter-client>=4.1
  Downloading jupyter_client-6.1.7-py3-none-any.whl (108 kB)
     |████████████████████████████████| 108 kB ...
Collecting ipykernel>=4.1
  Downloading ipykernel-5.3.4-py3-none-any.whl (120 kB)
     |████████████████████████████████| 120 kB ...
Collecting ipython-genutils
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting pynacl>=1.0.1
  Downloading PyNaCl-1.4.0-cp37-cp37m-win32.whl (193 kB)
     |████████████████████████████████| 193 kB ...
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.0-cp36-abi3-win32.whl (27 kB)
Collecting cryptography>=2.5
  Downloading cryptography-3.2.1-cp37-cp37m-win32.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB ...
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting nbclient<0.6.0,>=0.5.0
  Downloading nbclient-0.5.1-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB ...
Collecting entrypoints>=0.2.2
  Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting nbformat>=4.4
  Downloading nbformat-5.0.8-py3-none-any.whl (172 kB)
     |████████████████████████████████| 172 kB 3.3 MB/s
Collecting bleach
  Downloading bleach-3.2.1-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB ...
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.4.3.tar.gz (16 kB)
Requirement already satisfied: jinja2>=2.4 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from nbconvert>=4.0->spyder) (2.11.2)
Collecting testpath
  Downloading testpath-0.4.4-py2.py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 6.8 MB/s
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting helpdev>=0.6.10
  Downloading helpdev-0.7.1-py3-none-any.whl (14 kB)
Requirement already satisfied: setuptools>=18.5 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from ipython>=4.0->spyder) (41.2.0)
Collecting decorator
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting colorama; sys_platform == "win32"
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.8-py3-none-any.whl (355 kB)
     |████████████████████████████████| 355 kB ...
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Processing c:\users\*******\appdata\local\pip\cache\wheels\0b\04\79\c3b0c3a0266a3cb4376da31e5bfe8bba0c489246968a68e843\pathtools-0.1.2-cp37-none-any.whl
Collecting toml>=0.7.1
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting mccabe<0.7,>=0.6
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting astroid<=2.5,>=2.4.0
  Downloading astroid-2.4.2-py3-none-any.whl (213 kB)
     |████████████████████████████████| 213 kB 6.8 MB/s
Collecting isort<6,>=4.2.5
  Downloading isort-5.6.4-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 4.5 MB/s
Collecting ujson>=3.0.0; python_version > "3"
  Downloading ujson-4.0.1.tar.gz (7.1 MB)
     |████████████████████████████████| 7.1 MB ...
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pluggy
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting python-jsonrpc-server>=0.4.0
  Downloading python_jsonrpc_server-0.4.0-py3-none-any.whl (8.9 kB)
Collecting autopep8; extra == "all"
  Downloading autopep8-1.5.4.tar.gz (121 kB)
     |████████████████████████████████| 121 kB ...
Collecting flake8>=3.8.0; extra == "all"
  Downloading flake8-3.8.4-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB ...
Collecting pycodestyle<2.7.0,>=2.6.0; extra == "all"
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 126 kB/s
Collecting pyflakes<2.3.0,>=2.2.0; extra == "all"
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 4.8 MB/s
Collecting rope>=0.10.5; extra == "all"
  Downloading rope-0.18.0.tar.gz (249 kB)
     |████████████████████████████████| 249 kB 6.4 MB/s
Collecting yapf; extra == "all"
  Downloading yapf-0.30.0-py2.py3-none-any.whl (190 kB)
     |████████████████████████████████| 190 kB 6.8 MB/s
Collecting pydocstyle>=2.0.0; extra == "all"
  Downloading pydocstyle-5.1.1-py3-none-any.whl (35 kB)
Collecting sortedcontainers<3.0,>=2.0
  Downloading sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Collecting pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32"
  Downloading pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting snowballstemmer>=1.1
  Downloading snowballstemmer-2.0.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 3.2 MB/s
Collecting sphinxcontrib-serializinghtml
  Downloading sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 4.2 MB/s
Collecting alabaster<0.8,>=0.7
  Downloading alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting sphinxcontrib-jsmath
  Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting imagesize
  Downloading imagesize-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting babel>=1.3
  Downloading Babel-2.8.0-py2.py3-none-any.whl (8.6 MB)
     |████████████████████████████████| 8.6 MB 6.8 MB/s
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 6.4 MB/s
Collecting sphinxcontrib-htmlhelp
  Downloading sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.6 MB/s
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB ...
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 1.7 MB/s
Collecting docutils>=0.12
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
     |████████████████████████████████| 548 kB ...
Requirement already satisfied: requests>=2.5.0 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from sphinx>=0.6.6->spyder) (2.22.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from jupyter-core->qtconsole>=4.6.0->spyder) (225)
Collecting tornado>=4.1
  Downloading tornado-6.0.4-cp37-cp37m-win32.whl (416 kB)
     |████████████████████████████████| 416 kB ...
Requirement already satisfied: python-dateutil>=2.1 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from jupyter-client>=4.1->qtconsole>=4.6.0->spyder) (2.8.0)
Requirement already satisfied: six in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from pynacl>=1.0.1->paramiko>=2.4.0; platform_system == "Windows"->spyder) (1.12.0)
Collecting cffi>=1.4.1
  Downloading cffi-1.14.3-cp37-cp37m-win32.whl (166 kB)
     |████████████████████████████████| 166 kB 6.4 MB/s
Collecting nest-asyncio
  Downloading nest_asyncio-1.4.2-py3-none-any.whl (5.3 kB)
Collecting async-generator
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 2.0 MB/s
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from jinja2>=2.4->nbconvert>=4.0->spyder) (1.1.1)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8"
  Downloading typed_ast-1.4.1-cp37-cp37m-win32.whl (135 kB)
     |████████████████████████████████| 135 kB 6.4 MB/s
Collecting lazy-object-proxy==1.4.*
  Downloading lazy_object_proxy-1.4.3-cp37-cp37m-win32.whl (18 kB)
Collecting wrapt~=1.11
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from packaging->sphinx>=0.6.6->spyder) (2.4.6)
Requirement already satisfied: pytz>=2015.7 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from babel>=1.3->sphinx>=0.6.6->spyder) (2019.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.5.0->sphinx>=0.6.6->spyder) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.5.0->sphinx>=0.6.6->spyder) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.5.0->sphinx>=0.6.6->spyder) (1.25.6)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB ...
Collecting attrs>=17.4.0
  Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB ...
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.17.3.tar.gz (106 kB)
     |████████████████████████████████| 106 kB ...
Building wheels for collected packages: watchdog, intervaltree, pandocfilters, ujson, autopep8, rope, wrapt, pyrsistent
  Building wheel for watchdog (setup.py) ... done
  Created wheel for watchdog: filename=watchdog-0.10.3-py3-none-any.whl size=73875 sha256=2d29afe21631aa40d6d83b897bd826aad4f9870956d6ed5f6802c5079374090f
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\27\21\35\9d1e531f9de5335147dbef07e9cc99d312525ba128a93d1225
  Building wheel for intervaltree (setup.py) ... done
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26106 sha256=9cd3f5f9d61155d4c815b529b5a40ff6c3ee6afea09a0597a700c59fc709c7a4
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\16\85\bd\1001cbb46dcfb71c2001cd7401c6fb250392f22a81ce3722f7
  Building wheel for pandocfilters (setup.py) ... done
  Created wheel for pandocfilters: filename=pandocfilters-1.4.3-py3-none-any.whl size=7997 sha256=55813364be3db1279bb2359ebcc9e093609143690ea769a9774e20538394eb7a
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\42\81\34\545dc2fbf0e9137811e901108d37fc04650e81d48f97078000
  Building wheel for ujson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\*******\appdata\local\programs\python\python37-32\python.exe' 'c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\*******\AppData\Local\Temp\tmptcadynlz'
       cwd: C:\Users\*******\AppData\Local\Temp\pip-install-hx4vkx5p\ujson
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for ujson
  Building wheel for autopep8 (setup.py) ... done
  Created wheel for autopep8: filename=autopep8-1.5.4-py2.py3-none-any.whl size=45292 sha256=33d7636008addf3b175efdd8472633523fad2af418e8fb9a1c125d57ce81eb80
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\2c\ad\e2\f5322a230aedd0091b75ec899404e3562d8bb4e7ba0f025cbd
  Building wheel for rope (setup.py) ... done
  Created wheel for rope: filename=rope-0.18.0-py3-none-any.whl size=181135 sha256=b524874919f1c21aaf2e36214b198d054df14bd513964ea38a9421ba7035d344
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\e7\b5\26\1e976cf5c9f27c7090c7bd8884e5fc5a19dc723c9e7a6db51a
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19558 sha256=ca5fe38cf3e29717fecc56141864abe22032c89ad8aa4c1fc6a308f15123c7ba
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\62\76\4c\aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp37-cp37m-win32.whl size=55874 sha256=3ade10a1a73ccf2d6fcdeb2f122a256458e012eb6fdc410cc39dcc0e51b424c7
  Stored in directory: c:\users\*******\appdata\local\pip\cache\wheels\a5\52\bf\71258a1d7b3c8cbe1ee53f9314c6f65f20385481eaee573cc5
Successfully built watchdog intervaltree pandocfilters autopep8 rope wrapt pyrsistent
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly

**Comment by stonebig** [comment]
you can indeed do install free visual-cpp-build tools. or get the binaries from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ujson

**Comment by cnsltnt51** [comment]
"C:\WPy32-3850\WinPython Control Panel.exe"
Will not open.

"C:\WPy32-3740\WinPython Control Panel.exe" functions perfectly.

**Comment by cnsltnt51** [comment]
Thanks that took care of the problem.

**Comment by stonebig** [comment]
Well, It was interesting to so how far from the "conda" experience, official "pip" is.
