### ISSUE TITLE
"VS Code.exe" does not recognize "&" symbol in folder names and crops the name

### ISSUE THREAD

**Issue by yilmazdurmaz** [winpython/winpython#899]
I recently started to work with python and found this by accidentally as I was trying to open current folder I am in.

I have a "python&sql" folder and tried to open while in terminal. since "vscode ." does not work  (as in #898), I tried using "vscode %cd%" and in return got this error message:

> 'sql' is not recognized as an internal or external command, operable program or batch file.

took me a while to see the problem. changing the folder name as "python-sql", the command successfully opened the folder in VS Code.

Please take a look and fix.

version: WPy64-3830

**Comment by stonebig** [comment]
Could you try with vscode "%cd%" ?

**Comment by stonebig** [comment]
looking further, I don't see any solution with that because of DOS. and PowerShell is not an option authorized per default on Windows.

**Comment by yilmazdurmaz** [comment]
@stonebig,  I don't understand why you closed it!?

I just found out that the problem is not only with folder names, but also exist for file names too.

I have my usual VSCode installation in the path as ``code.exe``, and the one came with WinPython renamed as ``vscode.exe``.

trying to open a file ,``code "try&see.py"``  opens the file with correct name but ``vscode "try&see.py"`` crops the name to "try" and ignores the rest of it. "

I tried on "cmd", "powershell" and even on "bash" from git installation. all the same: names after "&" are cropped.

**Comment by stonebig** [comment]
hum,

Can you try to modify \WPy64-3830\scripts\Noshell.vbs like this:


```
'from http://superuser.com/questions/140047/how-to-run-a-batch-file-without-launching-a-command-window/390129
If WScript.Arguments.Count >= 1 Then
    ReDim arr(WScript.Arguments.Count-1)
    For i = 0 To WScript.Arguments.Count-1
        Arg = WScript.Arguments(i)
        If InStr(Arg, " ") > 0 or InStr(Arg, "&") > 0 Then Arg = chr(34) & Arg & chr(34)
      arr(i) = Arg
    Next

    RunCmd = Join(arr)
    CreateObject("Wscript.Shell").Run RunCmd, 0 , True
End If
```

**Comment by yilmazdurmaz** [comment]
nope, still the same @stonebig

**Comment by stonebig** [comment]
it works on mine:

````
WPy64-3860>"vs code.exe" "see&pray.py"
````
![image](https://user-images.githubusercontent.com/4312421/98449526-94005d80-2134-11eb-9c2e-1f0077ec8fe5.png)

**Comment by stonebig** [comment]
I called the icon, maybe you called something else ?

**Comment by yilmazdurmaz** [comment]
my bad, I keep an older v3760 and I changed this file in its folder 👍 

used the edit on v3830 and it is working.

**Comment by stonebig** [comment]
aaaaah. will patch next release accordingly.

**Comment by yilmazdurmaz** [comment]
any luck you have time for #898, might be solved in a similar scripting manner I hope.

and thanks for the help.
