### ISSUE TITLE
Stripping down large distribution to keep only geopandas and dependencies

### ISSUE THREAD

**Issue by crolando** [winpython/winpython#911]
Hello.  This is a very exciting project for me, as I am searching for a deployable version of python w/ geopandas to include in a larger geo-data processing application.  winpython seems perfect!   I am a little concerned about the file-size at the moment though.  The 3.7 version of winpython with geopandas expands to 1.8 gigs.  

I have tried to go into wppm and uninstall everything except the geopandas and its dependencies (fiona shapely, etc as listed on geopandas website).  When I was done, I ran "import geopandas" and it said it was missing a timezone python package (pytz i think).  So clearly I do not have the correct dependency list and have blasted away something that was needed after all.

Can you recommend a way that I can uncover the full dependency tree of geopandas?  I appologize if this is a basic python question, I'm sort of new to this.

Thanks!

**Comment by stonebig** [comment]
Pipdeptree -p geopandas ?

**Comment by stonebig** [comment]
A smaller version requires to remove something big:
- Qt stack,
- jupyterlab,
- mkl,
- pytorch or vscode.

**Comment by crolando** [comment]
that's great, thanks!
What I did to get a minimal version was the following:

- I use `pipdeptree -p *package_name*` to generate the dependencies
- I got all the packages installed using `pip list` and stuck the output into a text file
- I manually went into this text file and removed the package names and dependences, so now the text file only has packages I don't care about.
- **you have to also remove pip package**
- I use notepad++ to strip out everything except just the package names (since `pip list` gives the version number and table headers)
- Again, using notepad++, I prepend all these package names with `pip uninstall -y *package_name*`
- I save this as a bat file
- now, I go into `WinPython Command Prompt.exe` and then just run the bat file

This process runs for a bit and automatically uninstalls everything except the stuff you want.

I chose to keep rasterio and geopandas, and this took a 3.8 gig disk image down to 900 megs.  Sweet.

**Comment by stonebig** [comment]
notepad++ is a great tool, just sad the comparison module is not in per default.
