### ISSUE TITLE
Starting ipython3 on Winpython-64bits-3.4.3.2 uses Python 2.7.9

### ISSUE THREAD

**Issue by ispmarin** [winpython/winpython#93]
I'm trying to use ipython3 notebook, from an Winpython-64bits-3.4.3.2 installation. I go to the python-3.4.3.amd64/scripts folder with the Windows console and try to start it with

    ipython3

but when it starts, it shows

    Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

If I use directy the python.exe on the python folder, it starts python 3.4.3 correctly. What am I missing?

**Comment by stonebig** [comment]
You didn't pre-initialize the path, so I guess your default system Python2.7 installation is firing up.

Try:
````
..\..\scripts\env.bat && ipython3
````

**Comment by ispmarin** [comment]
It worked. Could you kindly point me to the docs about this?

**Comment by stonebig** [comment]
it's in the `readme.txt` that is at the same place as the `env.bat`:
````
These batch files are not required to run WinPython.

The purpose of these files is to help the user writing his/her own
batch file to call Python scripts inside WinPython.
The examples here ('spyder.bat', 'spyder_light.bat', 'wppm.bat',
'pyqt_demo.bat', 'python.bat' and 'cmd.bat') are quite similar to the
launchers located in the parent directory.
The environment variables are set-up in 'env.bat'.
````
