### ISSUE TITLE
Request for package inclusion

### ISSUE THREAD

**Issue by jcrmatos** [winpython/winpython#94]
Hello,

I would like to request that you consider adding the following packages to WinPython:
future (not futures)
py2exe (there are Py2 and Py3 versions)
pytest
pytest-cov
flake8

Thanks,

JM

**Comment by stonebig** [comment]
what reason behind this request ?
what is `future`about ?

**Comment by jcrmatos** [comment]
Hello,

Clean single-source support for Python 3 and 2

future is the missing compatibility layer between Python 2 and Python 3. It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.

https://pypi.python.org/pypi/future

Thanks,

JM

**Comment by stonebig** [comment]
ok. In my context/way of thinking:
- including `future` now will add weight to Winpython without helping the future,
- keeping in check the total download weight (and unzip time) of Winpython is important to me.

So I'm afraid I won't add `future`.
