### ISSUE TITLE
Debugging Python Code in vscode

### ISSUE THREAD

**Issue by git-tiger** [winpython/winpython#945]
I tried debugging tool for my python code.
When I run it, and dialog pops up.
says,
"Couldn't find a debug adapter descriptor for debug type 'python' (extension might have failed to activate)"

How do I enable debugging for python in WinPython?

Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by stonebig** [comment]
I never tried... Could you:
- put an animated GIF example ?
- try by first selecting manually the absolute path to the python executable ?

**Comment by git-tiger** [comment]
Tried "make_winpython_fix.bat", and got this.

patch pip and current launchers for non-move
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\My Programs\Programming\WPy64-3860\python-3.8.6.amd64\lib\site-packages\winpython\wppm.py", line 565, in patch_standard_packages
    utils.patch_sourcefile(
  File "C:\My Programs\Programming\WPy64-3860\python-3.8.6.amd64\lib\site-packages\winpython\utils.py", line 484, in patch_sourcefile
    content = fh.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0x9e in position 7241: illegal multibyte sequence
Press any key to continue . . .

**Comment by git-tiger** [comment]
I can reproduce the issue. 
Downloaded WinPython 3.870-cod version. Debugging works as normal.
Updated VScode to version 1.54.1, and the dialog appears.

**Comment by stonebig** [comment]
isn't it relative to this ? https://github.com/microsoft/vscode/issues/118562
(corrected in VSCode-1.54.3 only)

**Comment by git-tiger** [comment]
Working with 1.54.3
