### ISSUE TITLE
Jupyter lab, notebook and spyder not launching with last release WinPython64-3.9.2.0cod

### ISSUE THREAD

**Issue by leopoletti** [winpython/winpython#949]
Hello,

I have just install the last version WinPython64-3.9.2.0cod.

When I launch jupyter Lab.exe or Jupyter Notebook.exe they do not launch with nothing to report in the prompt which is waiting in the current directory.
When I launch spyder I have a e error message ask me to reinstall software due to a missing librairy: api-ms-win-core-path-l1-1-0.dll

I have tried WinPython64-3.8.8.0 and it is working as expected.

Thx you for your support.

**Comment by stonebig** [comment]
what is you operating ststem ?

**Comment by leopoletti** [comment]
My operating is Win7 so I guess all the pbs come from the OS as you mentioned.
