### ISSUE TITLE
Please include mpldatacursor in the installer

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#95]
Currently it has to be installed via `pip install mpldatacursor` in the "WinPython Command Prompt" (Spyder menu Tools->Open command prompt), which is annoying when I want to convince people to switch from Matlab.

It should be included to reduce the functionality differences to Matlab.

**Comment by stonebig** [comment]
there is no wheel format
it's not referenced by [Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs) (who would then do a wheel)
the web pypi page is not written in valid .rst format.

**Comment by jondo** [comment]
@joferkington - could you maybe create a wheel package? And fix the pypi page?

**Comment by joferkington** [comment]
Will do on both with the next release (which is long overdue). Thanks!

**Comment by stonebig** [comment]
is `mpldatacursor`python 3 compatible ?

**Comment by jondo** [comment]
Yes, it works for me with Python 3.4.3.

**Comment by joferkington** [comment]
@stonebig - Yes it is, though the current release has a few python3-specific bugs that have been fixed in the github HEAD.  (And my apologies for the radio silence. I've been traveling lately.)

On a side note, while I can easily build a wheel, `mpldatacursor` is a pure python package.  There shouldn't be any need for a wheel.  Am I missing something?

**Comment by stonebig** [comment]
Winpython ships only wheel packages.

The wheel format has three **BIG** advantages, for **binary AND source**  packages:
- **ZERO** code is run during installation process, giving **100% stability** to the Winpython "build" process,
- the **dependancies can be SPECIFIED** in the wheel format, and so **can be MANAGED** by the standard pip system.
- a lot of new features are coming to the **standard** Python packaging as a result, some being used by Winpython `build` process.

Doing a wheel from a source package should be super easy for you:
````
python setup.py sdist bdist_wheel --universal
twine upload dist/*
````

**Comment by joferkington** [comment]
Good to know, thanks!

**Comment by joferkington** [comment]
@stonebig  - Just FYI, if you do decide to include mpldatacursor, the new 0.6 release should meet your requirements.

**Comment by stonebig** [comment]
I see

**Comment by stonebig** [comment]
testing now with spyder 3.0dev and QT4 and Qt5:
- on Qt4 (or tcl/tk) It seem I don't see the  interactive cursor anymore
- all fails apart in Qt5, and matplotlib seems to say winpythonQt5 has a problem:
````
import numpy as np
import matplotlib.pyplot as plt
from mpldatacursor import HighlightingDataCursor

x = np.linspace(0, 10, 100)

fig, ax = plt.subplots()

# Plot a series of lines with increasing slopes...
lines = []
for i in range(1, 20):
    line, = ax.plot(x, i * x, label='$y = {}x$'.format(i))
    lines.append(line)

HighlightingDataCursor(lines)

plt.show()
````
gives
````
>>> runfile('D:/result_tests/winpython-3.4.3.6Qt5_build3.amd64/settings/.spyder-py3/temp.py', wdir='D:/result_tests/winpython-3.4.3.6Qt5_build3.amd64/settings/.spyder-py3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 786, in runfile
    execfile(filename, namespace)
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 87, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "D:/result_tests/winpython-3.4.3.6Qt5_build3.amd64/settings/.spyder-py3/temp.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "D:\result_tests\winpython-3.4.3.6Qt5_build3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\qt_compat.py", line 144, in <module>
    raise RuntimeError("PyQt{4,5} bindings found despite sip importing\n"
RuntimeError: PyQt{4,5} bindings found despite sip importing
Please install PyQt4 or PyQt5, uninstall sip or explicitly set the pyside backend.
>>> 
````

I don't know what to do from here, and the Qt5 messages is worrying me (a non-Qt expert as I am)

**Comment by joferkington** [comment]
I can verify that `mpldatacursor` (and matplotlib in general) work as expected on my Linux system with mpl v1.5rc2 on with the Qt4Agg, TkAgg, GtkAgg, and NbAgg (notebook) backends.  

However, I don't currently have access to a non-work Windows machine, so I can't test on Windows.  I also can't build with Qt5 at the immediate moment, so I haven't tested the Qt5Agg backend (I'll have that built shortly, though).

Qt5 problems aside, I'm not sure what the issue might be for `mpldatacursor` with the TkAgg and Qt4Agg backends might be.  They're working fine for me.  However, I've never tried to run anything through Spyder.  I'll install it and see if I can see the same issues when running things through Spyder.

It's entirely possible that there are platform-specific issues with `mpldatacursor` that are causing it to not work with mpl v1.5rc2 on Windows.  I'll see if I can get access to a Windows machine to test on.

**Comment by stonebig** [comment]
maybe it's my fault, maybe it's a new matplotlib bug on windows. I may let the dust settle around matplotlib 1.5 before retrying.

**Comment by stonebig** [comment]
Updating seaborn and holoviews to Matplotlib 1.5 level was a nightmare, I don't dare to add anymore complementary package over Matplotlib.

**Comment by jondo** [comment]
@stonebig, could you please retry?

I have just successfully tested `mpldatacursor-0.6.2` with the Qt5 backend in `WinPython-64bit-3.6.1.0Qt5.exe`.

**Comment by jondo** [comment]
Great, I see mpldatacursor 'checked' in the [release checklist](https://github.com/winpython/winpython/issues/516#issuecomment-289303109)!
