### ISSUE TITLE
nest_asyncio and jupyterlab 3

### ISSUE THREAD

**Issue by fleming79** [winpython/winpython#950]
Not sure where the problem lies, but it appears nest_asyncio patch doesn't work in the latest winpython release (jupyterlab 3) as it had previously.
![image](https://user-images.githubusercontent.com/1474668/111895065-1d6d5800-8a64-11eb-9def-af7b9a4dc7ac.png)
Although it runs and finishes that cell, no further output is returned. It also causes the same issue in VScode.

It works correctly with 3910 (jupyterlab 2)
![image](https://user-images.githubusercontent.com/1474668/111895030-ebf48c80-8a63-11eb-91a0-a43aceaaadc6.png)

**Comment by stonebig** [comment]
So I'll remove nest_asyncio, as i read this : https://github.com/erdewit/nest_asyncio/issues/51#issuecomment-801938081

**Comment by fleming79** [comment]
The only other package I see in the WinPython distribution that uses nest_asyncio is nbclient: https://github.com/jupyter/nbclient/issues/135. Will you remove that also?

**Comment by stonebig** [comment]
ha... hum .... thinking

**Comment by stonebig** [comment]
it's not clear to me what disappears by switching to Jupyterlab-only, maybe nbclient is irrelevant now.
but this week-end was about fighting with pip-20.0.1.
... can you try to push the understanding of the problem by yourself ?

**Comment by fleming79** [comment]
Thanks for your comments. Personally I can get by without it for the moment and I suppose will move away from using nest_asyncio if you decide to drop it from WinPython.
I don't use nbclient but thought I should mention it...

**Comment by Chaoses-Ib** [comment]
@fleming79 I'm having the same problem as you. May I ask if you've found the reason for the problem? Or any workaround except not using nest_asyncio?

**Comment by fleming79** [comment]
@Chaoses-Ib I stopped using nest-asynio.
You could try:
``` python

from jupyter_core.utils import run_sync

# Wrapping
async def myCoro2(message):
    return message
print(run_sync(myCoro2)("wrapped"))

# As a decorator
@run_sync
async def myCoro(message):
    return message
print(myCoro('as decorator'))

```
I recommend using these sparingly where there is no other option (such as a property getter).

Note that jupyter_core is actively working around these issues. 

Refs:
https://github.com/jupyter/jupyter_core/pull/387
https://github.com/python/cpython/issues/66435 (asyncio: nested event loop)

**Comment by Chaoses-Ib** [comment]
nest_asyncio v1.5.9 fixed this issue.
