### ISSUE TITLE
can not use Jupyterlab Code Formatter in WinPython64-3.9.2.0 

### ISSUE THREAD

**Issue by achilles78** [winpython/winpython#951]
after   "pip install jupyterlab_code_formatter"
the jupyter lab says "Jupyterlab Code Formatter Error Unable to find server plugin version...." when starting up

**Comment by stonebig** [comment]
hum, maybe try looking in the issue here https://github.com/ryantam626/jupyterlab_code_formatter/issues/193

**Comment by stonebig** [comment]
success ?

**Comment by stonebig** [comment]
you may look there https://github.com/ryantam626/jupyterlab_code_formatter/issues/192#issuecomment-757026310
`jupyter server extension enable jupyterlab_code_formatter`

**Comment by FGTFH** [comment]
in WPy64-31090, once I upgraded jupyterlab and the dependences, it magically got fixed.
