### ISSUE TITLE
Release 2021-03 Follow-up

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#953]
Release Date: june 2021 

Wanted:
- Infrastructure:
   - [x] include SHA3-256, as SQlite uses it, and it's there since Python-3.6
   - [x] Python-3.9.5, Python-3.10beta3
   - [x] Python-3.7+ **PyPy**  64 bit beta variant (belief: PyPy3 problems of now are also cPython-3.11 speed problems)
   - [x] Jupyterlab-3.0.16 
- [x] Spyder-5.0.3 for Qt able versions
- Improve Dashboarding experience: (seeing [this](https://github.com/holoviz/panel/pull/2198))
    - integration with Jupyterlab-3 and VSCode,
    - ship an example for each (Panel, Voila, ...)
- [x] a big WinPython-3.10 (with cPython-3.10 beta3)

Focus:
- pushing a PyPy3 variant to see if it can run [ahead of the others](https://us.pycon.org/2021/summits/language/))
- Web Technology: Dashboarding, Web API, WASM
- [Data Engineering](https://talkpython.fm/episodes/show/302/the-data-engineering-landscape-in-2021): dagster, dagster-dask, dbt, prefect, meltano, SQLite
- Machine Learning: Integrated Windows ML, Fastai

Postponed:
- Jupyterlab-3.1 moved to next release (seems for late july)
- improved Qt flexibility:
   - a better life in non-Qt world: wppm WinPython can work without Qt
   - Qt-6.1 compatibility: compatibility for WinPython, QtConsole, PyQtGraph, when [Matplotlib support is there](https://github.com/matplotlib/matplotlib/pull/19255) is the missing basic , Qt-6.1 requires Matplotlib-3.5.0

Hopes/Wishes for 2021:
- Q3 2021 PyPy:
   - gets more care from python package owners, 
   - get 3.8 compatibility (alpha this september),
   - a PEP for Hpy interface is written for a convergence point with cPython-3.11 or 3.12
- a solution to create launcher icons without NSIS ([shimmy ](https://github.com/pfmoore/shimmy) didn't arrive there).

**Comment by stonebig** [comment]
Audit-Trail:

b1

b2

b3

rc

celebrate

**Comment by RoyiAvital** [comment]
Why does MKL appears only for Numpy?
I think on Anaconda MKL is also used in Scipy, am I wrong?

**Comment by stonebig** [comment]
@RoyiAvital may you try the https://github.com/winpython/winpython/discussions  for discussions / general questions  ?

**Comment by RoyiAvital** [comment]
May we have TensorFlow 2 + Keras in a variation of this release?
Having PyTorch and Keras+TF will make it the perfect choice for starting with DL?

Any chance having it in release 3?

**Comment by stonebig** [comment]
rc (2021-05-xx, '????' )

Changes from WinPython 2021-02:
- Infrastructure: 
  - WinPython becomes compatible with PyPy3 64bit, (a 64bit only branch)
  - Python-7.3.10 on PyPy-7.3.x, cPython-3.9.5, cPython-3.10.0b1
  - pip-21.1.1 (with https://github.com/pypa/pip/pull/9845 ?)
  - reverting from WinPython 2020-01, "Jupyter Notebook" icon points:
       - back to winpython_notebook.bat, (VSCode mode, rise compatible)
       - instead of winjupyter_nbclassic.bat (JupyterLab mode simulating Classic look)
- New Packages: 
  - qpsolvers , quadprog, qdldl 
  - flit
  - voila_gridstack-0.2.0
  - nbdime-3.0.0, jupyterlab_git
- Upgraded Packages: 
  - Spyder-5.0.1, pandas-1.2.4
- variation per version:
  -  Pytorch in standard branch only,
  -  portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
If no major problem is detected, these binaries will be re-tagged as final in a few days

Areas of particular interest for testers:
- Spyder-5.0.1
- pip-21.1.0dev further speed improvements 

Postponed to WinPython 2021-03:
- jupyterlab-3.1

**Comment by stonebig** [comment]
build 2 (2021-05-23/24, 'PyPy-7.3.5 and Spyder-5.0.3' )

Changes from WinPython 2021-03 build1:
- Infrastructure: 
  - Python-7.3.10 on PyPy3-7.3.5 final
  - pip-21.1.2
  - a big PyPy3 version full of compatibility bugs to iron out:
     - is ok: Numpy, Scipy, Matplotlib, Pandas, seaborn, sympy, holoviews
     - is not ok:
           - jupyter_core because of pywin32 dependancy on [three functions to re-write using ctypes ](https://github.com/jupyter/jupyter_core/issues/226#issuecomment-846453917) instead
           - statsmodels has apparently an uncompatible practice with [its "docstring" ](https://github.com/statsmodels/statsmodels/issues/7460)
     - is missing: Qt Stack (but [under investigation per Qt Company](https://gitter.im/PySide/pyside2?at=60a62a3477c281623c689b81) )
- New Packages: 
  - csvs_to_sqlite , datasette_graphql, sqlite_utils
- Upgraded Packages: 
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- finding and narrowing  down issues in  PyPy3 version (some are PyPy3 issues, some are packages issues, but issues shall be identified to be nailed down)


## hash codes 
<details>

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------

**Comment by stonebig** [comment]
build 3 (2021-0x, 'PyPy reaches Jupyter' )

Changes from WinPython 2021-03 build2:
- Infrastructure: 
  - PyPy3 progress:
    - 420 packages are ok, especially : Jupyterlab + Jupyter Notebook, statsmodels, plotnine 
    - some core dev interest on [writing performant Python code for PyPy](https://twitter.com/cfbolz/status/1398352941849907203)  

Next build effort:
- pushing on PyPy3 pain points :
    - PyPy-7.3.6 suppresses some slow behaviours on pure Python Code: import of modules, close of files, list mutation, 
    - Qt Stack ([pyside6-6.1 for PyPy3 under investigation per Qt Company](https://gitter.im/PySide/pyside2?at=60a62a3477c281623c689b81) )
   - pushing PyPy to reduce its lag of being on 3.7:
      - 3.8 would gives us typed-ast
      - lag reduction increases core Developer interest and "big money" from the general Python "speed-up" effort.

**Comment by stonebig** [comment]
interlude, Python-3.10.0b2 (2021-06-06)

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
950bf8f800212610338b182762a10276 | 324891759082a90450de638f3dc3b87b84cc2689 | 9e8a51c742a9cdb6d58c571e5ed600d128144a283c6322b41a9fedcdbc1a4e0c | Winpython64-3.10.0.0dotb2.exe     |   25 999 002 Bytes | 8a67949219316b9c8548c23e0e0e97c0f35ef595332dfbdaad987e573b1c1bbf
7be7863a75c18b1f2b538b9effea6736 | 5610ccaf2d5be0ca225cd37e3cc0f4f0aff8e86f | 132001ad46e8c468c3207ad7e091e86ddc53a939a3930ebcbfb9067fae111bba | Winpython32-3.10.0.0dotb2.exe     |   24 862 581 Bytes | ecd796e2a77eb9fde6bf357d1b8889fd697a330acd9c72ae6baa496a9d3383fa

**Comment by stonebig** [comment]
build 4 (2021-06-06, 'VSCode reaches PyPy3' )



 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
ebf4e9e614aa562a417ed6c4359e433b | 4d8e042592828eb99dcd30e8ace960f989b6b346 | d5a4215d8cd627b69d397e477ded58df984a217233cde65243891b194bc0c499 | Winpython64-3.7.10.0dotPyPyb4.exe |   25 771 409 Bytes | 148a1160d9d6083401429db4fd9326330d51d4a45cb41fcbf3df7f5a88137713

**Comment by stonebig** [comment]
Interlude: Python-3.10.0b2 first big build (2021-06-12)

With Python-3.10.0b2

Interest of building fat WinPython over beta2 cPython is to uncover painfull issues in advance, and seek resolution before rc.

currently missing:
- Qt (bug https://bugs.python.org/issue44242)

**Comment by stonebig** [comment]
build 5 (2021-06-14, 'last beta' )

Changes from WinPython 2021-03 build4:
- Infrastructure: 
  - PyPy3 (python-3.7) progressing:
    - 12 more packages are included:
       - shapely, ipyleaflet, geopandas,
       - reportlab, nbconvert_reportlab, scs, sounddevice,
       - wasmer, wasmer_compiler_singlepass, wasmer_compiler_cranelift
    - ... work ongoing on PyPy for 'hpy' in Cython, Python-3.8 compatibility (may take the summer)
- New Packages:
  - maturin is now inside all big versions
- Upgrade Packages:
  - mypy-0.902 (will be friendly to next PyPy Python-3.8)
  - numpy-1.21.0rc2 for Python-3.10 

Interest for users:
 - the goal for WinPython 2021-03 PyPy3 is achieved https://github.com/winpython/winpython/issues/966#issue-861977495 ...
 - ... please help iron out next issues (discovered or to discover) at this new PyPy3 stage : 
    - solving  "Shapely" ,  "orjson" and "reportlab" problems would be [helpfull ](https://github.com/winpython/winpython/issues/966#issuecomment-855238265)
    - the PyPy3 team needs support and help in any form to speed-up further and get more momentum
 
Next build effort:
- pushing on PyPy3 next pain points :
    - missing: "Shapely" ,  "orjson" and "reportlab"  packages (or a replacement, like for PyODBC), 
    - coming: 
      - PyPy-7.3.6 to suppress some slow behaviour vs cPython Code: import of modules, close of files, list mutation ...
      - Qt Stack ([pyside6-6.1 for PyPy3 under investigation per Qt Company](https://gitter.im/PySide/pyside2?at=60a62a3477c281623c689b81) )
       - some PyPy3 progress [towards 3.8 compatibility](https://twitter.com/cfbolz/status/1401199542700236814) ), that will bring typed_ast

**Comment by stonebig** [comment]
Interlude: Python-3.10.0b3  (2021-06-20)


Interest of building WinPython over beta3 cPython is to uncover painfull issues in advance, and seek resolution before rc.

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
6eedaf37a519567c90d4c6eccbfb0ef6 | c360540100ceab43473f4b42506bb90406f940ef | ece73e8265173fb4c474d5d18cc7e2145f8ae3c155b670e081899cecd241267d | Winpython64-3.10.0.0dotb3.exe     |   26 031 190 Bytes | 14ef11d02c89d5e914a5e72a8aeef4a82f4ba90b61b977e9446f1749eacd20db
4ee55d1bbff1bd01543815628db75162 | 568d0cc5b7b17859fd6c4cbb1d54211fffb03597 | 65eef7a087f3336a3ccca59e3f6ab9a0bb69410b5d4644be263214a5409cd8f0 | Winpython32-3.10.0.0dotb3.exe     |   24 885 218 Bytes | dde951205edb1f645a5c51d0d5ebe1f5068294a3ab6e0dddc792d9f63ef7a4e7

**Comment by stonebig** [comment]
rc (2021-06-26, numpy-1.21.0)

Changes from WinPython 2021-03 build5:
- Infrastructure: 
  - PyPy3 (python-3.7) progressing:
    - ipycanvas , pymc,, sklearn_contrib_lightning, cartopy, pyproj, reportlab
    - removed the fake 'python.exe', in hope VSCode will detect 'pypy3.exe' more automatically in the future
- New Packages:
  - fastai
- Upgrade Packages:
  - numpy-1.21.0, scipy-1.7.0, mypy-0.910
  - spyder-5.0.5, plotly-5.0.0

Interest for users:
 - check new packaged and resolved problems for PyPy3:
     - shapely, reportlab, ipyleaflet, ...  
 -   help iron out next issues (discovered or to discover) at this new PyPy3 stage : 
    - solving  "orjson" or "cartopy" or "pyproj" problems on WinPythonChecker would be [helpfull ](https://github.com/winpython/winpython/issues/966#issuecomment-860021143)
    - the PyPy3 team needs support and help in any form to speed-up further and get more momentum
 
Next build effort: (should be rc)
- pushing on PyPy3 next pain points :
    - missing:  "orjson" and "cartopy"   packages (or a replacement, like for PyODBC), 
    - following progress on : 
      - PyPy-7.3.6 to suppress some slow behaviour, 
      - hpy in

**Comment by stonebig** [comment]
Helllo, 

Final release is equal to rc

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
fa2715d98015019192ebf728f253ae9c | ba4f263ef533df404f7c8cc0b47a6eb78f429bfa | 489ab15c35336cdac32b88a5282d7b5631af74afba34ac6cee3ac475ffd7c7dd | Winpython64-3.7.10.0dotPyPy.exe   |   25 763 221 Bytes | 8758c48b8c74ba3621989b9abf2ddcfcd38049de21512ffcc9ae2688156508c9
819d5da22c5b2f025eba789ea3edf725 | 4e67187e3bf949ee7ab85d7fbc873f2ac7691c5a | 959d3f7a29134ec758a048217c3bee1010dd1322c98f2452b853796360b748fd | Winpython64-3.7.10.0PyPy.exe      |  486 605 762 Bytes | a686ffa27b8cfe96aa227cec7ca1ace5da744ea969dfbdbc76c96f2c9c63d514
2f730858920f12c65991b7f7490bbdd2 | f26b443eaad4727c3e765af85e08081772e48bed | 7e95875b3217429b54939d45d69f87b6f2013a6cbd2e08b52429b466785bdba2 | Winpython64-3.8.10.0dot.exe       |   25 375 720 Bytes | 96ef274f4691a66386d173d873e187259729773cb8e3ef6dc224b82493ca6759
6033a8688e3e10c7f2000b1529683abe | 289f45be877469c8237f373b62eaa280f739ed10 | f63295ee104790e80ca1a7e67274d57f1a22aa33dce5850bd9f3464b709739d6 | Winpython32-3.8.10.0dot.exe       |   24 217 953 Bytes | a1946929a4d5c3d58e4413aa43131eefd14db6bb0291c9cd29a161940adabe21
dc35b0436535d39166fbc97d0915d22a | a62f1ce23f4569a995368b31599f67a9ab308a69 | 01f2a00265110a51f1fc91a058f1698aef1ef9a1b70f4e6d09f2c9fdccf6edf8 | Winpython64-3.9.5.0dot.exe        |   25 839 482 Bytes | 020906ab69e829447cfaa8058863636e4af22e35288ad94081c2416db676d71a
5fd4f594ce5219db3c1269cc79d5f0b6 | bcba1b841afeb476a171af4342703ec962ef247e | 5dc6715618e58944668c28525b2dc7aeacc1a38d9a7df75070ee639e10429b05 | Winpython32-3.9.5.0dot.exe        |   24 682 542 Bytes | 87638c83b59a952a71fcaa90aa834634b39c08cea4130342be04635e5cb368ba
dc35b0436535d39166fbc97d0915d22a | a62f1ce23f4569a995368b31599f67a9ab308a69 | 01f2a00265110a51f1fc91a058f1698aef1ef9a1b70f4e6d09f2c9fdccf6edf8 | Winpython64-3.9.5.0dot.exe        |   25 839 482 Bytes | 020906ab69e829447cfaa8058863636e4af22e35288ad94081c2416db676d71a
5fd4f594ce5219db3c1269cc79d5f0b6 | bcba1b841afeb476a171af4342703ec962ef247e | 5dc6715618e58944668c28525b2dc7aeacc1a38d9a7df75070ee639e10429b05 | Winpython32-3.9.5.0dot.exe        |   24 682 542 Bytes | 87638c83b59a952a71fcaa90aa834634b39c08cea4130342be04635e5cb368ba
1783b1eb3e7d124e481898db5c94aeff | ed1476a8122ab2b65cc5b31e5de6691c39da6f15 | 9a2f25ee58a35656a06bafeddba87c47de28cf11931cdbafe0ebd5b5a4eac2d5 | Winpython64-3.9.5.0.exe           |  790 159 865 Bytes | dd5d79c6e306597d51b57f87aabb725028eecf5f3018d2ef6644327bca8604cf
