### ISSUE TITLE
WinPython 3.9.2.0 64bit can't run under Windows 7 64bit

### ISSUE THREAD

**Issue by asmwarrior** [winpython/winpython#957]
Hi, I just installed the `Winpython64-3.9.2.0.exe` and after install, I try to double click on the "Spyder.exe", and it shows that "api-ms-win-core-path-l1-1-0.dll" is missing in my system.

This issue doesn't happens in the `Winpython64-3.8.8.0.exe`.

So, any suggestions on how to fix this issue?

Do I have to manually install some Microsoft C run time library?

Thanks.

**Comment by stonebig** [comment]
[Python 3.9.2 cannot be used on Windows 7 or earlier](https://www.python.org/downloads/windows/)

**Comment by asmwarrior** [comment]
Oh, thanks for the reply.

So, It looks like any python which is newer than Python 3.9 won't work on Windows 7 either.

I will close this issue.

**Comment by stonebig** [comment]
I notice someone claims to have Winpython-3.9.0 somewhat working in windows 7: https://github.com/winpython/winpython/issues/906#issuecomment-749146260

**Comment by stonebig** [comment]
I found the same guy trying hard on Windows7, on some ultra-corner case, had to go down to WinPython_3.6.3.0
https://github.com/Nuitka/Nuitka/issues/904#issuecomment-759432882

**Comment by asmwarrior** [comment]
> 
> 
> I found the same guy trying hard on Windows7, on some ultra-corner case, had to go down to WinPython_3.6.3.0
> [Nuitka/Nuitka#904 (comment)](https://github.com/Nuitka/Nuitka/issues/904#issuecomment-759432882)

For me, 3.8.8.0 works OK in my Windows 7. So, I don't need to downgrade to WinPython 3.6.3.0.
Thanks for the hint.

**Comment by asmwarrior** [comment]
Hi, I would like to ask a question:

What is the latest version of winpython I can use under Windows 7(64bit)?

I see for CPython, the 3.9.x is not supported under Windows. (https://www.python.org/downloads/windows/)

But when I look at your homepage, you are supplying PyPy 3.8 for the latest release, which is not CPython, can I use this? can you give some suggestion? Thanks?

**Comment by stonebig** [comment]
It's a question of what the binaries packages or DLL that you use are utilizing new windows post-7 api.

It's impossible to answer until what moment it works for your use case

**Comment by asmwarrior** [comment]
Well, I just install this package in my Win7: [Winpython64-3.8.12.3PyPy.exe](https://github.com/winpython/winpython/releases/download/4.7.20220709final/Winpython64-3.8.12.3PyPy.exe)

But I can't open the Spyder.exe or other top-level executables.

So, I guess the PyPy 3.8.x is not supporting Windows 7?

**Comment by stonebig** [comment]
for PyPy, situation is different:
- Spyder is not yet compatible enough with Pyside6 
- so a check for you is if you can open "WinPython Control Panel"

**Comment by asmwarrior** [comment]
>     * so a "Hope" check for you is if you can open "WinPython Control Panel"

No, I can't, when double click on file "WinPython Control Panel.exe", nothing happened.

**Comment by CrimsonVex** [comment]
> No, I can't, when double click on file "WinPython Control Panel.exe", nothing happened.

What was the update to this? I have the same issue.

**Comment by patricktokeeffe** [comment]
> What is the latest version of winpython I can use under Windows 7(64bit)?
> 
> I see for CPython, the 3.9.x is not supported under Windows. (https://www.python.org/downloads/windows/)
> 
> But when I look at your homepage, you are supplying PyPy 3.8 for the latest release, which is not CPython, can I use this?

Python's support for Windows 7 diverged at 3.9.1 so, in theory, you could still use the 3.8.x release series. However, as pointed out already, the PyPy implementation does not work. I wound up just trying various releases and determined the most recent working version with Spyder included is WinPython64-3.8.9.0 (environment is Win7 Pro SP1 x64)

* ~~[WinPython64-3.8.12.2 (incl. Spyder)](https://github.com/winpython/winpython/releases/download/4.6.20220501/Winpython64-3.8.12.2PyPy.exe)~~
  * *Control panel & Spyder do not launch*
* ~~[WinPython64-3.8.10.0dot (no Spyder)](https://github.com/winpython/winpython/releases/download/4.3.20210620/Winpython64-3.8.10.0dot.exe)~~
  * *Control panel does not launch*
* [WinPython64-3.8.9.0 (incl. Spyder)](https://github.com/winpython/winpython/releases/download/4.1.20210417/Winpython64-3.8.9.0.exe)
  * *Launched OK and appears to be fully functional*

xref #1086

**Comment by asmwarrior** [comment]
@patricktokeeffe thanks for sharing the information.
