### ISSUE TITLE
WinPython 64 bit with PyPy

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#966]
To celebrate the arrival of PyPy on Windows 64 bit, Let see if we can build a WinPython with PyPy.

Interception course with cPython:
- interesting spot is: PyPy + VSCode + Jupyterlab + Cython + [HPy ](https://www.pypy.org/posts/2019/12/hpy-kick-off-sprint-report-1840829336092490938.html), on 64 bit, maybe [pyside6-6.1](https://bugreports.qt.io/browse/PYSIDE-535)
- WinPython 2021-03: PyPy-7.3.5 for Python3.7+ VSCode + Jupyterlab + Cython, on 64 bit only
- WinPython 2021-04: Matplotlib-3.5.0 + PySide-6.1 + HPy and performances fixes
- WinPython 2021-05: PyPy for Python-3.8, [beta seems coming this summer 2021](https://www.twitch.tv/videos/1046851224) 
- WinPython ~~2022-02~~ 2022-03: PyPy for Python-3.9 
- WinPython 2022-05: PyPy for Python-3.10
- WinPython 2023-02: PyPy for Python-3.11

so far:
- [x] WinPython 'dot' version; Yes but missing WPPM GUI (the Qt Problem) 
- [x] SQLite_bro : Yes but slightly different behavior, 6x slower
- [x] VScode without Jupyter: ... works by updating VSCode settings per menu, to tell where  pypy3.exe is
- [x] SQLite_bro-0.9.2 fixes [PyPy compatibility](https://github.com/stonebig/sqlite_bro/commit/a63e8e89e6ca262b96de0c9d6b306bb8fd6068d1)
- [x] a small Speed-Center table (below)
- [x] Adapt Build System to automate PyPy builds like the cPython builds
- [x] SQLite-3.35.5 in PyPy-7.3.5rc1 (becoming level with CPython)
- [x] Numpy, Matplotlib,  Pandas, scikit-learn
- [x] Pywinpty
- [x] a cython wheel (but compiling to cython slows things 2.5x, currently)
- [x] statsmodels (after statsmodels [made a compatibility patch](https://github.com/statsmodels/statsmodels/pull/7462))
- [x] [pyzmq fix](https://github.com/zeromq/pyzmq/pull/1534) (per Christoph Gohlke)
- [x] [Jupyter compatibility](https://github.com/jupyter/jupyter_core/issues/226#issuecomment-847341125) (since May 25th morning ... to integrate in a release)

Roadblocks or Hacks :
- Qt Stack: needs 
  - [x] COMPATIBLE PySide6-6.1 with PyPy,
  - [x] COMPATIBLE Matplotlib-3.5.0 with PySide6-6.1 (end  october ~~june~~ ?)

Other:
- follow HPy progress (hpy-0.02 [there ](https://foss.heptapod.net/pypy/pypy/-/commits/branch/hpy-0.0.2))
- performance on PyPy3 (vs optimized PyPy2):
   - [x] [Import lib speed-up like it's done in cPython (via cache)](https://foss.heptapod.net/pypy/pypy/-/tree/branch/py3.7-import-speedup)
   - [x] [better PyPy3 string handling](https://foss.heptapod.net/pypy/pypy/-/tree/branch/py3.7-newtext-const-arg-caching)
 - performance vs cPython:
   - example from the expert shows [it can indeed fly 3x cython speed](https://foss.heptapod.net/pypy/pypy/-/issues/3473#note_159611)
   - but it's not performant in current raw form when we use current numpy

Speed-Center:

speed test (seconds) | Cpython-3.9 | Pypy-7.3.5 3.7.10 | PyPy-7.3.6 3.8.10 nightly | comment
------------|---------------|-----------|----------|-----|
SQLite_bro | 13 | 85 | 35 | seems linked to ['import' not being cached](https://foss.heptapod.net/pypy/pypy/-/issues/3431) , but now SQLite-3.35.0 with math functions included, and PyPy-7.3.6 will cache imports (200x speed-up, but apparently no effect)
[sudoku_norvig_for_comparison_of_complexity.py](https://github.com/winpython/winpython_afterdoc/blob/master/docs/Solvers_Raymond_Hettinger/python/sudoku_norvig_for_comparison_of_complexity.py) | 0.09 | 0.51 | 
[sudoku_norvig_for_comparison_of_complexity.py (hard1)](https://github.com/winpython/winpython_afterdoc/blob/master/docs/Solvers_Raymond_Hettinger/python/sudoku_norvig_for_comparison_of_complexity.py) | 89 | 42 | 65 | python-3.10a7 = 89s, numba can't, cython = 47s
speed_basic.py (code below or [there](https://realpython.com/pypy-faster-python/))  | 25.5 |  0.27 |  
[pyconumpy ](https://github.com/paugier/piconumpy)| |  |  |  **the microbench to prove or not that Pypy is a scientific option (should become good with HPy)**

[the Nbody experiment](https://foss.heptapod.net/pypy/pypy/-/issues/3349) became [good in PyPy with type freezing ](https://www.csl.cornell.edu/~cbatten/pdfs/cheng-type-freezing-cgo2020.pdf) 
 at [CGO ’20, February 22–26, 2020, San Diego, CA, USA](https://cgo-conference.github.io/cgo2020/)

Climate Impact
![image](https://user-images.githubusercontent.com/4312421/115785494-d30f2c00-a3bf-11eb-9ae6-6f19b6ac6b1a.png)

**Comment by stonebig** [comment]
speed measures
- using sqlite_bro:
```
pydef py_sin(s):
    "sinus function : example loading module, handling input/output as strings"
    import math as py_math
    return ("%s" %  py_math.sin(s*1));
WITH RECURSIVE
  cnt(x) AS (
     SELECT 1
     UNION ALL
     SELECT x+1 FROM cnt
      LIMIT 30000000
  )

select sum(sin(x))  from cnt  
```
- mandelbrot (when necessary wheels in  place)

**Comment by stonebig** [comment]
VSCode does the sudoku with pypy3.7-v7.3.4-win64

![image](https://user-images.githubusercontent.com/4312421/115345564-455cf200-a1af-11eb-9534-d31165a66f87.png)

**Comment by stonebig** [comment]
speed_basic.py test

```python
import time

start_time = time.time()

total = 0
for i in range(1, 10000):
    for j in range(1, 10000):
        total += i + j

print(f"The result is {total}")

end_time = time.time()
print(f"It took {end_time-start_time:.2f} seconds to compute")

```

**Comment by stonebig** [comment]
build a1  (2021-04-20 'SQLite-0.35.5')

change from build a0:
- SQLite-0.35.5 (math functions included)
- sqlite-bro-0.9.2 fixes to become compatible with PyPy 

Next build a2:
- start modify build system
- wait the 64bit binary wheel problem is solved

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size              
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|-------------------
338cdc161b2bc091a9f2184621681860 | 81e5d38c1ccc90746ad089ce975d1cc3e834a76d | 52c207f2916399a3f222b9d0b87e80f7ccf5cdcbf2a9ba40d08746b173394026 | Winpython64-3.7.10.0dotpypya1.exe |   25 034 421 Bytes | 


Included Package:
- WinPython
- sqlite_bro-0.9.2
- pip-20.1.0dev

Location: https://sourceforge.net/projects/winpython/files/WinPython_3.7/3.7.10.0/alphas/

**Comment by stonebig** [comment]
PyPy build a2  (2021-04-2x 'automated build')

change from build a1:
- Infrastructure work:
  - standard automation  ... and so back to the old  SQlite shipped per PyPy-7.3.4
  - unchecked; "associate" function, or Qt integration
- a few clean-ups

Areas of particular interest for testers:
- it works as any other WinPython, except you must type "pypy3" instead of python
- for experts knowing what they do:
   - check the associate function, (Winpython in the windows menu)
   - look ahead on Qt integration.

**Comment by stonebig** [comment]
looking at [Cython CI](https://github.com/cython/cython/runs/2527503116), it seems Pypy-3.7 is  (8m 10 s/ 5m 18s)  35% slower than Python-3.7 on this exercise ... room for improvement

**Comment by stonebig** [comment]
cython source wheel is compatible with PyPy, on more package, but fails to compile statsmodels extensions. so fligth domiain is currently constrained per:
- jupyter_core needing pywin32
- failing to build wheels for statsmodels, pywinpty
- pyside6 wheel (on the road from Qt, but not there).

on PyPy3 side:
- "import package speed-up" is only coming for 7.3.6, (to check if performance with sqlite test improves widely)
- hpy talk or article at pycon 2021 is not yet available.
- python-3.8 compat is slow to come

**Comment by stonebig** [comment]
may 23rd morning status; 
- improvement:
  - wheels for statsmodels, pywinpty provided per cgohlke,
  - switch to a fresher numpy+mkl solved the "import pandas" (was old) issue

Flight domain is currently constrained per:
- PROBLEM NARROWED: jupyter_core needing pywin32 => cgohlke did "empty" pywin32 wheel, suggests a solution is easy to replace the 3 missing functions.
- PyPy3 is missing a python-3.5 (windows) change: https://foss.heptapod.net/pypy/pypy/-/issues/3469
- pyside6 wheel on the road from Qt, but not there.

**Comment by stonebig** [comment]
- "science":
     - statsmodels bug is solved per this patch  https://github.com/statsmodels/statsmodels/pull/7462)

**Comment by stonebig** [comment]
- "Jupyter":
    - SOLVED by Christoph Gohlke: a ccfi bug in pyzmq + jupyter_core to patch + statsmodels to patch

**Comment by stonebig** [comment]
Flight domain is currently constrained per:
- in "Jupyter":
    -  shapely: in need for a few geograhic packages cartopy and ipyleaflet
    - orjson: missing to [ipycanvas](https://github.com/martinRenou/ipycanvas/issues/201)
- "science":
     - numba: [missing to fastparquet](https://github.com/numba/numba/issues/4761#issuecomment-854610108)
     -  pyside6 wheel on the alpha road from Qt Company, but not there yet.
- "Deep Learning":
     - out of scope for now, need to have the rest flying.

**Comment by stonebig** [comment]
milestone 1 "credibility" is now reached "WinPython 2021-03: PyPy-7.3.5 for Python3.7+ VSCode + Jupyterlab + Cython, on 64 bit only". 

Next milestone is about more natural "performance" (as PyPy can perform, but you need often to tweak your code)

**Comment by stonebig** [comment]
You may report ithe problem on pypy with the code and crash report, asking if it's a pypy bug, a way of writing not tolerated per pypy, or an incompatibility from matplotlib or tk

**Comment by stonebig** [comment]
Do it also on stackoverflow

**Comment by stonebig** [comment]
hum, launched this way, it doesn't blow up with Winpython64-3.7.10.0PyPycodb4.exe

![image](https://user-images.githubusercontent.com/4312421/121770078-8944f580-cb67-11eb-96ba-6db20c3bd475.png)

**Comment by stonebig** [comment]
this way:
![image](https://user-images.githubusercontent.com/4312421/121770194-3ae42680-cb68-11eb-9e98-85f3702cab9e.png)

**Comment by stonebig** [comment]
Updated Flight domain seems now currently constrained per:
- in "Jupyter":
    - cartopy: missing to geoviews
    - orjson: missing to [ipycanvas](https://github.com/martinRenou/ipycanvas/issues/201)
- "science":
     - numba: [missing to fastparquet](https://github.com/numba/numba/issues/4761#issuecomment-854610108)
     -  pyside6 wheel on the alpha road from Qt Company, but not there yet.
- "Deep Learning":
     - out of scope for now, need to have the rest flying.
 - "Qt": no PySide6-6.1 yet

**Comment by stonebig** [comment]
Updated Flight domain seems now currently constrained per:
- in "Jupyter":
    - a pyproj binary compatibility bug ??
- "science":
     - numba: forecast is it will remain missing till the python-3.11 (june 2022 ?)
     -  pyside6 wheel on the alpha road from Qt Company, guess it will need PyPy-3.8 (sept 2021 ?)
- "Deep Learning":
     - out of scope for now, need to have the rest flying, ep numba. (dec 2022 ?)
 - Cpython eco-system compatibility:
     - Python-3.8 compatibility to get type-ast, mypy, (alpha around september)
     - [hpy Cython compatibility to get same performance](https://github.com/cython/cython/issues/4197)
  - VSCode-python better compatiblity, as [not super friendly with pypy3 per default](https://github.com/microsoft/vscode-python/issues/16493)

**Comment by stonebig** [comment]
Update of PyPy progress, testing on PyPy3-3.8 nightly:
- MyPy is working, if you comment the [gc.set_threshold() ](https://github.com/python/mypy/blob/97b3b90356893e2a9f6947ebe52b41cd54ab1cb7/mypy/build.py#L205)line (purely non-functional, used to gain 4% on cPython)
- Black is (so) installable
- the Sqlite test is performed in 30 seconds in PyPy3-3.8 vs 85 seconds in PyPy-7.3.6 and 13 seconds in cPython.
-

**Comment by stonebig** [comment]
PyPy Nightly for Python3.8 build a0 (2021-08-12, from PyPy3-3.8 nightly of July 29th:)


Infrastructure work:
- toolchain creatoin
- Location: https://sourceforge.net/projects/winpython/files/WinPython_3.7/38.10.1/alphas/

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
78dad874bee910c74b78fe3692d99a1d | be2defd71f6da7fde270ebee3f56813b1469ee84 | 6fad49119e0f7753318239c7671388f450bac58d20d6cd21686ffbabda7e9cd9 | Winpython64-3.8.10.0dotPyPyNighta0.exe |   26 623 538 Bytes | 3c5aaa75da5f3d491ee9a57112cbcdba678286b3ceb2b49c52c4de3cbf710ef6


next step:
- correct release version (.1 vs .0)
- integrate an  msvc_runtime
- push on the interesting new bits:
  - mypy
  - ...

**Comment by stonebig** [comment]
Update of PyPy eco-system progress, as of August 28th:
- Jupyter:
  - jupyter-core is now 'officialy' compatible: 
    - patch from cgohlke was merged in Jupyter-core-4.8.0rc0
    - pywin32 is now longer reqired
  - PyPy-3.7 is included in CI of Jupyterlab now.
- DL:
  - effort ongoing to make PyTorch build (on condaforge)
- mypy/black :
  - basic compatibility in PyPy python 3.8
  - work continues on the 'ast' part of it:
     [08:51 <mattip> we are down to 213 failures, 35 errors on the lib-python tests, 24 of them are test_dis and test_ast](https://libera.irclog.whitequark.org/pypy/2021-08-26)

**Comment by stonebig** [comment]
Speed-Center: (2021-08-28 version of PyPy 3.8

speed test (seconds) | Cpython-3.9 | Pypy-7.3.5 3.7.10 | PyPy-7.3.6 3.8.10 nightly  | comment
------------|---------------|-----------|----------|-----|
SQLite_bro | 13 | 85 | 27 | measures PyPy internal weaknesses reduction like ['import' not being cached](https://foss.heptapod.net/pypy/pypy/-/issues/3431) 
[sudoku_norvig_for_comparison_of_complexity.py](https://github.com/winpython/winpython_afterdoc/blob/master/docs/Solvers_Raymond_Hettinger/python/sudoku_norvig_for_comparison_of_complexity.py) | 0.09 | 0.51 | 
[sudoku_norvig_for_comparison_of_complexity.py (hard1)](https://github.com/winpython/winpython_afterdoc/blob/master/docs/Solvers_Raymond_Hettinger/python/sudoku_norvig_for_comparison_of_complexity.py) | 89 | 42 | 65 | python-3.10a7 = 89s, numba can't, cython = 47s
speed_basic.py (code below or [there](https://realpython.com/pypy-faster-python/))  | 25.5 |  0.27 |  
[pyconumpy ](https://github.com/paugier/piconumpy)| |  |  |  **the microbench to prove or not that Pypy is a scientific option (should become good with HPy)**

[the Nbody experiment](https://foss.heptapod.net/pypy/pypy/-/issues/3349) became [good in PyPy with type freezing ](https://www.csl.cornell.edu/~cbatten/pdfs/cheng-type-freezing-cgo2020.pdf) 
 at [CGO ’20, February 22–26, 2020, San Diego, CA, USA](https://cgo-conference.github.io/cgo2020/)

**Comment by stonebig** [comment]
PyPy Nightly for Python3.8 build a0b (2021-08-28, from PyPy3-3.8 nightly of August 28th:)

Changes from Winpython64-3.8.10.0dotPyPyNighta0.exe :

- Infrastructure:
   - adds msvc_runtime
   - PyPy nightly has corrected nearly all its Tcl/tk bugs,
   - latest version as:
      - a further 20% speed-up in SQlite test, now only 2x slower than cpython vs 6x slower on 3.7
      - still a 20% regression sudoku_norvig_for_comparison_of_complexity.py (hard1)

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
4c057a6df3fe3e818cd507b5a01c9c1b | bf0a29de1710247bd643e51669241e874405ade3 | 49c804921f110afdf8ea7961a00f591f79b70960dbeccc9c2666d6166cfa7cb5 | Winpython64-3.8.10.0dotPyPyNighta0b.exe |   27 356 866 Bytes | 1f0218b9ff05c15d8224e036f188f5aeafe805e640920895ceec4de836f1cb6d


next step:
- gently push on the apparent speed regression test

**Comment by stonebig** [comment]
PyPy v7.3.6 rc is very soon (unless waiting for Hpy-0.0.3
https://foss.heptapod.net/pypy/pypy/-/blob/eed30f5374249b5652278e3b3b83de694b693712/pypy/doc/release-v7.3.6.rst

![image](https://user-images.githubusercontent.com/4312421/132040994-61572888-99f5-478f-8706-08e094fc3fc1.png)

**Comment by stonebig** [comment]
2021-09-18 news:
- down to 60 missing packages: 
   - 15 related to Qt (but ctismer of Qt/PySide advancing hard on it)
   - 5 needing PyPy-3.8 (mypy, black, ...)

**Comment by stonebig** [comment]
testing cpython-3.11.0a2: not yet a truly visible speed-up at first try.

**Comment by stonebig** [comment]
testing Pyjion: not yet a truly visible speed-up at first try on the sudoku example.

on "elegant classic" code, for now: 
- PyPy gets the same 2x speed-up as cython,
- the other fail to improve anything 

Educated guess is:
- working hard on JIT is not enough to solve the Python "slowness" on executing existing code, 
- a minuscule touch on the code should bring a 5x larger improvement,
- designing both JIT improvement and a PEP-JIT-performance-enabler should result on:
   - 2x less heroic effort on JIT,
   - 10x better performance result,
   - no split in the community on what that "minuscule" changes shall be, so we have a "Tweaked Classic Elegant" way to write Fast Python Code, and preferably only one.

**Comment by stonebig** [comment]
december 11th news:
- cpython-3.11.0a3 improves and goes up to cpython-3.9.0 speed.

**Comment by stonebig** [comment]
January 2nd:
- new: opencv for PyPy-3.8
- still missing from PyPy-3.7: osqp, gdal, pandas-1.4

**Comment by stonebig** [comment]
January 22nd:
- new in PyPy-3.8:  pandas-1.3.5 with fix, gdal, osqp

**Comment by stonebig** [comment]
February 27th, 2022:
- PyPy-3.8-7.3.8 with Python-3.8 official compatibility
- Python-3.9-7.3.8 beta, seems on track for a Q2 official release (moving from 3.7 to 3.9 in 1 year would be awesome)

**Comment by firai** [comment]
Pyside6 wheels for PyPy v7.3 (Python 3.8 edition) appear to have been released:
https://www.qt.io/blog/qt-for-python-details-on-the-new-6.3-release
https://download.qt.io/official_releases/QtForPython/pypy/

**Comment by stonebig** [comment]
super ! thanks for the head-up

**Comment by stonebig** [comment]
So, as of May 2nd 2022, let say PyPy reached a Milestone:
- PyPy3.8-7.3.9 has now its first set of PySide6-6.3 wheels, in a WinPython release Candidate
- PyPy3.9 is likely to be declared stable in June,
- PyPy / Qt teams have now big 'real life' Qt packages to play with and improve.

... PyPy is keeping on its interception (and synergy) course with cPython in 2023

**Comment by stonebig** [comment]
On my true 4 core new PC sudoku test, PyPy-3.8 is still 2x faster then cpython-3.11, which is only 10% faster than cpython-3.10.
... so on immediate speed-up (in 1 year):
- the "nogil" +" python" splitting in python-made-EASY in 4, would be the best simple move forward
- PyPy may speed-up per 20% if it gets more support, while getting clother to cpython version
- cpython may speed-up per 20%
- hardware do promise 20% per year at this strange speed-up again years

==> so software and hardware do split the coming improvements,
but the multi-core part of hardware is still waiting cpython to naturally/effortlessly use it and boost by 8x for the average user.

**Comment by stonebig** [comment]
humm, as of now:
- PyPy-3.9 stable is 6 month later than hoped,
- the benefit of PyPy team exploring ahead on jit things / having jit expertise for Python, remains,
- the need for Hpy momentum seems necessary to get a notable (3x) benefit over cPython in typical WinPython use-cases.

So:
- on the two benchmark that were looked at:
  -  Sqlite-bro : 
     - PyPy is twice slower, Hpy is necessary to get PyPy on same level as cPython,
     - SQlite integrating the math functions removes the real-life problem,
   -  Sudoku:
      - PyPy is twice faster, cpython-3.11 didn't improve on speed on this,
      - cpython-3.12 may bring benefit by focussing on other optimisations, so is to follow,
      - these 2x gains are insignificant if a nice & simple thread parallelism can be implemented following Nogil or Gil-per-Thread
- interest/effort may shift on pyodide / cpython-3.12 as more short term benefit.

**Comment by stonebig** [comment]
PyPy for Python-3.10 is out on june 2023, 6 month after 3.9, so back to a better  9 month cycle vs 12 for cpython.
... it's now only 18 month behind cpython.

Hpy seems to be integrate after Numpy-2.0, so 2.1
... we should have a competitive PyPy around  end 2024

**Comment by stonebig** [comment]
humm, co-petition is catching-up:
- cpython-3.13: copy-and-patch JIT, with multi-interpreters and free-threads, 
- mojo.

the JIT expertise of PyPy may now help to challenge/improve/avoid mistakes in  cpython JIT.

**Comment by stonebig** [comment]
cpython-3.13.0a4 is out:
- it seems to give a boost of 10% versus 3.11 on pure python things, not bad,
- it's before JIT is activated, where the added benefit is currently only 1%, hope it will go to 10%, so total boost like 3.11.

**Comment by stonebig** [comment]
PyPy main idea of JIT Speed-up will be integrated via the Copy-and-patch JIT in classic cPython-3.13

**Comment by stonebig** [comment]
hummm, no perceptible speed progress with python-3.13.0a5.amd64 yet

**Comment by stonebig** [comment]
with python-3.15a6, havong tailcall, we get 58"

````
 .\python.exe sudoku_norvig_for_comparison_of_complexity.py
All tests pass.
. . . |. . 6 |. . .
. 5 9 |. . . |. . 8
2 . . |. . 8 |. . .
------+------+------
. 4 5 |. . . |. . .
. . 3 |. . . |. . .
. . 6 |. . 3 |. 5 4
------+------+------
. . . |3 2 5 |. . 6
. . . |. . . |. . .
. . . |. . . |. . .
4 3 8 |7 9 6 |2 1 5
6 5 9 |1 3 2 |4 7 8
2 7 1 |4 5 8 |6 9 3
------+------+------
8 4 5 |2 1 9 |3 6 7
7 1 3 |5 6 4 |8 2 9
9 2 6 |8 7 3 |1 5 4
------+------+------
1 9 4 |3 2 5 |7 8 6
3 6 2 |9 8 7 |5 4 1
5 8 7 |6 4 1 |9 3 2
(58.66 seconds)
````
