### ISSUE TITLE
"VS Code.exe" Not Starting

### ISSUE THREAD

**Issue by robert99** [winpython/winpython#977]
Windows 10 64 bit.
Winpython64-3.8.9.0

I downloaded Winpython64-3.8.9.0 today and every thing works fine, except that "VS Code.exe" does not start.
Nothing happens when I click it.

I have Visual Studio Code installed already as a standalone.

Does this need to be linked to somehow?

**Comment by stonebig** [comment]
Yes this on has no VS code included.


You can:
- download "WinPython64-3.9.4.0cod",
- unzip it,
- copy/past it subdirectory `\t\VSCode ` in the exact same place in you current "Winpython64-3.8.9.", and try again

**Comment by stonebig** [comment]
if you wanted something else or had already a VScode, there are some posts about other solution in "issues" or maybe in "stafkoverflow", like this one: https://github.com/winpython/winpython/issues/918

**Comment by stonebig** [comment]
there is also the notebook "installing VScode.ipynb" in your current downloaded version  (or [here](https://github.com/winpython/winpython_afterdoc/blob/master/docs/installing%20VScode.ipynb)) that describes how to add it yourself

**Comment by stonebig** [comment]
it should be solved with latest VSCode-python https://github.com/microsoft/vscode-python/commit/f7a9f19d15010f2df8c1b73440e3aa65cb235952
