### ISSUE TITLE
what is difference between dot/cod/ releases

### ISSUE THREAD

**Issue by yekanchi** [winpython/winpython#987]
I didn't found any guide on what's the difference between dot/cod releases. they have differences in sizes.

**Comment by stonebig** [comment]
The difference is what is inside, that you can discover by following [the front page links](https://winpython.github.io/)

Example:
https://github.com/winpython/winpython/blob/master/changelogs/WinPythondot-64bit-3.9.4.0.md
https://github.com/winpython/winpython/blob/master/changelogs/WinPython-64bit-3.9.4.0.md
https://github.com/winpython/winpython/blob/master/changelogs/WinPythoncod-64bit-3.9.4.0.md
