### ISSUE TITLE
is winpython next generation of pythonxy?

### ISSUE THREAD

**Issue by chapgaga** [winpython/winpython#99]
seems code of pythonxy is destroyed by author :(

http://code.google.com/p/pythonxy/source/list

**Comment by stonebig** [comment]
It's rather that code.google.com is closing down.

Perhaps can you get the source by clicking on "export to github" button on the main page https://code.google.com/p/pythonxy/

**Comment by stonebig** [comment]
Maybe Python(x,y) has been the first usable distro on Windows.

Users have a little more choice than before on Windows, at least 4, not 1.

Each one is picking some good ideas and benefiting some work from the other.

Each one is trying to contribute to the global python communauty, in the friendly and open-minded spirit that animates it.

**Comment by chapgaga** [comment]
hg clone https://code.google.com/p/pythonxy/ not works, in fact, the code is not hosted there

**Comment by sebix** [comment]
Python(x,y) is another project with similar aims, but has nothing to do with Winpython itself. Thus we can't give support on using or improving Python(x,y).

You can get in contact with the developers e.g. via the mailinglist, linked on their [support page](https://code.google.com/p/pythonxy/wiki/Support).
