### ISSUE TITLE
Release 2021-04 follow-up + post1

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#995]
Release Date: mid november 2021  ~~october~~    ~~september~~ 

Wanted:
- Infrastructure:
   - [x] PyPy3.7-7.3.7 (with 3 weeks long  regressions finally hunted down) 
   - [x] PyPy3.8-7.3.7 beta, with alignment effort to cPython standard, lag from cPython is reduced:
       - from 29 month with 3.7, 2018-06 to  2020-11 (PyPy-3.7beta),
       - down to 25 month with 3.8, 2019-10 to 2021-10 (PyPy-3.8beta)
   - [x] Python-3.10.0
   - [x] Python-3.9.8
   - [x] pip-21.3.1
- major modules:
   - [x] Jupyterlab-3.2.1
   - [x] Pandas-1.3.4
   - [x] Spyder-5.1.5
   - [x] Matplolib-3.5.0pre
- Improve Dashboarding experience:
    - the 4 of interest: Panel, Voila, Dash, streamlit (apache-superset seems cloud only)
    - ship a tiny example for each 

Focus:
- pushed to increase PyPy3 package list and compatibility (until next limit requiring Python-3.8),
- Web Technology:  Dashboarding, Web API, WASM
- [Data Engineering](https://talkpython.fm/episodes/show/302/the-data-engineering-landscape-in-2021): dagster, dagster-dask, dbt, prefect, meltano
- Machine Learning: Integrated Windows ML, opencv ?
- [x] Qt-6.2.1  compatibility (for Python-3.10)

Hopes/Wishes for winter 2021-2022:
- PyPy writes a PEP for Hpy interface (the necessary step to glory)
- Spyder gets PySide6-6.2.1 compatiblity
- co-competition heats-up on speed: PyPy-3.8, python-3.11.0a3, Pyjion, Python-nogil
- a perceptible move to bind with rust rather than c, see: https://www.youtube.com/watch?v=-XyWG_klSAw&t=320s
- push to get a competitive PyPy-3.10 in Q4 2022

**Comment by stonebig** [comment]
autid traill

looka t: superset

**Comment by stonebig** [comment]
interlude, Python-3.10.0b4 (2021-07-11) 

This is the last beta of Python-3.10.0

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
189a85e4741d5cc5243a1b69e6d5ff97 | 4cd76dd0441204ed99e151ec9f8870348b4024fa | 2a42c8be9545effb8d6304ad5c3abb89b9274b4d95fedb4423d3c096342eadc5 | Winpython64-3.10.0.0dotb4.exe     |   26 002 818 Bytes | 4db841ad828852b94bc1983d1c6a995673104df6ac14e523f1ab115e74acc7b2
8a6afb77048626ee315067aa47acdbb8 | c0301393c4fea58767ced3f1fc56f0f736dcb5b2 | 55a592a9c42121054c369f223b37a6a1642e27caed729260162bc13944cbb777 | Winpython32-3.10.0.0dotb4.exe     |   24 857 330 Bytes | ddc0f7d0730e6b02da35ae687d52ece15a7a465cae6df80a2aa9b3f0b32c3662

**Comment by stonebig** [comment]
build 1 (2021-07-xx, jupyterlab-3.1.0rc1 )

Changes from WinPython 2021-03:
- Infrastructure: 
  - PyPy3-7.3.6 final
  - jupyterlab-3.1.0rc1
- Upgraded Packages: 
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- jupyterlab-3.1.0rc checks
- finding and narrowing  down issues in  PyPy3 version.
- PyPy3 issues or non-understood issues are to report there: https://foss.heptapod.net/pypy/pypy/-/issues?sort=updated_desc
- packages issues with PyPy3 are to check also on their issue list are sometimes already created, like [here for Matplotlib 
](https://github.com/winpython/winpython/issues/953)
- for jupyter, the ironing out threads are there  https://github.com/jupyter/jupyter_core/issues/226#issuecomment-846453917 and there https://foss.heptapod.net/pypy/pypy/-/issues/3469

Next build effort:
- pushing on PyPy3 pain points :
  - jupyter_core pywin32 replacement patch not yet mainline

**Comment by stonebig** [comment]
build 2 (2021-08-12, jupyterlab-3.1.4, spyder-5.1.1)

Changes from WinPython 2021-03:
- Infrastructure: 
  - python-3.10.0rc1
- New Packages:
- Upgraded Packages: 
   - jupyterlab-3.1.4, spyder-5.1.1,
   - scipy-1.17.1, pandas-1.3.1
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- spyder-5.1.1 shall be quicker on completion
- jupyterlab-3.1.4

Next build effort:
- following on PyPy3 pain points :
  - compatibility fix from Cpython packages: jupyter_core, pyproj bug
  - PyPy-7.3.6 to suppress some speed problems
  - hpy/cpython-hpy to give a warp-speed bump to C-packages
  
 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
b80e303c0f2b62ff442134886f986913 | 516a953405c7dc2d4b01dcee4bc395cd003e8090 | a33db04d162bef6537fc89e34364fec792f1290006f2120fb331aa8c76b50e8c | Winpython64-3.7.10.1dotPyPyb2.exe |   25 825 247 Bytes | 17180b1b66a4a4c9fb7c91f7443e0d871b56022ba0b049ec64d5cae01df62376
91ef99678fc244166ab82d1c5e23f267 | 75e82fab2fb89c3d2528ad88b39185d114acdb7b | 3149918fe5952be67c8744d95e0babc2d32a159ed1fa1f64eaba0de15144b37d | Winpython64-3.7.10.1PyPyb2.exe    |  271 415 070 Bytes | d67a6990c532b6183a80af4339aed58747804e53d261aa1739359025c1d5c02a
38a57bb7e98b802793af6088b2961a03 | 6500284978cb69849b7a4c40d00f35ca78dfd263 | 36212ad21bf0508a70cd2a6de9c3b2c58bc9e23405dabf2f023b94ceddac7844 | Winpython64-3.9.6.0dotb2.exe      |   23 541 536 Bytes | 5afd166b3b0f38df56e1c79dd3ddb4844d45e4bff40f471723450f4ece14ff90
eae2cc5ead9a97153fb0f53ddd909cad | 68ced5b1b0316f1dcb79e73ebb986565ad5da683 | 02c5443fde087e2be03ed453733ccb0c5f5d664f5a6a2437c3de14747f08f75c | Winpython32-3.9.6.0dotb2.exe      |   22 376 563 Bytes | a5fbc7e4b89c1d7bc8be8cc62cb36ed86cddcfefb14310af9562b1e849d504b8
40dff8155898190cf06a0321b136b15f | 60b62290725a765f9fb32f1cb0a2fb177f0b4703 | 18967f6a9c5b8f9b3fef36345cd74ddae52f4dc51e0bb3aabbb3eb98e27877bb | Winpython64-3.9.6.0b2.exe         |  822 192 809 Bytes | e97a4c785b2643fe83241c7bc1f9edf4c498827e2482013f4b0a7651e68638a7
e1a373bf4f3080ba9c2f31eaa4d4c6dc | b600a680e605f48ab3475bcf24dd18b8c208552c | c4a12ba86c9330e161a93175d2bcbf8d4dbb3adb995b3a26c85a553d96c8f1e3 | Winpython64-3.10.0.1dotb2.exe     |   26 061 932 Bytes | 62e286f1dea530cd6af25b08dd6cbfe06fbf8fc964fc73bb441ea18fb4c39148
05186dceeaafb0778c52db39034a9b9b | 5f1d028ecdc1234157a12e30ba90e1dd82c4c609 | a8781ca8b5b143c6333513909aa36f6103482485709521bb2f03e3318d245e4e | Winpython32-3.10.0.1dotb2.exe     |   24 919 302 Bytes | 65b78cf9ca7de9fe356366e01adfd3eafb9522060cdcc8e32536ab93acf0b996

**Comment by RoyiAvital** [comment]
> Machine Learning: Integrated Windows ML, opencv ?

That would be great. I think it will be great to have OpenCV out of the box.
What's Windows ML in the context of Python?

**Comment by stonebig** [comment]
build 3 (2021-09-05, spyder-5.1.3)

Changes from WinPython 2021-04 build2:
- Infrastructure: 
  - python-3.9.7
- New Packages:
- Upgraded Packages: 
   - spyder-5.1.3,
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- spyder-5.1.1 shall be quicker on completion
- following on PyPy3 pain points :
  - jupyter_core and pyproj bugs are fixed in official packages.
  - PyPy-7.3.6 3.8 aligns itself on site-package location and executable name (python.exe) 

Next build effort:
- following on PyPy3 pain points :
  - PyPy-7.3.6 remaining speed problems (and christmas expected  [threaded-generation branch ](https://foss.heptapod.net/pypy/pypy/-/tree/branch/threaded-code-generation)
  - hpy/cpython-hpy-0.0.4 and PEP
  
 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                            | Size               | SHA3-256                                                         
---------------------------------|------------------------------------------|------------------------------------------------------------------|-----------------------------------|--------------------|------------------------------------------------------------------
7159556b71a1f258a8ee0d6f80b4d5a5 | 358b2c42157bddab90bbf800f5fb88ccf652ee87 | d7f419e2bb0dc6e5dd33728036acde77414981241770f58048a37bbe4f930bde | Winpython64-3.9.7.0dotb3.exe      |   26 355 788 Bytes | d6a0de4781ce9129ca6c0a668a64fcc48c1f20f640543002bc01bad678cd23c2
d54234ee1e7d3fd85ab660d93382f795 | a8fd943eaba8d964a34451ac06471325794c7072 | b386e726cf68d1e56c47e0d5a158d0c28dd2909df196f59967d5e0e35a37cd3f | Winpython32-3.9.7.0dotb3.exe      |   25 207 674 Bytes | 8451fb00132f3b53d1354b8eb7cc08ef62e93e6160abb75bd7d5c4800ba1e708

**Comment by stonebig** [comment]
build 4 (2021-09-13/19, PyPy-7.3.6rc1)


Changes from WinPython 2021-04 build3:
- Infrastructure: 
  - pypy3.7-v7.3.6rc1 (2021-09-13)
  - pypy3.8-v7.3.6rc1 (2021-09-13)
  - python-3.10.0rc2 (2021-09-0x)
- New Packages:
- Upgraded Packages: 
   - spyder-5.1.4
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- spyder-5.1.4, pandas-1.3.3
- resolved PyPy3 pain points :
  - huge speed-up of PyPy-7.3.6 on sqlite_bro test
  - jupyter_core and pyproj PyPy compatibility bugs are fixed in official packages.
  - PyPy-7.3.6 3.8 aligns to cpython standard on site-package directory location and executable name (python.exe) 

Next build effort:
- following on PyPy3 pain points :
  - PyPy-7.3.6 remaining speed problems, and christmas expected  [threaded-generation branch ](https://foss.heptapod.net/pypy/pypy/-/tree/branch/threaded-code-generation)
  - hpy/cpython-hpy-0.0.4

**Comment by stonebig** [comment]
build 5 (2021-09-19, PyPy-7.3.6rc1, fixed build issue)


Changes from WinPython 2021-04 build4:
- Infrastructure: 
  - fix the PyPy 7.3.6rc1 build adaptation problem https://github.com/winpython/winpython/pull/1013
- New Packages:
- Upgraded Packages: 
   - spyder-5.1.5, pandas-1.3.3
   - jupyter_core-4.8.1 officially compatible with PyPy
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard cpython branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- spyder-5.1.5, pandas-1.3.3
- resolved PyPy3 pain points :
  - better adaptation to PyPy-3.7 structural changes in 7.3.6rc1 update

Next build effort:
- following on PyPy3 pain points :
  - hpy/cpython-hpy-0.0.3 (at PyPy rc2 or final) 
  - PyPy-3.8 7.3.6rc2 (PyPy structural changes broke virtualenv and venv)

**Comment by stonebig** [comment]
build 6 (2021-09-2x, Python-3.9.7, update pip and build):

Changes from WinPython 2021-04 build4:
- Infrastructure: 
  - re-merge pip fix to latest 2021-09-26 (1 out of 3 patches included)
  - new spyder luncher icon to match spyder official icon change
- Upgraded Packages: 
   - bokeh-2.4.0, geoviews-1.9.2a0 , panel-0.12.4rc1, 
   - scikit_learn-1.0, voila-0.2.15, torch-1.9.1
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard cpython branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- bokeh-2.4.0, scikit_learn-1.0, voila-0.2.15
- pip with updated patch works well for you

Next build effort:
- following on PyPy3 pain points :
  - hpy/cpython-hpy-0.0.3 (at PyPy rc2 or final) 
  - PyPy-3.8 7.3.6rc2 (PyPy structural changes broke virtualenv and venv)
 - finalize release before next wave of changes: 
     - a solid PyPy-3.7 and cpython-3.9
     - a tiny PyPy-3.8 and cpython-3.10  
     - true big releases of PyPy-3.8 and cpython-3.10 may only happen during next cycle (get wheels, test, get fixes, stabilize, assemble)

**Comment by stonebig** [comment]
build 6 (2021-10-10 for Python-3.10.0 + PySide6-6.2, update pip and build system):

Changes from WinPython 2021-04 build4:
- Infrastructure: 
  - pip-21.3.0dev-20211010 with performance improvements now in 'main' pip  
  - QtPy-1.11.3.dev0-20201010+ patch to get QtConsole and Pyzo (patched)  working on PySide6-6.2.0
  - Patch Qt icons to support PySide6
  - hpy-0.0.3 on PyPy-7.3.6rc2
- Upgraded Packages: 
   - PySide6-6.2.0 on WinPython-3.10 branch
   - Matplotlib-3.5.0rc1 (Pyside6 compatibility) on WinPython-3.10 
- variation per version:
  - no Qt nor ML package in PyPy3 versions yet,
  - Pytorch in standard cpython branch only,
  - portable VSCode in "cod" branch only. (but you can copy the "\t\cod" directory from one to the other)
 
Areas of particular interest for testers:
- PySide6-6.2.0 on WinPython-3.10
- Matplotlib-3.5.0rc1

Next build effort:
- following on PyPy3 pain points :
   - PyPy-3.8 7.3.6rc2 (PyPy structural changes broke virtualenv and venv)
 - finalize release before next wave of changes: 
     - a solid PyPy-3.7 and cpython-3.9
     - a medium cpython-3.10  
     - true big releases of PyPy-3.8 and cpython-3.10 may only happen during next cycle (get wheels, test, get fixes, stabilize, assemble)

**Comment by stonebig** [comment]
wrap-up:
- [ ] changelogs
- [ ] shas addition
- [ ] front-page
- [ ] upload to github

**Comment by fleming79** [comment]
I get an import error for scipy.signal for a fresh download of Winpython64-3.9.8.0.exe

```
import scipy.signal
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16548/2352750389.py in <module>
----> 1 import scipy.signal

C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\signal\__init__.py in <module>
    290 
    291 """
--> 292 from . import sigtools, windows
    293 from .waveforms import *
    294 from ._max_len_seq import max_len_seq

C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\signal\windows\__init__.py in <module>
     39 """
     40 
---> 41 from .windows import *
     42 
     43 __all__ = ['boxcar', 'triang', 'parzen', 'bohman', 'blackman', 'nuttall',

C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\signal\windows\windows.py in <module>
      5 
      6 import numpy as np
----> 7 from scipy import linalg, special, fft as sp_fft
      8 
      9 __all__ = ['boxcar', 'triang', 'parzen', 'bohman', 'blackman', 'nuttall',

C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\linalg\__init__.py in <module>
    193 """  # noqa: E501
    194 
--> 195 from .misc import *
    196 from .basic import *
    197 from .decomp import *

C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\linalg\misc.py in <module>
      1 import numpy as np
      2 from numpy.linalg import LinAlgError
----> 3 from .blas import get_blas_funcs
      4 from .lapack import get_lapack_funcs
      5 

C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\linalg\blas.py in <module>
    211 import functools
    212 
--> 213 from scipy.linalg import _fblas
    214 try:
    215     from scipy.linalg import _cblas

ImportError: DLL load failed while importing _fblas: The specified module could not be found.
```

**Comment by stonebig** [comment]
hum, you are right. onlywinpython-3.9.8 seems to have the problem... digging
![image](https://user-images.githubusercontent.com/4312421/141467279-f10ad082-6e12-4084-9e0d-8faa63f1c427.png)

**Comment by stonebig** [comment]
the wheel cames rigth from the place suggested as a solution, in similar error report of 2019 https://stackoverflow.com/questions/57120965/from-scipy-linalg-import-fblas-importerror-dll-load-failed-the-specified-mod

**Comment by stonebig** [comment]
the problem is maybe in numpy: numba forced me down to numpy-1.20.3+mkl for Winpython64-3.9.8.0, instead of numpy-1.21.4+mkl for 3.10 or 3.7PyPy, as there is no numba available for the other two yet.

**Comment by stonebig** [comment]
ha, I didn't notice: Christoph gohlke remove numpy-1.20.3 from his site, and scipy-1.7.1 also, so a sort of a sign of non-compatibility, .... so:
- if I put back old scipy-1.7.1 it works, for scipy,
- other option is to increase numpy version and reduce numba version, but numba is not so compatible then,
- other option is to wait next numba very late .

option1:
![image](https://user-images.githubusercontent.com/4312421/141471212-db6dc74a-0c2b-49df-b689-26c302d60059.png)

**Comment by stonebig** [comment]
on principle:
- WinPython is about bleeding edge, so numba backpedaling numpy was already a pain,
- Numpy bleeding edge shall get the prefered treatment, as it's part of the strategy of reducing cPython technical debt, and helping PyPy and AMD.
- previous versions of cgohlke wheels of scipy and numpy are no more public, so you can't replicate.

so the less bad action is  looking to be option3: 
- better a bad numba that no numba,
- scipy and numpy are the "coherent" latest set of cgohlke..

.... preparing a re-spin with numpy upgraded, and numba dowgraded (still passing winpython_checker tests)

**Comment by stonebig** [comment]
post1 (2021-11-12)

Changes from WinPython 2021-04:
- spin a Winpython64-3.9.8.0post1.exe that:
  - patches numba-0.54.1 to allow numpy-1.21.4+mkl
  - uses numpy-1.21.4+mkl instead of numpy-1.20.3+mkl

**Comment by fleming79** [comment]
Thank you for your excellent work!
