### ISSUE TITLE
WPy32-3880 Spyder 5.0.5 missing dependency rtree>=0.9.7 : none (NOK)

### ISSUE THREAD

**Issue by cnsltnt51** [winpython/winpython#997]
After running the following in WinPython powershell.

python -m pip install -U spyder

the error panel appears the rtree is missing even thought it is there.

running
python -m pip install -U rtree

does not resolve the issure.

**Comment by stonebig** [comment]
I see the issue in spyder issues, but for an anaconda+pip mix-up https://github.com/spyder-ide/spyder/issues/16036

**Comment by cnsltnt51** [comment]
I do not have anaconda loaded.
winpython 32 bit version 3.8.8.0

**Comment by stonebig** [comment]
the bug was in Spyder and has been resolved since a few Spyder releases.
