### ISSUE TITLE
Unable to run from path containing a closing parenthesis, ")"

### ISSUE THREAD

**Issue by DIV-on-github** [winpython/winpython#999]
I previously 'installed' WinPython 3.7.7.0 (x64) to a path resulting in
"C:\Program files (portable)\WinPy_3-7\WPy64-3770\Spyder.exe"
and also WinPython 3.8.3.0-RC (x64) to a path resulting in
"C:\Program files (portable)\WinPy_3-8\WPy64-3830\Spyder.exe"
Each of these ran with no problem.  The OS is Windows 10 Pro for Workstations (x64).  

On a different workstation, following the same procedure, I 'installed' 3.8.9.0 (x64) to a path resulting in
"C:\Program files (portable)\WinPy_3-8\WPy64-3890\Spyder.exe"
and also WinPython 3.9.5.0 (x64) to a path resulting in
"C:\Program files (portable)\WinPy_3-9\WPy64-3950\Spyder.exe"
NEITHER of these ran at all.  The OS is Windows 10 Pro for Workstations (x64) too.  
Running Spyder produced nothing, including no error message.  However, running "Jupyter Lab.exe" from the above two directories indicated a problem with the path name, with the following error message reported in the 'console' (cmd window):  
"\WinPy_3-9\WPy64-3950\scripts was unexpected at this time."
Notice that this comprises the path immediately after the closing parenthesis, ")".  

On the second workstation I tried copying the files to "c:\TMP".  They all ran just fine.  
I also tried "C:\TMP 0123456789_ A0123456789_ B0123456789_ 0123456789_" to check issues with a long pathname or spaces.  All executables ran just fine.  
Even with an opening parenthesis in the path there is no problem.  
**The problem only occurred with a closing parenthesis in the path** (regardless of the presence or absence of an opening parenthesis).

—DIV

P.S.   Each 'installation' is a portable installation, without 'registration'.  One was manually extracted using an installed copy of 7-Zip.  The remainder all used the self-extraction capability of the 'installer'.

**Comment by stonebig** [comment]
Did you search in the script/env.bat what may be the problem ?

**Comment by stonebig** [comment]
hum, that's very strange:
- if you double-clik on `C:\Program files (portable)\WinPy_3-9\WPy64-3950\scripts\windile.bat`, noting works
- if you launch a DOS window, than type in it `C:\Program files (portable)\WinPy_3-9\WPy64-3950\scripts\windile.bat`, it works

**Comment by stonebig** [comment]
regression may be somewhere in `scripts/env_for_icons.bat`

**Comment by stonebig** [comment]
hum I don't guess, help welcomed . if you open a DOS windows and Drag&drop `C:\Program files (portable)\WinPy_3-9\WPy64-3950\scripts\winspyder.bat` , if you double-click it it fails...

**Comment by stonebig** [comment]
ok, when dos is in a "(" thing, it miss-interprets.

you have to modify One line 28  in C:\Program files (portable)\WinPy_3-9\WPy64-3950\scripts\env_for_icons.bat:

from

`if not "%CD%\"=="%~dp0" set  WINPYWORKDIR1=%CD%
`
to

`if not "%CD%\"=="%~dp0" set  WINPYWORKDIR1="%CD%"`

![image](https://user-images.githubusercontent.com/4312421/128593671-caa0a247-04ac-4f5c-9aa3-52f4cecf1abf.png)

**Comment by DIV-on-github** [comment]
> Did you search in the script/env.bat what may be the problem ?

I didn't know where to look!   I'm glad you seem to have resolved this nonetheless :-)

**Comment by stonebig** [comment]
Try the change on your pc, to confirm.

**Comment by DIV-on-github** [comment]
Hello, stonebig.  
I have manually made the small modification (to version 3.9.5) that you described here, and I can confirm that it has indeed fixed the issue on my computer too.  
Thanks!  

—DIV
